### PR TITLE
Object color cycling on adventure map

### LINKED ISSUE #289: No animation of water surface
Currently we have a static water surface:
image

While original game has a good water surface animation. We should have it too.

### LINKED ISSUE #290: Animation of Treasure Chest is incorrect
If you watch how Treasure Chest is animated you would notice that shadow of the chest changes as well as the number of frames for animation is way less than it's in original game:
image

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #289 . Fixes #290 

Replaced fake animation ICNs with cycling. Targeting specific objects for the color change. Added a save correction for backwards compatibility with 0.7.

Example:
ezgif-5-926c70b5ea0e

### CODE REVIEW

File: src/fheroes2/agg/pal.cpp [hunk 1]
```diff
@@ -174,6 +189,10 @@ void PAL::CreateStandardPalette()
         col.r = kb_pal[index] << 2;
         col.g = kb_pal[index + 1] << 2;
         col.b = kb_pal[index + 2] << 2;
+        // create distinction between cycling color #220 and non-cycling #222
+        if ( ii == 0xEC ) {
+            col.b--;
+        }
```
Comment (idshibanov) [inline src/fheroes2/agg/pal.cpp:195]: Big issue here is that we swap RGB colors and index 220 and 222 had the same value, causing both of them to be replaced. Since we don't keep the index by the type cycling happens this is what I had to do to make sure they are recognized correctly.

Our 32-bit RGBA colors are in increments of 4 anyway, so tiny adjustment shouldn't be noticeable.

File: src/fheroes2/agg/pal.cpp [hunk 2]
```diff
@@ -174,6 +189,10 @@ void PAL::CreateStandardPalette()
         col.r = kb_pal[index] << 2;
         col.g = kb_pal[index + 1] << 2;
         col.b = kb_pal[index + 2] << 2;
+        // create distinction between cycling color #220 and non-cycling #222
+        if ( ii == 0xEC ) {
```
Comment (ihhub) [inline src/fheroes2/agg/pal.cpp:193]: Hi @idshibanov , I think we face a limitation of our drawing engine. This hack should not be present as well as ChangeColor function is absolute mess...

I have a better idea: for every Surface when we read any **icn** file in `RenderICNSprite` method we must create an 8-bit image (simple uint8_t array) based on the original input information. We can call it as primary data or something. Then using this array and provided palette we can construct required image. In this case for color changing the function would need only a palette. Rendering image using this information is way faster and more accurate than changing colors on existing image.

If you're okay with such approach I can make required changes.

Comment (idshibanov) [reply src/fheroes2/agg/pal.cpp:193]: I totally agree with the approach, that's why I wanted to show you this. Let's make it change, it will simplify a lot of future work as well.

Comment (idshibanov) [reply src/fheroes2/agg/pal.cpp:193]: @ihhub What do you think about caching then? For example adventure map has a lot of small tiles, it might be a bit slow to re-render them on every draw call. At the same time storing different palette versions is a waste of space. Can we pre-render a bigger surface with uint8_t indexes and render color much later?

Comment (ihhub) [reply src/fheroes2/agg/pal.cpp:193]: If we talk about map tiles which is ground,water and fog we could draw everything exactly on Surface without extra copies of Surfaces which is way faster. Memory operations are slowest in any system. Secondly, we could store a flag for each tile whether it is cycling or not. We know which colors we need to cycle and we know which palette indexes exist in tile or Surface so having such information will help us to identify 'special' tile.
Let's do step by step and see how it goes. I will prepare needed changes soon in a separate pull request.

Comment (idshibanov) [reply src/fheroes2/agg/pal.cpp:193]: Please keep in mind that on adventure map a lot of objects (as TileAddon) also have cycling animations: rivers ("stream"), lakes, fountain, treasure chest, teleporters. We might have to apply color *after* everything was placed or set a flag similar to unit sprites and update them separately.

I'll convert this PR into a draft while we sort out how it works.

Comment (ihhub) [reply src/fheroes2/agg/pal.cpp:193]: Today or tomorrow I'll create another pull request just for this ;) Please wait

**Comment by ihhub** [comment]
Hi @idshibanov , I will create a new PR today for map tiles first as they are 8-bit images and we need to use another technique for them.

**Comment by ihhub** [comment]
Hi @idshibanov , the next step which I think would be register specific ICNs and upon retrieval of them from AGG namespace apply needed palette. What do you think?

**Comment by idshibanov** [comment]
> Hi @idshibanov , the next step which I think would be register specific ICNs and upon retrieval of them from AGG namespace apply needed palette. What do you think?

Yes, I'll convert this PR into fixing object animations. Registering makes sense.

**Comment by ihhub** [comment]
> > Hi @idshibanov , the next step which I think would be register specific ICNs and upon retrieval of them from AGG namespace apply needed palette. What do you think?
> 
> Yes, I'll convert this PR into fixing object animations. Registering makes sense.

Great! I think you got my idea ;)

**Comment by ihhub** [comment]
Next step would be to use map cycling for specific Sprite objects upon Blit method call. We could do this as the next iteration. So then we can fix drawings for all cycling color objects. But we need to be careful as we have situations when we need to use other palettes as well.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 3]
```diff
@@ -2824,7 +2814,33 @@ StreamBase & Maps::operator<<( StreamBase & msg, const TilesAddon & ta )
...
+        ta.object = 0xA4;
+        ta.index = 122;
+        break;
+    case 0x14:
+        ta.object = 0xA4;
+        ta.index = 15;
+        break;
+    case 0x15:
+        ta.object = 0xB8;
+        ta.index = 19;
```
Comment (idshibanov) [inline src/fheroes2/maps/maps_tiles.cpp:2838]: Hey @ihhub, I had to add this fix to support old saves. `master` version replaces objects with custom ids, so without this rollback they won't be displayed at all. Might make use of the savegame versioning in the future?

This PR is ready for review. In `TilesAddon::hasColorCycling` I target very specific objects for the redraw instead of registering. They are scattered across different ICN files, but not everything within those ICNs have to be cycled.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:2838]: From another point we could ignore about backward compatibility as 0.7 version was still too early. I don't think that many people has multiple saves from the game which they want to continue playing.

Comment (idshibanov) [reply src/fheroes2/maps/maps_tiles.cpp:2838]: > 
> 
> From another point, we could ignore backward compatibility as 0.7 version was still too early. I don't think that many people have multiple saves from the game which they want to continue to play.

I think we don't lose anything by having this right now (affect only game load) and we can get rid of this after the release.

**Comment by ihhub** [comment]
Hi @idshibanov , I think pyramid is missing animation:
image

Also one type of Stone Lights looks weird (we can make a separate issue for it or it's a problem from the original game itself):
image

Overall looks awesome!

File: src/fheroes2/maps/maps_tiles.cpp [hunk 4]
```diff
@@ -1512,7 +1517,10 @@ void Maps::Tiles::RedrawBottom( Surface & dst, bool skip_objs ) const
             const int icn = MP2::GetICNObject( object );
 
             if ( ICN::UNKNOWN != icn && ICN::MINIHERO != icn && ICN::MONS32 != icn ) {
-                const Sprite & sprite = AGG::GetICN( icn, index );
+                Sprite sprite = AGG::GetICN( icn, index );
+                if ( TilesAddon::hasColorCycling( *it ) ) {
+                    AGG::ReplaceColors( sprite, area.GetCyclingPalette(), icn, index, false );
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1522]: `AGG::ReplaceColors` function replaces colors within Surface without making a copy of it. We could close eyes that we modify the original image by this as no harm to do this but we do an overkill by calling this function for every object which uses this Sprite. For example, we have 10 lava lakes so we call this function 10 times instead of calling once.

We need to make an optimization of this code. This method is called only from one place: `Interface::GameArea::Redraw` so what we can do is:
- create an std::set<Sprite> just before the loop for `RedrawBottom` and pass this set into the function
- inside the function check if Sprite exist. If it's not then call **AGG::ReplaceColors** and put the Sprite into the set. Otherwise do nothing.

Sprite is a lightweight wrapper over SDL_Surface so we're safe to make a copy of it and put into std::set.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:1522]: With latest change we need to expand the idea to `RedrawBottom` and `RedrawTop`.

**Comment by idshibanov** [comment]
> Hi @idshibanov , I think pyramid is missing animation:
> 
> Also one type of Stone Lights looks weird (we can make a separate issue for it or it's a problem from the original game itself):

They both had "top" tiles that weren't animated - should be fixed right now. I'll take a look at the optimization.

File: src/fheroes2/maps/maps_tiles.cpp (hunk 4 above)
Comment (idshibanov) [reply src/fheroes2/maps/maps_tiles.cpp]: Done. I moved the code to `RedrawAddon` since both function had almost the same logic. I clear the std::set when color cycle changes, not on every redraw. It's actually a noticeable improvement, ReplaceColors dropped down behind GetICN:

profile1

File: src/fheroes2/gui/interface_gamearea.h [hunk 5]
```diff
@@ -23,9 +23,10 @@
 #ifndef H2INTERFACE_GAMEAREA_H
 #define H2INTERFACE_GAMEAREA_H
 
-#include "gamedefs.h"
+#include <set>
 
-class Sprite;
+#include "gamedefs.h"
+#include "sprite.h"
```
Comment (idshibanov) [inline src/fheroes2/gui/interface_gamearea.h:29]: Check if you like how `MapObjectSprite` is implemented. I had to include `sprite.h` here for it, don't know if there's a way to avoid it.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 6]
```diff
@@ -1512,7 +1518,17 @@ void Maps::Tiles::RedrawBottom( Surface & dst, bool skip_objs ) const
...
+                if ( TilesAddon::hasColorCycling( *it ) ) {
+                    std::set<MapObjectSprite>::iterator cachedSprite = spriteCache.find( MapObjectSprite( object, index ) );
+                    if ( cachedSprite != spriteCache.end() ) {
+                        sprite = cachedSprite->sprite;
+                    }
+                    else {
+                        AGG::ReplaceColors( sprite, area.GetCyclingPalette(), icn, index, false );
+                        spriteCache.insert( MapObjectSprite( object, index, sprite ) );
+                    }
+                }
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1531]: We could optimize this code further:
```
                Sprite sprite;
                if ( TilesAddon::hasColorCycling( *it ) ) {
                    std::set<MapObjectSprite>::iterator cachedSprite = spriteCache.find( MapObjectSprite( object, index ) );
                    if ( cachedSprite != spriteCache.end() ) {
                        sprite = cachedSprite->sprite;
                    }
                    else {
                        sprite = AGG::GetICN( icn, index );
                        AGG::ReplaceColors( sprite, area.GetCyclingPalette(), icn, index, false );
                        spriteCache.insert( MapObjectSprite( object, index, sprite ) );
                    }
                }
                else {
                    sprite = AGG::GetICN( icn, index );
                }
```
so that we don't call `GetICN` for cached Sprites saving more time.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 7]
```diff
@@ -1496,13 +1501,14 @@ void Maps::Tiles::RedrawEmptyTile( Surface & dst, const Point & mp )
     }
 }
 
-void Maps::Tiles::RedrawBottom( Surface & dst, bool skip_objs ) const
+void Maps::Tiles::RedrawAddon( Surface & dst, const Addons & addon, bool skip_objs ) const
 {
-    const Interface::GameArea & area = Interface::Basic::Get().GetGameArea();
+    Interface::GameArea & area = Interface::Basic::Get().GetGameArea();
+    std::set<MapObjectSprite> & spriteCache = area.GetSpriteCache();
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1507]: Let's put this variable declaration inside `if ( TilesAddon::hasColorCycling( *it ) ) {` body as we don't need it for any other cases.

File: src/fheroes2/gui/interface_gamearea.h [hunk 8]
```diff
@@ -47,6 +48,17 @@ enum level_t
     LEVEL_ALL = 0xFF
 };
 
+struct MapObjectSprite
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.h:51]: An equivalent solution without implementing a new class is to use `std::map<std::pair<uint8_t, uint8_t>, Sprite >` structure :)

Comment (idshibanov) [reply src/fheroes2/gui/interface_gamearea.h]: Oh didn't know that pair supports the operators too. Changed it to 
`typedef std::map<std::pair<uint8_t, uint8_t>, Sprite> MapObjectSprite;` looks cleaner to me.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 9]
```diff
@@ -1496,23 +1501,39 @@ void Maps::Tiles::RedrawEmptyTile( Surface & dst, const Point & mp )
...
             const u8 & index = ( *it ).index;
             const int icn = MP2::GetICNObject( object );
 
             if ( ICN::UNKNOWN != icn && ICN::MINIHERO != icn && ICN::MONS32 != icn ) {
-                const Sprite & sprite = AGG::GetICN( icn, index );
+                Sprite sprite;
+                if ( TilesAddon::hasColorCycling( *it ) ) {
+                    MapObjectSprite & spriteCache = area.GetSpriteCache();
+                    std::pair<uint8_t, uint8_t> tileIndex = {object, index};
+                    MapObjectSprite::iterator cachedSprite = spriteCache.find( tileIndex );
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1524]: `MapObjectSprite::iterator cachedSprite = spriteCache.find( std::make_pair( object, index ) );` is even shorter :)

File: src/fheroes2/maps/maps_tiles.cpp (hunk 4 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp]: I'm just curious: has it become faster after our latest optimizations?

Comment (idshibanov) [reply src/fheroes2/maps/maps_tiles.cpp]: GetICN call dropped significantly, but ReplaceColors still takes considerate time (up and down depending on a run) on debug build. Release build is very fast for both, I guess because we are using maps.

profile2

I'll test std::set once more to see if there's any difference.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp]: We should ignore Debug build as **msbuild** adds a lot of checks in containers making them in more than 100 times slower.

Comment (idshibanov) [reply src/fheroes2/maps/maps_tiles.cpp]: @ihhub I think we can add a second version of `AGG::ReplaceColors` that will take `std::vector<uint32_t> & colorMap` instead of re-building it for each tile. It's a huge speedup.

**Comment by idshibanov** [comment]
@ihhub After a bit more testing I like this PR as is, I think we can either merge now or wait a day for me to push more optimizations.

`AGG::ReplaceColor` refactor can go in a separate PR. I already made the change locally and see a lot of benefits, but have to clean it up. I'm also thinking about drawing TIL tiles on 8bit surface first to avoid `tile.ResetPalette()` on every single one.

After those two `Display.Flip()` in cursor redraw is the last noticeable performance bottleneck, but it's already being addressed.

**Comment by ihhub** [comment]
> @ihhub After a bit more testing I like this PR as is, I think we can either merge now or wait a day for me to push more optimizations.
> 
> `AGG::ReplaceColor` refactor can go in a separate PR. I already made the change locally and see a lot of benefits, but have to clean it up. I'm also thinking about drawing TIL tiles on 8bit surface first to avoid `tile.ResetPalette()` on every single one.
> 
> After those two `Display.Flip()` in cursor redraw is the last noticeable performance bottleneck, but it's already being addressed.

I had the same idea for 8-bit images. First we need to fix scrolling and area displaying issues as well as centering of heroes. I'll check this PR later again and merge if everything is fine.

**Comment by idshibanov** [comment]
> 
> I had the same idea for 8-bit images. First we need to fix scrolling and area displaying issues as well as centering of heroes. I'll check this PR later again and merge if everything is fine.

Sounds great. I'll have more spare time a bit later this week to close more issues down.

**Comment by ihhub** [comment]
Great job, @idshibanov ! Thanks a lot for making it happen!
