### PR TITLE
Scenario Window UI Items position fix

### LINKED ISSUE #1250: Scenario window, elements position
- In fheroes2, the text "Rating 100%" is not centered horizontally in the window.
This text is not centered horizontally in the original game either.
For my part, I would prefer that it be centered horizontally in the window.
- In fheroes 2, the edge of the "OKAY" and "CANCEL" buttons are not the same distance from the edge of the window.
These buttons are not the same distance from the edge of the window in the original game either.
For my part, I would prefer that they be at the same distance from the edge of the window.
- The shadows of the difficulty level buttons and the scenario name bar do not have the same offset as in the original game.
4 pixels to the left, 3 pixels to the bottom in the original game.
4 pixels to the left, 4 pixels to the bottom in fheroes2.
For my part, I prefer the evenly distributed shadow of fheroes2.
So for me, no need to change that. :)

- The words "Hard", "Expert" and "Impossible" are not centered in relation to the difficulty level buttons, 1 pixel offset to the left of the word.

- Opponent buttons, hero class buttons and double arrow graphics for changing player order have no shadows.

**Some adjustments to make to improve the visual appearance of this window:**

By taking the title of the window "Scenario:" as a reference and which must remain in its current position.

- Move the position of the difficulty level selection buttons 2 pixels down to prevent the red frame indicating the selected difficulty from covering the text shadow of the letter "y" of the word "Difficulty".

- Put the same vertical space between the median of the line of the text and the element just above (11 pixels).
Example, the bottom of the scenario name graphic and the median of the line of the text "Game Difficulty:".

- Put the same vertical space between the baseline of the line of the text and the element just below (8 pixels).
Example, the baseline of the text "Game Difficulty:" and the top of the graphic of the difficulty level selection button.

- Adjust the vertical spacing between the median of the line of the text "Random" and the bottom of the hero class button graphic (5 pixels).

- The vertical spacing between the bottom of the scenario difficulty level graphic and the median of the line of the text of the difficulty level must remain at 7 pixels.

Scenario window, improve the visual appearance 01

In the original game:

Scenario window 03

In fheroes2:

Scenario window 05

**Edit 2022/05/23.**

Related discussion: https://github.com/ihhub/fheroes2/discussions/5444.

**Edit 2022/10/22.**

Vertical spacing adjusted with the addition of the new handicap buttons.

Vertical spacing 02

### PR DESCRIPTION
**Pull request by HaveFun91**
Close #1250

### CODE REVIEW

**Comment by HaveFun91** [comment]
@ihhub or @oleg-derevenetz - feel free to review :)

**Comment by zenseii** [comment]
Hi @LeHerosInconnu.

I addressed your last concern about the alignment of the Normal difficulty text:
image

Please have a look and if it is all good now please confirm this so that this PR can move towards being merged.
Thank you!

**Comment by oleg-derevenetz** [comment]
Hi @zenseii could you please merge the master branch to this PR to run the lately introduced checks against it?

File: src/fheroes2/gui/ui_text.cpp [hunk 1]
```diff
@@ -814,3 +814,9 @@ namespace fheroes2
         return true;
     }
 }
+
+int32_t TextUtils::GetCenteredTextXCoordinate( const int32_t startCoordX, const int32_t areaWidth, const int32_t textWidth )
```
Comment (ihhub) [inline src/fheroes2/gui/ui_text.cpp:818]: I believe that a proper fix is to change `void Text::draw( const int32_t x, const int32_t y, const int32_t maxWidth, Image & output ) const` and `void MultiFontText::draw( const int32_t x, const int32_t y, const int32_t maxWidth, Image & output ) const` methods to make auto alignment. `void Text::draw()` method is used in 33 places while `void MultiFontText::draw()` isn't used anywhere. Since these methods accept an input parameter for maximum width we can update the documentation (comments) stating that the text will be centered.

Alternatively, we can add text alignment option which might cover all possible cases in the game. I will try to take a look at it.

File: src/fheroes2/gui/player_info.cpp [hunk 2]
```diff
@@ -338,9 +338,12 @@ void Interface::PlayersInfo::RedrawInfo( const bool displayInGameInfo ) const
         fheroes2::Blit( classIconShadow, display, info.classRoi.x - 5, info.classRoi.y + 3 );
         fheroes2::Blit( classIcon, display, info.classRoi.x, info.classRoi.y );
 
-        const std::string & className = ( Race::NECR == info.player->GetRace() ? _( "Necroman" ) : Race::String( info.player->GetRace() ) );
-        Text text( className, Font::SMALL );
-        text.Blit( info.classRoi.x + ( info.classRoi.width - text.w() ) / 2, info.classRoi.y + info.classRoi.height + 2 );
+        const int32_t maxClassNameTextWidth = classIcon.width() + 10;
+        const std::string & className = _( "playerInfo|" + Race::String( info.player->GetRace() ) );
```
Comment (ihhub) [inline src/fheroes2/gui/player_info.cpp:342]: This is an incorrect approach: `Race::String()` returns **translated** string. Our translation tools do not understand string concatenation.

File: src/fheroes2/gui/player_info.cpp [hunk 3]
```diff
@@ -338,9 +338,12 @@ void Interface::PlayersInfo::RedrawInfo( const bool displayInGameInfo ) const
...
+        fheroes2::Text text( className, fheroes2::FontType::smallWhite() );
```
Comment (ihhub) [inline src/fheroes2/gui/player_info.cpp:343]: This variable can be **const**.

File: src/fheroes2/game/game_scenarioinfo.cpp [hunk 4]
```diff
@@ -104,45 +104,54 @@ namespace
...
-    void RedrawRatingInfo( TextSprite & sprite )
+    fheroes2::Rect RedrawRatingInfo( int32_t x_, int32_t y_, int32_t width_ )
     {
-        sprite.Hide();
         std::string str( _( "Rating %{rating}%" ) );
         StringReplace( str, "%{rating}", Game::GetRating() );
-        sprite.SetText( str );
-        sprite.Show();
+
+        fheroes2::Text text( str, fheroes2::FontType::normalWhite() );
```
Comment (ihhub) [inline src/fheroes2/game/game_scenarioinfo.cpp:149]: This variable can be **const**.

File: src/fheroes2/game/game_scenarioinfo.cpp [hunk 5]
```diff
@@ -104,45 +104,54 @@ namespace
...
     void RedrawDifficultyInfo( const fheroes2::Point & dst )
     {
         const int32_t width = 77;
-        const int32_t height = 70;
+        const int32_t height = 69;
 
         for ( int32_t current = Difficulty::EASY; current <= Difficulty::IMPOSSIBLE; ++current ) {
             const int32_t offset = width * current;
+            int32_t normalSpecificOffset = 0;
+            // Add offset shift because the original difficulty icons have irregular spacing.
```
Comment (ihhub) [inline src/fheroes2/game/game_scenarioinfo.cpp:134]: Should we modify assets instead of having such hacks? Can you provide images with different difficulties?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @HaveFun91 and @zenseii , I put several comments in this pull request. Can you please take a look?

File: src/fheroes2/game/game_scenarioinfo.cpp (hunk 5 above)
Comment (zenseii) [reply src/fheroes2/game/game_scenarioinfo.cpp:134]: Since it is only a column of 1 pixel in width it might be doable to modify the background of this asset. You could maybe copy from the side of another Icon in this dialog.

**Comment by LeHerosInconnu** [comment]
Hello @zenseii,

> Hi @LeHerosInconnu and @ihhub.
> 
> I made the minor necessary changes to address the last issues with this PR that were noted by @LeHerosInconnu. Please have a look at it when you have the time to, @ihhub.
> 
> @LeHerosInconnu, I addressed your last concern about the alignment of the Normal difficulty text:
image
> 
> Please have a look, @LeHerosInconnu, and if it is all good now please confirm this so that this PR can move towards being merged. Thank you!

The word "Normal" is correctly centered in relation to the corresponding difficulty graphic.

File: src/fheroes2/game/game_scenarioinfo.cpp (hunk 5 above)
Comment (zenseii) [reply src/fheroes2/game/game_scenarioinfo.cpp:134]: image

Comment (zenseii) [reply src/fheroes2/game/game_scenarioinfo.cpp:134]: At this point I think it is better to add better code that accounts for this irregular spacing...

File: src/fheroes2/dialog/dialog_gameinfo.cpp [hunk 6]
```diff
@@ -43,6 +43,34 @@
...
+    {
+        SCENARIO_INFO_VALUES_BOX_WIDTH = 80,
+        DIALOG_CONTENT_WIDTH = 420,
+        SCENARIO_INFO_BOX_RIGHT_MARGIN = 11,
+        SCENARIO_INFO_ROW_LEFT_MARGIN = 16,
+        // This is a shadow offset from the original ICN::SCENIBKG image.
+        DIALOG_SHADOW_OFFSET_X = 16,
+        DIALOG_SHADOW_OFFSET_Y = 4,
+        DIALOG_BORDER_WIDTH = 18,
+        // CALCULATED
```
[the remark this answers is not in the document]
Comment (zenseii) [reply src/fheroes2/dialog/dialog_gameinfo.cpp:58]: Hi, @ihhub.

I'm not entirely sure what the purpose of this comment is. Since I'm wrapping up this PR on @HaveFun91's behalf I'd need to address this too.

File: src/fheroes2/game/game_scenarioinfo.cpp (hunk 5 above)
Comment (HaveFun91) [reply src/fheroes2/game/game_scenarioinfo.cpp:134]: I guess modifying all that stuff is going to be difficult as difficulty level graphics are melted into background and there is no way to move them.

**Comment by zenseii** [comment]
Hi, @oleg-derevenetz.

I'm struggling a bit with IWYU's suggestions and would like to ask your assistance. It suggests to add `bits/utility.h` in `interface_gamearea.cpp` and `bits/chrono.h` in `ui_tools.h`. However, if I include them I'm told that these files are not found. I assume they are supposed to replace the inclusion of `<algorithm>` since removing that is another suggested change.

**Comment by oleg-derevenetz** [comment]
Hi @zenseii those `bits/*` headers are private headers, they shouldn't be included directly. Sometimes IWYU cannot recognize a situation like this:

`include/some_public_header.h`:

```
[...]
#include <bits/some_private_header.h>
[...]
```

`include/some_private_header.h`:

```
struct SomeStruct { [...] };
```

Your code:

```
#include <some_public_header.h>

SomeStruct s;
```

It thinks that you should include `some_private_header.h` instead because it's really that header that defines the `SomeStruct`. There is the `iwyu.map` file in the project's root used to define such relationships when IWYU cannot detect them by itself.

**Comment by zenseii** [comment]
Thanks, @oleg-derevenetz ! I was about to attempt addressing this, but you beat me to it in https://github.com/ihhub/fheroes2/pull/6244. We should add your PR's changes to this PR once yours has been merged.

File: src/fheroes2/game/game_scenarioinfo.cpp (hunk 5 above)
Comment (ihhub) [reply src/fheroes2/game/game_scenarioinfo.cpp:134]: In this case we will leave it as it is.

File: src/fheroes2/kingdom/race.cpp [hunk 7]
```diff
@@ -53,6 +53,34 @@ std::string Race::String( int race )
     return _( "race|Neutral" );
 }
 
+std::string Race::DoubleLinedString( int race )
```
Comment (ihhub) [inline src/fheroes2/kingdom/race.cpp:56]: Please return const char * here as _() call returns the same type.

File: src/fheroes2/kingdom/race.cpp [hunk 8]
```diff
@@ -53,6 +53,34 @@ std::string Race::String( int race )
...
+    case Race::NECR:
+        return _( "doubleLined|Necro-\nmancer" );
+    case Race::MULT:
+        return _( "doubleLinedRace|Multi" );
+    case Race::RAND:
+        return _( "doubleLinedRace|Random" );
+    case Race::NONE:
+        return _( "doubleLinedRace|Neutral" );
+    default:
+        break;
```
Comment (ihhub) [inline src/fheroes2/kingdom/race.cpp:78]: Here we should actually assert because it is not an expected logic.

File: src/fheroes2/gui/player_info.cpp [hunk 9]
```diff
@@ -253,7 +253,6 @@ void Interface::PlayersInfo::RedrawInfo( const bool displayInGameInfo ) const
     const Maps::FileInfo & fi = conf.CurrentFileInfo();
 
     const uint32_t humanColors = conf.GetPlayers().GetColors( CONTROL_HUMAN, true );
-
```
Comment (ihhub) [inline src/fheroes2/gui/player_info.cpp:256]: We can revert this change. No harm in having an empty line for separation🙂

**Review by ihhub — COMMENTED** [review]
Hi @HaveFun91 and @zenseii , I put few more comments here. Could you please check them?

**Comment by zenseii** [comment]
Hi @ihhub.

I've addressed all the things I wanted to with this PR. It'd be great if you could review this too. There's a slight misaligning of 1px of the single lined necromancer class string, but all the other classes are correctly aligned so I'm not sure what to do there and I don't really want to spend time trying lots of different values for max lenght and for the x offset.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@HaveFun91 and @zenseii , thank you so much for handling this issue!
