### PR TITLE
Battlefield. Fix rendering of high obstacles

### LINKED ISSUE #7083: Combat screen, sprite of the obstacle should be displayed over the sprite of the creature
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the sprite of the obstacle should be displayed over the sprite of the creature (a titan in the example).

Not sure this obstacle is used in the original game.

The position of the sprite could also be adjusted by 4 pixels downwards, as the obstacle seems a bit "off-center" vertically in relation to the hexagon.

In fheroes2:

Creature sprite over obstacle 001

Creature sprite over obstacle 002

### Save file

Here is the test scenario file:
[0 9923b.zip](https://github.com/ihhub/fheroes2/files/11133075/0.9923b.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #7083 

This PR moves two "not flat" obstacles to the "high" obstacles rendering function.

This PR:
img

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -2399,6 +2399,7 @@ void Battle::Interface::RedrawCastleMainTower( const Castle & castle )
     fheroes2::Blit( sprite, _mainSurface, sprite.x(), sprite.y() );
 }
 
+// Draws cracks and pools that are not higher than the ground level.
 void Battle::Interface::RedrawLowObjects( const int32_t cellId )
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:2403]: Since we are modifying this code should we move the comment into the header file as also rename this method into `RedrawGroundObjects` so it would be much more obvious what this method does?

File: src/fheroes2/battle/battle_interface.cpp [hunk 2]
```diff
@@ -2438,6 +2433,7 @@ void Battle::Interface::RedrawLowObjects( const int32_t cellId )
     fheroes2::Blit( objectSprite, _battleGround, pt.x + pt.width / 2 + objectSprite.x(), pt.y + pt.height + objectSprite.y() + cellYOffset );
 }
 
+// Draws trees, rocks, bushes and other objects that are higher than the ground level.
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:2436]: Please move the comment into the header.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I added 2 comments regarding the styling of the solution. Would you mind to check it?

File: src/fheroes2/battle/battle_interface.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/battle/battle_interface.cpp]: Done)

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this improvement in rendering!
