### PR TITLE
Set starting hero and player information for RMG maps

### LINKED ISSUE #10415: Player information is not set for RMG maps
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Generate any map and try to set a player color on a Mine:

Image

Image

### Save file

No need.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #10415.

Exposed `updatePlayerRelatedObjects` helper that sets world object up according the the map format.

### CODE REVIEW

File: src/fheroes2/maps/map_format_info.cpp [hunk 1]
```diff
@@ -94,7 +94,7 @@ namespace
     constexpr uint16_t minimumSupportedVersion{ 2 };
 
     // Change the version when there is a need to expand map format functionality.
-    constexpr uint16_t currentSupportedVersion{ 10 };
+    constexpr uint16_t currentSupportedVersion{ 11 };
```
Comment (ihhub) [inline src/fheroes2/maps/map_format_info.cpp]: Hi @idshibanov , while this solution works, I think using this flag we might end up forcing us implementing a UI option for this as map makers would definitely see the difference in maps. I don't think we would like to change UI right now as the current map information window has no space for it.

I suggest instead of these changes to literally place heroes in front of castles at the time of generating a map. You can do this with the following code:
```cpp
Maps::addObjectToMap( _mapFormat, tile.GetIndex(), groupType, static_cast<uint32_t>( objectIndex ) );
```

We purposefully didn't add this option in the Editor to avoid confusion for map makers and give them better control of objects.

What do you think?

Comment (idshibanov) [reply src/fheroes2/maps/map_format_info.cpp]: Agreed, that was my initial approach. Updated the PR.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@idshibanov , many thanks for the fixes!
