### PR TITLE
Optimize Adventure Map: cache fog directions, do not render objects under fog, minor optimizations and fixes

### LINKED ISSUE #2169: Adventure map, AI hero's animation interrupted when an AI hero enters a square with the fog of war
In fheroes2, during the AI turn, when an AI hero enters a square with the fog of war, the hero's animation is interrupted.

Set the "Enemy Speed" to "1".
End the turn and observe the movement of the AI hero Jezebel near hero Ector.

In fheroes2:

Ai hero anim fog of war fh2 01

vlcsnap-2020-11-05-16h32m25s759 cercle

Here is the save file:
[Ai hero animation fog of war.zip](https://github.com/ihhub/fheroes2/files/5495420/Ai.hero.animation.fog.of.war.zip)

### PR DESCRIPTION
**Pull request by Districh-ru**
An attempt to optimize rendering of adventure map.
1. Fog direction is updated only:
- On human turn start (fully).
- On ally turn start in Hot Seat mode (fully).
- When fog is cleared (only in the area of cleared tiles plus 1 extra tile from each side).
- After using Magelan Maps (fully).

2. All map objects are not rendered if the map tile is fully under the fog.

3. Slightly optimized render of map objects: after forming a double end queue (deque) with objects the second loop through map tiles and search for object in deque using find() is not performed, the objects are rendered one by one from the deque.

4. Fixed bug: shadow is partly rendered over a boat sailing diagonally (relates to [#5716](https://github.com/ihhub/fheroes2/issues/5716)):
fheroes2 2023-03-12 18-52-37-613
The same was when hero moves diagonally down, but not so noticeable.

5. Fixed bug: Alchemist lab flag appears only when the roof is visible on the screen (relates to [#5716](https://github.com/ihhub/fheroes2/issues/5716)):

https://user-images.githubusercontent.com/113276641/224557371-ca726dc5-fab2-4567-a2c6-ea474c7027d8.mp4

The same bug was also for the Ghosts above the Abandoned mine.

<details><summary>Abandoned Mine video</summary>

https://user-images.githubusercontent.com/113276641/224569553-ddb6a3e5-cc46-4306-8490-ef23799906a6.mp4

</details>

6. The fog recover method  (world.ClearFog()) for all castles, heroes and mines now is called once on the map start, there is no need to do it on the start of every turn (it produces bugs when giving control to AI in Debug version and there are other AI allies).

7. Path icon is removed after a hero/boat makes a turn (relates to [#5716](https://github.com/ihhub/fheroes2/issues/5716)):

fheroes2 2023-03-12 20-42-14-819_

8. "Speed-up" AI hero movement calculations under the fog: do not calculate fog directions for every AI hero move under the fog as they are already cached in `_fogDirection`.

9. Fix #2169

This PR makes drastic changes in Adventure Map rendering algorithm and should be thoroughly tested. :)

### CODE REVIEW

**Review by Branikolog — APPROVED** [review]

File: src/fheroes2/game/game_startgame.cpp [hunk 1]
```diff
@@ -695,7 +702,15 @@ fheroes2::GameMode Interface::Basic::StartGame()
...
-                    world.ClearFog( player->GetColor() );
+#if defined( WITH_DEBUG )
+                    if ( player->isAIAutoControlMode()
+                         || ( conf.IsGameType( Game::TYPE_HOTSEAT ) && Players::isFriends( player->GetColor(), Players::HumanColors() ) ) ) {
+#else
+                    if ( conf.IsGameType( Game::TYPE_HOTSEAT ) && Players::isFriends( player->GetColor(), Players::HumanColors() ) ) {
+#endif
+                        // Fully update fog directions for allied AI players in Hot Seat mode as the previous move could be done by opposing player.
+                        Interface::GameArea::updateMapFogDirections();
+                    }
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:713]: To avoid code duplication we can do like this:
```cpp
const bool isFriendlyAI = conf.IsGameType( Game::TYPE_HOTSEAT ) && Players::isFriends( player->GetColor(), Players::HumanColors() );

#if defined( WITH_DEBUG )
if ( isFriendlyAI || player->isAIAutoControlMode() ) {
#else
if ( isFriendlyAI ) {
#endif
    // Fully update fog directions for allied AI players in Hot Seat mode as the previous move could be done by opposing player.
    Interface::GameArea::updateMapFogDirections();
}
```

What do you think about this?

File: src/fheroes2/game/game_startgame.cpp [hunk 2]
```diff
@@ -765,6 +780,8 @@ fheroes2::GameMode Interface::Basic::HumanTurn( bool isload )
     radar.SetHide( false );
     statusWindow.Reset();
     gameArea.SetUpdateCursor();
+    // Fully update fog directions at the start of player's move.
+    Interface::GameArea::updateMapFogDirections();
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:784]: Is there a reason of doing it or we are being precautious? Should we update directions after we load tiles from a save?

File: src/fheroes2/maps/maps_tiles.cpp [hunk 3]
```diff
@@ -2484,220 +2484,261 @@ void Maps::Tiles::ClearFog( const int colors )
...
 {
-    const fheroes2::Point & mp = Maps::GetPoint( _index );
+    // This method should not be called for a tile without fog.
+    assert( _fogDirection != Direction::UNKNOWN );
 
-    const int around = GetFogDirections( color );
+    const fheroes2::Point & mp = Maps::GetPoint( _index );
 
-    if ( DIRECTION_ALL == around ) {
+    if ( DIRECTION_ALL == _fogDirection ) {
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:2537]: What if we cache all directions into a map? Would it be a faster solution?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I left several comments in this pull request. Would you mind to take a look at them?

File: src/fheroes2/ai/ai_hero_action.cpp [hunk 4]
```diff
@@ -705,6 +705,12 @@ namespace
             hero.SetVisited( dst_index, Visit::GLOBAL );
             hero.setVisitedForAllies( dst_index );
             world.ActionForMagellanMaps( hero.GetColor() );
+
+            if ( Players::isFriends( hero.GetColor(), Players::HumanColors() ) ) {
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/ai/ai_hero_action.cpp:709]: Hi, @ihhub.
I did not put this logic into `world.cpp` as it does not contain code for interface and does not `#include "interface_gamearea.h"` or `"map_tiles.h"`.
But this logic can be placed there and work for both Human and AI-friend player.
If you think it is OK I can move the **updateMapFogDirections()** to `world.cpp`.

File: src/fheroes2/game/game_startgame.cpp (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp:784]: For a single player game we can update all fog directions after we load a map/save. In Hot Seat mode we need to update it for each player.
I'll put the fog directions update after map load and add a condition here: if `conf.IsGameType( Game::TYPE_HOTSEAT )`

File: src/fheroes2/ai/ai_hero_action.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (oleg-derevenetz) [reply src/fheroes2/ai/ai_hero_action.cpp:709]: Hi @ihhub to be honest I don't like an idea to over-mix the game logic with UI. They are already a bit over-mixed for my taste.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 5]
```diff
@@ -2484,220 +2484,261 @@ void Maps::Tiles::ClearFog( const int colors )
...
 }
 
-void Maps::Tiles::drawFog( fheroes2::Image & dst, int color, const Interface::GameArea & area ) const
+void Maps::Tiles::drawFog( fheroes2::Image & dst, const Interface::GameArea & area ) const
 {
-    const fheroes2::Point & mp = Maps::GetPoint( _index );
+    // This method should not be called for a tile without fog.
+    assert( _fogDirection != Direction::UNKNOWN );
 
-    const int around = GetFogDirections( color );
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2506]: Calculating directions for the whole map is more computation expensive task comparing to a single render of Adventure map for 640x480 game resolution by currently used `around = GetFogDirections( color )` approach. Especially for big maps.
In map viewing mode (no hero moves) we render 4 frames per second. For 640x480 resolution we have 14*14=196 tiles to get fog direction. Computing fog directions for 144x144 map will be: 144*144/196 = 105,8 times more expensive (it is equal to 26,5 seconds of rendering with current approach).
Yes, it is expensive. :(
But if the player spends more than half of minute for a turn it reduces the mean CPU usage.
Also we have to take into account that player, as i think, use resolutions more than 640x480. And when hero moves or player drags the map the more Redraws per second are performed.

Also this information is used for rendering other parts of the map, which also reduces the CPU usage.

For a Single player I'll address your comment and make the full recalculation of fog directions only on map load.
For Hot Seat we can redo the shading adventure map on player change: not recalculate the fog, but simply render fog image in the place of adventure map.
I can try to do it in a separate PR, currently I'll put a TODO for this.

I'll also place a TODO for making an array for all human players. I thought about it, but did not do as when making this array we have to take into account that there are alliances and fog directions are the same in one alliance. This can be done. :)

I'll also try tomorrow to redo the **updateFogDirectionsInArea()** to avoid using of **!Maps::isValidDirection( _index, it )** and **Maps::GetDirectionIndex( _index, it )**

Thanks @ihhub the tip on how to do a better optimization.

File: src/fheroes2/game/game_startgame.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp:713]: Sure, thanks!

File: src/fheroes2/maps/maps_tiles.h [hunk 6]
```diff
@@ -263,9 +263,20 @@ namespace Maps
...
 
-        void drawFog( fheroes2::Image & dst, int color, const Interface::GameArea & area ) const;
+        // Determine the fog direction in the area between min and max positions for given player(s) color code and store it in corresponding tile data.
+        static void updateFogDirectionsInArea( const fheroes2::Point & minPos, const fheroes2::Point & maxPos, const int32_t color );
+        // Determine the fog direction by fog data for given color code of player(s) and store it in tile data.
+        void updateFogDirection( const int32_t color );
+        // Return the fog direction by fog data for given color code of player(s).
+        uint16_t getFogDirection( const int32_t color ) const;
+        // Return fog direction of tile. A tile without fog returns "Direction::UNKNOWN".
+        uint16_t getFogDirection() const
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.h:274]: OK. :)

File: src/fheroes2/maps/maps_tiles.cpp (hunk 3 above)
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2537]: Do you mean to make an array in **World** class?
I made a cache in **Tiles** as we have to keep fog direction for every map tile. And while rendering the Adventure map the fog direction for current tile is mostly used (only in some places we check the fog direction of neighbor tile).
Maybe some calls will be faster, but we will have to calculate tile index for every fog direction call. While in this PR we simply call `if ( tile.getFogDirection() == DIRECTION_ALL && drawFog )` to check do we need to render map objects.

File: src/fheroes2/maps/maps_tiles.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2506]: Hi @ihhub,  we calculate fog direction by checking an array of directions and if there is fog we logically add this direction to _fogDirection. So we can not avoid the use of directions and the best way to access tiles around knowing the direction is using **GetDirectionIndex()**.
But as we know the world size and the tile index we can check for index outside the world without use of **isValidDirection()**.
I redone the logic of this check and it gives up to 40% computation speed increase: from 0.8-1 ms to 0.45-0.55 ms full fog directions update for XL maps with uncovered fog.

The other approach could be: caching all fog data to avoid many calls of **isFog()** and than calculate fog direction using directions pattern and this cached fog. This approach will force us to make a vector for isFog data.

[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2506]: I updated the fog directions calculation logic and quick tested it on a couple maps. It gives a performance boost in the release build.
@ihhub, could you please check the new code when you have time.

File: src/fheroes2/ai/ai_hero_action.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/ai/ai_hero_action.cpp:709]: Good points, guys.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 7]
```diff
@@ -2442,262 +2442,348 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
-            if ( !world.GetTiles( centerY + x ).isFog( color ) ) {
-                return false;
+    std::vector<bool> isFog( static_cast<size_t>( fogWidth ) * fogHeight, true );
+    std::vector<bool>::iterator isFogIter = isFog.begin();
+    const int32_t worldSize = static_cast<int32_t>( world.getSize() );
+
+    // Cache the 'isFog' data for the given area to use it in fog direction calculation.
+    for ( int32_t y = fogMinY; y < fogMaxY; ++y ) {
+        for ( int32_t x = fogMinX; x < fogMaxX; ++x ) {
+            const int32_t fogTileIndex = x + y * worldWidth;
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:2481]: `y * worldWidth` can be cached in the loop above. The performance depends on the number of elements.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I left few more suggestions in this pull request. Could you please check them when you have some time?

File: src/fheroes2/maps/maps_tiles.cpp [hunk 8]
```diff
@@ -2442,262 +2442,348 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
+    const int32_t fogMinX = minX - 1;
+    const int32_t fogMinY = minY - 1;
+    const int32_t fogMaxX = maxX + 1;
+    const int32_t fogMaxY = maxY + 1;
+    const int32_t fogWidth = fogMaxX - fogMinX;
+    const int32_t fogHeight = fogMaxY - fogMinY;
 
-            if ( !world.GetTiles( centerY + x ).isFog( color ) ) {
-                return false;
+    std::vector<bool> isFog( static_cast<size_t>( fogWidth ) * fogHeight, true );
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2474]: Hi @ihhub, thanks for the advice.
Using **uint8_t** here made fog directions calculation to run up to 2 times faster.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 9]
```diff
@@ -2442,262 +2442,348 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
+    std::vector<bool>::iterator isFogIter = isFog.begin();
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp]: Hi, @ihhub, I used access to the vector by index to avoid using of iterators. It also slightly simplified the vector accessing logic.

**Comment by ihhub** [comment]
Hi @Districh-ru do these changes fix #2169 as well?

File: src/fheroes2/game/game_startgame.cpp [hunk 10]
```diff
@@ -695,7 +711,33 @@ fheroes2::GameMode Interface::Basic::StartGame()
                     Redraw();
                     display.render();
 
-                    world.ClearFog( player->GetColor() );
+                    if ( isHotSeatGame ) {
+                        int32_t friendColors = 0;
+
+                        const bool isFriendlyAI = Players::isFriends( player->GetColor(), Players::HumanColors() );
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:717]: Could you please explain more this new chunk of code? I don't really understand why we do only for hot-seat and why we can't directly use **player->GetFriends()** and use binary AND with **Players::HumanColors()**?

Also I suggest to move calculations of friend colors into a separate method and this function has become too large.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put few more comments and questions. Would you mind to check them?

File: src/fheroes2/game/game_startgame.cpp [hunk 11]
```diff
@@ -596,6 +596,20 @@ fheroes2::GameMode Interface::Basic::StartGame()
...
 
+    if ( !loadedFromSave ) {
+        // Clear fog around heroes, castles and mines for all players when starting a new map.
+        for ( const Player * player : sortedPlayers ) {
+            world.ClearFog( player->GetColor() );
+        }
+    }
+
+    const bool isHotSeatGame = conf.IsGameType( Game::TYPE_HOTSEAT );
+
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp:607]: Sure!)

File: src/fheroes2/game/game_startgame.cpp (hunk 10 above)
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp]: Hi @ihhub, I moved these calculations into a separate method in Anonymous namespace.

Currently in fheroes2 in Hot Seat mode all moves of all human players allies are shown and the enemy AI movement is shown on tiles discovered from fog by all human players.
In master build it is done "automatically" as fog directions are generated on every gameArea render.
In this PR we cache fog directions so we have to recalculate them in this case.
In Single player there is no need to do this as we always have one fog directions cache for the only human player (and his allies).

Maybe it is not perfectly correct, but this is how fheroes2 master build works now. And there could be quections: if human players are enemies in Hot Seat mode then they will be able to see area of each other while AI moves.
But lets first discuss (if needed) how Hot Seat mode should work in these situations (in a separate discussion) and solve Hot Seat related issues in a separate PR.

So we cannot simply use **player->GetFriends()** as it will give me current AI friends colors and this is needed only if this AI player is an ally of one of human players.

File: src/fheroes2/maps/maps.cpp [hunk 12]
```diff
@@ -344,6 +345,7 @@ void Maps::ClearFog( const int32_t tileIndex, int scoutingDistance, const int pl
     }
 
     const int alliedColors = Players::GetPlayerFriends( playerColor );
+    const bool isHumanOrHumanFriend = Players::isFriends( playerColor, Players::HumanColors() ) || !isAIPlayer;
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps.cpp]: OK.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 13]
```diff
@@ -2442,262 +2442,347 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
+    // The fog might be cleared even without the hero's movement - for example, the hero can gain a new level of Scouting
+    // skill by picking up a Treasure Chest from a nearby tile or buying a map in a Magellan's Maps object using the space
+    // bar button. Reset the pathfinder(s) to make the newly discovered tiles immediately available for this hero.
+    world.resetPathfinder();
+}
 
-        const int32_t centerY = center + y * width;
+void Maps::Tiles::updateFogDirectionsInArea( const fheroes2::Point & minPos, const fheroes2::Point & maxPos, const int32_t color )
+{
+    const int32_t worldWidth = world.w();
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2459]: Sure, I added assertion.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 14]
```diff
@@ -2442,262 +2442,347 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
+
+        for ( int32_t x = fogMinX; x < fogMaxX; ++x ) {
+            fogData[x + fogDataOffsetY] = world.GetTiles( x + fogTileOffsetY ).isFog( color ) ? 1 : 0;
         }
     }
 
-    return true;
-}
+    // Set the 'fogData' index offset from the tile index for the TOP LEFT direction from the tile.
+    const int32_t TopLeftDirectionOffset = -1 - fogDataWidth;
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp]: Ow, for some unknown reason I named it from a capital letter.
Done. :)

File: src/fheroes2/game/game_startgame.cpp [hunk 15]
```diff
@@ -90,6 +90,37 @@ namespace
         return ( player1->isControlHuman() && !player2->isControlHuman() )
                || ( ( player1->isControlHuman() == player2->isControlHuman() ) && ( player1->GetColor() < player2->GetColor() ) );
     }
+
+    void updateFogDirectionsForHotSeatAIMove( const Player * player )
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:94]: I initially meant to create a function called **getAIFriends()** which will return an integer. Then inside the original switch case we could call:
```cpp
Maps::Tiles::updateFogDirectionsInArea( { 0, 0 }, { world.w(), world.h() }, getAIFriends( player ) );
```
To be consistent with the same code for human players which has **updateFogDirectionsInArea()** call as well.

I am still fine with the current approach, just the name of the function is too complex :)

File: src/fheroes2/game/game_startgame.cpp [hunk 16]
```diff
@@ -90,6 +90,37 @@ namespace
...
+    {
+        int32_t friendColors = 0;
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:96]: Should we check or assert that the player is AI? Also we should assert **player**.

**Review by ihhub — COMMENTED** [review]
Hi @Districh-ru , everything looks good to me. I left 2 more comments to polish the code, which don't affect the logic.

File: src/fheroes2/game/game_startgame.cpp (hunk 15 above)
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp]: Hi @ihhub, the logic for friends is currently complex and in one case it returns friend color for one human player and in the other - for all human players (and they can be hostiles for the current AI). And it has to be currently used in Hot Seat mode. But IMHO it should be changed in future: uncovering for for friends of all human players is not a good idea, but first we have to discuss how to behave in Hot Seat at all.
So I made a separate function for all Hot Seat fog uncover for AI. Doing so I also slightly separated this mode from the unified code for all modes.
I renamed the function to **hotSeatAIFogColors()** and made it to return int for **updateFogDirectionsInArea()** as you proposed. :)

File: src/fheroes2/game/game_startgame.cpp (hunk 16 above)
Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp]: I added an assertion for **player** and another one to assert that it is AI move - it won't be worse if we check it as this function is not made for human players: it will work, but it is too complex for this case.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please take a sneak peak on this pull request when you have time? I know that you haven't dig into rendering code but you might find some obvious mistakes which we missed🙂

**Comment by oleg-derevenetz** [comment]
@ihhub yes of course, I'll do it later today.

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 17]
```diff
@@ -470,21 +474,36 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
...
+
             switch ( objectType ) {
             case MP2::OBJ_HEROES: {
-                if ( !drawHeroes ) {
-                    continue;
+                const bool isUpperTileUnderFog = ( posY > 0 ) ? ( world.GetTiles( posX, posY - 1 ).getFogDirection() == DIRECTION_ALL ) : true;
+                const Heroes * hero = tile.GetHeroes();
+
+                // Boats are 2 tiles high so for hero on the boat we have to populate info for boat one tile lower than the fog.
+                if ( !drawHeroes || ( isTileUnderFog && ( isUpperTileUnderFog || !hero->isShipMaster() ) ) ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/gui/interface_gamearea.cpp:492]: Why we still can draw heroes here even if `drawHeroes` is `false`?

File: src/fheroes2/gui/interface_gamearea.h [hunk 18]
```diff
@@ -217,6 +217,8 @@ namespace Interface
             updateCursor = true;
         }
 
+        static void updateMapFogDirections();
```
Comment (oleg-derevenetz) [inline src/fheroes2/gui/interface_gamearea.h:220]: It would be good to add/update the descriptions to the new/heavily reworked functions in headers to describe (in general terms) what they do and what they return.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 19]
```diff
@@ -2468,262 +2468,347 @@ std::pair<uint32_t, uint32_t> Maps::Tiles::GetMonsterSpriteIndices( const Tiles
...
+            if ( fogData[fogDataIndex] == 0 ) {
+                // For the tile is without fog we set the UNKNOWN direction.
+                tile._setFogDirection( Direction::UNKNOWN );
+            }
+            else {
+                // The tile is under the fog so its CENTER direction for fog is true.
+                uint16_t fogDirection = Direction::CENTER;
+
+                // Check all tiles around for 'fogData' starting from the top left direction and if it is true then logically add the direction to 'fogDirection'.
+                fogDataIndex += topLeftDirectionOffset;
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles.cpp:2543]: Can the `fogDataIndex` become negative here (for example near top left edge of the map)? Can it become too big (out of `fogData` range) later after all these increments?

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @Districh-ru I usually don't touch map rendering, so I left a few questions, could you please take a look when you have time?

File: src/fheroes2/gui/interface_gamearea.cpp (hunk 17 above)
Comment (Districh-ru) [reply src/fheroes2/gui/interface_gamearea.cpp]: Hi @oleg-derevenetz, thanks for the review.
This is a regression: we will render all not moving AI heroes. I reverted the initial check for `!drawHeroes` and do all other checks after it.

File: src/fheroes2/gui/interface_gamearea.h (hunk 18 above)
Comment (Districh-ru) [reply src/fheroes2/gui/interface_gamearea.h:221]: I added a short description for this function and for other new one in `game_startgame.cpp`

File: src/fheroes2/maps/maps_tiles.cpp (hunk 19 above)
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2543]: After the first implementation of this approach I put here assertions for these cases. And after checks I removed them to speed-up this code.

`fogDataIndex` is equal to x + fogCenterDataOffsetY =  x + y * fogDataWidth + 1 - minX + ( 1 - minY ) * fogDataWidth  =
= ( x + 1 - minX ) + ( y + 1 - minY ) * fogDataWidth

And if we add `topLeftDirectionOffset` = -1 - fogDataWidth we will get:
( x + 1 - minX ) + ( y + 1 - minY ) * fogDataWidth -1 - fogDataWidth =
=  ( x - minX ) + ( y - minY ) * fogDataWidth

For the top left edge where minX and MinY are equal to 0  we will get: ( 0 - 0 ) + ( 0 - 0 ) * fogDataWidth = 0.

The same is for the other edge case, fogDataWidth and fogDataHeight both includes extra 2 tiles and here we shift 2 tiles to the right and 2 to the bottom after all increments..

Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles.cpp:2543]: I don't know whether the absence of assertions gives any noticeable gain, and if this gain is not actually noticeable, I recommend to bring them back. Even if now the logic looks good, assertions are useful to protect against programming errors in future if logic is changed somehow. They can be turned off if needed by defining the `NDEBUG`macro (it is defined for Android release builds, but not for Windows release builds yet).

Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.cpp:2549]: Thanks for the explanation. I added assertions.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 20]
```diff
@@ -2522,6 +2522,9 @@ void Maps::Tiles::updateFogDirectionsInArea( const fheroes2::Point & minPos, con
     // Set the 'fogData' index offset from the tile index for the TOP LEFT direction from the tile.
     const int32_t topLeftDirectionOffset = -1 - fogDataWidth;
 
+    // Cache the maximum border for fogDataIndex corresponding the "CENTER" tile to use in assertion. Should be removed if assertion is removed.
+    const int32_t centerfogDataIndexLimit = fogDataSize + topLeftDirectionOffset;
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles.cpp:2526]: Shouldn't this be `fogDataSize + ( topLeftDirectionOffset * 2 )`?

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , huge thanks for these improvements!
