### PR TITLE
Fix constantly moving AI heroes when they have nothing to do

### LINKED ISSUE #5650: Adventure map, AI being stuck on a small area is running non-stop
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A couple AI heroes being stuck on a small island run in panic on a few squares wasting their movement points.
image
I think these heroes should stay waiting other hero visit their island. Lookin at them running purposelessly is a waste of player's time.

### Save file

[Pirate_Utopia_0054.zip](https://github.com/ihhub/fheroes2/files/9112974/Pirate_Utopia_0054.zip)
Multiplayer save.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
It is also much faster as we do not need to recalculate the map for a hero.

close #5650

### CODE REVIEW

File: src/fheroes2/world/world_pathfinding.cpp [hunk 1]
```diff
@@ -679,61 +679,108 @@ int AIWorldPathfinder::getNearestTileToMove( const Heroes & hero )
 
 bool AIWorldPathfinder::isHeroPossiblyBlockingWay( const Heroes & hero )
 {
-    // paths have to be pre-calculated to find a spot where we're able to move
-    reEvaluateIfNeeded( hero );
+    const int heroIndex = hero.GetIndex();
```
Comment (oleg-derevenetz) [inline src/fheroes2/world/world_pathfinding.cpp:682]: Strictly speaking, the map index is `int32_t`, not `int`. While they are usually the same, this may not always be the case.

File: src/fheroes2/world/world_pathfinding.cpp [hunk 2]
```diff
@@ -679,61 +679,108 @@ int AIWorldPathfinder::getNearestTileToMove( const Heroes & hero )
...
+    // |   | o |   |
+    // | o | H | o |
+    // | x | r | x |
+    if ( bottomReachable && ( topReachable || leftReachable || rightReachable ) && !bottomLeftReachable && !bottomRightReachable ) {
         return true;
     }
 
     // Is the hero standing on Stoneliths?
-    return world.GetTiles( start ).GetObject( false ) == MP2::OBJ_STONELITHS;
+    return world.GetTiles( heroIndex ).GetObject( false ) == MP2::OBJ_STONELITHS;
```
Comment (oleg-derevenetz) [inline src/fheroes2/world/world_pathfinding.cpp:783]: How about the following scenario:

```
|   | r | x |
| x | H | o |
|   | o |   |
```

? Is it possible that the hero will block the way in this case? Maybe just count the number of passable and impassable cells around the hero and assume that he can block the way if there are at least 2 impassable cells and 2 passable cells nearby at the same time? This is of course a bit pessimistic, but this should cover all the cases.

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @ihhub I just left a few notes and questions, please take a look when you have time.

File: src/fheroes2/world/world_pathfinding.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:682]: Sure. I will fix it.

File: src/fheroes2/world/world_pathfinding.cpp (hunk 2 above)
Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:783]: We cannot just count the number of tiles. Consider this example:
```
    // | x | x | x |
    // | r | H | r |
    // | r | r | r |
```
A hero is just standing near a "wall" like he doesn't block any other way.

Comment (oleg-derevenetz) [reply src/fheroes2/world/world_pathfinding.cpp:783]: That's why I call it pessimistic - due to possible false positives.

Comment (oleg-derevenetz) [reply src/fheroes2/world/world_pathfinding.cpp:783]: We can also try to count passable/impassable cells on each side separately and consider the hero as possibly blocking if there are at least 2 impassable cells on 2 different sides and at least 2 passable cells on 2 different sides.

Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:783]: This pull request is aimed to avoid false positives which we have right now. I will check your idea.

Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:811]: Hi @oleg-derevenetz , I couldn't find a proper dependency between cell positions without introducing false positives. So far if a non-passable cell is left/right/bottom/top then it has 3 combinations with another non-passable cells. If a cell is a corner then it has 4 combinations. I checked everything and the logic covers all possible cases. We can simplify the logic if needed.

Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:811]: The complexity of this solution is much lower in comparison with previous solution.

**Review by oleg-derevenetz — APPROVED** [review]
