### PR TITLE
Bring the logic of calculating experience and losses in line with the logic of the original game

### LINKED ISSUE #10020: Raised ghosts that are killed in immediate retaliation don't count towards total killed
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Reported by MoucheronQuipet on discord:
There's a weird bug where sometimes, extra ghosts spawned during a fight don't count in the kill feed at the end of the battle (and don't provide XP). For the setup I use you need to loose an unit and then let the ghosts attack you a second time, and if they kill one of your units and you kill them with the retaliation, in that specific case the extra ghost don't seem to register. 

https://www.youtube.com/watch?v=_LWupuBjFtE

It also happens during Phixfox's fight here:

https://www.youtube.com/watch?v=IhetRaCo0VM&t=10900s

### Save file

None needed. Steps to reproduce are shown in the video above.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #10020

<details>
<summary>1. Ghosts: losses, experience and Necromancy</summary>

`master` branch:

https://github.com/user-attachments/assets/ef61be86-03a6-4eb2-aa7d-94129a6405dd

OG behavior:

https://github.com/user-attachments/assets/68929300-155e-47bb-859a-a0c660105eb4

This PR:

https://github.com/user-attachments/assets/ddacfae2-3ebc-42a6-b79a-080d0210a3db
</details>

<details>
<summary>2. Resurrect spell and Necromancy</summary>

`master` branch:

https://github.com/user-attachments/assets/07105b60-e6b6-4d1d-92b9-7e1aeaae30fe

OG behavior:

https://github.com/user-attachments/assets/a1b68a3e-cba7-497c-8f80-fd1fbf8aca78

This PR:

https://github.com/user-attachments/assets/dc227a9a-4a06-4409-8b47-a962a5902880
</details>

So far, these are all the differences with the original game that I have found (and fixed). If there are any more, please let me know.

Also, as part of this PR, I renamed some variables and functions in a more understandable (from my point of view) way.

### CODE REVIEW

File: src/fheroes2/battle/battle_army.h [hunk 1]
```diff
@@ -149,9 +152,28 @@ namespace Battle
         void resetIdleAnimation() const;
 
         void NewTurn();
-        void SyncArmyCount();
+
+        void syncOriginalArmy() const;
 
     private:
+        template <typename T>
+        void applyActionToTroopsFromOriginalArmy( const T & action ) const
```
Comment (Districh-ru) [inline src/fheroes2/battle/battle_army.h]: Just to follow the code style we can add `_` at the beginning of the private method's name:

```suggestion
        void _applyActionToTroopsFromOriginalArmy( const T & action ) const
```

File: src/fheroes2/battle/battle_main.cpp [hunk 2]
```diff
@@ -448,64 +452,65 @@ Battle::Result Battle::Loader( Army & army1, Army & army2, int32_t mapsindex )
...
-    return exp1;
+    return attackerExperience;
 }
 
-uint32_t Battle::Result::GetExperienceDefender() const
+uint32_t Battle::Result::getDefenderExperience() const
 {
-    return exp2;
+    return defenderExperience;
 }
```
Comment (Districh-ru) [inline src/fheroes2/battle/battle_main.cpp]: What do you think about making these getters inline?

File: src/fheroes2/battle/battle_army.cpp [hunk 3]
```diff
@@ -270,40 +271,36 @@ bool Battle::Force::HasMonster( const Monster & mons ) const
...
 
-        troop->SetCount( unit->GetDead() > unit->GetInitialCount() ? 0 : unit->GetInitialCount() - unit->GetDead() );
-    }
+    return result;
+}
+
+void Battle::Force::syncOriginalArmy() const
+{
+    applyActionToTroopsFromOriginalArmy(
+        []( Troop & troop, const Unit & unit ) { troop.SetCount( unit.GetDead() > unit.GetMaxCount() ? 0 : unit.GetMaxCount() - unit.GetDead() ); } );
```
Comment (Districh-ru) [inline src/fheroes2/battle/battle_army.cpp]: What about using `>=` for the condition so when `unit.GetMaxCount()` and `unit.GetDead()` are equal their difference is `0` and there is no need to calculate it.
```suggestion
        []( Troop & troop, const Unit & unit ) { troop.SetCount( unit.GetDead() >= unit.GetMaxCount() ? 0 : unit.GetMaxCount() - unit.GetDead() ); } );
```

File: src/fheroes2/battle/battle_main.cpp (hunk 2 above)
Comment (oleg-derevenetz) [reply src/fheroes2/battle/battle_main.cpp]: To be honest, I don't really know why they are needed, given that the corresponding members are public. But let them stay for now.

Comment (Districh-ru) [reply src/fheroes2/battle/battle_main.cpp]: Sure.
I thought the same about the need of these methods.

**Review by Districh-ru — APPROVED** [review]

**Comment by zenseii** [comment]
Hi, @oleg-derevenetz. Feel free to move ahead with this PR because I won't have time to look at it until at the earliest Thursday. I agree with the changes on a general basis.

**Comment by ihhub** [comment]
@oleg-derevenetz , many thanks for these changes!
