### PR TITLE
Fix crash while an AI hero captures a castle

### LINKED ISSUE #7377: Assertion failure in the AI::Normal::updatePriorityTargets()
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Related to #7289

How to reproduce:

1. Apply changes from #7376 (without them, you won't get to this point);
2. Load the attached save file;
3. Press F8 to transfer the control to AI;
4. Wait until the red Knight Maerlin begins to attack the orange Barbarian Fineous in the Lakeside Warlock castle.

### Save file

[Crash.zip](https://github.com/ihhub/fheroes2/files/11931934/Crash.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7377

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_hero.cpp [hunk 1]
```diff
@@ -1949,6 +1949,14 @@ namespace AI
         switch ( task.type ) {
         case PriorityTaskType::DEFEND:
         case PriorityTaskType::REINFORCE: {
+            if ( objectType == MP2::OBJ_HEROES ) {
+                // The castle has just captured. No task should be updated.
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_hero.cpp:1953]: I suppose here is a typo: "The castle has just been captured".

**Review by oleg-derevenetz — APPROVED** [review]
Hi @ihhub I only found one typo in the comment. LGTM.
