### PR TITLE
*nix case insensitive file access

### LINKED ISSUE #429: *nix case insensitive file access
Project have an `script/demo/demo_linux.sh` that will download zip, after extraction data directory named by default as "DATA", but program will attempt to access with naming as "data", which will fail on *nix systems, to avoid this need to rename it manually. I think that fheroes2 need case-insensitive file access to be more friendly for new users. In addition different HOMM2 distributives could have different naming and manual renaming on *nix is a time wasting.

### PR DESCRIPTION
**Pull request by shprotru**
Adds case insensitive file access on *nix systems
Closes #429

### CODE REVIEW

File: src/engine/dir.cpp [hunk 1]
```diff
@@ -48,33 +48,38 @@ void ListFiles::ReadDir( const std::string & path, const std::string & filter, b
     }
 #else
     // read directory
-    DIR * dp = opendir( path.c_str() );
 
-    if ( dp ) {
-        struct dirent * ep;
-        while ( NULL != ( ep = readdir( dp ) ) ) {
-            const std::string fullname = System::ConcatePath( path, ep->d_name );
+    char *r = ( char * ) alloca ( strlen( path.c_str() ) + 2 );
```
Comment (ihhub) [inline src/engine/dir.cpp:52]: We strongly discourage **alloca** usage. Please use a normal C++ way such as `std::string` variable.

File: src/engine/dir.cpp [hunk 2]
```diff
@@ -48,33 +48,38 @@ void ListFiles::ReadDir( const std::string & path, const std::string & filter, b
...
+    if ( System::casepath( path.c_str(), r ) )
```
Comment (ihhub) [inline src/engine/dir.cpp:53]: To do not change much the existing code (all code is shifted to the right) we could do something like this:
```
if ( !System::casepath( path.c_str(), r ) )
    return;
and then here existing code.
```

File: src/engine/system.cpp [hunk 3]
```diff
@@ -494,3 +505,79 @@ int System::GetRenderFlags( void )
 #endif
 #endif
 }
+
+#if !defined( _MSC_VER ) || !defined( ANDROID )
+// taked here: https://github.com/OneSadCookie/fcaseopen
+#include <dirent.h>
+int System::casepath( char const *path, char *r )
```
Comment (ihhub) [inline src/engine/system.cpp:512]: This looks like a C-function. The function should accept `const std::string & input, std::string & output)`. **output** variable does not need to be resized before this function call. We could do this inside.

File: src/engine/system.cpp [hunk 4]
```diff
@@ -494,3 +505,79 @@ int System::GetRenderFlags( void )
...
+            rl += strlen( c );
+            last = 1;
+        }
+
+        c = strsep( &p, "/" );
+    }
+
+    if ( d )
+        closedir( d );
+    return 1;
```
Comment (ihhub) [inline src/engine/system.cpp:581]: The function should return `bool` instead.

File: src/engine/system.cpp [hunk 5]
```diff
@@ -494,3 +505,79 @@ int System::GetRenderFlags( void )
...
+}
+#endif
```
Comment (ihhub) [inline src/engine/system.cpp:583]: We should add an empty line at every file. Please add it.

File: src/engine/system.h [hunk 6]
```diff
@@ -95,6 +95,10 @@ namespace System
 
     int ShellCommand( const char * );
     int GetRenderFlags( void );
+
+    #if !defined( _MSC_VER ) || !defined( ANDROID )
```
Comment (ihhub) [inline src/engine/system.h:99]: Please remove all indentation for macro statements.

File: src/engine/system.h [hunk 7]
```diff
@@ -95,6 +95,10 @@ namespace System
...
+    int casepath( char const *path, char *r );
```
Comment (ihhub) [inline src/engine/system.h:100]: Please rename this function into more user-friendly, something like `GetCaseInsensitivePath`

File: src/engine/system.cpp [hunk 8]
```diff
@@ -494,3 +505,79 @@ int System::GetRenderFlags( void )
 #endif
 #endif
 }
+
+#if !defined( _MSC_VER ) || !defined( ANDROID )
+// taked here: https://github.com/OneSadCookie/fcaseopen
+#include <dirent.h>
```
Comment (ihhub) [inline src/engine/system.cpp:511]: We must not add file inclusions in the middle of a file. Also this inclusion breaks Windows builds. Should it be `#if !defined( _MSC_VER ) && !defined( ANDROID )` instead?

File: src/engine/system.h (hunk 6 above)
Comment (shprotru) [reply src/engine/system.h:99]: it's *nix only function, how to cut it otherway for non *nix builds?

File: src/engine/dir.cpp (hunk 1 above)
Comment (shprotru) [reply src/engine/dir.cpp]: resolved, but still inside `GetCaseInsensitivePath`, because original code(linked) used a c-pointer, hope there usage is acceptable

File: src/engine/dir.cpp (hunk 2 above)
Comment (shprotru) [reply src/engine/dir.cpp]: done

File: src/engine/system.cpp (hunk 3 above)
Comment (shprotru) [reply src/engine/system.cpp]: done

File: src/engine/system.cpp (hunk 4 above)
Comment (shprotru) [reply src/engine/system.cpp]: done

File: src/engine/system.cpp (hunk 5 above)
Comment (shprotru) [reply src/engine/system.cpp]: done

File: src/engine/system.h (hunk 7 above)
Comment (shprotru) [reply src/engine/system.h]: done

File: src/engine/system.cpp (hunk 8 above)
Comment (shprotru) [reply src/engine/system.cpp]: done, no, it must not be `#if !defined( _MSC_VER ) && !defined( ANDROID )`.

File: src/engine/system.h (hunk 6 above)
Comment (shprotru) [reply src/engine/system.h]: done

File: src/engine/system.cpp [hunk 9]
```diff
@@ -494,3 +509,76 @@ int System::GetRenderFlags( void )
...
+
+#if !( defined( _MSC_VER ) || defined( __MINGW32CE__ ) || defined( __MINGW32__ ) )
+// taked here: https://github.com/OneSadCookie/fcaseopen
+bool System::GetCaseInsensitivePath( const std::string path, std::string &ci_path )
+{
+    DIR *d;
+    ci_path = "";
+    bool result = false;
+
+    if ( path.length() > 0 ) {
```
Comment (ihhub) [inline src/engine/system.cpp:521]: We could do like this:
```
if ( path.empty() )
    return true;
```

File: src/engine/system.cpp [hunk 10]
```diff
@@ -494,3 +509,76 @@ int System::GetRenderFlags( void )
 #endif
 #endif
 }
+
+#if !( defined( _MSC_VER ) || defined( __MINGW32CE__ ) || defined( __MINGW32__ ) )
+// taked here: https://github.com/OneSadCookie/fcaseopen
+bool System::GetCaseInsensitivePath( const std::string path, std::string &ci_path )
+{
+    DIR *d;
+    ci_path = "";
```
Comment (ihhub) [inline src/engine/system.cpp:518]: `ci_path.clear()` does better.

File: src/engine/system.cpp [hunk 11]
```diff
@@ -494,3 +509,76 @@ int System::GetRenderFlags( void )
...
+    bool result = false;
+
+    if ( path.length() > 0 ) {
+        std::string tmp_path = path;
```
Comment (ihhub) [inline src/engine/system.cpp:522]: If we do not modify `tmp_path` then we do not need to even create this variable.

File: src/engine/system.cpp [hunk 12]
```diff
@@ -494,3 +509,76 @@ int System::GetRenderFlags( void )
...
+        char *p = const_cast<char *>( tmp_path.c_str() );
```
Comment (ihhub) [inline src/engine/system.cpp:523]: Put `const` modifier to this variable. I think we do not modify it.

File: src/engine/dir.cpp [hunk 13]
```diff
@@ -48,12 +48,17 @@ void ListFiles::ReadDir( const std::string & path, const std::string & filter, b
     }
 #else
     // read directory
-    DIR * dp = opendir( path.c_str() );
+
+    std::string ci_path;
```
Comment (ihhub) [inline src/engine/dir.cpp:52]: Let's call this variable with more meaningful name. Something like `convertedPath` or `correctedPath` or `validatedPath`.

File: src/engine/dir.cpp [hunk 14]
```diff
@@ -48,12 +48,17 @@ void ListFiles::ReadDir( const std::string & path, const std::string & filter, b
...
+    if ( !System::GetCaseInsensitivePath( path, ci_path ) )
```
Comment (ihhub) [inline src/engine/dir.cpp:53]: I am thinking to be fully false safe should we return a string from this function instead? No harm to run existing code.
```
const std::string convertedPath = System::GetCaseInsensitivePath( path );
```
and use **convertedPath** below. The same concept applies for other places. What do you think?

File: src/engine/dir.cpp (hunk 1 above)
Comment (shprotru) [reply src/engine/dir.cpp]: completely resolved

File: src/engine/system.cpp [hunk 15]
```diff
@@ -318,12 +322,17 @@ bool System::IsFile( const std::string & name, bool writable )
...
-    if ( stat( name.c_str(), &fs ) || !S_ISREG( fs.st_mode ) )
-        return false;
+    std::string ci_path;
+    if ( GetCaseInsensitivePath( name, ci_path ) )
+    {
+        struct stat fs;
+        if ( stat( ci_path.c_str(), &fs ) || !S_ISREG( fs.st_mode ) )
+            return false;
+
+            return writable ? 0 == access( ci_path.c_str(), W_OK ) : S_IRUSR & fs.st_mode;
```
[the remark this answers is not in the document]
Comment (shprotru) [reply src/engine/system.cpp:332]: done

File: src/engine/system.cpp [hunk 16]
```diff
@@ -318,12 +322,17 @@ bool System::IsFile( const std::string & name, bool writable )
 #elif defined( ANDROID )
     return writable ? 0 == access( name.c_str(), W_OK ) : true;
 #else
-    struct stat fs;
-
-    if ( stat( name.c_str(), &fs ) || !S_ISREG( fs.st_mode ) )
-        return false;
+    std::string ci_path;
+    if ( GetCaseInsensitivePath( name, ci_path ) )
+    {
```
[the remark this answers is not in the document]
Comment (shprotru) [reply src/engine/system.cpp:327]: done

File: src/engine/system.h [hunk 17]
```diff
@@ -95,6 +95,10 @@ namespace System
 
     int ShellCommand( const char * );
     int GetRenderFlags( void );
+
+#if !( defined( _MSC_VER ) || defined( __MINGW32CE__ ) || defined( __MINGW32__ ) )
```
[the remark this answers is not in the document]
Comment (shprotru) [reply src/engine/system.h:99]: done

File: src/engine/system.h [hunk 18]
```diff
@@ -95,6 +95,10 @@ namespace System
...
+    bool GetCaseInsensitivePath( const std::string path, std::string &ci_path );
```
[the remark this answers is not in the document]
Comment (shprotru) [reply src/engine/system.h:100]: done

File: src/engine/system.cpp [hunk 19]
```diff
@@ -494,3 +509,76 @@ int System::GetRenderFlags( void )
...
+{
+    DIR *d;
+    ci_path = "";
+    bool result = false;
+
+    if ( path.length() > 0 ) {
+        std::string tmp_path = path;
+        char *p = const_cast<char *>( tmp_path.c_str() );
+        if ( p[0] == '/' )
+        {
```
[the remark this answers is not in the document]
Comment (shprotru) [reply src/engine/system.cpp:525]: done

File: src/engine/system.cpp (hunk 10 above)
Comment (shprotru) [reply src/engine/system.cpp:518]: done

File: src/engine/system.cpp (hunk 11 above)
Comment (shprotru) [reply src/engine/system.cpp:522]: done

File: src/engine/system.cpp (hunk 12 above)
Comment (shprotru) [reply src/engine/system.cpp:523]: removed

File: src/engine/dir.cpp (hunk 13 above)
Comment (shprotru) [reply src/engine/dir.cpp:52]: done

File: src/engine/dir.cpp (hunk 14 above)
Comment (shprotru) [reply src/engine/dir.cpp:53]: I prefer return style as I make: bool for success flag and convertedPath, otherway: how to know is it success? convertedPath.empty() I don't know why, seems to me a bad solution.

File: src/engine/system.cpp (hunk 9 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/dir.cpp (hunk 14 above)
Comment (ihhub) [reply src/engine/dir.cpp]: We will still proceed with logic even if the function fails. Inside that function we return the original string in case of failure.

File: src/engine/system.cpp [hunk 20]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
...
+
+// based on: https://github.com/OneSadCookie/fcaseopen
+bool System::GetCaseInsensitivePath( const std::string path, std::string & correctedPath )
+{
+    DIR * d;
+    bool last = false;
+    correctedPath.clear();
+
+    const char chCurDir = '.';
+    const char * strCurDir = &chCurDir;
```
Comment (ihhub) [inline src/engine/system.cpp:551]: Why do we need to use an extra variable just to keep a pointer to a variable? We can use the pointer directly within the code.

File: src/engine/system.cpp [hunk 21]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
 #endif
 #endif
 }
+
+#if !( defined( _MSC_VER ) || defined( __MINGW32CE__ ) || defined( __MINGW32__ ) )
+// splitString - function for splitting strings by delimiter
+std::vector<std::string> splitString( std::string path, std::string delimiter )
```
Comment (ihhub) [inline src/engine/system.cpp:513]: All input parameters we must pass by const reference.

File: src/engine/system.cpp [hunk 22]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
...
+{
+    std::vector<std::string> result;
+
+    if ( path.empty() ) {
+        return result;
+    }
+
+    size_t nPos = path.find( delimiter, 0 );
+    while ( nPos != std::string::npos ) { // while found delimiter
+        size_t nnPos = path.find( delimiter, nPos + 1 );
```
Comment (ihhub) [inline src/engine/system.cpp:523]: Let's name thus variable as nextPos and make it const as well.

File: src/engine/system.cpp [hunk 23]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
...
+// splitString - function for splitting strings by delimiter
+std::vector<std::string> splitString( std::string path, std::string delimiter )
+{
+    std::vector<std::string> result;
+
+    if ( path.empty() ) {
+        return result;
+    }
+
+    size_t nPos = path.find( delimiter, 0 );
```
Comment (ihhub) [inline src/engine/system.cpp:521]: Let's name this variable as **pos**. We do not support Hungarian style of variable naming.

File: src/engine/system.cpp [hunk 24]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
...
+    while ( nPos != std::string::npos ) { // while found delimiter
+        size_t nnPos = path.find( delimiter, nPos + 1 );
+        if ( nnPos != std::string::npos ) { // if found next delimiter
+            result.push_back( path.substr( nPos + 1, nnPos - nPos - 1 ) );
+        }
+        else { // if no more delimiter present
+            if ( !path.substr( nPos + 1 ).empty() ) { // if not a postfix delimiter
```
Comment (ihhub) [inline src/engine/system.cpp:528]: What the intention to check if it is not an end of the path? If yes then we could compare pos with the size of the string instead.

File: src/engine/system.cpp [hunk 25]
```diff
@@ -494,3 +507,104 @@ int System::GetRenderFlags( void )
...
+            closedir( d );
+            return false;
+        }
+
+        correctedPath.append( strDelimiter );
+
+        struct dirent * e = readdir( d );
+        while ( e ) {
+            if ( strcasecmp( ( *subPathIter ).c_str(), e->d_name ) == 0 ) {
+                correctedPath += e->d_name;
```
Comment (ihhub) [inline src/engine/system.cpp:582]: Adding **subPathIter** is faster as we do not need to convert from char* to std::string.

File: src/engine/dir.cpp (hunk 14 above)
Comment (shprotru) [reply src/engine/dir.cpp]: Can't understand how we can proceed in this place in a situation with failure, because of check and return:
```
std::string correctedPath;
if ( !System::GetCaseInsensitivePath( path, correctedPath ) ) // if fails
    return; // return from function
// otherways logic ...
```
could you explain?

File: src/engine/system.cpp (hunk 25 above)
Comment (shprotru) [reply src/engine/system.cpp:582]: **subPathIter** will contain requested part of path, that could be incorrected(that's why we do here case insensitive check), so need adding here a **e->d_name** that will contain always correct part of the path.

File: src/engine/dir.cpp (hunk 14 above)
Comment (ihhub) [reply src/engine/dir.cpp]: My idea was that even if we fail in that function we still proceed with the code. I think we could keep your way. No harm in this.

File: src/engine/system.cpp [hunk 26]
```diff
@@ -318,12 +322,16 @@ bool System::IsFile( const std::string & name, bool writable )
 #elif defined( ANDROID )
     return writable ? 0 == access( name.c_str(), W_OK ) : true;
 #else
-    struct stat fs;
+    std::string correctedPath;
+    if ( GetCaseInsensitivePath( name, correctedPath ) ) {
```
Comment (ihhub) [inline src/engine/system.cpp:326]: To do not make much changes in existing code we could do like this:
if ( !GetCaseInsensitivePath( name, correctedPath ) )
    return false;
...
old code

File: src/engine/system.h [hunk 27]
```diff
@@ -95,6 +95,8 @@ namespace System
 
     int ShellCommand( const char * );
     int GetRenderFlags( void );
+
+    bool GetCaseInsensitivePath( const std::string path, std::string & correctedPath );
```
Comment (ihhub) [inline src/engine/system.h:99]: First parameter must be const reference.

File: src/engine/system.cpp (hunk 20 above)
Comment (shprotru) [reply src/engine/system.cpp:551]: resolved

File: src/engine/system.cpp (hunk 21 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.cpp (hunk 22 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.cpp (hunk 23 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.cpp (hunk 24 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.h [hunk 28]
```diff
@@ -95,6 +95,8 @@ namespace System
 
     int ShellCommand( const char * );
     int GetRenderFlags( void );
+
+    bool GetCaseInsensitivePath( std::string const & path, std::string & correctedPath );
```
Comment (ihhub) [inline src/engine/system.h:99]: Please use `const std::string &` instead as a defined naming in this project.

File: src/engine/system.cpp [hunk 29]
```diff
@@ -494,3 +505,104 @@ int System::GetRenderFlags( void )
...
+
+    if ( path[0] == chDelimiter ) {
+        d = opendir( &chDelimiter );
+    }
+    else {
+        correctedPath = chCurDir;
+        d = opendir( &chCurDir );
+    }
+
+    std::vector<std::string> splittedPath = splitUnixPath( path, &chDelimiter );
```
Comment (ihhub) [inline src/engine/system.cpp:564]: `const std::vector<std::string>` as we do not change this variable.

File: src/engine/system.cpp [hunk 30]
```diff
@@ -494,3 +505,104 @@ int System::GetRenderFlags( void )
...
+        const size_t nextPos = path.find( delimiter, pos + 1 );
+        if ( nextPos != std::string::npos ) { // if found next delimiter
+            if ( pos + 1 < nextPos ) { // have what to append
+                result.push_back( path.substr( pos + 1, nextPos - pos - 1 ) );
+            }
+        }
+        else { // if no more delimiter present
+            if ( pos + 1 < path.length() ) { // if not a postfix delimiter
+                result.push_back( path.substr( pos + 1 ) );
+            }
```
Comment (ihhub) [inline src/engine/system.cpp:530]: Should we call `break` a loop here as it is a last part of the path?

File: src/engine/system.cpp [hunk 31]
```diff
@@ -494,3 +505,104 @@ int System::GetRenderFlags( void )
...
+bool System::GetCaseInsensitivePath( std::string const & path, std::string & correctedPath )
+{
+    DIR * d;
+    bool last = false;
+    correctedPath.clear();
+
+    const char chCurDir = '.';
+    const char chDelimiter = '/';
+
+    if ( path.empty() )
```
Comment (ihhub) [inline src/engine/system.cpp:553]: For this corner case we must put this code at the very beginning of the function:
```
correctedPath.clear();
if ( path.empty() )
    return false;
...
the rest of the code
```
In this case we do not waster resources for extra variables.

File: src/engine/system.cpp (hunk 30 above)
Comment (shprotru) [reply src/engine/system.cpp:529]: done

File: src/engine/system.cpp (hunk 31 above)
Comment (shprotru) [reply src/engine/system.cpp:548]: resolved

File: src/engine/system.cpp (hunk 29 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.h (hunk 28 above)
Comment (shprotru) [reply src/engine/system.h]: resolved

File: src/engine/system.cpp (hunk 26 above)
Comment (shprotru) [reply src/engine/system.cpp]: resolved

File: src/engine/system.h (hunk 27 above)
Comment (shprotru) [reply src/engine/system.h]: resolved

**Comment by ihhub** [comment]
Hi @shprotru do you have a chance to test the changes on MacOS? Everything looks ready to be merged but we need to make such that the changes work on every OS.

**Comment by shprotru** [comment]
> Hi @shprotru do you have a chance to test the changes on MacOS? Everything looks ready to be merged but we need to make such that the changes work on every OS.
I launched [test](https://github.com/shprotru/fheroes2tests) and got failures:
Снимок экрана от 2020-05-03 15-28-23
On macOS failures are possible! Will attempt to understand why.

**Comment by shprotru** [comment]
@ihhub now same, as on Linux
Снимок экрана от 2020-05-03 16-15-08

File: src/engine/dir.cpp [hunk 32]
```diff
@@ -47,13 +47,17 @@ void ListFiles::ReadDir( const std::string & path, const std::string & filter, b
         FindClose( hFind );
     }
 #else
+    std::string correctedPath;
+    if ( !System::GetCaseInsensitivePath( path, correctedPath ) )
+        return;
```
Comment (ihhub) [inline src/engine/dir.cpp:52]: Shall we use `correctedPath = path;` to avoid such mishaps like with MacOS?

Comment (shprotru) [reply src/engine/dir.cpp:52]: problem on MacOS was because I defined 2 char variables in a row, in the memory they was represented without \0 separator as in Linux(this was default clang optimization trick), and curDir was represented in program memory as "./\0". I think that assignment `correctedPath = path;` have no sense, why you have thoughts that it can have different behaviour?

Comment (shprotru) [reply src/engine/dir.cpp:52]: this is our actual master on mac os(builded with SDL1 and launched in virtual machine)
Снимок экрана от 2020-05-04 12-31-18
i hear a sound but don't see graphics or any actual error's in terminal

Comment (ihhub) [reply src/engine/dir.cpp:52]: Does SDL1 with your fix work now?

Comment (ihhub) [reply src/engine/dir.cpp:52]: We even specified that SDL1 is broken on MacOS but if your change fixes it then it would be awesome!

Comment (shprotru) [reply src/engine/dir.cpp:52]: I couldn't expect that fheroes2 does not work on MacOS with SDL1, that's why I show you that screenshot. I think these error are unrelated to this PR, that was just a question about operability fheroes2 on MacOS. What do you think on `correctedPath = path;` ? I think it's not necessary, fheroes2 with SDL2 launches on MacOS

**Comment by ihhub** [comment]
Hi @shprotru , thank you very much for your continuous contribution to the project!
