### PR TITLE
Fix crash when using quick switch to hero when castle is current object 

### LINKED ISSUE #8723: Crash found by Google Play Store
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Android

### Describe the bug

Version 1.0.13.

This is a strack trace of the crash:
```
pid: 0, tid: 14423 >>> org.fheroes2 <<<

backtrace:
  #00  pc 0x000000000033eee0  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Heroes::GetColor() const) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #01  pc 0x00000000002e651c  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Interface::AdventureMap::EventSwitchFocusedHero(int)+96) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #02  pc 0x00000000002eceac  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Interface::GameArea::QueueEventProcessing(bool)+800) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #03  pc 0x00000000002daf3c  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Interface::AdventureMap::HumanTurn(bool)+1776) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #04  pc 0x00000000002d89cc  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Interface::AdventureMap::StartGame()+1144) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #05  pc 0x00000000002d8508  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Game::StartGame()+92) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #06  pc 0x00000000002c90ac  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (Game::mainGameLoop(bool, bool)+248) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #07  pc 0x00000000002aaf84  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libmain.so (SDL_main+3492) (BuildId: b17aae456b5efb368928807e2546568e3815d861)
  #08  pc 0x0000000000099be4  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/split_config.arm64_v8a.apk!libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+692) (BuildId: 9fc163d6a30673b2e47502d82a93e7091aa81fb0)
  #09  pc 0x000000000003fd0c  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/oat/arm64/base.odex (art_jni_trampoline+156)
  #10  pc 0x00000000005b9798  /apex/com.android.art/lib64/libart.so (nterp_helper+152)
  #11  pc 0x00000000004a9c98  /data/app/~~q6Nw45E0a9SPK7jHekykDw==/org.fheroes2-GeY4rlAkwX0a24W95tWnTA==/base.apk (org.libsdl.app.SDLMain.run+144)
  #12  pc 0x00000000004fee88  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Thread.run+72)
  #13  pc 0x000000000033eda4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #14  pc 0x0000000000239d54  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #15  pc 0x000000000053a1b0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600)
  #16  pc 0x00000000000c150c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #17  pc 0x0000000000054930  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zenseii**
This changes the check to see what is current color according to the settings. Thanks to @Districh-ru for solution.
Fix #8723

### CODE REVIEW

File: src/fheroes2/gui/interface_events.cpp [hunk 1]
```diff
@@ -132,7 +133,7 @@ void Interface::AdventureMap::EventSwitchFocusedHero( const int32_t tileIndex )
 {
     Heroes * selectedHero = world.GetTiles( tileIndex ).getHero();
     const Heroes * currentHero = GetFocusHeroes();
-    if ( selectedHero == nullptr || selectedHero == currentHero || selectedHero->GetColor() != currentHero->GetColor() ) {
+    if ( selectedHero == nullptr || selectedHero == currentHero || selectedHero->GetColor() != Settings::Get().GetPlayers().getCurrentColor() ) {
```
Comment (Districh-ru) [inline src/fheroes2/gui/interface_events.cpp:136]: Hi, @zenseii, in the case when `selectedHero == nullptr` we do not ever use the `currentHero`, so we could slightly optimize this part by calling `GetFocusHeroes()` only after the first nullptr check:
```suggestion
    if ( selectedHero == nullptr || selectedHero == GetFocusHeroes()|| selectedHero->GetColor() != Settings::Get().GetPlayers().getCurrentColor() ) {
```
And removing the 135 line.

**Review by Districh-ru — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@zenseii , thank you so much for this fix!
