### PR TITLE
Map pathfinding refactoring

### LINKED ISSUE #219: Path calculation must not include boat position
Find a situation when there is no other way to move to another location rather then sit in boat. You would notice that somehow a hero could use a boat as a part of land which is a bug:
boat_path

### LINKED ISSUE #880: Wrong path calculation over roads
In the OG path is created over roads, while in our version hero want to cross fields, than walk on roads.
path
path2

### LINKED ISSUE #1028: Question about path penalty
Playing current version of our game i have a few questions regarding paths and penalty behavior.
Does current indication of terrain penalty, which we can see by right click over land near hero, correct?
If so, what is the difference between straight and diagonal hero movement?
roadss
roadss2
Why does game shows different penalty when hero stands close to the road turning ?
Roads
Roads1

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #219 . Fixes #880.  Fixes #1028 .

- Making `Route::Find` code non-dependent on Hero reference to enable future AI features.
- Correct game logic issues internally, including movement penalty amounts.
- Minor optimization of pathfinding logic (less checks to run on each tile processed).
- `Move2Dest` function no longer triggers hero action or applies penalty, it should happen outside.

### CODE REVIEW

File: src/fheroes2/maps/maps_tiles.cpp [hunk 1]
```diff
@@ -1983,6 +1961,8 @@ void Maps::Tiles::SetObjectPassable( bool pass )
 /* check road */
 bool Maps::Tiles::isRoad( int direct ) const
 {
+    // return mp2_object == MP2::OBJ_CASTLE
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1964]: Shall we remove it?

File: src/fheroes2/heroes/route_pathfind.cpp [hunk 2]
```diff
@@ -200,20 +180,25 @@ bool PassableFromToTile( const Heroes & hero, s32 from, const s32 & to, int dire
...
-    const u32 cost2 = Maps::Ground::GetPenalty( to, Direction::Reflect( direct ), pathfinding ); // penalty: for [tmp] in
-    return std::min( cost1, cost2 );
+    const Maps::Tiles & tileTo = world.GetTiles( to );
+    uint32_t penalty = ( world.GetTiles( from ).isRoad( direction ) || tileTo.isRoad( Direction::Reflect( direction ) ) )
+                           ? Maps::Ground::roadPenalty
+                           : Maps::Ground::GetPenalty( tileTo, pathfinding );
+
+    // diagonal move costs 50% extra
+    if ( direction & ( Direction::TOP_RIGHT | Direction::BOTTOM_RIGHT | Direction::BOTTOM_LEFT | Direction::TOP_LEFT ) )
+        penalty *= 1.5;
```
Comment (ihhub) [inline src/fheroes2/heroes/route_pathfind.cpp:195]: Let's avoid type conversion here and use `penalty = penalty * 3 / 2;`. We really want to reduce the number of compilation warnings :(

**Comment by ihhub** [comment]
Hi @idshibanov , thanks a lot for such valuable fixes for the project!
