### PR TITLE
Fix passability for tiles with shadows only

### LINKED ISSUE #4149: Adventure map, a hero cannot reach area near rock
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
Hero cannot even attack skeletons.

### Save file

[Unreachable area.zip](https://github.com/ihhub/fheroes2/files/7106055/Unreachable.area.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #4149

### CODE REVIEW

File: src/fheroes2/maps/maps_tiles.cpp [hunk 1]
```diff
@@ -1619,10 +1619,10 @@ bool Maps::Tiles::isStream( void ) const
     return tileICN == ICN::STREAM || ( tileICN == ICN::OBJNMUL2 && objectIndex < 14 );
 }
 
-bool Maps::Tiles::isShadow( void ) const
+bool Maps::Tiles::isShadow() const
 {
     return isShadowSprite( objectTileset, objectIndex )
-           && addons_level1.size() != static_cast<size_t>( std::count_if( addons_level1.begin(), addons_level1.end(), TilesAddon::isShadow ) );
+           && addons_level1.size() == static_cast<size_t>( std::count_if( addons_level1.begin(), addons_level1.end(), TilesAddon::isShadow ) );
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles.cpp:1625]: Yeah, logic of `isShadow()` was suspicious long ago, that's why I didn't use it in `Maps::Tiles::GoodForUltimateArtifact()` at the time (and replicated the current logic). BTW, can the tile with `objectTileset == 0` have any shadow addons? I vaguely remember something like this...

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @ihhub I just left one question, could you please take a look when it's convenient for you?

File: src/fheroes2/maps/maps_tiles.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:1625]: Yes and no. The structure of map is still not fully known to me and I saw tiles having something in addonss but not in the main tile structure.

**Review by oleg-derevenetz — APPROVED** [review]
