### PR TITLE
Fix interface buttons in hero dialog

### LINKED ISSUE #144: World map UI is drawn inside castle options
Move a hero inside castle, click on hero, exit hero window and notice this (check image near resources):
world_map_in_castle

### PR DESCRIPTION
**Pull request by andrey-starodubtsev**
Remove image artifacts while being in the castle

When hero's details dialog is opened from inside the castle, after exiting it interface buttons are drawn under the troops panel.

Similar problem is encountered if one opens hero's details dialog from heroes/castles statistics dialog.

This fixes #144.

### CODE REVIEW

File: src/fheroes2/game/game.h [hunk 1]
```diff
@@ -231,7 +231,7 @@ namespace Game
     void	PlayPickupSound(void);
     void	DisableChangeMusic(bool);
     bool	ChangeMusicDisabled(void);
-    void	OpenHeroesDialog(Heroes &);
+    void OpenHeroesDialog( Heroes &, bool = true );
```
Comment (ihhub) [inline src/fheroes2/game/game.h]: I'd recommend to name variables especially with default values.

Comment (andrey-starodubtsev) [reply src/fheroes2/game/game.h]: fixed

**Comment by ihhub** [comment]
@andrey-starodubtsev thank you very much for your continuous contribution to the project!
