### PR TITLE
fix starting xp

### LINKED ISSUE #5696: Hero screen, experience points of a modified hero in the editor
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When the creator of a scenario modifies a hero that he has positioned on the adventure map and he leaves the number of experience points at "0", this is not taken into account in fheroes2 and the hero has a number of experience points different from "0".

In original game:

Editor modified hero 01

Hero experience 001

In fheroes2:

Hero experience 008

### Save file

Here is the test scenario file:
[0 9992a.zip](https://github.com/ihhub/fheroes2/files/9182786/0.9992a.zip)

### Additional info

Version 0.9.17 5674

### PR DESCRIPTION
**Pull request by undef21**
fix #5696

### CODE REVIEW

File: src/fheroes2/heroes/heroes.cpp [hunk 1]
```diff
@@ -325,9 +325,6 @@ void Heroes::LoadFromMP2( int32_t map_index, int cl, int rc, StreamBuf st )
     // Experience
     experience = st.getLE32();
 
-    if ( experience == 0 )
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes.cpp:328]: What's the value of this variable when a map creator didn't specify experience?

Comment (undef21) [reply src/fheroes2/heroes/heroes.cpp:328]: in the OG this value is 0

Comment (undef21) [reply src/fheroes2/heroes/heroes.cpp:328]: In the OG this value is 0

Comment (oleg-derevenetz) [reply src/fheroes2/heroes/heroes.cpp:328]: @ihhub there is no way for a map creator NOT to specify hero's experience, because this field is not optional in the map editor:

xp

Unlike Troops or Skills, there is no some checkbox to use "standard" experience, there is always a specific value.

**Comment by ihhub** [comment]
@undef21 , thank you very much for this fix!
