### PR TITLE
Offer the Wisdom skill to the heroes of "magic" classes on a mandatory basis at least once every three level-ups

### LINKED ISSUE #8261: Secondary skills, mandatory wisdom for magic heroes
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There is mandatory wisdom proposal for magic(Necromancer, sorcerer, sorceress, warlock) heroes in OG 3 levels after last proposal. 

### Save file

Easy to check in OG, and fheroes2

### Additional info

F.e If wisdom wasnt proposed, it always appear on left slot on level 4.
If it was proposed on level 2, the latest it can be proposed is level 5. 
Always wisdom is mandatory 3 levels after last proposal.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8261

### CODE REVIEW

File: src/fheroes2/heroes/skill.cpp [hunk 1]
```diff
@@ -669,83 +733,69 @@ void Skill::SecSkills::FillMax( const Skill::Secondary & skill )
         resize( HEROESMAXSKILL, skill );
 }
 
-int Skill::SecondaryGetWeightSkillFromRace( int race, int skill )
+std::pair<Skill::Secondary, Skill::Secondary> Skill::SecSkills::FindSkillsForLevelUp( const int race, const uint32_t firstSkillSeed,
+                                                                                      uint32_t const secondSkillSeed ) const
 {
-    const stats_t * ptr = GameStatic::GetSkillStats( race );
+    std::vector<int> blacklist;
```
Comment (ihhub) [inline src/fheroes2/heroes/skill.cpp:739]: Since we are touching this function should we change the container type to `std::set` or `std::unsorted_set` which are designed for these purposes?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I have only one suggestion here. Would you mind to take a look?

File: src/fheroes2/heroes/skill.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/heroes/skill.cpp:739]: @ihhub Eh, well, since we are rewriting this anyway, we can.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for the fix!
