### PR TITLE
Make campaign buttons translatable, add text adaptable button method, fix campaign button issues, make guildWell EXIT button adapt to text

### LINKED ISSUE #4977: Campaign description window, missing shadows for buttons
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Shadows for buttons are missing in the window, but appear after releasing of buttons.
image
image
image
Also, in a pressed state we can watch another button under the pressed one.
image

The bug is present in the OG too.

### Save file

Any PoL campaign window.

### Additional info

_No response_

### LINKED ISSUE #7312: Exit button in well window not well positioned Bulgarian text
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Exit button in well window not well positioned Bulgarian text

### Save file

image

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zenseii**
This PR adds a function that takes a text and adapts a specified empty button template to the width of that text.

The campaign buttons and the smaller EXIT button in the guilds and the well are generated with this. 

Campaign buttons are made in sets which include the DIFFICULTY button now. This streamlines the code.

Empty templates for Price of Loyalty and smaller exit button for guilds/well were added to make this possible.

`BUTTON_GUILDWELL_EXIT` serves as a proof of concept of how the new function works and is used.

The Price of Loyalty buttons have been given transparency so that the parts of the released state of the buttons do not show when pressing the buttons.

To do this it was necessary to add a small piece of stone background `stonebak_pol` for Price of Loyalty buttons.

All campaign buttons have been given shadows, both when and when not using the same language as the provided assets.

To do this I chose to remove the already embedded shadows in the original GOOD and EVIL campaign buttons and use `addGradientShadow()` to all buttons. Thanks to @Districh-ru for this valuable advice.

Fix #7312
Fix #4977

Additionally I discovered that the pressed state of the empty good and evil buttons were missing dark edges on the left side. With this change they behave like the original buttons (NOTE that single bright pixel to the left of the text area of the released state has been fixed for both good and evil interfaces):

Before:
image
 After:
 image

Relates to #6105 

<details>
<summary>Pictures of the related screens with buttons in different languages</summary>

image

image

image

image

image

</details>

### CODE REVIEW

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi @zenseii! 
You did a great work, visually it looks perfect and at last I can translate the EXIT button in the castle Well.
Well done!

I left several comments, could you please check them when you have time?

File: src/fheroes2/gui/ui_button.cpp [hunk 1]
```diff
@@ -547,23 +616,52 @@ namespace fheroes2
...
+        int32_t backgroundBorders = 0;
+        int backgroundIcnID = ICN::UNKNOWN;
+        fheroes2::Point releasedOffset = {};
+        fheroes2::Point pressedOffset = {};
+
+        getButtonSpecificValues( emptyButtonIcnID, buttonFont, textAreaBorder, minimumTextAreaWidth, backgroundBorders, backgroundIcnID, releasedOffset, pressedOffset );
+
+        const fheroes2::FontType releasedButtonFont{ fheroes2::FontSize::BUTTON_RELEASED, buttonFont };
+
+        const char * translatedText = _( text );
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/gui/ui_button.cpp:639]: My apologies, you are absolutely right!
There should be `_( )` as the `text` was made using `gettext_noop()`.
Thanks for the explanation. :)

**Comment by Districh-ru** [comment]
> As for the actual text I realized that we might not even need the `guildWell|` context anymore because the button can fit any word you choose. Actually now the limiting buttons are the larger normal ones (until we generate them with this new function).
> I suppose we can remove this context. What do you think?

Hi, @zenseii, yes, now we can remove the `guildWell|` context.

File: src/fheroes2/agg/agg_image.cpp [hunk 2]
```diff
@@ -3795,6 +3786,9 @@ namespace fheroes2
                 // move dark border to new released state from original pressed state button
                 const Sprite & originalReleased = GetICN( originalID, 4 );
                 const Sprite & originalPressed = GetICN( originalID, 5 );
+                if ( originalReleased.width() != 94 && originalPressed.width() != 94 ) {
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:3811]: We should also check these images height as we are later accessing `pixelPosition` which is on the 4th row of image (`4 *96`), so the height should be more than 5.
If it is less than 5 (in case these images are corrupted) we may try to access this "pixel" outside of image data.

File: src/fheroes2/gui/ui_button.h [hunk 3]
```diff
@@ -230,6 +230,9 @@ namespace fheroes2
         void unsubscribeAll();
     };
 
+    // Make transparent edges around buttons making the pressed state appear without parts of the released state
+    void makeTransparentBackground( fheroes2::Sprite & released, fheroes2::Sprite & pressed, const int backgroundIcnID );
```
Comment (Districh-ru) [inline src/fheroes2/gui/ui_button.h:234]: `Sprite & released` can be **const**.

File: src/fheroes2/game/game_campaign.cpp [hunk 4]
```diff
@@ -1325,19 +1300,38 @@ fheroes2::GameMode Game::SelectCampaignScenario( const fheroes2::GameMode prevMo
...
+    fheroes2::Button buttonViewIntro( viewIntroPlacement, top.y + 431, buttonIconID, 0, 1 );
+    fheroes2::Button buttonRestart( okRestartPlacement, top.y + 431, buttonIconID, 2, 3 );
+    fheroes2::Button buttonOk( okRestartPlacement, top.y + 431, buttonIconID, 4, 5 );
+    fheroes2::Button buttonCancel( cancelPlacement, top.y + 431, buttonIconID, 6, 7 );
+    fheroes2::Button buttonDifficulty( difficultyPlacement, top.y + 431, buttonIconID, 8, 9 );
+
+    fheroes2::addGradientShadow( fheroes2::AGG::GetICN( buttonIconID, 0 ), display, { viewIntroPlacement, top.y + 431 }, { -5, 5 } );
+    fheroes2::addGradientShadow( fheroes2::AGG::GetICN( buttonIconID, okayRestartIndex ), display, { okRestartPlacement, top.y + 431 }, { -5, 5 } );
+    fheroes2::addGradientShadow( fheroes2::AGG::GetICN( buttonIconID, 6 ), display, { cancelPlacement, top.y + 431 }, { -5, 5 } );
+    fheroes2::addGradientShadow( fheroes2::AGG::GetICN( buttonIconID, 8 ), display, { difficultyPlacement, top.y + 431 }, { -5, 5 } );
```
Comment (Districh-ru) [inline src/fheroes2/game/game_campaign.cpp:1334]: We can cache the button's vertical offset so we don't have to do the same calculation in these lines: 1325 - 1334.
```cpp
const int32_t buttonOffsetY = top.y + 431;
```

File: src/fheroes2/agg/agg_image.cpp [hunk 5]
```diff
@@ -1473,47 +1486,94 @@ namespace fheroes2
...
+                if ( useOriginalResources() ) {
+                    const bool isEvilInterface = id == ICN::EVIL_CAMPAIGN_BUTTONS;
+                    const int originalIcnId = isEvilInterface ? ICN::CAMPXTRE : ICN::CAMPXTRG;
 
-                renderTextOnButton( _icnVsSprite[id][0], _icnVsSprite[id][1], gettext_noop( "DIFFICULTY" ), releasedOffset, pressedOffset, { textWidth, 16 },
-                                    fheroes2::FontColor::GRAY );
+                    // The evil buttons' released state are 2 pixels wider.
+                    const int offsetEvilX = isEvilInterface ? 2 : 0;
+                    // remove embedded shadows so that we can generate shadows with our own code later
+                    for ( uint32_t i = 0; i < 4; ++i ) {
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:1500]: As in this loop we use `i` four times multiplying it by 2 we can do this multiply once:
```suggestion
                    for ( uint32_t i = 0; i < 8; i += 2 ) {
```
and replace all `2 * i` by `i` on lines 1502, 1504, 1511, 1513.

Doing this we will reduce computations and also make Cland-Tydy happy. :)

File: src/fheroes2/agg/agg_image.cpp [hunk 6]
```diff
@@ -1473,47 +1486,94 @@ namespace fheroes2
...
-                    Sprite & out = _icnVsSprite[id][i];
-                    out = GetICN( ICN::X_CMPBTN, 0 + i );
+                const int baseIcnId = ICN::X_CMPBTN;
 
-                    // clean the button.
-                    const int32_t pixelPosition = 5 * 132;
-                    if ( pixelPosition < ( out.width() * out.height() ) ) {
-                        Fill( out, 4, 3 + i, 132 - i, 16, out.image()[pixelPosition] );
+                if ( useOriginalResources() ) {
+                    for ( uint32_t i = 0; i < 4; ++i ) {
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:1537]: The same comment as above, we can do `i+=2` here instead of multiplying i by 2 every time in this loop. :)

File: src/fheroes2/agg/agg_image.cpp [hunk 7]
```diff
@@ -416,6 +416,30 @@ namespace
...
+            emptyButtonIcnID = ICN::EMPTY_POL_BUTTON;
+            break;
+        default:
+            // Was a new set of buttons added?
+            assert( 0 );
+            break;
+        }
+
+        for ( size_t i = 0; i < texts.size(); ++i ) {
+            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][2 * i], _icnVsSprite[campaignSetIcnId][2 * i + 1], texts[i], emptyButtonIcnID );
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:439]: We could cache `2 * i` here:
```cpp
const size_t icnIndex = 2 * i;
```

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @zenseii. The buttons in campaign info dialog looks great!
I left several comments. Could please you take a look when you have time.

File: src/fheroes2/agg/agg_image.cpp [hunk 8]
```diff
@@ -416,6 +416,31 @@ namespace
...
+            break;
+        default:
+            // Was a new set of buttons added?
+            assert( 0 );
+            break;
+        }
+
+        for ( size_t i = 0; i < texts.size(); ++i ) {
+            const size_t icnIndex = 2 * i;
+            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][2 * i], _icnVsSprite[campaignSetIcnId][icnIndex + 1], texts[i], emptyButtonIcnID );
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:440]: Please replace `2 * i` with the cached `icnIndex`.
```suggestion
            fheroes2::getTextAdaptedButton( _icnVsSprite[campaignSetIcnId][icnIndex], _icnVsSprite[campaignSetIcnId][icnIndex + 1], texts[i], emptyButtonIcnID );
```

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi @zenseii, I left one comment, could you address it when you have time.

File: src/fheroes2/gui/ui_button.cpp [hunk 9]
```diff
@@ -474,6 +524,26 @@ namespace fheroes2
...
+        const fheroes2::Sprite & background = fheroes2::AGG::GetICN( backgroundIcnID, 0 );
+        // you are trying to apply transform on an image that is single-layered
+        assert( !pressed.singleLayer() && !released.singleLayer() );
+        const uint8_t * releasedTransform = released.transform();
+        uint8_t * pressedTransform = pressed.transform();
+        uint8_t * pressedImage = pressed.image();
+        const uint8_t * backgroundImage
+            = background.image() + ( background.width() - pressed.width() ) / 2 + ( background.height() - pressed.height() ) * background.width() / 2;
+
+        for ( int32_t x = 0; x < pressed.width() * pressed.height(); ++x ) {
```
Comment (ihhub) [inline src/fheroes2/gui/ui_button.cpp:539]: I suggest to cache **pressed.width() * pressed.height()** as a compiler won't do this.

File: src/fheroes2/agg/agg_image.cpp [hunk 10]
```diff
@@ -3713,7 +3754,8 @@ namespace fheroes2
             }
             case ICN::EMPTY_GOOD_BUTTON:
             case ICN::EMPTY_EVIL_BUTTON: {
-                const int32_t originalId = ( id == ICN::EMPTY_GOOD_BUTTON ) ? ICN::SYSTEM : ICN::SYSTEME;
+                const bool isGoodInterface = id == ICN::EMPTY_GOOD_BUTTON;
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:3757]: Please bring back parenthesis for the expression. It helps with code readability.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @zenseii , I put few small comments here. Could you please check them?

**Review by Districh-ru — APPROVED** [review]
👍

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@zenseii , huge thanks for this improvements!
