### PR TITLE
Adjust morale and luck descriptions

### LINKED ISSUE #4725: Morale and Luck info windows, adjust the beginning of the description text according to the title
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

We have changed the title and the text in the info bar at the bottom of the screen regarding the different levels of Morale and Luck, but the expressions used in the introduction of the description text have not been changed.
I think we should do that too.

Example, the title says:

"Blood Morale"

But the introduction of the description text says:

"Good Morale may give..."

In fheroes2:

Morale Luck intro text 001

Morale Luck intro text 002

Morale Luck intro text 003

Morale Luck intro text 004

Morale Luck intro text 005

### Save file

Not needed.

### Additional info

Related closed issue: https://github.com/ihhub/fheroes2/issues/2808.

### PR DESCRIPTION
**Pull request by lwollnikowski**
Close #4725

### CODE REVIEW

**Comment by zenseii** [comment]
@leherosinconnu, could you have a look at this PR if it solves the issue described?

File: src/fheroes2/kingdom/luck.cpp [hunk 1]
```diff
@@ -52,22 +54,28 @@ std::string Luck::String( int luck )
...
 std::string Luck::Description( int luck )
 {
+    std::string msg;
+
     switch ( luck ) {
     case Luck::CURSED:
     case Luck::AWFUL:
     case Luck::BAD:
-        return _( "Negative luck sometimes falls on the hero's units in combat, causing their attacks to only do half damage." );
+        msg = _( "%{luck} luck sometimes falls on the hero's units in combat, causing their attacks to only do half damage." );
```
Comment (ihhub) [inline src/fheroes2/kingdom/luck.cpp]: I recommend to be more specific for luck as %{luck} can be interpreted as a number. What if we use %{luck-type} ?

The same comment for morale.

Comment (lwollnikowski) [reply src/fheroes2/kingdom/luck.cpp]: Agreed, done.

**Comment by ihhub** [comment]
@lwollnikowski , thank you so much for these changes!
