### PR TITLE
Properly restore the screen after closing the hero dialog during combat

### LINKED ISSUE #6702: Combat, display default when exiting hero screen during combat
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there is a display default when exiting the hero screen during a combat.

In fheroes2:

vlcsnap-2023-02-23-17h43m30s253

https://user-images.githubusercontent.com/43583994/220975688-ca967bf8-1de8-4277-a5b4-f631dcf012f3.mp4

### Save file

Not needed.

### Additional info

Version 1.0.1 6678

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Fix #6702

### CODE REVIEW

File: src/fheroes2/battle/battle_dialogs.cpp [hunk 1]
```diff
@@ -948,23 +948,36 @@ int Battle::Arena::DialogBattleHero( const HeroBase & hero, const bool buttons,
                 statusMessage = _( "Hero's Options" );
             }
         }
+        else {
```
Comment (ihhub) [inline src/fheroes2/battle/battle_dialogs.cpp:951]: Could you please explain this change? I am not entirely sure what it does.

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left one question here. Would you mint to check it?

File: src/fheroes2/battle/battle_dialogs.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_dialogs.cpp:951]: Actually, it's just a restructure of thee old code.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for this fix!
