### PR TITLE
Fix shifted by 16 pixels position of a map for the first opening in the Editor

### LINKED ISSUE #9989: A newly open map in the Editor should be shifted by 16 pixels from both edges
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

This is what happens when someone opens a map in the Editor:

Image

while we should show this:

Image

### Save file

No need. It is for the Editor only.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #9989

### CODE REVIEW

File: src/fheroes2/editor/editor_interface.h [hunk 1]
```diff
@@ -146,6 +148,10 @@ namespace Interface
             _historyManager.setStateCallback( [&editorPanel = _editorPanel]( const bool isUndoAvailable, const bool isRedoAvailable ) {
                 editorPanel.updateUndoRedoButtonsStates( isUndoAvailable, isRedoAvailable );
             } );
+
+            // This is to compensate [16, 16] pixel offset on a first opening of the Editor
+            // and to show the correct top-left corner of the map.
+            _gameArea.SetAreaPosition( 0, 0, 2 * fheroes2::borderWidthPx, 2 * fheroes2::borderWidthPx );
```
Comment (Districh-ru) [inline src/fheroes2/editor/editor_interface.h]: Hi @ihhub, what do you think about adding the next lines after the line 732 in `editor_interface.cpp` instead of these changes?

```cpp
        if ( prevRoi == fheroes2::Rect{} ) {
            // This is the first initialization of the game area for editor.
            // Make the top-left corner of first tile to be at the top-left corner of the shown game area.
            _gameArea.SetCenterInPixels( { newRoi.width / 2, newRoi.height / 2 } );

            return;
        }
```

Comment (ihhub) [reply src/fheroes2/editor/editor_interface.h]: Sure, we can do this as well.
