### PR TITLE
Adjusted number of resources subtracted in event messages.

### LINKED ISSUE #6795: Adventure map, the number of resources subtracted in the event messages should be adjusted
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, when an amount of resources is taken away from the player in an event, global or local, the amount of resources taken away from the player is adjusted to the player's actual treasury in the message displayed.
This is not the case in fheroes2.
In fheroes2, it is always the quantity indicated in the scenario editor which is displayed, without taking into account the treasury of the player.
This should be corrected.

In original game:

Gold event true value 001

Gold event true value 003
Gold event true value 004

Gold event true value 006
Gold event true value 007

Gold event true value 008
Gold event true value 009

In fheroes2:

Gold event true value 002

In original game:

Event true value 001

Event true value 002

In fheroes2:

Event true value 003

### Save file

Here is the test scenario file (for map event):
[0 9925f.zip](https://github.com/ihhub/fheroes2/files/10932461/0.9925f.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by slawomir-witkowski**
fix #6795

### CODE REVIEW

File: src/fheroes2/game/game_startgame.cpp [hunk 1]
```diff
@@ -333,8 +333,8 @@ void ShowNewWeekDialog()
 
 void ShowEventDayDialog()
 {
-    const Kingdom & myKingdom = world.GetKingdom( Settings::Get().CurrentColor() );
-    const EventsDate events = world.GetEventsDate( myKingdom.GetColor() );
+    Kingdom & myKingdom = world.GetKingdom( Settings::Get().CurrentColor() );
+    const EventsDate & events = myKingdom.GetAppliedEvents();
 
     for ( const EventDate & event : events ) {
         if ( event.resource.GetValidItemsCount() ) {
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:340]: I suggest to do a simplified version of this fix:
```cpp
void ShowEventDayDialog()
{
    const Kingdom & myKingdom = world.GetKingdom( Settings::Get().CurrentColor() );
    const EventsDate events = world.GetEventsDate( myKingdom.GetColor() );

    Funds funds = myKingdom.GetFunds();

    for ( const EventDate & event : events ) {
        Funds fundsToUpdate;
        if ( event.resource.GetValidItemsCount() ) {
            const Funds fundsBefore = funds;
            funds = funds + event.resource;
            funds.Trim();
            fundsToUpdate = funds - fundsBefore;
        }

        if ( fundsToUpdate ) {
            fheroes2::showResourceMessage( fheroes2::Text( event.title, fheroes2::FontType::normalYellow() ),
                                           fheroes2::Text( event.message, fheroes2::FontType::normalWhite() ), Dialog::OK, fundsToUpdate );
        }
        else if ( !event.message.empty() ) {
            fheroes2::showStandardTextMessage( event.title, event.message, Dialog::OK );
        }
    }
}
```
This should be enough to fix the initial problem. What do you think?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @slawomir-witkowski , I proposed an alternative approach to fix the problem. Could you please take a look at it and see if it is a valid one?

File: src/fheroes2/game/game_startgame.cpp (hunk 1 above)
Comment (slawomir-witkowski) [reply src/fheroes2/game/game_startgame.cpp:340]: Hi @ihhub, this doesn't work. The problem is that at this point myKingdom.GetFunds(); returns funds that have already been reduced by a call to AddFundsResource(event.resource) in kingdom.cpp:262.  
We need a way to store information about how much each event subtracted for each kingdom in the current day.

**Comment by Branikolog** [comment]
Hello, @slawomir-witkowski 
After scenario restart I still got messages, which I got on previous game:
image
image
The second one is which I've established in map editor.
But the first (-1000) was showed on previous game, when a player didn't have resources anymore. Now It appears before the main message.

**Comment by slawomir-witkowski** [comment]
Initially I focused on daily events. Now I added support for Map Events as well. @Branikolog Castle generates 1000gold/day, so a daily event can display -1000 every day. If you still see problems, can you attach your map to the issue?

File: src/fheroes2/game/game_startgame.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/game/game_startgame.cpp:340]: Ah, you are right. Actually we have a much bigger problem here:
**World::NewDay()** is called for the whole day which updates all statuses for players, especially updating resources. Let's imagine this situation:
- we play in hot-seat mode 1 vs 1
- my turn first, yours second
- you completed the turn and you know that you have 5000 gold in your kingdom
- a new day starts deducting 10,000 gold from each player
- I attack your hero and you need to surrender to save Dragon but you couldn't as your gold now is zero

In this case the logic is wrong as you haven't started your turn so you must have that 5,000 gold.

Hi @LeHerosInconnu, could you please verify this scenario?

Comment (LeHerosInconnu) [reply src/fheroes2/game/game_startgame.cpp:340]: It works correctly in the original game.

Comment (slawomir-witkowski) [reply src/fheroes2/game/game_startgame.cpp:340]: Hi guys, IMO this problem deserves a separate issue. We have to consider all resource updates and do them in the right moment.

Consider an opposite situation when players get +10k bonus. Player first to act can use the gold to buy an army and kill another player before he has a chance to use his bonus.

Comment (ihhub) [reply src/fheroes2/game/game_startgame.cpp:340]: Hi @slawomir-witkowski , as confirmed the logic for new day is not correct so your changes and the logic are actually correlate to each other. I foresee that even after your fix other would find that the number of resources in the bottom-right corner is not updated (@LeHerosInconnu missed that for now). Your proposed solution is indeed fixing the problem but since the original code is wrong the solution looks more like a temporary patch (any other solution would look the same to be honest).

If we move events out of NewDay() method and execute them once with and without windows then we could solve 3 existing problems at once. Right now even if we go with the proposed solution we would need to redesign it due to other 2 highlighted issues. What do you think?

Comment (slawomir-witkowski) [reply src/fheroes2/game/game_startgame.cpp:340]: Ok, I added a change that will delay updating resources until your turn. Now you can save the dragon. However, I don't see the problem with resources in bottom-right corner not being updated.

**Comment by Branikolog** [comment]
Hi, @slawomir-witkowski !
I've tested on daily events exactly. The problem is that there appear several messages from previously played games (which showed the substracted value on previous game). So, starting new game for several times comes up with several messages.
Your last fix solved the problem with restart.
But after we load the game on the next turn we'd see two messages for the player loaded the game. The same happens if we load the game, skip 1 turn and then restart the scenario.

https://user-images.githubusercontent.com/55348946/226594880-cc3ee58b-e782-4cdd-9899-612063abe245.mp4

**Comment by slawomir-witkowski** [comment]
@Branikolog Thank you for this video. It allowed me to find and fix the problem.

File: src/fheroes2/resource/resource.h [hunk 2]
```diff
@@ -96,6 +96,7 @@ class Funds
     int GetValidItems() const;
     uint32_t GetValidItemsCount() const;
 
+    Funds GetUpdate( const Funds & ) const;
```
Comment (ihhub) [inline src/fheroes2/resource/resource.h:99]: It is not clear what exactly this method does at first place. I suggest to just remove it or rename in a way what it reflects what it actually does. Also please add the name of the input argument.

File: src/fheroes2/kingdom/kingdom.cpp [hunk 3]
```diff
@@ -236,7 +236,10 @@ void Kingdom::ActionNewDay()
 
     // Reset the effect of the "Identify Hero" spell
     ResetModes( IDENTIFYHERO );
+}
 
+const EventsDate Kingdom::ActionNewDayResourceUpdate()
```
Comment (ihhub) [inline src/fheroes2/kingdom/kingdom.cpp:241]: In order to avoid unnecessary double event loops and also not to mix UI and logic this method can accept an `std::function`. For AI it is going to be nullptr while for humans it is going to be passed as a lambda function:
```cpp
[]( const EventDate & event, const Funds & funds ) {
    if ( funds ) {
        fheroes2::showResourceMessage( fheroes2::Text( event.title, fheroes2::FontType::normalYellow() ), fheroes2::Text( event.message, fheroes2::FontType::normalWhite() ), Dialog::OK, funds );
    }
    else if ( !event.message.empty() ) {
        fheroes2::showStandardTextMessage( event.title, event.message, Dialog::OK );
    }
};
```
so then we don't need to have extra functions to run events for the second time. After this we:
- remove **ShowEventDayDialog()** function
- within **Interface::Basic::HumanTurn()** method
```cpp
...
    if ( !isload ) {
        if ( 1 < world.CountWeek() && world.BeginWeek() ) {
            ShowNewWeekDialog();
        }

       auto lambdaFunction = ...;
        ActionNewDayResourceUpdate( lambdaFunction ); // or directly define here.
        ...
```
- inside **Interface::Basic::StartGame()** method after line `world.ClearFog( player->GetColor() );` for AI we call **ActionNewDayResourceUpdate( nullptr )**.

At the end the code becomes smaller and we still don't mix logic and UI. What do you think?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @slawomir-witkowski . I put few more suggestions in this pull request. Would you mind to take a look once you have spare time?

File: src/fheroes2/kingdom/kingdom.cpp (hunk 3 above)
Comment (slawomir-witkowski) [reply src/fheroes2/kingdom/kingdom.cpp]: Hi, I made the suggested changes.

File: src/fheroes2/game/game_startgame.cpp [hunk 4]
```diff
@@ -716,6 +699,8 @@ fheroes2::GameMode Interface::Basic::StartGame()
 
                     conf.SetCurrentColor( player->GetColor() );
 
+                    world.ClearFog( player->GetColor() );
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:702]: Could you please explain why we need to clear fog here?

File: src/fheroes2/game/game_startgame.cpp [hunk 5]
```diff
@@ -761,6 +746,9 @@ fheroes2::GameMode Interface::Basic::StartGame()
                         Maps::Tiles::updateFogDirectionsInArea( { 0, 0 }, { world.w(), world.h() }, hotSeatAIFogColors( player ) );
                     }
 
+                    if ( !loadedFromSave )
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:749]: Please add parenthesis for this if-body. It would be easier to read.

File: src/fheroes2/resource/resource.h [hunk 6]
```diff
@@ -96,6 +96,7 @@ class Funds
     int GetValidItems() const;
     uint32_t GetValidItemsCount() const;
 
+    Funds CalculateEventResourceUpdate( const Funds & eventFunds ) const;
```
Comment (ihhub) [inline src/fheroes2/resource/resource.h:99]: I think this method shouldn't belong to this class as it's for a very specific case. Usually developers just create a separate helper function outside the class to address specific cases. For instance you can take on a mess which still exist in Maps::Tiles class where many non-generic methods were added in the past.

What do you think, @oleg-derevenetz ?

File: src/fheroes2/kingdom/kingdom.cpp [hunk 7]
```diff
@@ -256,9 +259,12 @@ void Kingdom::ActionNewDay()
     }
 
     // Resources from events
-    const EventsDate events = world.GetEventsDate( GetColor() );
+    EventsDate events = world.GetEventsDate( GetColor() );
     for ( const EventDate & event : events ) {
-        AddFundsResource( event.resource );
+        Funds fundsUpdate = GetFunds().CalculateEventResourceUpdate( event.resource );
```
Comment (ihhub) [inline src/fheroes2/kingdom/kingdom.cpp:264]: Please make this variable const.

File: src/fheroes2/heroes/heroes_action.cpp [hunk 8]
```diff
@@ -2667,7 +2667,9 @@ namespace
         if ( event_maps && event_maps->isAllow( hero.GetColor() ) ) {
             hero.SetMove( false );
 
-            std::vector<fheroes2::ResourceDialogElement> resourceUI = fheroes2::getResourceDialogElements( event_maps->resources );
+            Funds fundsToUpdate = hero.GetKingdom().GetFunds().CalculateEventResourceUpdate( event_maps->resources );
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes_action.cpp:2670]: Please make this variable const.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @slawomir-witkowski , I added few more comments and questions here. We've almost completed it. Would you mind to check them?

File: src/fheroes2/game/game_startgame.cpp (hunk 4 above)
Comment (slawomir-witkowski) [reply src/fheroes2/game/game_startgame.cpp]: This shouldn't be here. My mistake.

File: src/fheroes2/resource/resource.h (hunk 6 above)
Comment (oleg-derevenetz) [reply src/fheroes2/resource/resource.h]: @ihhub I'm fine with the current solution where this auxiliary function is moved to the namespace.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@slawomir-witkowski , huge thanks for these changes!
