### PR TITLE
Fix map monster attack and fade animation

### LINKED ISSUE #812: Missing attacking animation of creatures being attacked on a world map
In the OG Creature you attacked changes its icon to attacking stance. Also it turns to the side, hero attacks it from.
Attack

### LINKED ISSUE #936: Disappearing monster on the map is shifted before animation
A monster after being attacked and defeated has a different location on the map. Here is a screenshot of the monster before being attacked:
image

and this is its position during fading animation:
image

There is obviously a shift for a monster which we need to fix.

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #936 . Fixes #812 .

There's two ICN files with monster sprites: MONS32 (full one, for UI) and MINIMON (with animation, split in two parts). Wrong sprite cause animation shift because offsets are different.

### CODE REVIEW

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 1]
```diff
@@ -177,12 +177,30 @@ void Interface::GameArea::Redraw( Surface & dst, int flag ) const
...
+            const std::pair<int, int> monsterIndicies = Maps::Tiles::GetMonsterSpriteIndices( world.GetTiles( removalInfo.tile ), removalInfo.index );
+
+            // base monster sprite
+            if ( monsterIndicies.first ) {
+                Sprite sprite = AGG::GetICN( ICN::MINIMON, monsterIndicies.first );
+                sprite.SetAlphaMod( removalInfo.alpha, false );
+                BlitOnTile( dst, sprite, sprite.x() + 16, sprite.y() + TILEWIDTH, mp );
+            }
+            // animated monster part
+            if ( monsterIndicies.second ) {
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:193]: This value could be -1 leading to a list of debug messages.

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 2]
```diff
@@ -177,12 +177,30 @@ void Interface::GameArea::Redraw( Surface & dst, int flag ) const
...
-        surface.SetAlphaMod( removalInfo.alpha, false );
         const Point mp = Maps::GetPoint( removalInfo.tile );
-        BlitOnTile( dst, surface, 0, 0, mp );
+        const int icn = MP2::GetICNObject( removalInfo.object );
+
+        if ( icn == ICN::MONS32 ) {
+            const std::pair<int, int> monsterIndicies = Maps::Tiles::GetMonsterSpriteIndices( world.GetTiles( removalInfo.tile ), removalInfo.index );
+
+            // base monster sprite
+            if ( monsterIndicies.first ) {
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:187]: Index could be equal to 0 but not less than it.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 3]
```diff
@@ -2549,6 +2509,48 @@ void Maps::Tiles::UpdateRNDResourceSprite( Tiles & tile )
...
+    // scan hero around
+    const MapsIndexes & v = ScanAroundObject( tileIndex, MP2::OBJ_HEROES );
+    for ( MapsIndexes::const_iterator it = v.begin(); it != v.end(); ++it ) {
+        const Tiles & heroTile = world.GetTiles( *it );
+        attackerIndex = *it;
+
+        if ( tile.isWater() != heroTile.isWater() )
+            attackerIndex = -1;
+        else
+            break;
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:2528]: We should write like this:
```
if ( tile.isWater() == heroTile.isWater() ) {
    attackerIndex = *it;
    break;
}
```

**Comment by ihhub** [comment]
@idshibanov , thanks a lot for fixing these issues in a shot!
