### PR TITLE
Fix AI capturing a dwelling protected by monsters

### LINKED ISSUE #7245: Игра падает
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

/home/toper/Games/HOMM2/fheroes2                                                                                                                                                                             ──(Вс,мая28)─┘
fheroes2 engine, version: 1.0.4
28.05.2023 17:35:52: [ERROR]    _createRenderer:  Failed to set a linear scale hint for rendering.
----------
Main Menu

Press N to choose New Game.
Press L to choose Load previously saved game.
Press H to show High Scores.
Press C to show Credits.
Press T to open Game Settings.
Press Q or ESCAPE to Quit the game.
----------
----------
Load Game

Press S to choose Standard Game.
Press C to choose Campaign Game.
Press M to show Multi-Player Game.
Press ESCAPE to go back to Main Menu.
----------
----------
�������� ���

��������� ���� ����� ��� ����� ������.
�� ������������� ������ ��������� ���?
Press RETURN to choose YES.
Press ESCAPE to choose NO.
----------
fheroes2: ../fheroes2/maps/maps_tiles_helper.cpp:834: void Maps::updateDwellingPopulationOnTile(Maps::Tiles&, bool): Assertion `count > 0' failed.
[1]    11188 IOT instruction (core dumped)  /home/toper/Games/HOMM2/fheroes2

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/11583896/AUTOSAVE.zip)
[SURFTURF.MX2.zip](https://github.com/ihhub/fheroes2/files/11583902/SURFTURF.MX2.zip)

### Additional info

Приложил сейв и карту.

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #7245

In master build it possible that AI captures the Dragon City (or Troll Bridge, or City of Dead), byes all creatures and is vanquished. So the dwelling's color is reset to NONE and we have 0 creatures count.

This PR makes AI logic as for non-AI heroes: Set ownership of the dwelling to a Neutral (gray) player.
Also to fix such cases (with 0 creatures and NONE color after AI vanquish) the dwelling population is increased like the dwelling was captured.

### CODE REVIEW

File: src/fheroes2/ai/ai_hero_action.cpp [hunk 1]
```diff
@@ -1292,7 +1292,8 @@ namespace
             if ( res.AttackerWins() ) {
                 hero.IncreaseExperience( res.GetExperienceAttacker() );
 
-                setColorOnTile( tile, hero.GetColor() );
+                // Set ownership of the dwelling to a Neutral (gray) player so that any player can recruit troops without a fight.
+                setColorOnTile( tile, Color::UNUSED );
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/ai_hero_action.cpp:1296]: Hi @Districh-ru I'm not sure that this is a proper behavior. First of all, why just AI? Human player can be vanquished as well in multiplayer game. Also, IIRC, there is special logic that shows the actual number of creatures in such a dwelling to the last player who successfully visited it. Try to press the right mouse button on Dragon City when playing by different kingdoms before and after visiting the Dragon City.

Comment (Districh-ru) [reply src/fheroes2/ai/ai_hero_action.cpp:1296]: Hi @oleg-derevenetz, the same change is already made in #6786, but in that PR I forgot to make the change to AI player.

Comment (oleg-derevenetz) [reply src/fheroes2/ai/ai_hero_action.cpp:1296]: > the same change is already made for Human player in https://github.com/ihhub/fheroes2/pull/6786

Ah, it's OK then.

File: src/fheroes2/maps/maps_tiles_helper.cpp [hunk 2]
```diff
@@ -801,11 +801,23 @@ namespace Maps
 
         case MP2::OBJ_TROLL_BRIDGE:
         case MP2::OBJ_CITY_OF_DEAD:
-            count = isFirstLoad ? Rand::Get( 4, 6 ) : ( Color::NONE == getColorFromTile( tile ) ) ? count : count + Rand::Get( 1, 3 );
+            if ( isFirstLoad ) {
+                count = Rand::Get( 4, 6 );
+            }
+            else if ( getColorFromTile( tile ) != Color::NONE || count == 0 ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles_helper.cpp:807]: Hi @Districh-ru is there a real possibility that tile color would be `NONE` (so the left part of this expression would be `false`), but `count` would be zero?

Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles_helper.cpp:807]: Currently it is possible and it happens in save, attached to #7245. This change is made to allow to continue the game in such cases.
In future there should be no such cases and it will be just an overprotect.

Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles_helper.cpp:807]: > This change is made to allow to continue the game in such cases.

Yes, I mean that maybe it would be good to add the "fixup" with the appropriate savefile version check to the corresponding `operator>>()` instead, because this is a temporary fix and "normally" this shouldn't be the case. Or maybe we can leave this check in place with TODO comment. I'm not sure what the best thing to do here.

Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles_helper.cpp]: I added the save file version check as in saves after v.1.0.5 this fix will not be needed.

**Review by oleg-derevenetz — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thanks a lot for this fix!
