### PR TITLE
Changed town portal's text and condition to be similar to town gate

### LINKED ISSUE #5164: Adventure map, Town Portal spell, operation should be adjusted to be similar to the Town Gate spell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the operation should be adjusted to be similar to the Town Gate spell.

In fheroes2:

The spell text should be grayed out when the player does not have a town or castle:
Town Portal 01

It should not be possible to cast the spell on the adventure map if the player does not have a town or castle:
Town Gate spell 03

"Town Portal

You do not currently own any town or castle, so you can't cast the spell."

Instead of:
Town Portal 02

In the Magic Book in the hero's screen.

In fheroes2:
Town Portal 03

"Town Portal

Returns the hero to the town or castle of choice, provided it is controlled by you.

You do not currently own any town or castle."

Here is the test scenario file:
[0 9936.zip](https://github.com/ihhub/fheroes2/files/8342306/0.9936.zip)

### Save file

Not needed.

### Additional info

Version 0.9.13 5161

Related closed PR: https://github.com/ihhub/fheroes2/pull/5120.

### PR DESCRIPTION
**Pull request by felix642**
closes #5164

### CODE REVIEW

File: src/fheroes2/heroes/heroes_base.cpp [hunk 1]
```diff
@@ -408,14 +408,20 @@ bool HeroBase::CanCastSpell( const Spell & spell, std::string * res /* = nullptr
...
+            bool hasCastles = std::any_of( castles.begin(), castles.end(), []( const Castle * castle ) { return castle && !castle->GetHeroes().Guest(); } );
+            if ( !hasCastles ) {
                 if ( res != nullptr ) {
                     *res = _( "You do not currently own any town or castle, so you can't cast the spell." );
                 }
                 return false;
             }
+        }
+
+        if ( spell == Spell::TOWNGATE ) {
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes_base.cpp:422]: Hi @felix642 , in this case `Dialog::Message( "", _( "No available towns.\nSpell Failed!!!" ), Font::BIG, Dialog::OK );` should never be executed. Please replace it by `assert( 0 );`.

**Comment by ihhub** [comment]
@felix642 , a bunch of thanks for fixing this issue!
