### PR TITLE
Fix cursor offsets

### LINKED ISSUE #365: Cursor glitching while pointing terrain objects
When you point any terrain object, hero cannot move through, cursor from a green horse becomes a default arrow. When you do it in a slow manner you can notice, that cursor appears in position slightly moved to the upper left. When you continue moving cursor - it returns the place it should be.
Безымянный4
Безымянный5
Безымянный6

### LINKED ISSUE #802: Cursor image doesn't match its actual position
I've noticed, that cursor changes its type over different objects on a world map not over the object, but a little shifted to right...
On a screenshots helmet's area is shifted to right. (Both helmets are screened at left and right edges)
cursor
cursor2
 I suppose this issue is connected with #365

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #365. Fixes #802.

Updating correct cursor offsets and applying it immediately after sprite switch.

### CODE REVIEW

File: src/fheroes2/gui/cursor.cpp [hunk 1]
```diff
@@ -48,33 +48,26 @@ int Cursor::Themes( void )
 bool Cursor::SetThemes( int name, bool force )
 {
     if ( force || theme != name ) {
-        if ( isVisible() )
-            Hide();
```
Comment (idshibanov) [inline src/fheroes2/gui/cursor.cpp:52]: Not sure why it was hiding it in the first place, but haven't noticed a difference after removing this. To me it makes no sense here.

**Comment by ihhub** [comment]
Hi @shprotru , could you please take a look into this pull request as it is to yours?

File: src/fheroes2/gui/cursor.cpp [hunk 2]
```diff
@@ -101,40 +94,17 @@ void Cursor::Move( s32 x, s32 y )
 }
 
 /* set offset big cursor */
-void Cursor::SetOffset( int name )
+void Cursor::SetOffset( int name, const Point & defaultOffset )
```
Comment (ihhub) [inline src/fheroes2/gui/cursor.cpp:97]: Hi @idshibanov , is it correct that for some cursors we don't have any offset while for the rest we have an offset to the center of the cursor?

File: src/fheroes2/gui/cursor.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/gui/cursor.cpp:52]: Most likely it's because we have `Hide` call before setting calling this method and `Show` call after.

Comment (ihhub) [reply src/fheroes2/gui/cursor.cpp:52]: Guess what? I tested it too and I see no problem after removing the cursor. I think it is because we redraw everything on mouse movement, in which case we always redraw the cursor :)

**Comment by ihhub** [comment]
Hi @idshibanov , thanks a lot for fixing these issues!

**Comment by shprotru** [comment]
Hi @ihhub after this merged it's very hard to understand how this changes should be merged with #515. I am totally confused in `cursor.cpp`, but on master branch on SDL2 build mouse cursor inertness actually present's and should be fixed.
