### PR TITLE
Optimize View World rendering

### LINKED ISSUE #4753: View World screen, all symbols (Mine, Artifact, etc.) are shifted
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, all symbols (Mine, Artifact, etc.) are shifted down.
Compare with the mines in the center completely south of the adventure map.
In the original game, there is a space between the mines and the bottom of the map, whereas in fheroes2 the mines are completely at the bottom of the map.
Also compare the artifacts that are indicated outside the map, as well as the resource piles in fheroes2.
The symbols are also not correctly centered horizontally on the objects.
Even the hero symbols are not centered correctly.

In original game:

View World icons position 001

In fheroes2:

View World icons position 002

In original game:

View World icons position 003

View World icons position 004

In fheroes2:

View World icons position 005

View World icons position 006

### Save file

Here is the save file:
[Broken_Alliance_0061 b.zip](https://github.com/ihhub/fheroes2/files/7655845/Broken_Alliance_0061.b.zip)

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/4200.

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR slightly optimizes the View World rendering, as the most CPU expensive is rendering of Adventure map (`gamearea.Redraw( temporaryImg, drawingFlags );`).

In this PR:
- Filling black borders is done without using `Transform` layer (without calling `Fill`).
- Map objects are rendered once on View World open for each zoom level.
- Removed creation of vector on every loop of map objects render.
- Interface elements are rendered once on View World open, using `Copy` instead of `Blit`.

Also fix #4753 , relates to #6017

Comparison of View World maps between fheroes2 and original game:
<details><summary>View screenshots</summary>

fheroes2, tile size 4:

Heroes 2, tile size 4:
4o
fheroes2, tile size 6:

Heroes 2, tile size 6:
6o
fheroes2, tile size 12:

Heroes 2, tile size 12:
12o

</details>

### CODE REVIEW

File: src/fheroes2/kingdom/view_world.cpp [hunk 1]
```diff
@@ -258,149 +277,152 @@ namespace
...
-                    int index = -1;
-
-                    int letterIndex = -1;
-
-                    int spriteOffsetX = 0;
-                    int spriteOffsetY = 0;
+        // Initialize variables before the loop to avoid many memory allocations inside the loop.
+        int32_t index{ -1 };
+        uint32_t letterIndex{ 0 };
+        // There could be maximum 2 objects.
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:287]: Could we please expand this comment a bit? Maximum 2 object for what?

Comment (ihhub) [reply src/fheroes2/kingdom/view_world.cpp:287]: We could also use **std::array<MP2::MapObjectType, 2>** to allocate memory on stack.

File: src/fheroes2/kingdom/view_world.cpp [hunk 2]
```diff
@@ -258,149 +277,152 @@ namespace
...
+        std::vector<MP2::MapObjectType> objectTypes( 2 );
+        uint32_t objects{ 0 };
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:289]: Should we name it as **objectCount** to be more clear what this variable is about?

File: src/fheroes2/kingdom/view_world.cpp [hunk 3]
```diff
@@ -258,149 +277,152 @@ namespace
...
+
+                    objectTypes[0] = tile.GetObject( false );
+
+                    if ( objectTypes[0] != tile.GetObject( true ) ) {
+                        objectTypes[1] = tile.GetObject( true );
+                        objects = 2;
+                    }
+                    else {
+                        objects = 1;
+                    }
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:310]: To avoid extra function calls I suggest to do this way:
```cpp
objectTypes[1] = tile.GetObject( true );
objectCount = ( objectTypes[0] == objectTypes[1] ) ? 1 : 2;
```
In this case we have only one call and the same number of comparisons. What do you think?

File: src/fheroes2/kingdom/view_world.h [hunk 4]
```diff
@@ -65,14 +68,14 @@ class ViewWorld
         const fheroes2::Rect & GetROIinPixels() const;
         fheroes2::Rect GetROIinTiles() const;
 
-        ZoomLevel _zoomLevel;
+        ZoomLevel _zoomLevel{ ZoomLevel2 };
         fheroes2::Point _center;
-        fheroes2::Rect _roiForZoomLevels[4];
+        std::vector<fheroes2::Rect> _roiForZoomLevels{ 4 };
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.h:73]: We can use **std::array<fheroes2::Rect, 4>** to allocate memory on stack.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put several comments in this pull request. Would you mind please to take a look at them?

File: src/fheroes2/kingdom/view_world.cpp [hunk 5]
```diff
@@ -65,23 +65,29 @@ namespace
...
-    const int tileSizePerZoomLevel[4] = { 4, 6, 12, 32 };
-    const int icnPerZoomLevel[4] = { ICN::MISC4, ICN::MISC6, ICN::MISC12, ICN::MISC12 };
-    const int icnLetterPerZoomLevel[4] = { ICN::LETTER4, ICN::LETTER6, ICN::LETTER12, ICN::LETTER12 };
-    const int icnPerZoomLevelFlags[4] = { ICN::VWFLAG4, ICN::VWFLAG6, ICN::VWFLAG12, ICN::VWFLAG12 };
+    const std::vector<int32_t> tileSizePerZoomLevel{ 4, 6, 12, 32 };
+    const std::vector<int32_t> icnPerZoomLevel{ ICN::MISC4, ICN::MISC6, ICN::MISC12, ICN::MISC12 };
+    const std::vector<int32_t> icnLetterPerZoomLevel{ ICN::LETTER4, ICN::LETTER6, ICN::LETTER12, ICN::LETTER12 };
+    const std::vector<int32_t> icnPerZoomLevelFlags{ ICN::VWFLAG4, ICN::VWFLAG6, ICN::VWFLAG12, ICN::VWFLAG12 };
+
+#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: Hi @ihhub, I've made 1:1 scale available, so now we have:
- *1 (23:32),
- *0,375 (12:32) - selected by default,
- *0,1875 (6:32)
- *0,125 (4:32) zooms.

File: src/fheroes2/kingdom/view_world.cpp (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: Sure!)

File: src/fheroes2/kingdom/view_world.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: I've expanded the comment and changed `std::vector` to `std::array` everywhere in this file as we always know the exact number of array elements.

File: src/fheroes2/kingdom/view_world.cpp (hunk 3 above)
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: Sure, it looks better, faster and does the same. 👍

**Comment by Districh-ru** [comment]
Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.

Yes, I will take a look at it sometime next week.

File: src/fheroes2/kingdom/view_world.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: Hi @ihhub!
Allowing the 1:1 zoom makes the engine to use extra 40 MB of memory on X-L maps. This is OK for PC, but maybe it is critical for mobile devices.
If it is so then we have to revert back and do not use 1:1 scale untill we rewrite the render for this scale (in another PR): for 1:1 scale we have to render the adventure map as usual, plus render the View World objects.

[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/kingdom/view_world.cpp]: This is a valid argument not to do. Let's not add 1:1 scale then.

File: src/fheroes2/kingdom/view_world.cpp [hunk 6]
```diff
@@ -143,48 +150,70 @@ namespace
...
         explicit CacheForMapWithResources( const ViewWorldMode viewMode )
         {
-#ifdef VIEWWORLD_DEBUG_ZOOM_LEVEL
-            cachedImages.resize( 4 );
-#else
-            cachedImages.resize( 3 );
-#endif
-
-            for ( size_t i = 0; i < cachedImages.size(); ++i ) {
+            for ( size_t i = 0; i < zoomLevels; ++i ) {
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:189]: Pleas make this variable `int32_t` as **zoomLevels**.

File: src/fheroes2/kingdom/view_world.cpp [hunk 7]
```diff
@@ -258,75 +299,99 @@ namespace
...
+            }
+        };
 
-        // add a margin of 2 tiles because icons outside of view can still show on the view
-        assert( worldWidth >= 0 && worldHeight >= 0 );
-        const int32_t minTileX = std::clamp( roiTiles.x - 2, 0, worldWidth );
-        const int32_t maxTileX = std::clamp( roiTiles.x + roiTiles.width + marginForRightSide + 2, 0, worldWidth );
-        const int32_t minTileY = std::clamp( roiTiles.y - 2, 0, worldHeight );
-        const int32_t maxTileY = std::clamp( roiTiles.y + roiTiles.height + 2, 0, worldHeight );
+        // Render hero/atrifact icon.
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:324]: Misspelled **atrifact**.

File: src/fheroes2/kingdom/view_world.cpp [hunk 8]
```diff
@@ -258,75 +299,99 @@ namespace
...
+                fheroes2::Blit( sprite, cache.cachedImages[zoomLevelId], dstx - sprite.width() / 2, dsty - sprite.height() / 2 );
+                const fheroes2::Sprite & letter = fheroes2::AGG::GetICN( icnLetterPerZoomLevel[zoomLevelId], letterIndex );
+                fheroes2::Blit( letter, cache.cachedImages[zoomLevelId], dstx - letter.width() / 2, dsty - letter.height() / 2 );
+            }
+        };
 
-                for ( const MP2::MapObjectType objectType : objectTypes ) {
-                    int icn = icnBase;
-                    int index = -1;
+        // There could be maximum 2 objects on the tile to analyze (in example: a Hero and a Catle).
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:357]: Misspelled **Catle**.

File: src/fheroes2/kingdom/view_world.cpp [hunk 9]
```diff
@@ -336,71 +401,35 @@ namespace
                     case MP2::OBJ_MINES:
                     case MP2::OBJ_SAWMILL:
                         if ( revealMines || !tile.isFog( color ) ) {
-                            index = colorToOffsetICN( tile.QuantityColor() );
-                            spriteOffsetX = -6; // TODO -4 , -3
-                            letterIndex = tile.QuantityResourceCount().first;
+                            const uint32_t colorOffset = colorToOffsetICN( tile.QuantityColor() );
+                            // Do not render an unknown color.
+                            if ( colorOffset != 7 ) {
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.cpp:406]: This is absolutely optional but I would suggest to avoid hardcoded values here and at line 392 but I understand why it is done.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put few very small comments. Could you please take a look?

File: src/fheroes2/kingdom/view_world.cpp (hunk 9 above)
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.cpp]: Hi @ihhub, I made `const uint32_t unknownIndex = UINT32_MAX;` for this.

**Review by ihhub — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , huge thanks for improving the code!

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hello @Districh-ru,
> 
> > Hi @LeHerosInconnu, could you, please, check does this PR solve the symbols positioning issue.
> 
> Yes, I will take a look at it sometime next week.

Here are my observations.

At the farthest zoom level, the icon positions are consistent with the original game.

In original game:

Icons View World 005

In fheroes2:

Icons View World 006

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

Icons View World 011 Icons View World 012

At the intermediate zoom level, in order to have an icon position that is consistent with the original game, it would be necessary to shift the icons one pixel down and one pixel to the right.

In original game:

Icons View World 003

In fheroes2:

Icons View World 004

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

Icons View World 009 Icons View World 010

At the highest zoom level, there is a problem with the display of the adventure map area depending on the positioning of the crosshair (https://github.com/ihhub/fheroes2/issues/6618).
I think that this problem should be corrected first before checking and possibly correcting the position of the icons.

In original game;

Icons View World 001

In fheroes2:

Icons View World 002

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

Icons View World 007 Icons View World 008

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu, thanks for the review!
The issue here is in the default map position and also in fact that tiles in OG and in fheroes2 are rendered differently: in fheroes2 it is a resize of original adventure map, while in original game at highest zoom level it is parts of original tiles (scaled by an integer factor and not 32/12 like in fheroes2) and at other zoom levels ... something else (generated from some points of original tile ???). So we cannot rely on tile images to check the position of icons.
In my first post you can see screenshots which are made by positioning the view to the right-bottom corner of the map, and the icon positions there looks consistent with OG.

I've opened a PR #6624 to fix the default map position on opening the View World.
