### PR TITLE
If the hero's army does not have any of the original troops left alive at the end of the battle, then the hero should lose

### LINKED ISSUE #3786: Adventure map, instant combat with summoned Elementals and Necromancy
Something goes wrong in this case, the Hero gets 1 more Skeleton.
May be linked to this closed issue: https://github.com/ihhub/fheroes2/issues/1496.

Before the combat, Sandro has an army of 32 Skeletons and 31 Vampire Lords.
vlcsnap-2021-07-02-19h51m30s722

After the instant battle, Sandro's starting army is completely decimated.
(Sandro summoned Elementals during the combat.)
vlcsnap-2021-07-02-19h23m59s927

Thanks to the Necromancy skill, Sandro gets 18 Skeletons back at the end of the combat (which also allows him not to disappear from the adventure map because the summoned Elementals will also disappear at the end of the combat).
vlcsnap-2021-07-02-19h50m31s830

However, when the human player gets the hand back, on the adventure map, Sandro's army has 19 Skeletons, which is 1 Skeleton in excess.
vlcsnap-2021-07-02-19h24m20s430

https://user-images.githubusercontent.com/43583994/124311377-eda71380-db6d-11eb-8241-8249b55b7eae.mp4

End the turn.

Here is the save file from related issue: https://github.com/ihhub/fheroes2/issues/3499.
[Before ai embark 02.zip](https://github.com/ihhub/fheroes2/files/6529080/Before.ai.embark.02.zip)

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3786

Apparently the behavior described in #775 is wrong - if all creatures from the initial army were killed in a battle, then the hero should lose regardless of using Resurrect during the battle.

### CODE REVIEW

File: src/fheroes2/battle/battle_army.h [hunk 1]
```diff
@@ -39,8 +39,8 @@ namespace Battle
 
         Units & operator=( const Units & ) = delete;
 
-        Unit * FindMode( u32 );
-        Unit * FindUID( u32 );
+        Unit * FindMode( u32 ) const;
+        Unit * FindUID( u32 ) const;
```
Comment (felix642) [inline src/fheroes2/battle/battle_army.h:43]: Hi @oleg-derevenetz since you're modifying those methods, would you mind changing the parameters to uint32_t as well ?

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 

> Apparently the behavior described in #775 is wrong - if all creatures from the initial army were killed in a battle, then the hero should lose regardless of using Resurrect during the battle.

I've just described the original behaviour here. ) After the battle is over in the OG A hero, that resurrected creature (Not the "true" spell) owns one creature from a resurrected stack...

**Comment by oleg-derevenetz** [comment]
@Branikolog

> I've just described the original behaviour here. ) After the battle is over in the OG A hero, that resurrected creature (Not the "true" spell) owns one creature from a resurrected stack...

According to tests (described in #3786 and #3812) this behavior is very unstable (sometimes it happens, but sometimes doesn't), so there is a suspicion that it's just a bug in OG and should not be replicated in fheroes2 - H3 behavior should be implemented instead (no "auto-resurrection", if hero doesn't have any of his original troops at the end of the battle, he will lose).

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this fix!
