### PR TITLE
Animations: correct attacks and timing

### LINKED ISSUE #500: Wrong animation while angled attack
While angled attacking phoenix's animation is the same as front attack animation.
Diagonal attack
Diagonal attack2
Diagonal attack3

### PR DESCRIPTION
**Pull request by idshibanov**
- Matching projectile sprites based on FRM data, including shooting angles.
- Using `shootSpeed` and `moveSpeed` variables from FRM file to drive the animation.
- Shifted global battle delay to 120ms, that's what is used for melee, wince and death.
- Fix Centaur projectile sprite, fix units wincing twice after lich attack.
- Draw bad luck animation.

Fixes #500 . Reused old branch here that's why you see that many commits. Diff is fine.

### CODE REVIEW

File: src/fheroes2/monster/monster.cpp [hunk 1]
```diff
@@ -1855,8 +1855,10 @@ void RandomMonsterAnimation::increment()
     _frameId = _frameSet.front();
     _frameSet.pop_front();
 
-    _frameOffset = _offsetSet.front();
-    _offsetSet.pop_front();
+    if ( !_offsetSet.empty() ) {
```
Comment (ihhub) [inline src/fheroes2/monster/monster.cpp:1858]: Could you please explain when can we reach the opposite condition?

File: src/fheroes2/battle/battle_interface.cpp [hunk 2]
```diff
@@ -2418,53 +2418,48 @@ void Battle::Interface::RedrawActionAttackPart1( Unit & attacker, Unit & defende
...
-        const Sprite & missile = AGG::GetICN( attacker.ICNMiss(), ICN::GetMissIndex( attacker.ICNMiss(), bp1.x - bp2.x, bp1.y - bp2.y ), bp1.x > bp2.x );
+        // Turns out OG missile offset is not perfect, so using 1/3 width and 3/4 height to compensate
+        const Point shooterPos( pos1.x + ( pos1.w / ( attacker.isReflect() ? 1.5 : 3 ) ), pos1.y + ( pos1.h * 3 / 4 ) );
+        // Calculating the 'center' of the defender, either left or right side
+        const Point targetPos = Point( pos2.x + ( pos1.x < pos2.x ? 0 : pos2.w ), pos2.y );
+
+        const int dx = targetPos.x - shooterPos.x;
+        const int dy = targetPos.y - shooterPos.y;
+        double angle = ( dx != 0 ) ? std::atan( static_cast<double>( -dy ) / static_cast<double>( dx ) ) * 180.0 / M_PI : ( dy < 0 ) ? 90 : -90;
+        if ( dx < 0 )
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:2444]: Let's create a boolean variable equal to `dx < 0` so we could it here and at line 2459 just for code readability.

File: src/engine/rect.h [hunk 3]
```diff
@@ -83,7 +83,8 @@ struct Rect : Point, Size
     bool operator&(const Point &)const;
     // rect intersects rect
     bool operator&(const Rect &)const;
-    //
+
+    Point getCenterPos() const;
```
Comment (ihhub) [inline src/engine/rect.h:87]: We do not use this function anywhere. Do we need it?

File: src/fheroes2/battle/battle_animation.cpp [hunk 4]
```diff
@@ -446,6 +446,36 @@ uint32_t AnimationReference::getFlightSpeed() const
...
+        else {
+            return _monsterInfo.projectileAngles.size() - 1;
+        }
+    }
+    return 0;
+}
+
+Point AnimationReference::getProjectileOffset( size_t direction ) const
+{
+    if ( _monsterInfo.projectileOffset.size() > direction ) {
```
[the remark this answers is not in the document]
Comment (idshibanov) [reply src/fheroes2/battle/battle_animation.cpp:473]: Uhm, no? Size should be 3 always and direction is 0...2

File: src/fheroes2/monster/monster.cpp (hunk 1 above)
Comment (idshibanov) [reply src/fheroes2/monster/monster.cpp:1858]: I had this crash on me a while ago when frame offsets weren't set right. `_pushFrames` doesn't guarantee that `_frameSet.size() == _offsetSet.size()`.

File: src/engine/rect.h (hunk 3 above)
Comment (idshibanov) [reply src/engine/rect.h:87]: I planned to use it for offsets but then realized that unit position Rect is not what I wanted it to be. I might need this in the future, but can remove if you want. I was actually thinking of overloading operators +/- for Point, would simplify the code a lot in the future.

File: src/fheroes2/battle/battle_animation.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/battle/battle_animation.cpp:469]: Yes, you are totally right! It is my mistake

File: src/engine/rect.h (hunk 3 above)
Comment (ihhub) [reply src/engine/rect.h:87]: Ideally, we should remove this just to simplify tracking changes.

File: src/fheroes2/battle/battle_interface.cpp [hunk 5]
```diff
@@ -21,7 +21,8 @@
  ***************************************************************************/
 
 #include <algorithm>
-#include <cmath>
+#define _USE_MATH_DEFINES
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:24]: Do we need this definition?

**Comment by ihhub** [comment]
I also fixed merging conflict from master. Please see if I did it in a right way.

File: src/fheroes2/battle/battle_interface.cpp (hunk 5 above)
Comment (idshibanov) [reply src/fheroes2/battle/battle_interface.cpp:24]: Yes, for M_PI, otherwise SDL1 version won't compile on windows. I can wrap this with ifndef.

Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp:24]: Shall we just define this variable instead of using this confusing definition? Something like this
```#define PI_VALUE 3.14159265358979323846`.? What is your opinion?

Comment (idshibanov) [reply src/fheroes2/battle/battle_interface.cpp]: Okay, in this case we don't need all that precision. I've put this in types.h with def guard, so it can use one defined in SDL2.

File: src/fheroes2/monster/monster.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/monster/monster.cpp:1858]: I'm curious how is it even possible that two arrays are not equal by sizes as
```
    if ( _offsetSet.size() != _frameSet.size() )
        _offsetSet.resize( _frameSet.size(), 0 );
```
makes equal arrays. I think the problem happened when arrays are empty. In this case we need to have a while loop at the beginning of this function `while ( _frameSet.empty() ) {` instead of `if ( _frameSet.empty() ) {`.

File: src/fheroes2/battle/battle_interface.cpp [hunk 6]
```diff
@@ -2418,53 +2417,51 @@ void Battle::Interface::RedrawActionAttackPart1( Unit & attacker, Unit & defende
...
-    if ( attacker.SwitchAnimation( actionStart ) ) {
-        RedrawTroopDefaultDelay( attacker );
-    }
-
-    // draw missile animation
+    // long distance attack animation
     if ( archer ) {
-        const Sprite & missile = AGG::GetICN( attacker.ICNMiss(), ICN::GetMissIndex( attacker.ICNMiss(), bp1.x - bp2.x, bp1.y - bp2.y ), bp1.x > bp2.x );
+        // Turns out OG missile offset is not perfect, so using 1/3 width and 3/4 height to compensate
+        const Point shooterPos( pos1.x + static_cast<uint32_t>( pos1.w / ( attacker.isReflect() ? 1.5 : 3 ) ), pos1.y + ( pos1.h * 3 / 4 ) );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:2436]: Using pos1 and pos2 is incorrect. For example, during this battle first archers have:
```
pos1.x = 529
pos1.y = 62
pos1.w = 44
pos1.h = 52
```
image

That is why I observed that arrows trajectory is slightly incorrect. Red rectangle on the image represents **pos1**, an yellow cross (at elves shoes) is **shooterPos**.

Comment (idshibanov) [reply src/fheroes2/battle/battle_interface.cpp:2436]: @ihhub I'm aware that pos1 and pos2 are not sprite positions, I even added few comments about this. I took some time trying to figure out this exact problem.

OG projectile offsets in `MonsterAnimInfo` are built in mind with being at the bottom of the sprite (around shoes), so to me `shooterPos` looks good. At some point I tried pulling sprite positions to calculate shooterPos but then when you apply OG offset FRONT missile will appear shifted up, not perfect either and very noticeable.

You can try drawing line between `line_from` and `targetPos`:
image
image

**Comment by ihhub** [comment]
Hi @idshibanov , could you please resolve merging conflicts? They have happened because of your another commit :(

Also one note: could you please intentionally make a code style mistake to check new GitHub Actions pipeline? I made such change to reduce the workload from Travis-CI and to receive results faster from our compilation platforms.

**Comment by idshibanov** [comment]
> Hi @idshibanov , could you please resolve merging conflicts? They have happened because of your another commit :(
> 
> Also one note: could you please intentionally make a code style mistake to check new GitHub Actions pipeline? I made such change to reduce the workload from Travis-CI and to receive results faster from our compilation platforms.

No problem, done!

**Comment by ihhub** [comment]
hi @idshibanov , it works perfectly fine. Thank you! You could fix these code styling issues while I'll remove Travis-CI code.

**Comment by ihhub** [comment]
Hi @idshibanov ,

I made a research on these calculations. Here is my solution to solve the arrow issue:
```
const Sprite & attackerSprite = AGG::GetICN( attacker.GetMonsterSprite().icn_file, attacker.GetFrame(), attacker.isReflect() );
const Point attackerPos = GetTroopPosition( attacker, attackerSprite );
const Point shooterPos( attackerPos.x + ( attacker.isReflect() ? 0 : pos1.w ), attackerPos.y + attackerSprite.h() / 2 );

const Sprite & defenderSprite = AGG::GetICN( defender.GetMonsterSprite().icn_file, defender.GetFrame(), defender.isReflect() );
const Point defenderPos = GetTroopPosition( defender, defenderSprite );
// Calculating the 'center' of the defender, either left or right side
const Point targetPos = Point( defenderPos.x + pos1.w / 2, defenderPos.y + defenderSprite.h() / 2 );

const int dx = targetPos.x - shooterPos.x;
const int dy = targetPos.y - shooterPos.y;
const bool reverse = dx < 0;
double angle = atan2( -dy, dx ) * 180.0 / M_PI;
// we only care about two quadrants, normalize
if ( reverse ) {
    angle = ( dy < 0 ) ? 180 - angle : -angle - 180;
}

// Angles are used in Heroes2 as 90 (TOP) -> 0 (FRONT) -> -90 (BOT) degrees
const int direction = angle >= 25.0 ? Monster_Info::TOP : ( angle <= -25.0 ) ? Monster_Info::BOTTOM : Monster_Info::FRONT;

// redraw archer attack animation
if ( attacker.SwitchAnimation( Monster_Info::RANG_TOP + direction * 2 ) ) {
    AnimateUnitWithDelay( attacker, attacker.animation.getShootingSpeed() );
}

// draw missile animation
const Sprite & missile = AGG::GetICN( attacker.ICNMiss(), attacker.animation.getProjectileID( angle ), reverse );
```
As a conclusion we do not use `GetStartMissileOffset` as it seems wrong. Are we sure that these values correct?

Overall now it seems very natural (with some slight few pixels offsets).

Could you please check this solution?

**Comment by ihhub** [comment]
@idshibanov , also please check this situation:
image

As you could see the arrow is not inverted.

**Comment by idshibanov** [comment]
> Overall now it seems very natural (with some slight few pixels offsets).
> 
> Could you please check this solution?

Yes, I'll do more research today. I'll check this plus I had a few ideas myself. I want to draw all 3 attack offsets so it's easier to see what's going on.

**Comment by idshibanov** [comment]
@ihhub your solution has fatal flaw: it ignores attack direction. It is **impossible** to be correct if projectile starts from the same point. When looking closely we can see that even for a straight line arrow starts its path underneath the bow:
image

This is exact problematic behavior I've seen trying to add `sprite.h / 2` to position. What's more correct is to add full height to get the bottom position and then add offset from `GetStartMissileOffset` with direction. Width has to be subtracted instead. This is the result, OG behavior:
```
Point shooterPos( attackerPos.x - ( attacker.isReflect() ? pos1.w : 0 ), attackerPos.y + attackerSprite.h() );
shooterPos111.x += offset.x;
shooterPos111.y += offset.y;
```

image

Looks perfect, right? But only for straight shot..

**Comment by ihhub** [comment]
> @ihhub your solution has fatal flaw: it ignores attack direction. It is **impossible** to be correct if projectile starts from the same point. When looking closely we can see that even for a straight line arrow starts its path underneath the bow:
> image
> 
> This is exact problematic behavior I've seen trying to add `sprite.h / 2` to position. What's more correct is to add full height to get the bottom position and then add offset from `GetStartMissileOffset` with direction. Width has to be subtracted instead. This is the result, OG behavior:
> 
> ```
> Point shooterPos( attackerPos.x - ( attacker.isReflect() ? pos1.w : 0 ), attackerPos.y + attackerSprite.h() );
> shooterPos111.x += offset.x;
> shooterPos111.y += offset.y;
> ```
> 
> image
> 
> Looks perfect, right? But only for straight shot..

I am more curious about start position of a missile. For example Archer has these values:
Projectile start positions:
[40, -62]
[62, -47]
[40, -1]

which for me looks incorrect. However, we could try to use these values mixing them with a Sprite position.

**Comment by idshibanov** [comment]
> I am more curious about start position of a missile. For example Archer has these values:
> Projectile start positions:
> [40, -62]
> [62, -47]
> [40, -1]
> which for me looks incorrect. However, we could try to use these values mixing them with a Sprite position.

This middle one `[62, -47]` is correct, but the other two are not. The point is that in OG missile start point is not right. So we have two options: go back to pre-defined starting points or we correct those two positions by small adjustment. What I am looking at right now is trying to determine this exact adjustment.

**Comment by idshibanov** [comment]
I'll clean up the branch once I figure out halfling's bug. They have a super weird sprite with base X position of -69. Here are a few screenshots meanwhile, three red crosses represent directional offset.

shooting

**Comment by idshibanov** [comment]
Turns out halflings have a very weird sprite with width of 278 pixels, so using `defenderSprite.w()` throws off all calculations.

Fixed the bug, now everything looks perfect to me. I even added the mage beam for #149 , although with 5 draw line calls.

image

File: src/fheroes2/battle/battle_interface.cpp [hunk 7]
```diff
@@ -2474,13 +2483,36 @@ void Battle::Interface::RedrawActionAttackPart1( Unit & attacker, Unit & defende
             if ( Battle::AnimateInfrequentDelay( Game::BATTLE_MISSILE_DELAY ) ) {
                 cursor.Hide();
                 Redraw();
-                missile.Blit( attacker.isReflect() ? ( *pnt ).x - missile.w() : ( *pnt ).x, ( *pnt ).y );
+                if ( attacker.GetID() == Monster::MAGE || attacker.GetID() == Monster::ARCHMAGE ) {
+                    display.DrawLine( Point( missileStart.x, missileStart.y - 2 ), Point( pnt->x, pnt->y - 2 ), PAL::GetPaletteColor( 0x77 ) );
+                    display.DrawLine( Point( missileStart.x, missileStart.y - 1 ), Point( pnt->x, pnt->y - 1 ), PAL::GetPaletteColor( 0xB5 ) );
+                    display.DrawLine( Point( missileStart.x, missileStart.y ), Point( pnt->x, pnt->y ), PAL::GetPaletteColor( 0xBC ) );
+                    display.DrawLine( Point( missileStart.x, missileStart.y + 1 ), Point( pnt->x, pnt->y + 1 ), PAL::GetPaletteColor( 0xB5 ) );
+                    display.DrawLine( Point( missileStart.x, missileStart.y + 2 ), Point( pnt->x, pnt->y + 2 ), PAL::GetPaletteColor( 0x77 ) );
```
Comment (idshibanov) [inline src/fheroes2/battle/battle_interface.cpp:2491]: Looks kinda ugly, but it uses 3 colors anyway, so hard to write a clean loop.

Is it worth replacing these with 3 calls of a new function? Performance-wise it will be similar anyway cause they go pixel-by-pixel..

**Comment by ihhub** [comment]
> Turns out halflings have a very weird sprite with width of 278 pixels, so using `defenderSprite.w()` throws off all calculations.
> 
> Fixed the bug, now everything looks perfect to me. I even added the mage beam for #149 , although with 5 draw line calls.
> 
> image

Please try to avoid width or height of a Sprite just because of this situation. The only ground truth is a position of a Sprite. I faced this problem many times.

File: src/fheroes2/battle/battle_interface.cpp [hunk 8]
```diff
@@ -2418,53 +2418,62 @@ void Battle::Interface::RedrawActionAttackPart1( Unit & attacker, Unit & defende
...
+        const Sprite & attackerSprite = AGG::GetICN( attacker.GetMonsterSprite().icn_file, attacker.GetFrame(), attacker.isReflect() );
+        const Point attackerPos = GetTroopPosition( attacker, attackerSprite );
+        const Sprite & defenderSprite = AGG::GetICN( defender.GetMonsterSprite().icn_file, defender.GetFrame(), defender.isReflect() );
+        const Point defenderPos = GetTroopPosition( defender, defenderSprite );
+
+        // For shooter position we need bottom center position of rear tile
+        // Use cell coordinates for X because sprite width is very inconsistent (e.g. halfling)
+        const int rearCenterX = ( attacker.isWide() && attacker.isReflect() ) ? pos1.w * 3 / 4 : CELLW / 2;
+        const Point shooterPos( pos1.x + rearCenterX, attackerPos.y + attackerSprite.h() );
+        const Point targetPos = Point( pos2.x + pos2.w / 2, defenderPos.y + defenderSprite.h() / 2 );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:2445]: Here please try to use an opposite value of `defenderSprite.y`. It should be the same as height but I found that one or two Sprites have extra empty field.

File: src/fheroes2/battle/battle_interface.cpp (hunk 7 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp:2491]: It is a special case so I think it is okay to leave it as it is. We have many special cases in the code.

File: src/fheroes2/battle/battle_interface.cpp (hunk 8 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp:2445]: I could be wrong :)

Comment (idshibanov) [reply src/fheroes2/battle/battle_interface.cpp:2445]: Tested, looks same to me. Changed.

**Comment by ihhub** [comment]
Hi @idshibanov , excellent job! Thank you very much for fixing this code!
