### PR TITLE
Make the regular small buttons translatable

### LINKED ISSUE #6155: Russian text is out of borders of MAX button
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
Until we optimize the Russian font I suggest to return back to MAX  instead of МАКС, which doesn't fit the button

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zenseii**
This generates and adds the small buttons to the engine.

Relates to #6331 #6194 https://github.com/ihhub/fheroes2/issues/1794
Part of solution to #6105 and https://github.com/ihhub/fheroes2/issues/3350

close #6155 

Buttons done:
CANCEL
OKAY
ACCEPT
DECLINE
S
M
L
X-L
ALL
NO
YES
TRADE
EXIT
DISMISS
UPGRADE
RESTART (Battle summary)
MAX (Recruit and fast split)

**Buttons for separate PRs:**

Campaign buttons (needs 3 variants):
VIEW INTRO
OKAY
CANCEL
RESTART

Irregular square buttons:
SKIP
AUTO
SELECT
MAX (WELL)
EXIT (Well, View Puzzle, View World)

### CODE REVIEW

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -649,6 +690,436 @@ namespace fheroes2
...
+                const bool isEvilInterface = ( id == ICN::BUTTON_SMALL_CANCEL_EVIL );
+
+                if ( useOriginalResources() ) {
+                    _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::CPANELE : ICN::CPANEL, 8 );
+                    _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::CPANELE : ICN::CPANEL, 9 );
+                    break;
+                }
+
+                int32_t textWidth = 86;
+                fheroes2::Point releasedOffset;
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:706]: I'm thinking that we might need to reduce code duplication as we so many identical cases. How about we create a function:
```cpp
void createNormalButton( fheroes2::Sprite & released, fheroes2::Sprite & pressed, int32_t textWidth, const char * text, const bool isEvilInterface )
{
    fheroes2::Point releasedOffset;
    fheroes2::Point pressedOffset;
    getCustomNormalButton( released, pressed, isEvilInterface, textWidth, releasedOffset, pressedOffset );

    const fheroes2::FontColor buttonFontColor = isEvilInterface ? fheroes2::FontColor::GRAY : fheroes2::FontColor::WHITE;

    renderTextOnButton( released, pressed, text, releasedOffset, pressedOffset, { textWidth, 16 }, buttonFontColor );
}
```

What do you think?

File: src/fheroes2/agg/agg_image.cpp [hunk 2]
```diff
@@ -649,6 +690,436 @@ namespace fheroes2
...
+                _icnVsSprite[id].resize( 2 );
+
+                const bool isEvilInterface = ( id == ICN::BUTTON_SMALL_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_EVIL );
+
+                if ( useOriginalResources() && ( id == ICN::BUTTON_SMALL_OKAY_EVIL || id == ICN::BUTTON_SMALL_OKAY_GOOD ) ) {
+                    _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 0 );
+                    _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 1 );
+                    break;
+                }
+                if ( useOriginalResources() && ( id == ICN::BUTTON_SMALLER_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_GOOD ) ) {
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:730]: I suggest to cache `useOriginalResources()` into a separate variable call as it is not instant to avoid double function call or we can do this:
```cpp
if ( useOriginalResources() ) {
    if ( id == ICN::BUTTON_SMALL_OKAY_EVIL || id == ICN::BUTTON_SMALL_OKAY_GOOD ) {
        _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 0 );
        _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 1 );
    }
    else if ( id == ICN::BUTTON_SMALLER_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_GOOD ) {
        _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 0 );
        _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 1 );
    }
    else {
        assert( 0 );
    }
    break;
}

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @zenseii , I left several comments in this pull request. Can you please take a look at them?

File: src/fheroes2/agg/agg_image.cpp [hunk 3]
```diff
@@ -649,6 +701,349 @@ namespace fheroes2
...
+                    _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 0 );
+                    _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::SPANBTNE : ICN::SPANBTN, 1 );
+                    break;
+                }
+                if ( isSameResourceAsLanguage && ( id == ICN::BUTTON_SMALLER_OKAY_EVIL || id == ICN::BUTTON_SMALLER_OKAY_GOOD ) ) {
+                    _icnVsSprite[id][0] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 0 );
+                    _icnVsSprite[id][1] = GetICN( isEvilInterface ? ICN::WINCMBBE : ICN::WINCMBTB, 1 );
+                    break;
+                }
+                int32_t textWidth = 86;
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:739]: Can we please add empty lines in this block between sections of the code? :)

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]
Besides of...

>There is an issue with the background shadow on the right side when pressed...

... which is relevant for almost every button on such stone-like background, everything seems to look nice. :+1:

**Comment by ihhub** [comment]
@zenseii , thank you so much for this improvement!
