### PR TITLE
Fix the scroll bar behavior after visiting a castle

### LINKED ISSUE #9522: Adventure map screen, positions of hero and castle lists are not retained after consulting a castle screen
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the positions of hero and castle lists are not retained after consulting a castle screen.

In fheroes2:

https://github.com/user-attachments/assets/e3c7f218-be23-4c6c-95fb-3bf28d901e47

### Save file

Here is the save file:
[Position castle list not memorized 01.zip](https://github.com/user-attachments/files/18631649/Position.castle.list.not.memorized.01.zip)

### Additional info

_No response_

### LINKED ISSUE #9695: Scoll bar isn't updated when heroes are added during your turn
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

How to reproduce: Start a map, recruit enough heroes to exceed the size of the item list for heroes and the scrollbar size won't update.

https://github.com/user-attachments/assets/5dec0834-8a31-4d56-b55f-f730e49cf28e

Image of bug:
There are actually 5 heroes in the right side panel.
Image

### Save file

None needed

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9522
fix #9695

### CODE REVIEW

File: src/fheroes2/game/game_startgame.cpp [hunk 1]
```diff
@@ -335,6 +335,8 @@ void Game::OpenCastleDialog( Castle & castle, bool updateFocus /* = true */, con
 
         // The castle garrison can change
         adventureMapInterface.RedrawFocus();
+        // A new hero could be hired in the castle
+        adventureMapInterface.ResetFocus( Interface::GetFocusType(), false );
```
Comment (Districh-ru) [inline src/fheroes2/game/game_startgame.cpp:339]: Hi @oleg-derevenetz, to fix this issue and keep https://github.com/ihhub/fheroes2/issues/9522 fixed we can add a condition:
```suggestion
        if ( heroCountBefore != myKingdom.GetHeroes().size() ) {
            // A new hero could be hired in the castle
            adventureMapInterface.ResetFocus( Interface::GetFocusType(), false );
        }
```

What do you think?

Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp:339]: > Hi @Districh-ru Need to figure this out a bit, because there is also some focus-related logic before these lines, inside the `if ( renderBackgroundDialog ) { ... }`, maybe all this can be simplified somehow... If you want, you are free to take a look, especially since you wrote this part, as far as I can see.

@oleg-derevenetz, I'll take a look and push a commit to this PR after doing some tests.

Comment (Districh-ru) [reply src/fheroes2/game/game_startgame.cpp]: @oleg-derevenetz, @zenseii,
I've updated the logic and checked hero recruiting: from the current castle, when switching between castles, when castle is opened from the Kingdom overview; checked hero dismissing and recruiting a hero from the jail.
#9522 is also fixed.

Could you please check the changes I made.

**Review by Districh-ru — APPROVED** [review]

File: src/fheroes2/game/game_startgame.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/game/game_startgame.cpp]: Hi @Districh-ru looks good to me, I tried different quirks by nested switching between castles and heroes and dismissing/hiring them and everything worked correctly.
