### PR TITLE
Fix update of map and players info when restarting the map that was changed and saved in Editor

### LINKED ISSUE #9944: Change in alliances for a map doesn't get updated until app restart
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Other

### Describe the bug

When making a map and saving it and then opening it later and adding/changing alliances, the original map before changes seems to be kept. If you restart the app, the changed alliances can be observed in the game.

Original map alliances:

Image

Original map description:

Image

Changed alliance:

Image

Wrong/Still old description and alliance setup:

Image

### Save file

None needed. Just make a map with at least three players and change alliances after saving the map once.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #9944

The issue happens if you star a map (or simply open a scenario info dialog when staring a new map and close it) then go to editor, change the players parameters, save the map and try to start a new game: the players parameters will be restored from the previous version of the map (now overwritten while saving).

This PR adds the reset of stored players' parameters to reload them when starting a new map.

It also removes redundant `Game::SavePlayers()` and `Game::LoadPlayers()` when changing the map because:
- there is no need to save players parameters from the previous map for the new different map, the parameters are always saved when leaving this dialog;
- the `Game::LoadPlayers()` immediately exits if the map name is different from the map name in ``Game::SavePlayers()` call and here they are always different.

### CODE REVIEW

File: src/fheroes2/game/game_scenarioinfo.cpp [hunk 1]
```diff
@@ -231,8 +231,9 @@ namespace
         const int buttonCancelIcn = isEvilInterface ? ICN::BUTTON_SMALL_CANCEL_EVIL : ICN::BUTTON_SMALL_CANCEL_GOOD;
         background.renderButton( buttonCancel, buttonCancelIcn, 0, 1, buttonOffset, fheroes2::StandardWindow::Padding::BOTTOM_RIGHT );
 
-        const Maps::FileInfo & mapInfo = [&lists, &conf = std::as_const( conf )]() {
```
Comment (ihhub) [inline src/fheroes2/game/game_scenarioinfo.cpp:234]: Are we sure that these optimizations don't break the logic? It seems to me that we are trying to cache a reference to an object which might be changed if a user changes a map.

Comment (ihhub) [reply src/fheroes2/game/game_scenarioinfo.cpp:234]: On the other hand the object in Setting class is always the same so even if the content of this object's structure changes the reference is still valid.

Comment (Districh-ru) [reply src/fheroes2/game/game_scenarioinfo.cpp:234]: After looking over the code I found that `_currentMapInfo` is not reallocated here because we use the same `Settings` instance.
The same we can say about `Players & players = conf.GetPlayers();`.
So the reference should be valid in any place of this code, IMHO.

Comment (Districh-ru) [reply src/fheroes2/game/game_scenarioinfo.cpp:234]: @ihhub, I've reverted this optimization to be absolutely sure that we access the real map info.
Also the `getCurrentMapInfo()` method is inlined.

File: src/fheroes2/editor/editor_interface.cpp [hunk 2]
```diff
@@ -2097,7 +2098,12 @@ namespace Interface
             // Set the saved map as a default map for the new Standard Game.
             Maps::FileInfo fi;
             if ( fi.loadResurrectionMap( _mapFormat, fullPath ) ) {
-                Settings::Get().setCurrentMapInfo( std::move( fi ) );
+                // Update the default map info to allow to start this map without the need to select it from the all maps list.
+                Settings & conf = Settings::Get();
+                conf.setCurrentMapInfo( std::move( fi ) );
+
+                // Reset saved players parameters (including alliances) for starting a new game because they may have changed in editor.
+                Game::SavePlayers( "", Players{} );
```
Comment (oleg-derevenetz) [inline src/fheroes2/editor/editor_interface.cpp]: I suppose, just `{}` should be enough here:

```suggestion
                Game::SavePlayers( "", {} );
```

**Review by oleg-derevenetz — APPROVED** [review]
Hi @Districh-ru looks good to me. I left just one optional suggestion related to style.

**Comment by ihhub** [comment]
@Districh-ru , thanks a lot for this great fix!
