### PR TITLE
Make AI more aggressive in losing situation

### LINKED ISSUE #3300: Combat, AI behavior, suggestion for last AI hero (fheroes2 0.9.2 3284)
I don't know how this is currently handled, but the last hero of an AI player should "fight to the death" in order to do maximum damage to the opposing troops, either by physical or magical damage.
Except in the case, where he has artifacts (but not cursed artifacts). :D

Ariel attacks Crag Hack.
Do your best to make the opposing troops be able to decimate a Phoenix, but the opposing hero runs away rather than decimate it.

In fheroes2:
The Iron Golems could have decimated a Phoenix.
Last AI Hero should fight to death fh2 01
Last AI Hero should fight to death fh2 02
Last AI Hero should fight to death fh2 03
Last AI Hero should fight to death fh2 04
Last AI Hero should fight to death fh2 05

Here is the save file:
[AI last hero should fight to d.zip](https://github.com/ihhub/fheroes2/files/6394998/AI.last.hero.should.fight.to.d.zip)

### LINKED ISSUE #4588: Game, AI behavior, last hero of an AI player should combat to death rather than flee (0.9.9 4551)
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the last hero of an AI player should combat to death rather than flee.

In the example, it is the last AI opposing hero. :)
But, the last hero of an AI player should combat to death rather than flee. 
It should be considered that the AI heroes should always try to do maximum damage to the human player's hero armies.

Some exceptions should also be considered.
The hero should flee if:
- he can no longer do damage to the opposing troops by magic or physical attack (no need to give extra experience points to the opposing hero).
- he has beneficial artifacts (if he has cursed artifacts, he can "offer" them to his opponent). :)

(It turns out that in the example, the opposing hero had some minor artifacts, but here it is more to illustrate the fact that the hero is fleeing.)

In fheroes2:

Last AI hero flees 01

Astra attacks Crag Hack.

### Save file

Here is the save file:
[Last AI hero flees 01.zip](https://github.com/ihhub/fheroes2/files/7500057/Last.AI.hero.flees.01.zip)

### Additional info

**Edit.**

Similar issue: https://github.com/ihhub/fheroes2/issues/3300.

It's time to stop. :D

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #4588 . Fixes #3300 .

Essentially if AI is left without castles and currently on timer it will take more risks and should focus on castle capture.

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_hero.cpp [hunk 1]
```diff
@@ -1180,7 +1185,7 @@ namespace AI
                 bool setNewMultiplier = false;
                 for ( int i = 0; i < monsterStrengthMultiplierCount; ++i ) {
                     if ( currentMonsterStrengthMultiplier > monsterStrengthMultipliers[i] ) {
-                        _pathfinder.setArmyStrengthMultiplier( monsterStrengthMultipliers[i] );
+                        _pathfinder.setArmyStrengthMultiplier( bestHero->isLosingGame() ? ARMY_ADVANTAGE_DESPERATE : monsterStrengthMultipliers[i] );
```
Comment (idshibanov) [inline src/fheroes2/ai/normal/ai_normal_hero.cpp:1188]: Might be a better way to handle this. I want to avoid unnecessary checks (with Medium & Small advantages) and go straight to the lowest though.

**Comment by ihhub** [comment]
@idshibanov , thank you very much for these improvements!
