### PR TITLE
Handle the AI hero's patrol mode in the AI pathfinder

### LINKED ISSUE #9015: AI is ignoring patrol limit
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

macOS

### Describe the bug

In some cases AI ignores patrol limit. The original map location and patrol information:

Screenshot 2024-07-30 at 00 22 53

Screenshot 2024-07-30 at 00 23 00

The hero was found lose way too far away from intended patrol area:

Screenshot 2024-07-30 at 00 29 17

### Save file

[Slayer_Legacy_0073.sav.zip](https://github.com/user-attachments/files/16419760/Slayer_Legacy_0073.sav.zip)

### Additional info

Revision: 81ddac960b83712b665be2efbd7c2dc5dc7e04ba

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9015

Currently in the `master` branch, the "patrol mode" is implemented as follows: objects outside the patrol radius are simply not considered as targets for the hero in "patrol mode". This leads to the possibility of behavior like this:

https://github.com/user-attachments/assets/2b42c8c9-7bde-4f67-89eb-566df29c11f2

This hero has the patrol mode enabled and a patrol radius of 4 tiles, thus, the artifact is "sort of" in this radius, so he does not hesitate to simply run through the already-explored territory to this object, even along a trajectory that is outside the patrol zone. I believe something similar could have happened in #9015, just on a larger scale.

With this PR:

https://github.com/user-attachments/assets/6715af88-4a08-41a1-bc3e-7f8e4372fc0e

Also, this PR removes any restrictions on the use of any adventure spells by heroes in patrol mode to pave the way. For instance, now such heroes can use Town Portal to teleport to any town or castle within their patrol radius.

### CODE REVIEW

File: src/fheroes2/ai/ai_planner_hero.cpp [hunk 1]
```diff
@@ -2452,19 +2436,16 @@ int AI::Planner::getPriorityTarget( const HeroToMove & heroInfo, double & maxPri
         if ( fogDiscoveryTarget >= 0 && fogDiscoveryValue > maxPriority ) {
             priorityTarget = fogDiscoveryTarget;
             maxPriority = fogDiscoveryValue;
-            DEBUG_LOG( DBG_AI, DBG_INFO, hero.GetName() << ": selected target: " << priorityTarget << " value is " << maxPriority << " (fog discovery)" )
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/ai_planner_hero.cpp:2455]: Here's another potential issue with fog discovery that could lead to heroes in patrol mode walking by themselves. If a hero in patrol mode had an object within his patrol radius as a target, but that target was so low priority that fog discovery was considered a higher priority, then this hero could perform fog discovery even outside his patrol radius. Now it's impossible because the AI pathfinder simply will not allow him to set a route outside the patrol area.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
I believe this PR should also fix #2315.

**Comment by ihhub** [comment]
@oleg-derevenetz , many thanks for this improvement!

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , could you please manage the project for a while as I need to solve many personal issues at the moment?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub 

> could you please manage the project for a while as I need to solve many personal issues at the moment?

Yes, of course. But I am not very familiar with some parts of the project, for example, the Editor. I hope you will be back soon.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much!

**Comment by oleg-derevenetz** [comment]
> I believe this PR should also fix https://github.com/ihhub/fheroes2/issues/2315.

Well, AI heroes of patrol will not return to the "starting point", because this point doesn't have any "special value" for them. But of course they will perform a fog discovery within their patrol area (see the video in the PR description), visit castles, regularly hire troops in the external dwellings and so on.
