### PR TITLE
Fix several button issues and do more button code cleanup

### LINKED ISSUE #2461: Combat screen, Surrender window, "ACCEPT" button has a graphic defect around it when it has been pressed
In fheroes2, the "ACCEPT" button has a graphic defect around it when it has been pressed.

In fheroes2:

vlcsnap-2020-12-23-09h02m51s306

https://user-images.githubusercontent.com/43583994/102978027-25206d80-4504-11eb-8848-8aafb8808363.mp4

### LINKED ISSUE #4537: Hero info window, flaws of "DISMISS" button
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In a case hero visits a castle we watch "DISMISS" button in a disabled state.
image
The button has double bottom edge and flaws with background near top corners.
image

### Save file

Any visiting hero in a castle has such flaw in info window.

### Additional info

_No response_

### LINKED ISSUE #9261: Button rendering issue in Autocombat UI with localized buttons
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There is an ugly border around the "restart" button in the German localization. This seems to be independent of the resolution, I tried multiple.

image

### Save file

[Alteris_0001.zip](https://github.com/user-attachments/files/17661168/Alteris_0001.zip)

### Additional info

_No response_

### LINKED ISSUE #9292: Combat, Surrender window, a line of black pixels is displayed at the top and to the right of the "DECLINE" button when pressed
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, a line of black pixels is displayed at the top and to the right of the "DECLINE" button when pressed.
A line of black pixels is also displayed to the left and at the bottom of the "ACCEPT" button when it is in its "grayed out" state (inaccessible).

When the user accesses the marketplace to obtain the requested gold, the "ACCEPT" button has the same problem of a line of black pixels at the top and to the right of the button as the "DECLINE" button when pressed.

In fheroes2:

Decline surrender button 01

### Save file

Here is the save file (1.1.3 9258)(end the turn):
[Decline surrender button 01.zip](https://github.com/user-attachments/files/17848229/Decline.surrender.button.01.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by zenseii**
This PR cleans up the button code further, doing a lot of reorganizing of the `generateDefaultImages()` so that buttons are grouped more logically together. This PR also adds a new method to render text-adapted buttons to the `StandardWindow` class. This PR also addresses these issues:

Fix #9292 
Fix #2461
Fix #9261
Fix #4537

Adding gradient shadows to army info dialog as part of #9552 (a consequence of fixing missing exit button shadow in editor's castle specs dialog.)

In addition, these improvements were made:
Fix French and German Accept and Decline, High score buttons (bug present in OG). French Okay and cancel visual errors (bug present in OG).
Adjustments to the good to evil button conversion table.

Also the missing shadow from the exit button in the castle specs window in the Editor was fixed.

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @zenseii 

I've noticed that exit button in castle options for the editor have some flaws not. There were some issues before, but with the PR they became more noticeable:
image
ezgif com-animated-gif-maker (8)

Also, I've noticed that restrict button was shifted slightly. Was it made on purpose?

I couldn't check https://github.com/ihhub/fheroes2/issues/9261, but the issue from my comment there is still on (https://github.com/ihhub/fheroes2/issues/9261#issuecomment-2650580929).
Surrender buttons work nice now!

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -462,6 +464,15 @@ namespace
         std::fill( imageTransform + imageHeight * imageWidth - 4, imageTransform + imageHeight * imageWidth, transparencyValue );
     }
 
+    void fillTransparentButtonText( fheroes2::Sprite & released )
+    {
+        fheroes2::Image background( released.width(), released.height() );
+        Fill( background, 0, 0, released.width(), released.height(), 10 );
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:470]: We can use a method of the `fheroes2::Image` class:
```cpp
background.fill( 10 );
```

File: src/fheroes2/agg/agg_image.cpp [hunk 2]
```diff
@@ -885,254 +938,482 @@ namespace
...
+        case ICN::BUTTON_QUIT_GOOD:
+        case ICN::BUTTON_SAVE_GAME_EVIL:
+        case ICN::BUTTON_SAVE_GAME_GOOD:
+        case ICN::BUTTON_LOAD_GAME_EVIL:
+        case ICN::BUTTON_LOAD_GAME_GOOD:
+        case ICN::BUTTON_NEW_GAME_EVIL:
+        case ICN::BUTTON_NEW_GAME_GOOD:
+        case ICN::BUTTON_SAVE_MAP_GOOD:
+        case ICN::BUTTON_LOAD_MAP_GOOD:
+        case ICN::BUTTON_NEW_MAP_GOOD: {
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:1306]: It would be great if we sort these entries alphabetically.

File: src/fheroes2/agg/agg_image.cpp [hunk 3]
```diff
@@ -885,254 +938,482 @@ namespace
...
+        case ICN::BUTTON_NEW_MAP_EVIL:
+        case ICN::UNIFORM_EVIL_MAX_BUTTON:
+        case ICN::UNIFORM_EVIL_MIN_BUTTON:
+        case ICN::BUTTON_SMALL_MAX_EVIL:
+        case ICN::BUTTON_SMALL_MIN_EVIL:
+        case ICN::BUTTON_SMALL_ACCEPT_EVIL:
+        case ICN::BUTTON_SMALL_DECLINE_EVIL:
+        case ICN::BUTTON_GIFT_EVIL:
+        case ICN::BUTTON_SMALL_RESTART_EVIL:
+        case ICN::BUTTON_MAP_SELECT_EVIL: {
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:1248]: It would be great if we sort these entries alphabetically.

**Review by ihhub — COMMENTED** [review]
Hi @zenseii , I left 3 small comments here. Would you mind to check them?

**Comment by Districh-ru** [comment]
> @Districh-ru, what do you think about adding an assertion to `setTransparentButtonCorners()`:
> 
> ```c++
> void setButtonCornersTransparent( fheroes2::Sprite & buttonSprite )
>     {
>         // There is no transform layer to add transparency to.
>         assert( !buttonSprite.singleLayer() );
> ```

Hi @zenseii, it is a good idea!
We can also do return from this function if the assertion is skipped:
```c++
void setButtonCornersTransparent( fheroes2::Sprite & buttonSprite )
    {
        if ( buttonSprite.singleLayer() ) {
            // There is no transform layer to add transparency to.
            assert( 0 );
            return;
        }
```

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@zenseii , thank you so much for these changes!
