### PR TITLE
Fix multiple issues with castle music

### LINKED ISSUE #3709: Kingdom Overview screen, terrain music should be restored from where it was interrupted when a castle screen is exited after being opened from the "Kingdom Overview" screen
In fheroes2, the terrain music should be restored from where it was interrupted when a castle screen is exited after being opened from the "Kingdom Overview" screen.

When the "Kingdom Overview" screen is opened, the music of the terrain where the hero or the castle is located is played.
When a castle screen is opened from the "Kingdom Overview" screen, the music of the castle is played.
When the castle screen is exited, the game returns to the "Kingdom Overview" screen but the castle music continues to be played.
The terrain music should be played from the point where it was interrupted.
(Also if the "Kindom Overview" screen is exited, the castle music continues to play until a hero or castle is selected).

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/122599228-4bb40100-d06e-11eb-98b8-0b6c220f0005.mp4

### LINKED ISSUE #3761: Adventure map/Castle screen Town theme continues to play after entering castle using spacebar
A hero should be inside a castle. Press spacebar, while hero is selected. 
image
After exiting a castle, theme continues to play.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3709
fix #3761

### CODE REVIEW

File: src/fheroes2/game/game_startgame.cpp [hunk 1]
```diff
@@ -176,7 +175,39 @@ void Game::OpenCastleDialog( Castle & castle, bool updateFocus /*= true*/ )
...
+        }
     }
+    else {
+        // If we don't update focus, we still have to restore environment sounds and terrain music theme
+        AGG::ResetMixer();
+
+        switch ( Interface::GetFocusType() ) {
+        case GameFocus::HEROES: {
+            const Heroes * focusedHero = Interface::GetFocusHeroes();
+            assert( focusedHero != nullptr );
```
Comment (ihhub) [inline src/fheroes2/game/game_startgame.cpp:189]: I think one of experimental options allows to put a hero into garrison loosing the focus of the castle. Could you please check this?

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left just one comment for verification. Would you mind to take a look?

File: src/fheroes2/game/game_startgame.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/game/game_startgame.cpp:189]: Hi @ihhub `Interface::GetFocusType()` is currently works like this:

```
int Interface::GetFocusType( void )
{
    Player * player = Settings::Get().GetPlayers().GetCurrent();

    if ( player ) {
        Focus & focus = player->GetFocus();

        if ( focus.GetHeroes() )
            return GameFocus::HEROES;
        else if ( focus.GetCastle() )
            return GameFocus::CASTLE;
    }

    return GameFocus::UNSEL;
}
```

and `Interface::GetFocusHeroes()` works like this:

```
Heroes * Interface::GetFocusHeroes( void )
{
    Player * player = Settings::Get().GetPlayers().GetCurrent();

    return player ? player->GetFocus().GetHeroes() : nullptr;
}
```

So `GetFocusType()` may only return `GameFocus::HEROES` if `GetFocusHeroes()` is not `nullptr`. But I added an assert just in case to catch early any issues if this will change in future.

Comment (ihhub) [reply src/fheroes2/game/game_startgame.cpp:189]: Got it. Thank you for the explanation.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this fix!
