### PR TITLE
Fix the pathfinding near monsters (OG-style)

### LINKED ISSUE #2888: Hero's disappearance after move through enemy
Снимок экрана_2021-03-01_09-13-09
Attack vampires by Crodo. After 2 battles hero will disappear.
Снимок экрана_2021-03-01_09-15-01

Save: 
[bug.zip](https://github.com/ihhub/fheroes2/files/6059498/bug.zip)

~Also, sometimes in this position I have game crash with message:
`fheroes2: ../fheroes2/battle/battle_board.cpp:824: void Battle::Board::SetCobjObject(int, s32): Assertion 'at( dst + 1 ).GetObject() == 0' failed.`~

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #2888

Alternative approach to #2910 - just don't apply (flawed) logic with restrictions on the passage of protected cells. This should work OG-style: hero can pass by the monster via adjacent cell (and will be attacked by one of the monsters guarding the cell), but not pass through the monster, as it happening now.

### CODE REVIEW

**Comment by idshibanov** [comment]
Issue with this version:
image

Yes, battle will be still triggered, but you shouldn't be able to set this path. Monsters should "block" movement for all tiles around them. I think this issue lies more in overlapping protection areas.

**Comment by oleg-derevenetz** [comment]
@idshibanov Well, then another ("HoMM3") approach is a way to go?

**Comment by Branikolog** [comment]
In the OG hero can step on the cell guarded by a creature either from adjacent free cell or if he's already standing in the cell, guarded by creature. 
Actually, I don't know if there is a difference between original H2 and H3...

**Comment by oleg-derevenetz** [comment]
@Branikolog I'll try to run OG on my Mac too (hope it's possible to do this using DOSBox or something else) to figure out the differences.

File: src/fheroes2/world/world_pathfinding.cpp [hunk 1]
```diff
@@ -259,25 +259,7 @@ std::list<Route::Step> PlayerWorldPathfinder::buildPath( int targetIndex ) const
 // Follows regular (for user's interface) passability rules
 void PlayerWorldPathfinder::processCurrentNode( std::vector<int> & nodesToExplore, int pathStart, int currentNodeIdx, bool fromWater )
 {
```
Comment (idshibanov) [inline src/fheroes2/world/world_pathfinding.cpp:261]: To fix this issue we have to skip tiles that contain monsters on them. Try this:
```
    if ( world.GetTiles( currentNodeIdx ).GetObject() == MP2::OBJ_MONSTER )
        return;
```

**Comment by oleg-derevenetz** [comment]
@idshibanov Yeah, I think this is more like the OG, if I understand the mechanics correctly. Now hero is able to attack the skeletons, passing by other nearby monsters:

OG

while in more strict "HoMM3-like" version he is able to attack only zombies, because he is unable to pass the cell guarded by both zombies & liches:

HoMM3

**Comment by oleg-derevenetz** [comment]
Yes, it seems that this mechanics is better.

**Comment by Branikolog** [comment]
Actually, on your second screenshot the cell is guarded by Liches, zombies and ghosts.)

**Comment by oleg-derevenetz** [comment]
@Branikolog Yes, that's true. In that version moving from nearby cell to diagonal cell considered as "retreating" too, although they are both guarded. Anyway, I think that mechanics from this PR looks better.

**Comment by ihhub** [comment]
> 
> 
> @Branikolog Yes, that's true. In that version moving from nearby cell to diagonal cell considered as "retreating" too, despite they are both guarded. Anyway, I think that mechanics from this PR looks better.

Hi @oleg-derevenetz , is this PR ready for review or we need to do something extra based on the discussion above?

**Comment by oleg-derevenetz** [comment]
Hi @ihhub I think it's ready, I closed the alternative PR already.

**Comment by ihhub** [comment]
@oleg-derevenetz , a huge thanks for your efforts making this project better one!
