### PR TITLE
Fix army order option related crash

### LINKED ISSUE #5167: Combat screen, Army order bar, the game crashes when the action bar goes over the edge of the screen and a hero flees or surrenders
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the game crashes when the action bar goes over the edge of the screen and a hero flees or surrenders.

In fheroes2:

Army order bar 004

### Save file

Here is the save file:
[Before full bar elemental 01.zip](https://github.com/ihhub/fheroes2/files/8344308/Before.full.bar.elemental.01.zip)

### Additional info

Version 0.9.13 5161

Related issue: https://github.com/ihhub/fheroes2/issues/5166.

### PR DESCRIPTION
**Pull request by ihhub**
This fixes #5167 . Also for cases when the number of units to display is more than the screen the order is floating (relates to #5166 ) which means that the bar will show only limited number of units but shifts the order during the progression of the battle.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @ihhub crash is not observed anymore, but there is problem with rendering:

Screenshot

Cavalry unit in upper left corner is never grayed out, although he skipped the turn.

**Comment by ihhub** [comment]
> Hi @ihhub crash is not observed anymore, but there is problem with rendering:
> 
> Screenshot
> 
> Cavalry unit in upper left corner is never grayed out, although he skipped the turn.

Hi @oleg-derevenetz , I addressed it. Please take a look.

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -911,23 +911,47 @@ void Battle::ArmiesOrder::Redraw( const Unit * current, const uint8_t currentUni
...
-            fheroes2::Rect::width += armyOrderMonsterIconSize;
+    int32_t unitsDrawn = 0;
+    int32_t unitsProcessed = 0;
+
+    for ( const Unit * unit : *orders ) {
+        if ( unitsDrawn == maximumUnitsToDraw ) {
+            break;
+        }
+
+        if ( unit == nullptr || !unit->isValid() ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/battle/battle_interface.cpp:939]: If `unit` from `orders` is `nullptr` then something is definitely wrong - it is already assumed that it may not be `nullptr` when `validUnitCount` is initialized. I suggest to add an assertion regarding this either on `validUnitCount` initialization or both here and on `validUnitCount` initialization, and remove this condition, because it's too late to check it here anyway.

**Review by oleg-derevenetz — CHANGES_REQUESTED** [review]
Hi @ihhub I just left one suggestion here, could you please take a look?

File: src/fheroes2/battle/battle_interface.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp]: Hi @oleg-derevenetz , I've added in both places.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, I partially addressed your suggestion for #5166 here.

I tried it, works fine. :)
