### PR TITLE
Fix sphinx riddle dialogs

### LINKED ISSUE #1361: Sphinx riddle, question window, add "Sphinx" as the title of the window
I suggest adding the title "Sphinx" to this window.

In the original game, this window also has no title.
I've always found it strange that some windows don't follow the convention of always having a title in Heroes 2.

Sphinx riddle 02

### LINKED ISSUE #1362: Sphinx riddle, reward window, add "Sphinx" as the title of the window
I suggest adding the title "Sphinx" to this window.

In the original game, this window also has no title.

Sphinx riddle 04

### LINKED ISSUE #1363: Sphinx riddle, challenge window, add "Sphinx" as the title of the window
I suggest adding the title "Sphinx" to this window.

In the original game, this window also has no title.

Sphinx riddle, challenge 01

### LINKED ISSUE #1364: Sphinx riddle, challenge window, wrong answer window, add "Sphinx" as the title of the window
I suggest adding the title "Sphinx" to this window.

In the original game, this window also has no title.

Sphinx riddle, challenge 02

### LINKED ISSUE #1365: Sphinx riddle, question window, answer field, response text length
In fheroes2, for the answer to the sphinx riddle, you must enter exactly the same answer as defined in the scenario editor.
In the original game, only the first four characters are needed to validate the answer.

This should be mentioned somewhere, as players familiar with how Heroes 2 works might be surprised.

In the scenario editor:

Sphinx riddle, response text length 01

### PR DESCRIPTION
**Pull request by undef21**
- add titles for dialogs;
- check the first 4 characters of answer only.
fix #1361
fix #1362
fix #1363
fix #1364
fix #1365

### CODE REVIEW

File: src/fheroes2/dialog/dialog.h [hunk 1]
```diff
@@ -102,7 +102,7 @@ namespace Dialog
     int ResourceInfo( const std::string &, const std::string &, const Funds &, int buttons = Dialog::OK );
     int SelectSkillFromArena( void );
     bool SelectCount( const std::string &, u32 min, u32 max, u32 & res, int step = 1 );
-    bool InputString( const std::string &, std::string & );
+    bool InputString( const std::string &, std::string &, const std::string & title = "" );
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog.h:105]: Could we please remove default value here? We use this function only in few places.

File: src/fheroes2/heroes/heroes_action.cpp [hunk 2]
```diff
@@ -3018,17 +3018,18 @@ void ActionToEyeMagi( const Heroes & hero, u32 obj )
 void ActionToSphinx( Heroes & hero, u32 obj, s32 dst_index )
 {
     MapSphinx * riddle = dynamic_cast<MapSphinx *>( world.GetMapObject( dst_index ) );
+    std::string title = MP2::StringObject( obj );
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes_action.cpp:3021]: This variable could be `const`.

File: src/fheroes2/dialog/dialog_selectcount.cpp [hunk 3]
```diff
@@ -219,19 +219,24 @@ bool Dialog::InputString( const std::string & header, std::string & res )
...
+    TextBox titlebox( title, Font::YELLOW_BIG, BOXAREA_WIDTH );
     TextBox textbox( header, Font::BIG, BOXAREA_WIDTH );
     const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ( Settings::Get().ExtGameEvilInterface() ? ICN::BUYBUILD : ICN::BUYBUILE ), 3 );
 
-    FrameBox box( 10 + textbox.h() + 10 + sprite.height(), true );
+    const uint32_t titleHeight = title.size() ? titlebox.h() + 10 : 0;
+    FrameBox box( 10 + titleHeight + textbox.h() + 10 + sprite.height(), true );
     const fheroes2::Rect & box_rt = box.GetArea();
 
+    if ( title.size() )
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_selectcount.cpp:230]: Please use `empty` method instead.

File: src/fheroes2/dialog/dialog_selectcount.cpp [hunk 4]
```diff
@@ -219,19 +219,24 @@ bool Dialog::InputString( const std::string & header, std::string & res )
     res.reserve( 48 );
     size_t charInsertPos = 0;
 
+    TextBox titlebox( title, Font::YELLOW_BIG, BOXAREA_WIDTH );
     TextBox textbox( header, Font::BIG, BOXAREA_WIDTH );
     const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ( Settings::Get().ExtGameEvilInterface() ? ICN::BUYBUILD : ICN::BUYBUILE ), 3 );
 
-    FrameBox box( 10 + textbox.h() + 10 + sprite.height(), true );
+    const uint32_t titleHeight = title.size() ? titlebox.h() + 10 : 0;
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_selectcount.cpp:226]: Please use `empty` method instead.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @undef21 , I left multiple code style comments. Could you please take a look?

**Comment by ihhub** [comment]
@undef21 , thank you very much for fixing these issues!
