### PR TITLE
Fix crash in Roland 10 scenario

### LINKED ISSUE #3581: Segfault OS X Map 10 Price of Loyalty
I have Seg Fault on OS X in the Price of Loyalty Map 10... In the start of the game if Kalindra attacks Corlagon and lightning bolts the Champions the same segfault after the victory screen.

Attached is part of the backtrace. I'll try to see if other combos work around or also crash but I tried it 3 times to make sure.

[sig_fault_osx-05312021.txt](https://github.com/ihhub/fheroes2/files/6571010/sig_fault_osx-05312021.txt)

-Mike

### PR DESCRIPTION
**Pull request by ihhub**
close #3581

### CODE REVIEW

File: src/fheroes2/kingdom/kingdom.cpp [hunk 1]
```diff
@@ -270,8 +272,13 @@ std::string Kingdom::GetNamesHeroStartCondLoss( void ) const
 void Kingdom::RemoveHeroes( const Heroes * hero )
 {
     if ( hero ) {
-        if ( heroes.size() )
-            heroes.erase( std::find( heroes.begin(), heroes.end(), hero ) );
+        if ( !heroes.empty() ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/kingdom/kingdom.cpp:275]: Hi @ihhub I think it worth to add similar assert() in RemoveCastles() too, what do you think? Now it has code written in the same manner.

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @ihhub, left one comment regarding possible update for `RemoveCastle()` as well.

File: src/fheroes2/kingdom/kingdom.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/kingdom/kingdom.cpp:275]: Sure, we can do this.
