### PR TITLE
File options menu disappears on cancelling load game dialog

### LINKED ISSUE #7665: File options menu disappears on cancelling load game dialog
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/17aa35ef-f0c1-4c00-97f7-335d5fffa427

Cancelling the dialog shouldn't close the entire menu.

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by lwollnikowski**
fix #7665

### CODE REVIEW

File: src/fheroes2/dialog/dialog_file.cpp [hunk 1]
```diff
@@ -97,8 +97,9 @@ fheroes2::GameMode Dialog::FileOptions()
                 fheroes2::showMessage( fheroes2::Text( _( "Load Game" ), fheroes2::FontType::normalYellow() ),
                                        fheroes2::Text( _( "No save files to load." ), fheroes2::FontType::normalWhite() ), Dialog::OK );
             }
-            else {
-                result = Interface::AdventureMap::Get().EventLoadGame();
+
+            if ( Interface::AdventureMap::Get().EventLoadGame() == fheroes2::GameMode::LOAD_GAME ) {
+                result = fheroes2::GameMode::LOAD_GAME;
                 break;
             }
```
Comment (Districh-ru) [inline src/fheroes2/dialog/dialog_file.cpp:104]: We should not remove the `else` statement. This new code should be executed only if `ListFiles::isEmpty()` returned `false` because we should not open Load Game dialog if there are no saved games.

```suggestion
            else {
                if ( Interface::AdventureMap::Get().EventLoadGame() == fheroes2::GameMode::LOAD_GAME ) {
                    result = fheroes2::GameMode::LOAD_GAME;
                    break;
                }
            }
```

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @lwollnikowski. I left one comment, could you please take a look when you have time.

File: src/fheroes2/dialog/dialog_file.cpp (hunk 1 above)
Comment (lwollnikowski) [reply src/fheroes2/dialog/dialog_file.cpp:104]: You are right, fixed.

**Review by Districh-ru — APPROVED** [review]

**Review by ihhub — APPROVED** [review]
