### PR TITLE
Explicitly call static function 'GetStrength()' to resolve the ambiguity between 'Army::GetStrength()' and 'Troops::GetStrength()'

### LINKED ISSUE #7298: Assertion while AI trying to split troops.
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

An assertion fails while AI turn:
`Assertion failed: weakestStack != nullptr, file G:\Games\heroes2\git\src\fheroes2\army\army.cpp, line 858`

### Save file

[troopSplitAssertion.zip](https://github.com/ihhub/fheroes2/files/11719315/troopSplitAssertion.zip)

### Additional info

This assertion occurs as for some reason AI hero has no troops in his army...

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #7298 

This PR fixes the army troops strength calculation while AI performing the army split by explicitly calling the static function 'GetStrength()' from the corresponding class.

The incorrect army strength calculation sometimes led to the dismissal of the only unit in the hero's army: [troopSplitAssertion.zip](https://github.com/ihhub/fheroes2/files/11719315/troopSplitAssertion.zip)

### CODE REVIEW

**Review by oleg-derevenetz — APPROVED** [review]

File: src/fheroes2/army/army.cpp [hunk 1]
```diff
@@ -698,7 +698,10 @@ void Troops::JoinStrongest( Troops & giverArmy, const bool keepAtLeastOneSlotFor
 
     // First check if the weakest troop is actually worth to keep.
     const double weakestStrength = weakest->GetStrength();
-    const double totalArmyStrength = GetStrength();
+    const double totalArmyStrength = Troops::GetStrength();
+
+    assert( totalArmyStrength >= weakestStrength );
+
     // The weakest army should not be more than 5% from the overall army strength.
     const double strengthLimit = totalArmyStrength / 20;
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:706]: I can't comment below so I do here: at line 734 we have the code:
```
cpp
weakest->SetCount( weakest->GetCount() - acceptableCount );
```
I think there could be the case when **acceptableCount** is equal to **weakest->GetCount()**. This is the case when the count is 1. Could you please modify the code to be:
```cpp
if ( acceptableCount == weakest->GetCount() ) {
    weakest->Reset();
}
else {
    weakest->SetCount( weakest->GetCount() - acceptableCount );
}

**Review by ihhub — CHANGES_REQUESTED** [review]

File: src/fheroes2/army/army.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/army/army.cpp:706]: @ihhub in fact, count 0 is fine, it is considered as an empty slot anyway.

Comment (ihhub) [reply src/fheroes2/army/army.cpp:706]: Then it is fine. We should come up with a better code design as the current one is very bad.

**Comment by ihhub** [comment]
@Districh-ru , thank you very much for the fix!
