### PR TITLE
QuickInfo dialogs have fixed position when clicked from right bar

### LINKED ISSUE #2248: Adventure map screen, wrong position of the information window of the castles and heroes for the lists of castles and heroes
In the original game, the information window of the castles in the list of castles is always displayed at the same position vertically and horizontally.
In fheores2, this is not the case and in addition the window is sometimes displayed over the minimap.

Also, I suggest that the vertical position of the castle information window be shifted one pixel downwards so that the top of the information window is vertically aligned with the top of the graphic frame of the first castle in the list of castles.

In original game:

Info position H2 02

Info position H2 01

In fheroes2:

Info position fh2 01

In the original game, the information window of the heroes in the list of heroes is always displayed at the same position horizontally.
In fheores2, this is not the case and in addition the window is sometimes displayed over the minimap.

Also, I suggest that the vertical and horizontal position of the hero information window to be fixe (as is the case for the castle information window) and that it be aligned vertically with the top of the graphic frame of the first hero in the list of heroes.
The horizontal distance between the frame of the hero graphic and the hero information window must also be 2 pixels (as it is the case for the castle information window).

In original game:

Info position H2 03

Info position H2 04

In fheroes2:

Info position fh2 02

### PR DESCRIPTION
**Pull request by vincent-grosbois**
Fix #2248

### CODE REVIEW

File: src/fheroes2/gui/interface_icons.cpp [hunk 1]
```diff
@@ -197,7 +197,8 @@ void Interface::CastleIcons::ActionListPressRight( CASTLE & item )
 {
     if ( item ) {
         Cursor::Get().Hide();
-        Dialog::QuickInfo( *item );
+        Point p( _topLeft.x - 1, _topLeft.y );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_icons.cpp:200]: Please make this variable `const` as we don't modify it.

File: src/fheroes2/gui/interface_icons.cpp [hunk 2]
```diff
@@ -283,7 +285,8 @@ void Interface::HeroesIcons::ActionListPressRight( HEROES & item )
...
```
Comment (ihhub) [inline src/fheroes2/gui/interface_icons.cpp:288]: Please make this variable `const` as we don't modify it.

File: src/fheroes2/gui/interface_icons.h [hunk 3]
```diff
@@ -99,6 +99,9 @@ namespace Interface
         void ActionListPressRight( HEROES & );
         void RedrawItem( const HEROES &, s32 ox, s32 oy, bool current );
         void RedrawBackground( const Point & );
+
+    private:
+        Point _topLeft;
```
Comment (ihhub) [inline src/fheroes2/gui/interface_icons.h:104]: This member needs a little bit more descriptive name as it's not obvious what is top left for. Also please use `fheroes2::Point` structure instead as` Point` is from old implementation. The same applies for the member in **CastleIcons** class.

Comment (ihhub) [reply src/fheroes2/gui/interface_icons.h:104]: Actually you can keep just `Point` for now.

File: src/fheroes2/gui/interface_icons.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/gui/interface_icons.cpp:200]: Please make this variable `fheroes2::Point` type as well at line 288 and use input parameter as fheroes2::Point for your newly created code.

File: src/fheroes2/dialog/dialog_quickinfo.cpp [hunk 4]
```diff
@@ -309,6 +309,34 @@ std::string ShowGroundInfo( const Maps::Tiles & tile, bool show, const Heroes *
     return str;
 }
 
+fheroes2::Rect MakeRectQuickInfo( LocalEvent & le, const fheroes2::Sprite & imageBox, const Point * fixedPositionTopRight )
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_quickinfo.cpp:312]: I'm not against using pointers but it feels a bit unusual to see a pointer among other input parameters. What if we pass `const fheroes2::Point & position = fheroes2::Point()` and check if x and y values of it less or equal to 0. Having `fixedPositionTopRight->x - imageBox.width()` expression makes the box invisible so it makes sense to check the values of Point. So we can avoid pointers and call `Dialog::QuickInfo( *item, fheroes2::Point( _topLeft.x - 1, _topLeft.y ) );` instead. What do you think?

Comment (ihhub) [reply src/fheroes2/dialog/dialog_quickinfo.cpp:312]: We can call the variable as `topRightOffset`. **fixed** is definitly redundant.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vincent-grosbois , I left multiple comments here. Could you please take a look and express your opinion?

**Comment by ihhub** [comment]
@vincent-grosbois thanks a lot for implementing this feature!
