### PR TITLE
Fix multiple issues with fullscreen mode on Windows

### LINKED ISSUE #5250: Windows: Embedding/locking fheroes2 to a side with DPI higher than 100% breaks fullscreen
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

When locking the game window to either side by using Windows Key + Left or Right Arrow, and then enter fullscreen breaks the window and it's not able to decide where to go and sometimes the window goes black. I'm on Windows 10. Resolution 1920x1080.

<details>
<summary>Locked to left half:</summary>

before
</details>

<details>
<summary>After pressing F4:</summary>

after

</details>

### Describe the possible solution

This is really low priority since there's not much reason to do this, but it's slightly related to the recent works on fullscreen mode.

### Additional info

Relevant discussion here: https://github.com/ihhub/fheroes2/pull/5209#issuecomment-1093628659

### LINKED ISSUE #6120: Fullscreen game mode: issues running on two screens
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Fheroes2 works really bad using 2 monitors currently.
After initiating the fullscreen mode of fheroes2 with dual monitor set up all applications from the main screen are shifted for ~0.5 screen width to the second screen.
Second screen after switching fheroes2 to fullscreen (on screen 1) with explorer stretched on the whole screen 1:
Screen1

Second screen after switching fheroes2 to fullscreen(on the screen 1) with explorer stretched on the whole screen 2:
Screen2

Note, that we can even see a recycle bin (and all shortcuts) from the right part of the main screen here.

In a case we run fheroes2 on the screen 2 using fullscreen mode, the second screen changes resolution for lower one...:
Screen3
... and the game runs on the main screen in the upper left corner with cursour locked on that area:
Screen4

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #5250
close #6120
relates to #4770

### CODE REVIEW

File: src/fheroes2/system/settings.cpp [hunk 1]
```diff
@@ -123,6 +123,12 @@ Settings::Settings()
         scroll_speed = SCROLL_SPEED_NONE;
     }
 
+    // SDL 1 uses cursor software emulation by default as it does not support anything else. SDL 2 supports 'hardware' mode and software emulation.
+    // It is observed that on small resolutions with a resized window the cursor remains the same in size within the game.
+    // In order to avoid this we set cursor software emulation by default.
+    _optGlobal.SetModes( GLOBAL_CURSOR_SOFT_EMULATION );
+    fheroes2::cursor().enableSoftwareEmulation( true );
```
Comment (oleg-derevenetz) [inline src/fheroes2/system/settings.cpp:130]: Hi @ihhub hmm, as far as I can see, software emulation only turns on everywhere, but it doesn't turn off anywhere - even if `cursor soft rendering` in `fheroes2.cfg` is `off`.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp:130]: You're right. I need to add the logic to turn it off.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp:130]: Fixed! :)

Comment (ihhub) [reply src/fheroes2/system/settings.cpp:130]: In the future this will be only mode because we want to add support of gamepads so we will have to make it as software emulation.

Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp:130]: @ihhub hardware cursor may move smoother, especially on slow systems, because its movement doesn't depend on SDL event loop processing.

Comment (zenseii) [reply src/fheroes2/system/settings.cpp:130]: Yes, I've just experienced that the software one is much slower and makes the game slow down frequently, on a slower PC.
It is up to you if we want to take this into account or not.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp:130]: Okay, I will revert this change but keep fullscreen changes.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: In this case we are back to situation when in fullscreen mode the cursor is too small :)

Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp]: @ihhub BTW I noticed that on Windows FPS never exceeds 60, while on macOS it could be 200+, and on macOS software cursor works much better.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: @oleg-derevenetz , did you enable V-sync on Windows?

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: Ah, you're right. It's very strange considering the fact that on SDL 1 it works absolutely fine.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: This is V-Sync related issue. You need to turn it off and restart the game.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: I found out that while toggling V-Sync option we do not set these flags in SDL itself.

Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp]: Well, there is nothing surprising that 60 fps software cursor works worse. It seems that SDL1 just ignores `vsync` option and FPS may achieve 200+ even if it is turned on, which shouldn't be.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: SDL 1 doesn't support V-Sync :)

Comment (zenseii) [reply src/fheroes2/system/settings.cpp]: > In this case we are back to situation when in fullscreen mode the cursor is too small :)

Yes, as I said I'm personally fine with this. I'm not sure how much of an impact it might have on weaker systems like even an Android phone. Then there's also PS Vita which I've seen players have concerns about the performance, but I have no way to test this not owning the system.

Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp]: @zenseii Touch devices (such as Android and Vita) have software emulated mouse enabled in any case. Also there is no much of "impact" with touch because mouse cursor instantly moved to the touch point, while with "real" mouse there is a ton of movement events on the way from the previous mouse point to a new one.

Comment (zenseii) [reply src/fheroes2/system/settings.cpp]: This is a good point, @oleg-derevenetz . I was under the impression that we wanted to enable software cursor to enable manual control of the cursor like for Android with an onscreen "joystick", which could also be done for systems like PS Vita with a physical joystick. In this case it might affect performance, right?

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: Hi @zenseii and @oleg-derevenetz , how is the performance with V-Sync being off? I rebased this branch from master so it has V-Sync fix.

Comment (zenseii) [reply src/fheroes2/system/settings.cpp]: With V-sync off there are no performance issues with software cursor. With V-sync on I occasionally see some slowdown when a hero is turning at a sharp angle on the Adventure map.

**Review by zenseii — APPROVED** [review]

File: src/fheroes2/system/settings.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp]: @zenseii

> I was under the impression that we wanted to enable software cursor to enable manual control of the cursor like for Android with an onscreen "joystick".

I hope not. According to feedback here in comments and discussions, people like the direct pointing by finger much more than virtual on-screen joystick. Maybe it's a little less accurate, but much more fun. Software cursor is needed for better control - for example, when you touch a tile on the adventure map to pave a path, the form of the software cursor (that will remain on this tile once you remove your finger) will suggest you how many days will the road take and whether there will be a battle.

@ihhub

> how is the performance with V-Sync being off

There was no performance impact when V-Sync was off before and there is no such impact now.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp]: I think we can bring back the original change for cursor software emulation. What do you think @oleg-derevenetz ?

Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp]: @ihhub I'm not against it. Hopefully this won't cause problems on slow machines.

Comment (ihhub) [reply src/fheroes2/system/settings.cpp:129]: Interesting, but what's the size of cursor in macOS without this mode while playing 640x480 in full screen?

**Comment by ihhub** [comment]
One more approach I need to explore is resizing of cursor. I remember that for newer SDL version on Windows cursor was too big. I think it's somehow might be possible to change.

File: src/fheroes2/system/settings.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/system/settings.cpp:129]: @ihhub Unfortunately, I can't make a screenshot that contains the hardware cursor, at least by regular means (Shift+Cmd+...), but the cursor in the form of a horse (on the adventure map) is about 1/4 of hero's size on the screen. Not so bad.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz and @zenseii , I made an alternative approach which should cover most of cases without damaging performance on other systems. Please take a look.

File: src/engine/screen.cpp [hunk 2]
```diff
@@ -755,13 +755,29 @@ namespace
 
             bool fullScreen = true;
             uint32_t flags = SDL_GetWindowFlags( _window );
+            static_assert( ( SDL_WINDOW_FULLSCREEN_DESKTOP & SDL_WINDOW_FULLSCREEN ) == SDL_WINDOW_FULLSCREEN && SDL_WINDOW_FULLSCREEN_DESKTOP > SDL_WINDOW_FULLSCREEN,
```
Comment (oleg-derevenetz) [inline src/engine/screen.cpp:758]: Hi @ihhub why just not check if either one of these flags is set, and if yes, then just clear both flags at once? In this case we shouldn't depend on the order of flag values as well as whether they intersect or not. Or is it not working for some reason?

Comment (ihhub) [reply src/engine/screen.cpp:758]: That's a goo point. I'll change the code.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by Branikolog** [comment]
Hi, @ihhub !
This PR changes nothing regarding #6120 . :(
Also, I want to note that on my home PC on Win 8 fheroes2 couldn't be minimized (Alt+Tab) from fullscreen mode long time ago. Application just blinks, trying to show desktop, and then recovers the game again. I was hoping, this PR would fix the issue, but it's still on. My other PC with Win 10 minimizes ok though.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog for the record: do you have software emulated cursor turned on (`cursor soft rendering = off` in `fheroes2.cfg`)? If not, then nothing was supposed to change.

**Comment by Branikolog** [comment]
@oleg-derevenetz , hello.
Oh, I completely forgot about this tiny detail! ))
I've tested once again properly and now the issue with fullscreen applications is gone. (#6120)
But I've found one flaw in current implementation.
While switching to windowed mode and back to fullscreen game sometimes doesn't stretch on the whole screen:
image
To reproduce the bug you need to switch game resolution in fullscreen mode (It works for me, in a case I set fullHD, which is maximum my notebook supports) and then switch to windowed mode.
To be sure, the "bug mode" is enabled, try to resize window with mouse: in normal mode, while resizing, new window area appears as black:
image
In a "bug mode" this area reminds me old win 98 windows lags:
изображение_viber_2022-11-24_23-34-09-146
So, after pressing F4 a few times game stratches in a way as I showed on the first screenshot.

**Comment by ihhub** [comment]
Hi @Branikolog , can you please be more specific what settings you set and how exactly you reproduce it? I don't understand the meaning of bug mode.

**Comment by ihhub** [comment]
I am proceeding to merge this pull request as the mentioned by @Branikolog issue is not directly related to changes. Also the changes in this pull request do not add any regression since on Windows software cursor rendering is disabled by default.

**Comment by ihhub** [comment]
@Branikolog , please file another issue describing in details the problem for 2 monitors using needed settings for the game.

**Comment by Branikolog** [comment]
@ihhub , hello!

>Hi @Branikolog , can you please be more specific what settings you set and how exactly you reproduce it? I don't understand the meaning of bug mode.

Start engine - enter fullscreen mode - set fHD resolution (I suppose, it also could be maximum available one) - set windowed mode - try to resize window several times dragging window corner - try to switch between fullscreen and window modes several times (issue occurs not each time we switch modes).
