### PR TITLE
Do not let the player get a random artifact that allows him to win the game

### LINKED ISSUE #3999: Random artifact is same as quest goal.
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Random artifact from grave is same as artifact in victory condition. In that case we get fast victory.

### Save file

[bug2.zip](https://github.com/ihhub/fheroes2/files/6964177/bug2.zip)

Search the grave for fast victory.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3999

### CODE REVIEW

File: src/fheroes2/resource/artifact.h [hunk 1]
```diff
@@ -205,8 +205,12 @@ class Artifact
 
 StreamBase & operator<<( StreamBase &, const Artifact & );
 StreamBase & operator>>( StreamBase &, Artifact & );
+
 u32 GoldInsteadArtifact( int );
 
+void ResetArtifactStats();
```
Comment (ihhub) [inline src/fheroes2/resource/artifact.h:211]: Could we please avoid using global functions? We can put them in `fheroes2` namespace to reduce their scope.

File: src/fheroes2/resource/artifact.h [hunk 2]
```diff
@@ -205,8 +205,12 @@ class Artifact
...
+void ExcludeArtifactFromRandom( int art );
```
Comment (ihhub) [inline src/fheroes2/resource/artifact.h:212]: I would recommend to make this input argument `const` and name it as `artifactID` :)

File: src/fheroes2/resource/artifact.cpp [hunk 3]
```diff
@@ -56,156 +58,162 @@ enum
...
-    case Artifact::ENDLESS_CORD_WOOD:
-        return _n( "The %{name} provides %{count} unit of wood per day.", "The %{name} provides %{count} units of wood per day.", count );
-    case Artifact::ENDLESS_CART_ORE:
-        return _n( "The %{name} provides %{count} unit of ore per day.", "The %{name} provides %{count} units of ore per day.", count );
-    case Artifact::ENDLESS_POUCH_CRYSTAL:
-        return _n( "The %{name} provides %{count} unit of crystal per day.", "The %{name} provides %{count} units of crystal per day.", count );
-    default:
-        break;
+    std::array<artifactstats_t, 104> artifacts = { {
+        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
```
Comment (ihhub) [inline src/fheroes2/resource/artifact.cpp:71]: Could we please remove translation calls here since we do the same in the code below and also it's a global variable which is initialized at the very beginning of the application.

File: src/fheroes2/world/world_loadmap.cpp [hunk 4]
```diff
@@ -80,6 +80,18 @@ bool World::LoadMapMP2( const std::string & filename )
     Reset();
     Defaults();
 
+    // clear artifact flags to correctly generate random artifacts
+    ResetArtifactStats();
```
Comment (ihhub) [inline src/fheroes2/world/world_loadmap.cpp:84]: What's about loading a save file? I think we need to reset there as well.

File: src/fheroes2/world/world_loadmap.cpp [hunk 5]
```diff
@@ -80,6 +80,18 @@ bool World::LoadMapMP2( const std::string & filename )
...
+
+    const Settings & conf = Settings::Get();
+
+    // do not let the player get a random artifact that allows him to win the game
+    if ( ( conf.ConditionWins() & GameOver::WINS_ARTIFACT ) == GameOver::WINS_ARTIFACT && !conf.WinsFindUltimateArtifact() ) {
+        const Artifact art = conf.WinsFindArtifactID();
+
+        ExcludeArtifactFromRandom( art.GetID() );
+    }
```
Comment (ihhub) [inline src/fheroes2/world/world_loadmap.cpp:93]: Shouldn't we need to put this check just before `ProcessNewMap` call?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , there are multiple comments. Could you please take a look at them?

File: src/fheroes2/world/world_loadmap.cpp (hunk 4 above)
Comment (oleg-derevenetz) [reply src/fheroes2/world/world_loadmap.cpp:84]: @ihhub As far as I know, random artifacts are replaced by actual ones on the start of a new game (when MP2 is processed), so in save files random artifacts are not random anymore :)

Comment (ihhub) [reply src/fheroes2/world/world_loadmap.cpp:84]: That's a good point :)

File: src/fheroes2/resource/artifact.cpp (hunk 3 above)
Comment (oleg-derevenetz) [reply src/fheroes2/resource/artifact.cpp:71]: I believe that translation calls are needed here to properly generate `.po` file. They don't really work but they are just markers for `gettext` parser.

Comment (ihhub) [reply src/fheroes2/resource/artifact.cpp:71]: Oh, yes. I totally forgot about this. We can leave as it is or use `gettext_noop` call instead.

Comment (oleg-derevenetz) [reply src/fheroes2/resource/artifact.cpp:71]: I believe `_()` looks shorter.

Comment (ihhub) [reply src/fheroes2/resource/artifact.cpp:71]: The difference between `_()` and `gettext_noop` is that the last function does exactly nothing. Anyway, I'm marking this comment as resolved.

**Comment by ihhub** [comment]
@oleg-derevenetz , good job! Thanks for the fix!
