### PR TITLE
Don't overwrite focus on game load

### LINKED ISSUE #5898: Save file, selected hero or castle should be stored in the save file
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In the original game, the selected hero or castle is stored in the save file, so that when a save is loaded, the hero or castle is selected automatically.

In fheroes2, it worked this way when the option "game: remember last focus" was activated.
This option has since been removed.
It is to be noted that it should have worked as in the original game whether the option "game: remember last focus" was activated or not.

### Save file

Here are the save files:
[Selected hero castle stored in save file 01.zip](https://github.com/ihhub/fheroes2/files/9674131/Selected.hero.castle.stored.in.save.file.01.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by felix642**
When loading a save file, the current focus was being overwritten by the first hero. This PR changes this default behavior.

closes #5898

### CODE REVIEW

File: src/fheroes2/gui/interface_focus.cpp [hunk 1]
```diff
@@ -89,6 +89,29 @@ void Interface::Basic::SetFocus( Castle * castle )
...
+    Player * player = Settings::Get().GetPlayers().GetCurrent();
+
+    if ( !player ) {
+        return;
+    }
+
+    Focus & focus = player->GetFocus();
+    if ( focus.first == FOCUS_CASTLE ) {
+        Castle * castle = GetFocusCastle();
+        iconsPanel.Select( castle );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_focus.cpp:103]: It would be good to add a check whether the pointer is not nullptr.

File: src/fheroes2/gui/interface_focus.cpp [hunk 2]
```diff
@@ -89,6 +89,29 @@ void Interface::Basic::SetFocus( Castle * castle )
...
+        gameArea.SetCenter( castle->GetCenter() );
+        statusWindow.SetState( StatusType::STATUS_FUNDS );
+    }
+    else if ( focus.first == FOCUS_HEROES ) {
+        Heroes * hero = GetFocusHeroes();
+        iconsPanel.Select( hero );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_focus.cpp:109]: It would be good to add a check whether the pointer is not nullptr.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @felix642 , I left 2 comments in this pull request. Would you mind to take a look when you have time?

**Comment by ihhub** [comment]
Hi @Branikolog , can you please test this change?

**Comment by Branikolog** [comment]
Hello, @ihhub & @felix642 !
I've noticed, that after loading game music doesn't start. Music starts only after refocus.

**Comment by felix642** [comment]
Hi @Branikolog, I have updated my PR. The sounds should now work properly when loading a save. Would you mind testing this PR again to make sure that everything works great? Thank you :)

**Review by Branikolog — APPROVED** [review]
Everything works fine now!

**Comment by ihhub** [comment]
@felix642 , thank you very much for the fix!
