### PR TITLE
Fix redraw order for unit count

### LINKED ISSUE #1618: Combat, creature count indicator, creature count indicator is displayed over hero sprite
In the example, the creature count indicator of the ghosts is displayed over the hero sprite.
This bug is not present in the original game.

In relation to the visual perspective, the creature count indicator should be displayed behind the horse's head.

In original game:

Creature shadow over creature count indicator 01

In fheroes2:

Creature shadow over creature count indicator 02

### PR DESCRIPTION
**Pull request by Oroty**
Fix #1618

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Oroty , I think it's not a fully correct solution. This is what happens with your changes:
image

As you could see the part of dragon is drawn below hero which looks awkward.

**Comment by Oroty** [comment]
> Hi @Oroty , I think it's not a fully correct solution. This is what happens with your changes
> 
> As you could see the part of dragon is drawn below hero which looks awkward.

Ok, I changed the draw order:
1.draw units on first and second row;
2.than draw both heroes (their position must be between tiles 21 and 22);
3. draw others units.
So now all the units displayed as they should (And as they displayed in original game)

**Comment by Oroty** [comment]
Original game:

heroes2-013

**Comment by Oroty** [comment]
New fix:
fixed-battle-redraw

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -1124,6 +1123,11 @@ void Battle::Interface::RedrawArmies( void )
             if ( _movingUnit != b && b->isValid() )
                 RedrawTroopCount( *b );
         }
+
+        // 21 is the last tile in the second row. Draw heroes now, because their position must be between tiles 21 and 22.
+        if ( ii == 21 ) {
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:1128]: Could we please avoid this hardcoded value as use something like: `2 * ARENAW - 1`? At least it will be less `hardcoded` in this sense :)

Comment (Oroty) [reply src/fheroes2/battle/battle_interface.cpp]: Of course, Boss! That looks much better! :)

**Comment by ihhub** [comment]
@Oroty thanks a lot for fixing this issue!
