### PR TITLE
Show highscores after multiplayer game

### LINKED ISSUE #4470: No highscore for multiplayer
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Win multiplayer game by eliminating red player:
image
After that we watch victory animation with dragon and then return to main menu.

### Save file

[Multiplayer score.zip](https://github.com/ihhub/fheroes2/files/7397740/Multiplayer.score.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by petar-stamenkov**
Fixes #4470

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Are the multiplayer results just supposed to be among standard/single player game results? Shouldn't there be a separate list for them (just like for campaign)?

**Comment by oleg-derevenetz** [comment]
> As pointed out in the issue thread, in the OG the multiplayer high score is shared with the non-multiplayer high score.

Funny, I always thought they should be separate. Well, OK then :)

File: src/fheroes2/game/game_over.cpp [hunk 1]
```diff
@@ -539,16 +538,16 @@ fheroes2::GameMode GameOver::Result::checkGameOver()
...
             AudioManager::ResetAudio();
             Video::ShowVideo( "WIN.SMK", Video::VideoAction::WAIT_FOR_USER_INPUT, { standardGameResults() }, true );
 
-            res = fheroes2::GameMode::MAIN_MENU;
+            res = fheroes2::GameMode::HIGHSCORES_STANDARD;
         }
-        else if ( multiplayerResult & GameOver::LOSS ) {
-            const bool showLossDialog = [currentColor, isCurrentPlayerWasActive, multiplayerResult]() {
+        else if ( result & GameOver::LOSS ) {
+            const bool showLossDialog = [currentColor, isCurrentPlayerWasActive, currentResult = result]() {
```
Comment (oleg-derevenetz) [inline src/fheroes2/game/game_over.cpp:550]: We can just add `this` here to the capture list and access the `result` directly instead of `currentResult = result`, but it's a matter of taste.

**Review by oleg-derevenetz — APPROVED** [review]
LGTM. BTW I just checked HoMM3 and in this game multiplayer results are mixed with single player results as well.

File: src/fheroes2/game/game_over.cpp (hunk 1 above)
Comment (petar-stamenkov) [reply src/fheroes2/game/game_over.cpp]: Thanks for the suggestion, I've updated it.

Comment (oleg-derevenetz) [reply src/fheroes2/game/game_over.cpp]: Hi @petar-stamenkov both variants are fine. The advantage of the previous variant is that `currentResult` was `const`, and when you are not going to change the variable, `const` is good. But the new variant is also good.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@petar-stamenkov , huge thanks for this improvement!
