### PR TITLE
Fix passabilities for old save files

### LINKED ISSUE #3775: Old save files are broken for passability
Recent commit for object passability broke old save files. We need to add version check.

### PR DESCRIPTION
**Pull request by ihhub**
close #3775

### CODE REVIEW

File: src/fheroes2/maps/maps_tiles.cpp [hunk 1]
```diff
@@ -2428,27 +2429,46 @@ void Maps::Tiles::setAsEmpty()
...
 StreamBase & Maps::operator>>( StreamBase & msg, TilesAddon & ta )
 {
-    uint8_t temp = 0;
+    static_assert( LAST_SUPPORTED_FORMAT_VERSION < FORMAT_VERSION_095_RELEASE, "Remove temp variable usage here." );
+    if ( Game::GetLoadVersion() >= FORMAT_VERSION_095_RELEASE ) {
+        msg >> ta.level >> ta.uniq >> ta.object >> ta.index;
+    }
+    else {
+        uint8_t temp = 0;
+        msg >> ta.level >> ta.uniq >> ta.object >> ta.index >> temp;
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles.cpp:2443]: I'd not duplicate the same code twice here, but it's a minor issue, since this code is temporary anyway.

**Review by oleg-derevenetz — APPROVED** [review]
Hi @ihhub LGTM with one minor note.

File: src/fheroes2/maps/maps_tiles.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:2443]: Good point. I'll fix it.
