### PR TITLE
Automatically assemble artifacts sets if their parts were captured in the battle

### LINKED ISSUE #6407: Combo artifact fails to assemble, if last part of it was captured from defeated enemy hero.
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

1. Have 2 out of 3 combo parts in your hero`s inventory and final part owned by enemy hero.
2. Make sure there is enough space for 3rd part of combo.
3. Defeat that enemy hero and capture enemy artifacts, make sure that final part of combo is  put into hero`s inventory.

Result - no prompt to assemble combo artifact on combat victory, no option to assemble combo artifact from hero screen, even with all 3 parts in inventory. Only meeting with other allied hero allowed assembling combo artifact and, in case of included save file, trigger victory comdition.

### Save file

[AUTOSAVE.zip](https://github.com/ihhub/fheroes2/files/10289144/AUTOSAVE.zip)

### Additional info

Unfortunately, i accidentally overwritten save file prior to enemy fight, hoping to get prompt to assemble combo artifact next day, but no luck. This one shows the result of the bug.
1.0.0

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #6407

Also play the `M82::TREASURE` sound effect when artifact assembly dialog is displayed (just like in the OG) and auto-assemble artifact sets when two AI-controlled heroes exchange their artifacts.

### CODE REVIEW

File: src/fheroes2/heroes/heroes_meeting.cpp [hunk 1]
```diff
@@ -468,17 +466,11 @@ void Heroes::MeetingDialog( Heroes & otherHero )
                 selectArmy2.ResetSelected();
 
             std::set<ArtifactSetData> assembledArtifacts = bag_artifacts.assembleArtifactSetIfPossible();
-            const std::set<ArtifactSetData> otherHeroAssembledArtifacts = otherHero.bag_artifacts.assembleArtifactSetIfPossible();
+            std::set<ArtifactSetData> otherHeroAssembledArtifacts = otherHero.bag_artifacts.assembleArtifactSetIfPossible();
 
-            // Use insert instead of std::merge to make appveyour happy
-            assembledArtifacts.insert( otherHeroAssembledArtifacts.begin(), otherHeroAssembledArtifacts.end() );
+            assembledArtifacts.merge( otherHeroAssembledArtifacts );
```
Comment (oleg-derevenetz) [inline src/fheroes2/heroes/heroes_meeting.cpp:471]: Funny thing - in C++17 there is an overload for `merge()` that takes the [rvalue reference](https://en.cppreference.com/w/cpp/container/set/merge), but MSVC 2017 has no idea about it :( This might be turned into just

```cpp
assembledArtifacts.merge( otherHero.bag_artifacts.assembleArtifactSetIfPossible() );
```
and this compiles with modern GCC and Clang, but not with MSVC2017, so we are forced to create a temporary variable.

File: src/fheroes2/dialog/dialog_artifact.cpp [hunk 2]
```diff
@@ -0,0 +1,43 @@
+/***************************************************************************
+ *   fheroes2: https://github.com/ihhub/fheroes2                           *
+ *   Copyright (C) 2022                                                    *
+ *                                                                         *
+ *   Free Heroes2 Engine: http://sourceforge.net/projects/fheroes2         *
+ *   Copyright (C) 2009 by Andrey Afletdinov <fheroes2@gmail.com>          *
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_artifact.cpp:6]: This part of license header is not applicable for new files.

File: src/fheroes2/heroes/heroes_meeting.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/heroes/heroes_meeting.cpp:471]: I suggest to leave the comment about it in the code to avoid other developers to change it.

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left 2 comments in this pull request. Could you please take a look at them?

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for these improvements!
