### PR TITLE
Battle AI should switch to offense instead of passing

### LINKED ISSUE #7498: Dragons decided not to act : a bug or a feature? (definitely not optimal)
### Your question

Please see the video and use the saved game to reproduce - most of times the situation reproduces if the same moves are performed.

https://youtu.be/YjkZwahUF8g

### Additional info

[New_Enemies_0064dragonstay.zip](https://github.com/ihhub/fheroes2/files/12233955/New_Enemies_0064dragonstay.zip)

### LINKED ISSUE #7517: Combat, AI behavior, red dragons skip their extra morale attack when they could attack a second time (1.0.6 7494)
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

In fheroes2, the red dragons skip their extra morale attack when they could attack a second time.

Red dragons attack greater druids.
High morale enables the red dragons to attack again.
Red dragons skip their turn.

In this case, the red dragons could attack the greater druids again and decimate them entirely.

In fheroes2:

Red dragon skip morale 01

https://github.com/ihhub/fheroes2/assets/43583994/c3cf947e-0d8f-484b-8026-684d9f6ea7b9

Here is the save file:
[Red dragon skip morale 01.zip](https://github.com/ihhub/fheroes2/files/12269831/Red.dragon.skip.morale.01.zip)

### Describe the possible solution

In this case, the red dragons could attack the greater druids again and decimate them entirely.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #7498 . Fixes #7517 .

Tested on saves within respective tickets but might be useful to check few others.

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_battle.cpp [hunk 1]
```diff
@@ -774,14 +774,18 @@ namespace AI
 
         const double defenceDistanceModifier = _myArmyStrength / STRENGTH_DISTANCE_FACTOR;
 
+        const std::function<bool( const int32_t )> isDefensivePosition = [this, &currentUnit]( const int32_t index ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_battle.cpp:777]: Hi @idshibanov we can use just `const auto isDefensivePosition = ...` here, in this case there is no need to include `<functional>` as currently suggested by IWYU.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
@idshibanov , thank you so much for the fix!
