### PR TITLE
Rework the Thieves Guild (Oracle) dialog code and minor fixes to Hero dialog rendering

### LINKED ISSUE #7728: Dialog's frame is not consistent for the same size windows
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The dialog's frame changes depending on what type of a window is being open:

https://github.com/ihhub/fheroes2/assets/19829520/e9b44537-db32-4f81-b1ea-e6eae3cefb7f

### Save file

No need

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
This PR reworks the code for the Thieves Guild (Oracle) dialog and:
- fixes #7728;
- adds a fade animation when opening/closing the dialog;
- adds a shadow to the Oracle dialog;
- implements a workaround to eliminate color name overlap (discussible, can be reverted):
   master build: изображение
   this PR: изображение;
- aligns monster sprites vertically:
   master build: изображение
   this PR: изображение;
- does some optimizations in the dialog code;
- also fixes variable names in hero_dialog.cpp;
- and makes `redraw()` calls in Hero dialog to update only the dialog area, not the whole screen.

### CODE REVIEW

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 1]
```diff
@@ -74,482 +73,409 @@ struct ValueColors : std::pair<int, int>
...
-        UpdateValuesColors( v, static_cast<int32_t>( townCount ), *color );
     }
-
-    std::sort( v.begin(), v.end(), ValueColors::SortValueGreat );
 }
 
-void GetCastlesInfo( std::vector<ValueColors> & v, const Colors & colors )
+void getInfo( std::vector<ValueColors> & v, const Colors & colors, const std::function<int( const int )> & getValue )
 {
     v.clear();
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:88]: Should we add an assertion here to verify that **getValue** is not empty?

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 2]
```diff
@@ -74,482 +73,409 @@ struct ValueColors : std::pair<int, int>
...
+        fheroes2::Blit( window, output, offsetX - window.width() / 2, pos.y - 4 );
 
-void GetIncomesInfo( std::vector<ValueColors> & v, const Colors & colors )
-{
-    v.clear();
+        const fheroes2::Sprite & icon = hero->GetPortrait( PORT_SMALL );
+        if ( !icon.empty() ) {
+            const int32_t iconWidth = icon.width();
+            fheroes2::Copy( icon, 0, 0, output, offsetX - iconWidth / 2, pos.y, iconWidth, icon.height() );
+        }
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:177]: We can skip this check and write this code:
```cpp
fheroes2::Copy( icon, 0, 0, output, offsetX - icon.width() / 2, pos.y, icon.width(), icon.height() );
```

**fheroes2::Copy()** function will immediately exit if **icon** is empty.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put 2 comments here. Would you mind to take a look when you have time?

File: src/fheroes2/dialog/dialog_thievesguild.cpp (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/dialog/dialog_thievesguild.cpp]: Sure!
Just a leftover from the old code. ;)

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
New element alignment looks nice.
I've only noticed that oracle on the adventure map and castle guild are rendered in different styles (Evil/Good):

https://github.com/ihhub/fheroes2/assets/55348946/4d4b2b7e-58f5-449b-992e-8096d1c2c57b

I know, that it's not related to the changes of the PR, and I can make a separate issue for that, if you wish.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Branikolog , please create a separate issue. This pull request is huge enough.

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , big thanks for these improvements!

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru ! New element alignment looks nice. I've only noticed that oracle on the adventure map and castle guild are rendered in different styles (Evil/Good):
> 
> I know, that it's not related to the changes of the PR, and I can make a separate issue for that, if you wish.

Hi, @Branikolog, it was made by a reason in PR https://github.com/ihhub/fheroes2/pull/7419:

> About the choice to keep it good for oracle, I believe the interface here should reflect if the oracle himself is a good or a bad person, and not what interface the player has due to his own alignment. This is why I think you could argue that the oracle should not change their alignment to evil just because you are playing an evil faction.
>The descriptive text for the oracle doesn't say whether he is good or evil. In fact, it does make more sense for him to be neutral.
>
> image
>
> Anyways, this isn't important for me and if someone else feels strongly about adapting the oracle too then I have no problem with that.

_Originally posted by @zenseii in https://github.com/ihhub/fheroes2/pull/7419#discussion_r1264685978_

**Comment by Branikolog** [comment]
@Districh-ru 
Hm.. I find it kind of questionable, actually. While choosing an "Evil" mode we have all interface changing, no matter castle, hero or adventure object interaction happens.
image
Oracle appears to be the only object which has "Good" colours. That looks even more obvious with the "Evil" frame on higher resolutions.

**Comment by Districh-ru** [comment]
> @Districh-ru Hm.. I find it kind of questionable, actually. While choosing an "Evil" mode we have all interface changing, no matter castle, hero or adventure object interaction happens. 
Oracle appears to be the only object which has "Good" colours. That looks even more obvious with the "Evil" frame on higher resolutions.

You are right, the borders should match the background.
We can make the borders "Good" for the Oracle or make the Oracle background match the selected interface mode.
@Branikolog, @zenseii what is your opinion?

**Comment by Branikolog** [comment]
@Districh-ru 
I still prefer using the same interface for all game windows.
