### PR TITLE
Fix use of plural/singular translation

### LINKED ISSUE #4837: xgettext warnings: msgid '...' is used without plural and with plural
### Your question

At the end of `make` run I'm always getting these warnings from `gettext`:
```
make -C dist pot
make[2]: Entering directory '/home/ash/src/fheroes2/src/dist'
gen: fheroes2.pot
xgettext: warning: msgid 'Water Wheel' is used without plural and with plural.
                   ../fheroes2/maps/mp2.cpp:219: Here is the occurrence without plural.
                   ../fheroes2/maps/mp2.cpp:651: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'Windmill' is used without plural and with plural.
                   ../fheroes2/maps/mp2.cpp:246: Here is the occurrence without plural.
                   ../fheroes2/maps/mp2.cpp:653: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'Magic Garden' is used without plural and with plural.
                   ../fheroes2/maps/mp2.cpp:464: Here is the occurrence without plural.
                   ../fheroes2/maps/mp2.cpp:655: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'The %{name} provides %{count} unit of sulfur per day.' is used without plural and with plural.
                   ../fheroes2/resource/artifact.cpp:151: Here is the occurrence without plural.
                   ../fheroes2/resource/artifact.cpp:205: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'The %{name} provides %{count} unit of mercury per day.' is used without plural and with plural.
                   ../fheroes2/resource/artifact.cpp:152: Here is the occurrence without plural.
                   ../fheroes2/resource/artifact.cpp:207: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'The %{name} provides %{count} unit of gems per day.' is used without plural and with plural.
                   ../fheroes2/resource/artifact.cpp:153: Here is the occurrence without plural.
                   ../fheroes2/resource/artifact.cpp:209: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'The %{name} provides %{count} unit of wood per day.' is used without plural and with plural.
                   ../fheroes2/resource/artifact.cpp:154: Here is the occurrence without plural.
                   ../fheroes2/resource/artifact.cpp:211: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
xgettext: warning: msgid 'The %{name} provides %{count} unit of ore per day.' is used without plural and with plural.
                   ../fheroes2/resource/artifact.cpp:155: Here is the occurrence without plural.
                   ../fheroes2/resource/artifact.cpp:213: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
make[2]: Leaving directory '/home/ash/src/fheroes2/src/dist'
```

I've never actually paid attention, as they look harmless, but they might make it harder to spot newly introduced problems later.  What is the approach to get rid of those?  Should we change the places where these are used without plural?

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by a1exsh**
Close #4837

### CODE REVIEW

File: src/fheroes2/resource/artifact.cpp [hunk 1]
```diff
@@ -76,148 +76,116 @@ struct artifactstats_t
 namespace
 {
     std::array<artifactstats_t, 104> artifacts = { {
-        { 0, 12, TYPE3, _( "Ultimate Book of Knowledge" ), _( "The %{name} increases your knowledge by %{count}." ) },
```
Comment (a1exsh) [inline src/fheroes2/resource/artifact.cpp:79]: Use of `_()` here was incorrect.

File: src/fheroes2/resource/artifact.cpp [hunk 2]
```diff
@@ -76,148 +76,116 @@ struct artifactstats_t
...
+        { 0, 0, TYPE0, "Sphere of Negation", "The %{name} disables all spell casting, for both sides, in combat." },
+        { 0, 5, TYPE3, "Staff of Wizardry", "The %{name} boosts your spell power by %{count}." },
+        { 0, 4, TYPE3, "Sword Breaker", "The %{name} increases your defense by %{count} and attack by 1." },
+        { 0, 5, TYPE3, "Sword of Anduran", "The %{name} increases your attack skill by %{count}." },
+        { 0, 0, TYPE4, "Spade of Necromancy", "The %{name} gives you increased necromancy skill." },
 
         { 0, 0, TYPE0, "Unknown", "Unknown" },
     } };
-
-    const char * GetPluralDescription( const Artifact & art, u32 count )
```
Comment (a1exsh) [inline src/fheroes2/resource/artifact.cpp:193]: This function seems pointless: we know the correct form for each artifact anyway.

File: src/fheroes2/resource/artifact.cpp [hunk 3]
```diff
@@ -76,148 +76,116 @@ struct artifactstats_t
...
-        { 0, 1, TYPE2, _( "Endless Cord of Wood" ), _( "The %{name} provides %{count} unit of wood per day." ) },
-        { 0, 1, TYPE2, _( "Endless Cart of Ore" ), _( "The %{name} provides %{count} unit of ore per day." ) },
-        { 0, 1, TYPE2, _( "Endless Pouch of Crystal" ), _( "The %{name} provides %{count} unit of crystal/day." ) },
-        { 0, 1, TYPE3, _( "Spiked Helm" ), _( "The %{name} increases your attack and defense skills by %{count} each." ) },
-        { 0, 2, TYPE3, _( "Spiked Shield" ), _( "The %{name} increases your attack and defense skills by %{count} each." ) },
-        { 0, 1, TYPE3, _( "White Pearl" ), _( "The %{name} increases your spell power and knowledge by %{count} each." ) },
-        { 0, 2, TYPE3, _( "Black Pearl" ), _( "The %{name} increases your spell power and knowledge by %{count} each." ) },
-
-        { 0, 0, TYPE0, _( "Magic Book" ), _( "The %{name} enables you to cast spells." ) },
+        { 0, 12, TYPE3, "Ultimate Book of Knowledge", "The %{name} increases your knowledge by %{count}." },
```
Comment (oleg-derevenetz) [inline src/fheroes2/resource/artifact.cpp:79]: Where will these lines (artifact names and descriptions) in the `.pot` file come from after such changes? These `_()`'s are needed to let the `xgettext` to include these strings in the `.pot`.

**Review by oleg-derevenetz — CHANGES_REQUESTED** [review]
Hi @a1exsh I just left one question here, please take a look when it's convenient for you.

File: src/fheroes2/resource/artifact.cpp (hunk 3 above)
Comment (a1exsh) [reply src/fheroes2/resource/artifact.cpp:79]: Haven't thought about that, obviously.  Let me revert this part.

File: src/fheroes2/resource/artifact.cpp (hunk 2 above)
Comment (oleg-derevenetz) [reply src/fheroes2/resource/artifact.cpp:193]: @a1exsh

> we know the correct form for each artifact anyway

How do we know that? For example, let's take the Endless Cord of Wood. In the singular form, the description should look like "The %{name} provides %{count} **_unit_** of wood per day." and in the plural form it should be "The %{name} provides %{count} **_units_** of wood per day." Who will replace "unit" by "units" in the proposed version of code?

Comment (a1exsh) [reply src/fheroes2/resource/artifact.cpp:193]: Well, that's easy: all the resource-producing artifacts actually always only produce _one_ unit per day, so there is no need for the plural form.  The same goes for the Wizard's Hat and the Enchanted Hourglass: the exact number of turns is known in advance, so there is no need for any variation in the translation messages.

Comment (oleg-derevenetz) [reply src/fheroes2/resource/artifact.cpp:193]: Yes it looks like it's a fossil from the time when the characteristics of artifacts were stored in separate xml files for modders. Now it's really unnecessary.

**Review by oleg-derevenetz — APPROVED** [review]

File: src/fheroes2/maps/mp2.cpp [hunk 4]
```diff
@@ -216,7 +216,7 @@ const char * MP2::StringObject( const MapObjectType objectType )
         return _( "Lighthouse" );
     case OBJN_WATERWHEEL:
     case OBJ_WATERWHEEL:
-        return _( "Water Wheel" );
+        return _n( "Water Wheel", "Water Wheels", 1 );
```
[the remark this answers is not in the document]
Comment (a1exsh) [reply src/fheroes2/maps/mp2.cpp:219]: @ihhub The reason to change anything at all is explained in the linked issue: `xgettext` warnings at compile time.

What do you suggest to do instead of the proposed change?

[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/maps/mp2.cpp:219]: In this case I'm suggesting to remove `getPluralObjectName` function and add to `StringObject` an extra parameter called `const int count` with default value 1.

[the remark this answers is not in the document]
Comment (a1exsh) [reply src/fheroes2/maps/mp2.cpp]: @ihhub done in b7122ee4

**Comment by ihhub** [comment]
@a1exsh , thank you so much for this fix!

File: src/fheroes2/resource/artifact.cpp (hunk 3 above)
Comment (a1exsh) [reply src/fheroes2/resource/artifact.cpp]: @ihhub @oleg-derevenetz should we actually change these uses of `_()` to `gettext_noop()`, so that no translation is attempted, but the `pot` file is populated?..

Comment (ihhub) [reply src/fheroes2/resource/artifact.cpp]: Yes, we can.
