### PR TITLE
Fix displaying of negative resources in dialog

### LINKED ISSUE #5560: Adventure map, Event windows, negative resource values are not displayed
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, negative resource values are not displayed in the global and map event windows.

In original game:

Message negative resource value 005

Message negative resource value 006

Message negative resource value 007

Message negative resource value 008

Message negative resource value 010

In fheroes2:

Message negative resource value 001

Message negative resource value 002

Message negative resource value 003

Message negative resource value 004

Message negative resource value 009

### Save file

Here is the test scenario file:
[Central0.zip](https://github.com/ihhub/fheroes2/files/8947177/Central0.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by undef21**
fix #5560

### CODE REVIEW

File: src/fheroes2/gui/ui_dialog.cpp [hunk 1]
```diff
@@ -370,25 +370,25 @@ namespace fheroes2
     {
         std::vector<ResourceDialogElement> elements;
 
-        if ( funds.wood > 0 ) {
```
Comment (ihhub) [inline src/fheroes2/gui/ui_dialog.cpp:373]: Let's be more explicit and add `!= 0` for all cases to improve code readability.

**Review by ihhub — CHANGES_REQUESTED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@undef21 . huge thanks for fixing this issue!
