### PR TITLE
Fill main menu with background when we do not stretch the main menu main image

### LINKED ISSUE #7014: Fill main menu with background when we do not stretch the main menu main image
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Stretching the Main Menu main image makes it too un-proportional on wide screens. We would like to keep aspect ratio of the image as it is but we don't want to render black on left and right sides.

### Describe the possible solution

We use background image while generating windows. We should use the same image to generate the background on left and right screen for resolutions which have different aspect ratio than the the original game. This will help with Android devices in particular where we can add proper wide screen mode.

### Additional info

_No response_

### LINKED ISSUE #7045: Main menu, buttons are shifting on hovering
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Main menu buttons start shifting while hovering cursor over them. Issue occurs with widescreen resolution selected.

https://user-images.githubusercontent.com/55348946/233648769-f524db22-7f12-4cf7-9c43-6d6041791928.mp4

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
This change might be not the best approach we could do but it does not stretch the main menu, avoiding button shifting issues and also serves as an indicator for widscreen resolutions.

image

image

image

close #7045
close #7014
relates to #4384

### CODE REVIEW

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -3615,17 +3617,21 @@ namespace fheroes2
...
+            const double scaleFactor = static_cast<double>( display.height() ) / Display::DEFAULT_HEIGHT;
+            const int32_t resizedWidth = std::lround( originalIcn.width() * scaleFactor );
+            const int32_t resizedHeight = std::lround( originalIcn.height() * scaleFactor );
+            const int32_t offsetX = static_cast<int32_t>( display.width() - Display::DEFAULT_WIDTH * scaleFactor ) / 2;
 
-            const int32_t resizedWidth = static_cast<int32_t>( originalIcn.width() * scaleFactorX + 0.5 );
-            const int32_t resizedHeight = static_cast<int32_t>( originalIcn.height() * scaleFactorY + 0.5 );
             // Resize only if needed
-            if ( resizedIcn.width() != resizedWidth || resizedIcn.height() != resizedHeight ) {
+            if ( resizedIcn.height() != resizedHeight ) {
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:3626]: I switched from 640x480 to 720x480 and then to 853x480 (x2.2) and got this:
изображение
The height remains the same and we do not update the position.

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub. I started testing and sometimes I get shifted main menu image. Could you take a look when you have time.

Also I think we need to position dialogs like for 3x4 screens (in the same place above the main menu). I'll take a look how to do it a little later.

File: src/fheroes2/agg/agg_image.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/agg/agg_image.cpp:3626]: Hi @Districh-ru . it is fixed. Please take a look again.

Comment (Districh-ru) [reply src/fheroes2/agg/agg_image.cpp:3626]: I checked many resolutions combinations and now the main menu background is positioned correctly. 👍

**Review by Districh-ru — CHANGES_REQUESTED** [review]
New game menu now displays with the correct offset in non 3x4 resolutions.
So we can apply the same offset to the load menu. :)

Also I noticed that https://github.com/ihhub/fheroes2/issues/4384 is not fully fixed. In 1366x768 resolution:

https://user-images.githubusercontent.com/113276641/236615602-5f3443a9-332f-4163-8ff2-72ed1eaccb51.mp4

It can be fixed in another PR.

**Comment by ihhub** [comment]
Hi @Districh-ru , yes, #4384 is not fixed for all resolutions. This is a task outside the scope of this pull request.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , yes, #4384 is not fixed for all resolutions. This is a task outside the scope of this pull request.

Sure)
But IMHO in this PR we also need to correct the offset of Load Game window as we did to the New Game window.

**Comment by Branikolog** [comment]
@ihhub 
Everything is fine, except Loading block and lights, which was mentioned by @Districh-ru above.

File: src/fheroes2/agg/agg_image.cpp [hunk 2]
```diff
@@ -3615,17 +3617,21 @@ namespace fheroes2
 
             Sprite & resizedIcn = _icnVsScaledSprite[icnId][index];
 
-            const double scaleFactorX = static_cast<double>( Display::instance().width() ) / Display::DEFAULT_WIDTH;
-            const double scaleFactorY = static_cast<double>( Display::instance().height() ) / Display::DEFAULT_HEIGHT;
+            const double scaleFactor = static_cast<double>( display.height() ) / Display::DEFAULT_HEIGHT;
+            const int32_t resizedWidth = std::lround( originalIcn.width() * scaleFactor );
+            const int32_t resizedHeight = std::lround( originalIcn.height() * scaleFactor );
+            const int32_t offsetX = static_cast<int32_t>( display.width() - Display::DEFAULT_WIDTH * scaleFactor ) / 2;
```
Comment (oleg-derevenetz) [inline src/fheroes2/agg/agg_image.cpp:3623]: Hi @ihhub I noticed that this code assumes that you will have to shift only along the X axis, that is, the monitor is stretched horizontally. However, there are also vertically elongated monitors, that is, theoretically, a shift along the Y axis may be required, right?

Comment (ihhub) [reply src/fheroes2/agg/agg_image.cpp:3623]: Hi @oleg-derevenetz , you are right. I will modify the code to support both cases.

Comment (ihhub) [reply src/fheroes2/agg/agg_image.cpp]: Fixed.

**Review by Districh-ru — APPROVED** [review]
I checked all of resolutions I have on my PC: background and main menu (including items) positioning works correctly.
👍

**Review by Branikolog — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]
