### PR TITLE
Fix object picking up animation, fix object remove from map and fix restoration of the object type for the tile

### LINKED ISSUE #8505: Adventure map, faulty artifact being picked up causes forest to disappear temporary
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The artifact my hero is picking does not correspond the sprite we watch on the screen. Picking it up also causes forest to disappear during fading animation.

https://github.com/ihhub/fheroes2/assets/55348946/8a5f9614-456b-4c74-a64f-3cee61d2bc3f

I've checked on two separate games - there's always a magic ring. But this could be a coincidence though.

### Save file

[Lost_Relic_artifact issue.zip](https://github.com/ihhub/fheroes2/files/14672894/Lost_Relic_artifact.issue.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
close #8505 

This PR also fixes:
- jail upper tiles object type update;
- restoration of the object type is there is another object in the tile besides the picked up object (the issue is described here : https://github.com/ihhub/fheroes2/pull/8936#issuecomment-2220225109);
- radar update on the place of picked up object (place a lighthouse or a mountain and an object behind it to check).

This PR affects **all** objects remove from the map including the move of the boat using Summon Boat.

Tile object type update:
- Master build:

https://github.com/user-attachments/assets/64b10155-0b51-48f1-9f0b-02ac0fe163ed

- This PR:

https://github.com/user-attachments/assets/7fb18080-0aa5-435d-aac0-0b1e16ba81a9

Radar update:
- Master build:

https://github.com/user-attachments/assets/d56f4b43-7d02-4594-896e-95b1312e9e59

- This PR:

https://github.com/user-attachments/assets/06fa6f61-210d-4b28-8f36-367c992ba446

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

File: src/fheroes2/heroes/heroes_action.cpp [hunk 1]
```diff
@@ -421,8 +449,9 @@ namespace
 
             setMonsterCountOnTile( tile, 0 );
```
Comment (oleg-derevenetz) [inline src/fheroes2/heroes/heroes_action.cpp:450]: I suppose we should do there the same sequence as we now do in the AI case, namely:

```cpp
runActionObjectFadeOutAnumation( tile, MP2::OBJ_MONSTER );

resetObjectMetadata( tile );
```

instead of calling the `setMonsterCountOnTile()`, right?

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @Districh-ru I just left one question, could you please take a look when you have time?

File: src/fheroes2/heroes/heroes_action.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/heroes/heroes_action.cpp]: Hi, @oleg-derevenetz.
Of course, both functions set the metadata to zero with the only difference: `setMonsterCountOnTile( tile, 0 )` resets only the first metadata value while `resetObjectMetadata();` resets all three metadata values.

For the consistency and make sure there is no junk left in the metadata, lets use `resetObjectMetadata();` here.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @Districh-ru , please resolve merge conflicts here.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , please resolve merge conflicts here.

Done!

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for these changes!
