### PR TITLE
Fix incorrect resource placements on certain maps

### LINKED ISSUE #6393: Assertion on resource collecting
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
image

Original campaign, 4 Roland scenario has incorrectly placed resource, which causes assertion on collecting.

### Save file

[X_CRASH_ON_TAKE_RES.zip](https://github.com/ihhub/fheroes2/files/10253728/X_CRASH_ON_TAKE_RES.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6393

This change must be thoughtfully tested on many maps to make sure that we don't break anything. The test scope should be done on maps with "bad" resources as well as any normal resources.

### CODE REVIEW

**Review by Branikolog — APPROVED** [review]
A miracle is here! :)
Resource is weirdly looking, being rendered over mountains, If it's not possible, to render it under mountains, like it was in the OG, I cannot imagine any better solution here.

**Comment by ihhub** [comment]
Hi @Branikolog , please test this issue on normal resources being generate on multiple maps as well as the underlying logic for placing them was modified.

**Comment by ihhub** [comment]
@Branikolog , I also added an error log in case if incorrect resource type would appear on any map. Try to load dozens of maps to see if you get the error message.

**Comment by Districh-ru** [comment]
Hi, @ihhub, @Branikolog, a couple of months ago I found a bug in "Voyage Home" expansion company, map 2. It has an unknown mine. But OG also has the same bug and it does not lead to a game crush, so I forgot about it :)

изображение

Save file: [vh2_bad_mine.zip](https://github.com/ihhub/fheroes2/files/10254008/vh2_bad_mine.zip)

File: src/fheroes2/maps/maps_tiles_quantity.cpp [hunk 1]
```diff
@@ -554,23 +557,54 @@ void Maps::Tiles::QuantityUpdate( bool isFirstLoad )
...
+
+        if ( ( objectTileset >> 2 ) == resourceTileSet ) {
+            // The resource is located at the top.
+            resourceType = Resource::FromIndexSprite( objectIndex );
+        }
+        else {
+            for ( TilesAddon & addon : addons_level1 ) {
+                if ( ( addon.object >> 2 ) == resourceTileSet ) {
+                    resourceType = Resource::FromIndexSprite( addon.index );
+                    // If this happens we are in trouble. It looks like that map maker put the resource under an object which is impossible to do.
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles_quantity.cpp:572]: Hi @ihhub What if we just remove this invalid addon?

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:572]: Then we need to add logic to remove the data from other tiles to make sure that the shadow is removed. By the way, is the shadow present for this case? I'm off my PC for now.

**Comment by oleg-derevenetz** [comment]
@Districh-ru see #5537 :)

File: src/fheroes2/maps/maps_tiles_quantity.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:572]: On top of this we will have to update object type and this is where we have no logic in the code. This should be added as a part of Editor phase.

**Comment by Districh-ru** [comment]
> @Districh-ru see #5537 :)

Thanks, I'll add my post with the save file to this issue.

File: src/fheroes2/maps/maps_tiles_quantity.cpp [hunk 2]
```diff
@@ -554,23 +557,54 @@ void Maps::Tiles::QuantityUpdate( bool isFirstLoad )
...
-        default:
+        case Resource::MERCURY:
+        case Resource::SULFUR:
+        case Resource::CRYSTAL:
+        case Resource::GEMS:
             count = Rand::Get( 3, 6 );
             break;
+        default:
+            // Some maps have broken resources being put which ideally we need to correct. Let's make them 0 Wood.
+            ERROR_LOG( "Tile " << _index << " contains unknown resource type. Tileset " << objectTileset << ", object index " << objectIndex )
```
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:601]: The error log would happen only if the new logic is wrong. This code affects only new maps. Old saves are untouched.

File: src/fheroes2/maps/maps_tiles_quantity.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:572]: @ihhub there is a shadow on the nearby tile, but it seems that it's a mountain's shadow, not a resource shadow. Anyway, the OG doesn't remove these resources, so this solution is OK.

**Comment by Districh-ru** [comment]
@ihhub, I also have checked all maps I have (it's a standard set from Buka CD) and did not find any unknown resource type.
Also I checked on what maps works your fix: maps 'peasants.mx2' and 'whoam.mp2'  has 1 resource under an object. And map 'lostreli.mp2' has 5.

**Review by oleg-derevenetz — APPROVED** [review]
LGTM. Could you please apply the IWYU suggestion? Also do you want to leave the `ERROR_LOG`? I used the `DEBUG_LOG` with `DBG_GAME` and `DBG_WARN` in similar cases.

**Comment by ihhub** [comment]
> LGTM. Could you please apply the IWYU suggestion? Also do you want to leave the `ERROR_LOG`? I used the `DEBUG_LOG` with `DBG_GAME` and `DBG_WARN` in similar cases.

Oh, I missed `IWYU` suggestion again :( I changed logging to `DEBUG_LOG`.
