### PR TITLE
AI: fix path selection for hero in patrol

### LINKED ISSUE #2576: Game freezes during AI turn
Something happens during yellow player's turn.
[Freeze.zip](https://github.com/ihhub/fheroes2/files/5795804/Freeze.zip)

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #2576 .

Patrol distance comparison was flawed, so AI perceived targets behind teleporter as "closer".

Also includes a fix to avoid hero in patrol mode leaving intended position.

### CODE REVIEW

File: src/fheroes2/battle/battle_pathfinding.h [hunk 1]
```diff
@@ -57,7 +57,7 @@ namespace Battle
         ArenaPathfinder();
         virtual void reset() override;
         void calculate( const Unit & unit );
-        virtual std::list<Route::Step> buildPath( int targetCell ) const override;
```
Comment (ihhub) [inline src/fheroes2/battle/battle_pathfinding.h:60]: Since base class doesn't have this virtual method should be remove virtual classifier as well?

**Review by ihhub — COMMENTED** [review]
Hi @idshibanov , I left just one comment. Could you please take a look?

File: src/fheroes2/world/world_pathfinding.cpp [hunk 2]
```diff
@@ -454,7 +454,7 @@ std::vector<IndexObject> AIWorldPathfinder::getObjectsOnTheWay( int targetIndex,
     return result;
 }
 
-std::list<Route::Step> AIWorldPathfinder::buildPath( int targetIndex ) const
+std::list<Route::Step> AIWorldPathfinder::buildPath( int targetIndex, bool isPlanningMode ) const
```
Comment (ihhub) [inline src/fheroes2/world/world_pathfinding.cpp:457]: There's no code which sets `isPlanningMode` input argument to true. Is it intentional?

Comment (idshibanov) [reply src/fheroes2/world/world_pathfinding.cpp:457]: Not used currently. I initially added it for the fix, but figured that `Maps::GetApproximateDistance` is better than building path every time. We can either leave it for future, or I'll remove if you want.

**Comment by ihhub** [comment]
@idshibanov thank you very much for fixing this bug!
