### PR TITLE
Render background between HEROES and TOWSN/CASTLES buttons in Kingdom Overview window

### LINKED ISSUE #6699: Adventure map buttons are partially visible through kingdom summary window
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
There's a small gap between "heroes" and "towns" buttons which allows to see adventure map buttons.
The issue appeared somewhere after 17.02.2023

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #6699 

k_overview

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

**Comment by Districh-ru** [comment]
> Hi @Districh-ru . I believe that area used to be black. I'm not sure about how it looked in the original. Either way I'm fine with it the way you've implemented it.

Hi, @zenseii. In original game the buttons were placed close one to other with no space between them. In fheroes2 there is a 3 pixels space. I think it was done for a reason. And with a little space between buttons it looks better IMHO. So I added a background there instead of moving the second button 3 pixels up.

File: src/fheroes2/kingdom/kingdom_overview.cpp [hunk 1]
```diff
@@ -727,11 +727,13 @@ void Kingdom::openOverviewDialog()
     dst_pt.y = cur_pt.y + 360;
     fheroes2::Button buttonHeroes( dst_pt.x, dst_pt.y, ICN::OVERVIEW, 0, 1 );
 
-    dst_pt.x = cur_pt.x + 540;
+    // We need to additionally render the background between HEROES and TOWSN/CASTLES buttons.
```
Comment (shprotru) [inline src/fheroes2/kingdom/kingdom_overview.cpp:730]:
```suggestion
    // We need to additionally render the background between HEROES and TOWNS/CASTLES buttons.
```

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for this fix!
