### PR TITLE
Fix archer evaluation regression

### LINKED ISSUE #7857: Combat screen, two enemy stacks are walking back and forth
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

https://github.com/ihhub/fheroes2/assets/55348946/ea698f00-4005-4f9e-9f18-48c38c9835b9

Elements attack + ogres go back. Next round elements run away, ogres run to fight. This happens several times in a row until rangers kill my druids.

### Save file

[Elements and ogres dance.zip](https://github.com/ihhub/fheroes2/files/12793553/Elements.and.ogres.dance.zip)
To reproduce you need to stay on starting positions and shoot a few times elements, so they won't kill druids at once.
*Note, that this issue is valid after #7845 will be merged.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #7857 . Handfighting check caused AI to flip between defence and offence modes constantly. Also wrapped a common unit modes check as a function.

### CODE REVIEW

**Review by Branikolog — APPROVED** [review]
Great! Troops are no more walking back and forth. 
In the beginning of the battle ogres were walking to cover archers, but on halfway they decide to rush druids. PR fixes that issue as well. 👍

File: src/fheroes2/ai/normal/ai_normal_spell.cpp [hunk 1]
```diff
@@ -159,7 +159,7 @@ namespace AI
             double unitPercentageLost = std::min( static_cast<double>( damage ) / hitpoints, 1.0 );
 
             // Penalty for waking up disabled unit (if you kill only 30%, rest 70% is your penalty)
-            if ( unit->Modes( SP_BLIND | SP_PARALYZE | SP_STONE ) ) {
```
Comment (ihhub) [inline src/fheroes2/ai/normal/ai_normal_spell.cpp:162]: **isImmovable()** method checks only `SP_BLIND | IS_PARALYZE_MAGIC` but not `SP_STONE`. Is it intentional?

The same for line 323.

**Review by ihhub — COMMENTED** [review]
Hi @idshibanov , I left one question. Can you please take a look?

File: src/fheroes2/ai/normal/ai_normal_spell.cpp (hunk 1 above)
Comment (idshibanov) [reply src/fheroes2/ai/normal/ai_normal_spell.cpp:162]: IS_PARALYZE_MAGIC flag is a combination of both SP_PARALYZE and SP_STONE

Comment (ihhub) [reply src/fheroes2/ai/normal/ai_normal_spell.cpp:162]: Can we then change `IS_PARALYZE_MAGIC = 0xC0000000,` into `IS_PARALYZE_MAGIC = SP_PARALYZE + SP_STONE` to avoid the same confusion in the future?

Comment (ihhub) [reply src/fheroes2/ai/normal/ai_normal_spell.cpp:162]: Actually, no need. I will create a separate pull request for this and other things.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@idshibanov , thank you so much for this fix!
