### PR TITLE
Fix handling of national symbols in the paths to music files on Windows

### LINKED ISSUE #4755: cannot find the music (error Cyrillic directory path)
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

If the path to the game directory contains Cyrillic, then the game cannot find the music

image

### Save file

-

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #4755

### CODE REVIEW

File: src/engine/system.cpp [hunk 1]
```diff
@@ -400,3 +403,80 @@ bool System::GetCaseInsensitivePath( const std::string & path, std::string & cor
...
+{
+#if defined( __MINGW32__ ) || defined( _MSC_VER )
+    static std::map<std::string, std::string> acpToUtf8;
+
+    if ( str.empty() ) {
+        return str;
+    }
+
+    const auto iter = acpToUtf8.find( str );
+
```
Comment (ihhub) [inline src/engine/system.cpp:417]: **You can ignore it if you like**: we can remove an extra space from variable definition and it's usage here and on lines 442, 458 and 466.

File: src/engine/system.cpp [hunk 2]
```diff
@@ -400,3 +403,80 @@ bool System::GetCaseInsensitivePath( const std::string & path, std::string & cor
...
+    if ( WideCharToMultiByte( CP_UTF8, WC_ERR_INVALID_CHARS | WC_NO_BEST_FIT_CHARS, wStr.get(), -1, uStr.get(), uLen, nullptr, nullptr ) != uLen ) {
+        ERROR_LOG( getLastErrorStr() );
+
+        return str;
+    }
+
+    const std::string result( uStr.get() );
+
+    // Put the final result to the cache
+    acpToUtf8[str] = result;
```
Comment (ihhub) [inline src/engine/system.cpp:476]: As of now we can ignore but I think let's put a TODO comment above this code:
```
// TODO: use a single variable for memory storage without copying it to a temporary string.
```

File: src/engine/system.cpp [hunk 3]
```diff
@@ -400,3 +403,80 @@ bool System::GetCaseInsensitivePath( const std::string & path, std::string & cor
...
+
+    return result;
```
Comment (ihhub) [inline src/engine/system.cpp:478]: I'd recommend to do this way to avoid extra memory copy:
```cpp
const inter insertedIter = acpToUtf8.insert( std::string result( uStr.get() ) );
return insertedIter->second;
```

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I left few minor comments here. Would you mind to take a look at them?

File: src/engine/system.cpp [hunk 4]
```diff
@@ -400,3 +403,81 @@ bool System::GetCaseInsensitivePath( const std::string & path, std::string & cor
     return true;
 }
 #endif
+
+std::string System::FileNameToUTF8( const std::string & str )
+{
+#if defined( __MINGW32__ ) || defined( _MSC_VER )
+    static std::map<std::string, std::string> acpToUtf8;
+
+    if ( str.empty() ) {
```
[the remark this answers is not in the document]
Comment (ihhub) [reply src/engine/system.cpp:412]: It's optional. You can ignore it.

File: src/engine/system.cpp (hunk 3 above)
Comment (oleg-derevenetz) [reply src/engine/system.cpp:478]: @ihhub I suppose we can't really use `insert()` here because there is already an item for this key in map. There is `insert_or_assign()`, but it requires C++17.

Comment (ihhub) [reply src/engine/system.cpp:478]: How about this?
```cpp
// In case of any issues, the original string will be returned, so let's put it to the cache right away
auto insertedIter = acpToUtf8.insert( str );
...
// some code here
...
insertedIter->second = std::string( result( uStr.get() ) );
return insertedIter->second;
```

Comment (oleg-derevenetz) [reply src/engine/system.cpp:478]: @ihhub Honestly, it looks like there will be no benefit. Consider:

```
S f1(const S &s)
{
    static std::map<int, S> m;

    m[0] = s; // Default constructor for S and then operator=(const S&) will be called

    S s1;

    m[0] = s1; // operator=(const S&) will be called once again

    return s1; // Copy elision
}
```

```
S f2(const S &s)
{
    static std::map<int, S> m;

    auto emplaceRes = m.emplace(0, s); // Copy constructor will be called for S

    emplaceRes.first->second = S(); // operator=(S&&) will be called

    return emplaceRes.first->second; // No copy elision, copy constructor will be called once again
}
```

So we have two copies in the first case (via `operator=()`), and one movement and the same two copies in the second case (via copy constructor). In fact, it looks like we even have [more operations in the second case](https://godbolt.org/z/aqhadbjbn) :)

File: src/engine/system.cpp (hunk 2 above)
Comment (oleg-derevenetz) [reply src/engine/system.cpp:476]: @ihhub Temporary string encourages copy elision, while other approaches do not (see below).

File: src/engine/system.cpp (hunk 3 above)
Comment (ihhub) [reply src/engine/system.cpp:475]: Ah, I forgot that we're returning the value, not const reference. Then yes, you're absolutely right.

Comment (oleg-derevenetz) [reply src/engine/system.cpp:475]: @ihhub I already thought about returning a const reference here, but I don't like this because of non-Windows version of this function. Consider some clever guy that likes to live dangerously (image with Austin Powers included) and writes code like this:

```
const std::string & s = FileNameToUTF8( someFunctionReturningString() );
```

In Windows version it will always be OK, because currently we get a reference to temporary with lifetime extension, and in case of `const std::string &` as return type we will get just a reference to the static container element. However, in case of non-Windows and `const std::string &` as return type, we will have a dangling reference.

**Comment by ihhub** [comment]
@oleg-derevenetz , huge thanks for these fixes!
