### PR TITLE
Fix a crash with castle overlapping inside a map

### LINKED ISSUE #5974: Map loading problem
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's an assertion while loading a particular map.
image
If we skip (ignore) three times the game starts, but in a such way:
image

I suppose, there's a problem with castles, placed in such manner. Original game load this map without a problem, but these castles are unreachable. Also, heroes hired there can't leave the sell in front of castle gates.
image

### Save file

[Map_0072.zip](https://github.com/ihhub/fheroes2/files/9784191/Map_0072.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #5974

### CODE REVIEW

File: src/fheroes2/castle/castle.cpp [hunk 1]
```diff
@@ -2806,11 +2806,17 @@ void AllCastles::AddCastle( Castle * castle )
                 continue;
             }
 
-            _castleTiles[center + fheroes2::Point( x, y )] = id;
+            const auto [dummy, inserted] = _castleTiles.try_emplace( center + fheroes2::Point( x, y ), id );
```
Comment (oleg-derevenetz) [inline src/fheroes2/castle/castle.cpp:2809]: Hi @ihhub I believe that comment before this `for` loop is not valid anymore :) I suppose we need a new comment that applies to the current logic.

**Review by oleg-derevenetz — APPROVED** [review]
