### PR TITLE
Fix adding an element of a vector to the same vector (golem animation frames copy issue)

### LINKED ISSUE #6689: Iron & Steel Golem animation issues
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

https://user-images.githubusercontent.com/32623900/220469527-f52c9d2b-1339-4b14-9963-5b01abf1aed8.mp4

Looks like they missing some frames. This is reproducible with the following settings:

settings

### Save file

No save file needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
fix #6689

https://user-images.githubusercontent.com/113276641/220747514-306bae7c-4054-4a5a-b7aa-2a02dff5b2fd.mp4

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @ihhub BTW we have a lot of the code like this:

https://github.com/ihhub/fheroes2/blob/3af8445a243f645e5ae6a06c27e61d3040644dc0/src/fheroes2/agg/agg_image.cpp#L1875

or this:

https://github.com/ihhub/fheroes2/blob/3af8445a243f645e5ae6a06c27e61d3040644dc0/src/fheroes2/gui/ui_font.cpp#L142

The problem here in both cases is that `insert()` takes the last parameter by const reference, and if reallocation occurs during an insertion, then this reference will be invalidated.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru it seems that situation is a bit worse then I thought:
> 
> https://en.cppreference.com/w/cpp/container/vector/insert
> 
> Using `insert()` with `first` and `last` iterators pointing into `*this` is undefined behavior in any case (see description of overload N 4), even if no reallocation occurs, so `reserve()` is not enough. It seems that there is no other way than using a temporary vector to be guaranteed to be safe.

Hi @oleg-derevenetz, and what do you think of using `push_back` (or `emplace_back`) in a loop for this case?

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -2230,9 +2230,11 @@ namespace fheroes2
 
                     _icnVsSprite[id].reserve( golemICNSize + copyFramesNum );
                     // 'MOVE_MAIN' frames starts from the 6th frame in Golem ICN sprites.
-                    const std::vector<fheroes2::Sprite>::const_iterator firstFrameToCopy = _icnVsSprite[id].begin() + 6;
-                    _icnVsSprite[id].insert( _icnVsSprite[id].end(), firstFrameToCopy, firstFrameToCopy + copyFramesNum );
-                    for ( int32_t i = 0; i < copyFramesNum; ++i ) {
+                    size_t copyFrame = 6;
+
+                    for ( int32_t i = 0; i < copyFramesNum; ++i, ++copyFrame ) {
+                        _icnVsSprite[id].push_back( _icnVsSprite[id][copyFrame] );
```
Comment (oleg-derevenetz) [inline src/fheroes2/agg/agg_image.cpp:2236]: Hi @Districh-ru this solution suffers from the same issue. `push_back()` gets the value to insert by const reference. Suppose that there is no room left and vector is forced to reallocate. Suppose it will reallocate first and only then it will access the reference that is passed as `push_back()` argument.

**Comment by ihhub** [comment]
Hi @Districh-ru and @oleg-derevenetz , this is indeed a huge problem. We must fix it immediately.

File: src/fheroes2/agg/agg_image.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/agg/agg_image.cpp]: Hi @oleg-derevenetz, I changed the code to make a copy of a vector element and then `std::move` it in in `emplace_back` to a vector.

**Comment by Districh-ru** [comment]
Hi @ihhub and @oleg-derevenetz, I also made some changes to other parts of the code where I found `push_back` or `emplace_back` of a vector element to the same vector.

File: src/fheroes2/campaign/campaign_data.cpp [hunk 2]
```diff
@@ -842,7 +843,10 @@ namespace Campaign
             std::string description( monsters.back().GetMultiName() );
 
             while ( monsters.back() != monsters.back().GetUpgrade() ) {
-                monsters.emplace_back( monsters.back().GetUpgrade() );
```
Comment (oleg-derevenetz) [inline src/fheroes2/campaign/campaign_data.cpp:845]: There is a different situation: `Monster::GetUpgrade()` returns a temporary, which is then will be added to the vector. So the temporary will be created first, and then inside `emplace_back()` only this temporary will be accessed through the rvalue reference (i.e. moved to the vector), not any of already existing vector elements, so this operation is safe.

File: src/fheroes2/campaign/campaign_data.cpp [hunk 3]
```diff
@@ -856,7 +860,10 @@ namespace Campaign
...
```
Comment (oleg-derevenetz) [inline src/fheroes2/campaign/campaign_data.cpp:859]: The same situation as above: `emplace_back()` deals with temporary, not with existing element of `monsters`.

File: src/fheroes2/dialog/dialog_recruit.cpp [hunk 4]
```diff
@@ -368,7 +369,10 @@ Troop Dialog::RecruitMonster( const Monster & monster0, uint32_t available, cons
 
     std::vector<Monster> upgrades = { monster0 };
     while ( upgrades.back().GetDowngrade() != upgrades.back() ) {
-        upgrades.emplace_back( upgrades.back().GetDowngrade() );
```
Comment (oleg-derevenetz) [inline src/fheroes2/dialog/dialog_recruit.cpp:371]: `Monster::GetDowngrade()` returns a temporary, not a reference to some already existing element of `upgrades`, so this operation is safe as well.

File: src/fheroes2/gui/ui_campaign.cpp [hunk 5]
```diff
@@ -155,7 +156,10 @@ namespace fheroes2
             uiElements.emplace_back( monsterUI.back().get() );
 
             while ( monsters.back() != monsters.back().GetUpgrade() ) {
-                monsters.emplace_back( monsters.back().GetUpgrade() );
```
Comment (oleg-derevenetz) [inline src/fheroes2/gui/ui_campaign.cpp:158]: The same logic as above - the temporary object is added to the vector, not some element of the same vector.

**Review by oleg-derevenetz — CHANGES_REQUESTED** [review]
Hi @Districh-ru It's really not THAT bad :) I just left a few comments, please take a look when you have time.

File: src/fheroes2/campaign/campaign_data.cpp (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/campaign/campaign_data.cpp]: Hi @oleg-derevenetz, thanks for the explanations.
I reverted the changes in these files.

**Review by oleg-derevenetz — APPROVED** [review]

File: src/engine/screen.cpp [hunk 6]
```diff
@@ -147,7 +147,11 @@ namespace
 
                 if ( ( resolutions[biggerId].width % resolutions[currentId].width ) == 0 && ( resolutions[biggerId].height % resolutions[currentId].height ) == 0
                      && ( resolutions[biggerId].width / resolutions[currentId].width ) == ( resolutions[biggerId].height / resolutions[currentId].height ) ) {
-                    resolutions.emplace_back( resolutions[currentId].width, resolutions[currentId].height, resolutions[biggerId].width / resolutions[currentId].width );
+                    // IMPORTANT: we MUST do a copy of a vector element if we want to emplace it to the same vector.
+                    const fheroes2::ResolutionInfo currentResolution = resolutions[currentId];
+                    const int32_t biggerResolutionWidth = resolutions[biggerId].width;
```
Comment (ihhub) [inline src/engine/screen.cpp:152]: Would it makes sense to calculate a scale factor instead of width?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I left one comment here. Could you please take a look?

File: src/engine/screen.cpp (hunk 6 above)
Comment (Districh-ru) [reply src/engine/screen.cpp]: Hi @ihhub, certainly, we can cache the scale factor here.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for these fixes!
