### PR TITLE
Fix displayed object info in popup dialogs

### LINKED ISSUE #1274: Abandoned Mine, info window
In fheroes2, when the hero is positioned on the entrance to the abandoned mine, after the combat with the ghosts, and the player right-clicks on part of the mine, the information window does not indicate the type of the mine.

Also, in the original game, the window is displayed over the mouse cursor, the cursor is no longer visible.
In fheroes2, the window is displayed next to the cursor.

In the original game:

Abandoned mine info 01

Abandoned mine info 02

In fheroes2:

Abandoned mine info 03

### LINKED ISSUE #1280: Mine, info window, mouse cursor position on the mine and right click
In fheroes2, depending on the position of the mouse cursor when the player clicks on a mine, there is not the same information available in the displayed information window.
In the original game, there is always the same information available in the displayed information window.

In fheroes2:

Mine, info window, mouse cursor position on the mine and right click 01

Mine, info window, mouse cursor position on the mine and right click 06

Mine, info window, mouse cursor position on the mine and right click 02

Mine, info window, mouse cursor position on the mine and right click 04

Mine, info window, mouse cursor position on the mine and right click 03

Mine, info window, mouse cursor position on the mine and right click 05

### LINKED ISSUE #1281: Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City
In fheroes2, depending on the position of the mouse cursor when the player clicks on a sawmill, there is not the same information available in the displayed information window.
In the original game, there is always the same information available in the displayed information window.

Also, when the sawmill is located near a dragon city, the information window of the dragon city is displayed instead of that of the sawmill.
This bug is also present in the original game.

In fheroes2:

Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 01

Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 02

Sawmill, info window, mouse cursor position on the sawmill and right click, and Dragon City 03

**Edit 2021/04/28.**

Similar behavior for information related to a hero ("(not visited)", "(already visited)") when another hero is positioned on a large object (an object that occupies several squares and part of which is directly accessible with the mouse cursor).

In fheroes2:

Large objet info window for hero fh2 01

### PR DESCRIPTION
**Pull request by ihhub**
close #1281
close #1280 
close #1274

### CODE REVIEW

File: src/fheroes2/dialog/dialog_quickinfo.cpp [hunk 1]
```diff
@@ -401,29 +403,56 @@ void Dialog::QuickInfo( const Maps::Tiles & tile )
...
+                    if ( std::find( uids.begin(), uids.end(), foundTile.GetObjectUID() ) != uids.end() && foundTile.GetObject( false ) == requiredObjectType ) {
+                        QuickInfo( foundTile );
+                        return;
+                    }
+                }
+            }
+        }
+
+        // How is it possible that the main tile is missing?
+        // assert( 0 );
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_quickinfo.cpp:455]: This assert should be uncommented once #3756 is merged.
