### PR TITLE
Fix passabilities of objects on map

### LINKED ISSUE #496: Cannot use "Dimension door" spell over some areas
Cannot use "Dimension door" spell to move hero to the areas behind mountains.
Mountains
Mountains2

### LINKED ISSUE #1521: Adventure map, Abandoned Mine, wrong passability
In fheroes2, the hero can move and position himself in the upper right square of the Abandoned Mine.

In fheroes2:

Abandoned Mine, wrong passability 01

Abandoned Mine, wrong passability 02

Abandoned Mine, wrong passability 03

### LINKED ISSUE #1951: Adventure map, wrong passability of objects
In fheroes2, some objects do not have the same passability as in the original game.

In original game:

Passability objets H2 01

In fheroes2:

Passability objets fh2 01

In original game:

Passability objets H2 02

In fheroes2:

Passability objets fh2 02

Passability objets fh2 02a

In original game:

Passability objets H2 03

In fheroes2:

Passability objets fh2 03

In original game:

Passability objets H2 04

Passability objets H2 04a

In fheroes2:

Passability objets fh2 04

Passability objets fh2 04a

Here are the save files:
[Wrong objets passability 01.zip](https://github.com/ihhub/fheroes2/files/5359235/Wrong.objets.passability.01.zip)

Similar issues: https://github.com/ihhub/fheroes2/issues/1577, https://github.com/ihhub/fheroes2/issues/1521.

**Edit 2020/11/01.**

In original game:

Passability objets fh2 10

In fheroes2:

Passability objets fh2 11

Here is the save file:
[Hero path 01.zip](https://github.com/ihhub/fheroes2/files/5471617/Hero.path.01.zip)

**Edit 2020/11/08.**

In original game:

Hero path passability H2 05

In fheroes2:

Hero path passability 05

**Edit 2021/05/01.**

In original game:

Before attack boat castle H2 01

In fheroes2:

Before attack boat castle fh2 01

**Edit 2021/05/30.**

In original game:

Path shipwreck 02

In fheroes2:

Path shipwreck 01

I think all objects should be checked in comparison to the original game.

### LINKED ISSUE #2364: Adventure map, the hero should not be able to attack a wandering troop through an object of the decor
In fheroes2, the hero should not be able to attack a wandering troop through an object of the decor.

In fheroes2:

Attack creature through objetc fh2 01

Here are the save files:
[Month of creature fh2 01.zip](https://github.com/ihhub/fheroes2/files/5683088/Month.of.creature.fh2.01.zip)

### LINKED ISSUE #2401: Path to barrier should exclude diagonal directions
In the OG hero comes to barrier from the top.
image
In fheroes2 hero can open barrier from diagonal cell
image

### LINKED ISSUE #2601: AI is stuck at coast and doesn't move
AI is standing for a long period of time at once cell with one of his leading heroes.
image
[AI chilling on a beach.zip](https://github.com/ihhub/fheroes2/files/5819542/AI.chilling.on.a.beach.zip)

### LINKED ISSUE #3246: Adventure map, heroes' path in relation to the objects
In fheroes2, the heroes take paths that give the impression that they are "penetrating" the objects.
This should be avoided.

In original game:

https://user-images.githubusercontent.com/43583994/115630134-c9c08980-a303-11eb-8b27-228ffc23c9bc.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/115630240-f7a5ce00-a303-11eb-909b-b985eca6e0a4.mp4

Here is the save file:
[Hero path and castle.zip](https://github.com/ihhub/fheroes2/files/6354317/Hero.path.and.castle.zip)

### LINKED ISSUE #3745: Adventure map, wrong object passability, hero moves through the Sphinx
In fheroes2, the hero moves through the Sphinx.

In fheroes2:

vlcsnap-2021-06-23-15h41m08s232

https://user-images.githubusercontent.com/43583994/123108846-0eb78800-d43b-11eb-86f6-e1e50ca90e65.mp4

Here is the test scenario file:
[0 9958.zip](https://github.com/ihhub/fheroes2/files/6702313/0.9958.zip)

### LINKED ISSUE #3750: Adventure map, wrong object passability, hero moves through the "Rock"
In fheroes2, the hero moves through the "Rock".

In original game:

https://user-images.githubusercontent.com/43583994/123179476-c6738680-d489-11eb-9032-3b0794706dfa.mp4

In fheroes2:

https://youtu.be/hHHNvecn1ik?t=2605

### PR DESCRIPTION
**Pull request by ihhub**
The original code was based on hacks and it wasn't reliable. The current approach uses an algorithm and a set of conditions to determine passability of a tile.

close #1951
close #3750
close #3745
close #1521
close #496
close #2601 
close #2401 
close #2364 
close #3246

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please test these changes as the highest priority? The changes only work on new games. To speed up the work you could consider modifying `debug` parameter in configuration file to **65535** giving you an extra powerful hero.

I would like to know that we didn't screw gameplay with these changes as the code is re-written from scratch.

**Review by oleg-derevenetz — COMMENTED** [review]
Hi @ihhub Since I'm not very familiar with map objects passability rules, I left a few questions here. Would you mind taking a look?

File: src/fheroes2/maps/maps_tiles.cpp [hunk 1]
```diff
@@ -1054,234 +790,99 @@ const fheroes2::Image & Maps::Tiles::GetTileSurface( void ) const
...
-
-        // fix mountain layer
-        if ( tilePassable && hasRocksOrTrees && ( mounts2 || trees2 ) ) {
-            tilePassable = 0;
-#ifdef WITH_DEBUG
-            impassableTileRule = 3;
-#endif
-        }
+    const int objId = GetObject( false );
+    const bool isActionObject = MP2::isGroundObject( objId );
```
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:831]: Excellent question. Even before changes `isGroundObject` covered all objects except `OBJ_COAST` by **obj > 127** condition. `isWaterObject` at the same time markes boats as non-action which leads to a fact that a hero cannot embrak a boat from top tiles. To avoid changing the logic in other places it was decided to use `isGroundObject` method.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 2]
```diff
@@ -1054,234 +790,99 @@ const fheroes2::Image & Maps::Tiles::GetTileSurface( void ) const
...
-             || icnIndex == 42 || icnIndex == 43 || icnIndex == 45 || icnIndex == 48 || icnIndex == 49 || icnIndex == 51 || icnIndex == 53 || icnIndex == 74
-             || icnIndex == 76 )
-            return true;
-        break;
+    const int objId = GetObject( false );
 
-    default:
-        break;
+    if ( MP2::isGroundObject( objId ) ) {
+        return MP2::getActionObjectDirection( objId );
```
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:798]: As explained in the other comment `isGroundObject` covers all action objects.

**Review by idshibanov — APPROVED** [review]
Overall new logic looks good to me, although with such a big PR it's impossible to check every case. Few testing sessions definitely needed.

File: src/fheroes2/maps/maps_tiles_quantity.cpp [hunk 3]
```diff
@@ -425,6 +425,7 @@ Troop Maps::Tiles::QuantityTroop( void ) const
 
 void Maps::Tiles::QuantityReset( void )
 {
+    // TODO: don't modify first 2 bits of quantity1.
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles_quantity.cpp:428]: AFAIK quantity1 is also used as a highest byte of monster count/resource count on a tile and, for example, is used in `Maps::Tiles::QuantityTroop()` (via `Maps::Tiles::MonsterCount()`) to return a count of monsters defending a dwelling or non-captureable dwelling objects, such as Troll Bridge. Won't this break something?

File: src/fheroes2/maps/maps_tiles.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles.cpp:833]: May be rename all this somehow? :) For example, rename `isGroundObject(int)` rename to `isActionObject(int)`, so there will be `isActionObject(int)` (more "generic" one) and `isActionObject(int, bool)` (more "specific" one), and add appropriate comments?

[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:833]: Sure. I will do.

File: src/fheroes2/maps/maps_tiles_quantity.cpp (hunk 3 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:428]: Right now the logic for passability rules checks if a tile is an action object so this code right now won't break anything. However, to prevent any possible issues in the future we have to fix it.

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , I addressed our comments. Could you please take a look again?

File: src/fheroes2/maps/maps_tiles_quantity.cpp (hunk 3 above)
Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:428]: Hi @ihhub Yes, I noticed that. Passability-related code respects object type. But other code (related to dwellings, etc) is currently unaware that these 2 bits are "special". So if tile contains more than 16383 units (yes, I know...), it may not be reset properly if we will not modify these first 2 bits here.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:428]: This issue we need to address in a separate pull request. By right once any information is read from mp2 or addon structures we have to extract priority information and use `quantity1` as a normal value. That's why I added these TODO comments.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:428]: Also right now passability is set at the time of reading a map but in the future we might have a code to remove objects from the map during gameplay which will break passability rules. For now we keep as it is and fix later priority value by storing it in a separate variable without bitwise operations like right now.

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, could you please test these changes as the highest priority? The changes only work on new games. To speed up the work you could consider modifying `debug` parameter in configuration file to **65535** giving you an extra powerful hero.
> 
> I would like to know that we didn't screw gameplay with these changes as the code is re-written from scratch.

It sounds like you are still working on this.
Are there any adjustments that need to be made before the change is in its "final" version?
I wouldn't want to start testing again.
Please tell me when it will be ready for testing.

File: src/fheroes2/maps/maps_tiles_quantity.cpp (hunk 3 above)
Comment (oleg-derevenetz) [reply src/fheroes2/maps/maps_tiles_quantity.cpp:428]: @ihhub

> For now we keep as it is and fix later priority value by storing it in a separate variable without bitwise operations like right now.

Yes, that's what I also wanted to offer.

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
> Hello @ihhub,
> 
> > Hi @LeHerosInconnu, could you please test these changes as the highest priority? The changes only work on new games. To speed up the work you could consider modifying `debug` parameter in configuration file to **65535** giving you an extra powerful hero.
> > I would like to know that we didn't screw gameplay with these changes as the code is re-written from scratch.
> 
> It sounds like you are still working on this.
> Are there any adjustments that need to be made before the change is in its "final" version?
> I wouldn't want to start testing again.
> Please tell me when it will be ready for testing.

Hi @LeHerosInconnu , I was addressing code related issues without touching the game's logic. Also right now all reviewers approved the changes so please proceed with testing once the current commit will be ready to be downloaded (in maximum 20 minutes).

**Comment by ihhub** [comment]
Hi @Branikolog , could you please also help with testing of these changes are they are very critical for the release?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

Here are the differences I've spotted so far.
(One image from the original game with one image from fheroes2.)
There are many.
[Passability differences 01 01.zip](https://github.com/ihhub/fheroes2/files/6729549/Passability.differences.01.01.zip)
[Passability differences 01 02.zip](https://github.com/ihhub/fheroes2/files/6729560/Passability.differences.01.02.zip)
[Passability differences 01 03.zip](https://github.com/ihhub/fheroes2/files/6729577/Passability.differences.01.03.zip)

**Comment by ihhub** [comment]
Hi @idshibanov  and @oleg-derevenetz , based on feedback from @LeHerosInconnu  and @Branikolog  I modified the logic. I also added temporary field called `_level` to avoid being overridden while we set artifact/spell/monster quantity. Could you please take a look at these changes again?

File: src/fheroes2/maps/maps_tiles.cpp [hunk 4]
```diff
@@ -2334,12 +2399,16 @@ void Maps::Tiles::setAsEmpty()
...
+    uint8_t temp = 0;
+
+    return msg << ta.level << ta.uniq << ta.object << ta.index << temp;
 }
 
 StreamBase & Maps::operator>>( StreamBase & msg, TilesAddon & ta )
 {
-    msg >> ta.level >> ta.uniq >> ta.object >> ta.index >> ta.tmp;
+     uint8_t temp = 0;
+
```
Comment (oleg-derevenetz) [inline src/fheroes2/maps/maps_tiles.cpp:2418]: I suppose, version check will be added later to not write/read an obsolete field.

**Review by oleg-derevenetz — APPROVED** [review]
Hi @ihhub no obvious issues found, except one note regarding read & write an obsolete field.

File: src/fheroes2/maps/maps_tiles.cpp (hunk 4 above)
Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:2418]: Yes. I didn't want to increase this pull request even further.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , could you please verify changes again? I addressed the majority of found problems. Not everything is identical to the original game but this implementation must be much closer to the original.

**Comment by ihhub** [comment]
Hi @LeHerosInconnu and @Branikolog , for any other passability issues let's create a separate issue where we could define them. I found that the original game has some flaws in passability as well.
