### PR TITLE
Fix the mouse interaction in the Editor's spell selection and castle properties windows

### LINKED ISSUE #9354: Spell selection dialog, spell info is triggering by hovering over the icon with the right mouse button pressed.
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Press right mouse button and move cursor over any spell icon:

https://github.com/user-attachments/assets/ea097c04-a513-4b90-81cc-3669c7c26d13

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #9354

### CODE REVIEW

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz !
I've checked the PR and the issue for shrines and pyramids is fixed. 👍 
I've noticed the same issue for castle window. Should I create a separate issue for that or these are similar problems and could be fixed within a single PR?
image

File: src/fheroes2/editor/editor_spell_selection.cpp [hunk 1]
```diff
@@ -138,14 +138,17 @@ namespace
                 return false;
             }
 
-            if ( eventProcessor.MouseClickLeft() ) {
-                assert( static_cast<size_t>( spellIndex ) < _spellRoi.size() );
+            assert( static_cast<size_t>( spellIndex ) < _spellRoi.size() );
 
+            const fheroes2::Rect spellRoi = _spellRoi[spellIndex];
```
Comment (Districh-ru) [inline src/fheroes2/editor/editor_spell_selection.cpp:143]: Hi, @oleg-derevenetz, should we convert this to `const &` not to make a copy?
```suggestion
            const fheroes2::Rect & spellRoi = _spellRoi[spellIndex];
```

Comment (oleg-derevenetz) [reply src/fheroes2/editor/editor_spell_selection.cpp:143]: @Districh-ru we can do it, but I'm not sure that we should. `Rect` is 4 32-bit ints, which rougly correspond to 2 64-bit pointers, it's not a some structure of a few hundreds or thousands bytes in size, so I doubt that we will win significantly here in terms of performance. Also I prefer not to take a references to items of externally-managed vectors without any particular need because they can easily become dangling if reallocation of this vector will be caused somewhere between.

Comment (Districh-ru) [reply src/fheroes2/editor/editor_spell_selection.cpp:143]: @oleg-derevenetz, thanks for the explanation!
I'll take this into account.

**Comment by oleg-derevenetz** [comment]
> Should I create a separate issue for that or these are similar problems and could be fixed within a single PR?

I (hopefully) fixed the castle properties window as well.

**Review by Districh-ru — APPROVED** [review]

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for the fix!
