### PR TITLE
Fix a crash due to an assertion failure when the shooter hits back at a unit under Berserk spell

### LINKED ISSUE #5213: Core dump when using berserk on titan
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

When a titan attacks an enemy under the influence of a berserk spell the game seems to crash because of an assertion. 

The core dump backtrace is this one 

```
Core was generated by `./fheroes2'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f68eac61f00 (LWP 153845))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f68ec767859 in __GI_abort () at abort.c:79
#2  0x00007f68ec767729 in __assert_fail_base
    (fmt=0x7f68ec8fd588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5604817980a8 "Unit::isHandFighting( attacker, defender ) ? dir > UNKNOWN : dir == UNKNOWN", file=0x560481797f90 "/home/felix/Documents/ElementPerso/fheroes2/src/fheroes2/battle/battle_action.cpp", line=113, function=<optimized out>) at assert.c:92
#3  0x00007f68ec779006 in __GI___assert_fail
    (assertion=0x5604817980a8 "Unit::isHandFighting( attacker, defender ) ? dir > UNKNOWN : dir == UNKNOWN", file=0x560481797f90 "/home/felix/Documents/ElementPerso/fheroes2/src/fheroes2/battle/battle_action.cpp", line=113, function=0x560481798058 "void Battle::Arena::BattleProcess(Battle::Unit&, Battle::Unit&, int32_t, int)")
    at assert.c:101
#4  0x00005604814aecd4 in Battle::Arena::BattleProcess(Battle::Unit&, Battle::Unit&, int, int) ()
#5  0x00005604814af88f in Battle::Arena::ApplyActionAttack(Battle::Command&) ()
#6  0x00005604814af37b in Battle::Arena::ApplyAction(Battle::Command&) ()
#7  0x00005604814c0dbd in Battle::Arena::TurnTroop(Battle::Unit*, Battle::Units const&) ()
#8  0x00005604814c1565 in Battle::Arena::Turns() ()
#9  0x0000560481515b01 in Battle::Loader(Army&, Army&, int) ()
#10 0x0000560481677ccc in ActionToHeroes(Heroes&, int) ()
#11 0x0000560481676734 in Heroes::Action(int, bool) ()
#12 0x000056048169b32b in Heroes::MoveStep(Heroes&, int, bool) ()
#13 0x000056048169b4d9 in Heroes::MoveStep(bool) ()
#14 0x000056048169c3cd in Heroes::Move(bool) ()
#15 0x000056048161f96d in Interface::Basic::HumanTurn(bool) ()
#16 0x000056048161e616 in Interface::Basic::StartGame() ()
#17 0x000056048161bc73 in Game::StartGame() ()
#18 0x000056048160e925 in Game::mainGameLoop(bool) ()
#19 0x00005604815e49ec in main ()

```

If any info is missing don't hesitate to ask me :) 

### Save file

[before_core_dump.zip](https://github.com/ihhub/fheroes2/files/8437562/before_core_dump.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5213

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
Hi @felix642 could you please test this fix? It looks like it solves the original issue, but it would be good to play as many battles as possible to ensure that there are no any regressions.

File: src/fheroes2/battle/battle_troop.cpp [hunk 1]
```diff
@@ -360,26 +360,49 @@ bool Battle::Unit::canReach( const Unit & unit ) const
...
         }
     }
 
     return false;
 }
 
-bool Battle::Unit::isHandFighting( const Unit & a, const Unit & b )
+bool Battle::Unit::isHandFighting( const Unit & attacker, const Unit & defender )
 {
-    return a.isValid() && !a.Modes( CAP_TOWER ) && b.isValid() && b.GetColor() != a.GetCurrentColor()
```
Comment (ihhub) [inline src/fheroes2/battle/battle_troop.cpp:378]: Are removed condition `b.GetColor() != a.GetCurrentColor()` and modified `bool Battle::Unit::isHandFighting() const` method above the only change required in order to fix the issue?

Comment (oleg-derevenetz) [reply src/fheroes2/battle/battle_troop.cpp:378]: Hi @ihhub In fact, yes. At first I had thoughts to leave the color check in `Unit::isHandFighting()` somehow, but this required too many modifications (in the process of which I replaced all these `b1`, `b2`, etc), but later I decided just to remove it, because this check has already been done in places where this function is called.

**Comment by ihhub** [comment]
@oleg-derevenetz , great thanks for polishing the code and fixing the issue!
