### PR TITLE
Fix the logic of purchasing a boat in shipyard

### LINKED ISSUE #7970: Cannot build a boat in a specific castle
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

In the castle Erliquin (the last of three castles owned by a player, a wizard's one) it is impossible to build a boat. If you try game takes your resources for a boat, game plays a sound of a boat materializing but it turns out it is a fraud, no boat created.

### Save file

[bug.zip](https://github.com/ihhub/fheroes2/files/13059558/bug.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7970

### CODE REVIEW

File: src/fheroes2/castle/castle.cpp [hunk 1]
```diff
@@ -2155,42 +2156,113 @@ Heroes * Castle::GetHero() const
...
+
+    if ( Maps::isValidAbsPoint( possibleSeaTile.x + 1, possibleSeaTile.y ) && doesTileHaveBoat( world.GetTiles( index + 1 ) ) ) {
+        return true;
+    }
+
+    return false;
 }
 
-bool Castle::PresentBoat() const
+int Castle::getTileIndexToPlaceBoat() const
```
Comment (oleg-derevenetz) [inline src/fheroes2/castle/castle.cpp:2233]: Hi @ihhub map indexes are usually `int32_t`, even in this function `index` is `int32_t`. It would be nice if this function followed the general logic and also returned `int32_t` instead of just `int`.

File: src/fheroes2/castle/castle.cpp [hunk 2]
```diff
@@ -2541,32 +2609,21 @@ bool Castle::BuyBoat() const
         return false;
     }
 
-    if ( !Maps::isValidAbsPoint( center.x, center.y + 2 ) ) {
+    // If this assertion blows up then you didn't even check conditions to build a shipyard!
+    assert( HasSeaAccess() );
+
+    const int index = getTileIndexToPlaceBoat();
```
Comment (oleg-derevenetz) [inline src/fheroes2/castle/castle.cpp:2615]: And accordingly, this variable should also be of type `int32_t`.

File: src/fheroes2/castle/castle.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/castle/castle.cpp:2233]: Thanks for spotting it!

**Review by oleg-derevenetz — APPROVED** [review]

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub, I left one comment regarding sea access check. Could you please take a look when you have time.

**Review by Districh-ru — APPROVED** [review]

**Comment by drevoborod** [comment]
Now it's possible to buy a boat, but it's impossible to occupy it by a hero - it becomes unreacheable. And, of course, after that it's impossible to buy new boat, because there is one already. So, we have here some lock situation, which doesn't seem to be ok.

**Comment by oleg-derevenetz** [comment]
Hi @drevoborod

> Now it's possible to buy a boat, but it's impossible to occupy it by a hero - it becomes unreacheable. And, of course, after that it's impossible to buy new boat, because there is one already. So, we have here some lock situation, which doesn't seem to be ok.

IIRC there is nothing we can do with this, because there is just one tile suitable for a boat near this castle and it is unreachable because of a tree. BUT this boat can be summoned once built, so it's still a progress.

**Comment by drevoborod** [comment]
> P.S. In the original game there is funny behavior in this castle:
> DOSBox.0.74-2.1.Cpu.speed_.max.100.cycles.Frameskip.0.Program_.HEROES2.2023-10-24.22-50-20.mp4
> 
> There is no boat on the adventure map nearby, but there is a boat in the castle and Shipyard doesn't allow to buy another one.

Yes, I also checked the original game behaviuor and the result was same if there was already a shipyard on start; if there was no shipyard and I bought it myself, the message appeared (It's Knight castle but I don't think it matters): 
изображение

**Comment by ihhub** [comment]
Thanks @drevoborod !
