### PR TITLE
Interface itemsbar adjustment + fix some split logics

### LINKED ISSUE #2391: Split logic operation with 1 selected troop
If we have selected a stack with 1 troop and then use right click over empty slot, current troop moves, but at the same time troop info window appears, as if we used simple right click over any unit:
image
I think, we don't need to show this info window while moving army over the slots.

### PR DESCRIPTION
**Pull request by eos428**
Also fixes #2391, but mostly this should be about refactoring `interface_itemsbar.h` and ensuring things are still working as before with improvements.

### CODE REVIEW

File: src/fheroes2/army/army_bar.cpp [hunk 1]
```diff
@@ -500,14 +496,31 @@ bool ArmyBar::ActionBarPressRight( ArmyTroop & troop )
...
-    else
-        RedistributeArmy( troop2, troop1 );
+    ArmyTroop & selectedTroop = *GetSelectedItem();
+
+    if ( troop.GetID() == selectedTroop.GetID() )
+        return false;
+
+    if ( !troop.isValid() || selectedTroop.GetMonster() == troop.GetMonster() ) {
+        ResetSelected();
+        RedistributeArmy( selectedTroop, troop, [&]() { can_see_troop_info = false; } );
```
Comment (ihhub) [inline src/fheroes2/army/army_bar.cpp:512]: This line and line 522 are only places passing a pointer to lambda function. This lambda function just sets a variable to some state. Would it be more easier if we just pass a pointer to a boolean variable?

File: src/fheroes2/army/army_bar.h [hunk 2]
```diff
@@ -65,6 +68,7 @@ class ArmyBar : public Interface::ItemsActionBar<ArmyTroop>
     bool use_mini_sprite;
     bool read_only;
     bool can_change;
+    bool can_see_troop_info;
```
Comment (ihhub) [inline src/fheroes2/army/army_bar.h:71]: Please use camelCase variable naming: `_isTroopInfoVisible`.

Comment (ihhub) [reply src/fheroes2/army/army_bar.h:71]: This new member is not initialized in the constructor.

File: src/fheroes2/gui/interface_itemsbar.h [hunk 3]
```diff
@@ -301,41 +301,81 @@ namespace Interface
...
         }
 
-        virtual bool ActionBarCursor( Item & ) override
+        virtual bool ActionBarLeftMouseRelease( Item &, Item & )
         {
             return false;
         }
 
-        virtual bool ActionBarCursor( Item &, Item & )
+        virtual bool ActionBarRightMouseHold( Item &, Item & )
```
Comment (ihhub) [inline src/fheroes2/gui/interface_itemsbar.h:339]: I'm change curious do we even check the return values of all these methods? If not we don't need to even return anything after all.

File: src/fheroes2/gui/skill_bar.h [hunk 4]
```diff
@@ -32,8 +32,8 @@ class PrimarySkillsBar : public Interface::ItemsBar<int>
     virtual void RedrawBackground( const Rect &, fheroes2::Image & ) override;
     virtual void RedrawItem( int &, const Rect &, fheroes2::Image & ) override;
 
-    virtual bool ActionBarSingleClick( int & ) override;
-    virtual bool ActionBarPressRight( int & ) override;
+    virtual bool ActionBarLeftMouseSingleClick( int & ) override;
+    virtual bool ActionBarRightMouseHold( int & ) override;
```
Comment (ihhub) [inline src/fheroes2/gui/skill_bar.h:36]: Since we change the code above to add input argument names please do the same here and for the 58-59 lines as well.

File: src/fheroes2/resource/artifact.h [hunk 5]
```diff
@@ -244,10 +244,10 @@ class ArtifactsBar : public Interface::ItemsActionBar<Artifact>
...
     void Redraw( fheroes2::Image & dstsf = fheroes2::Display::instance() );
 
-    virtual bool ActionBarSingleClick( Artifact & ) override;
-    virtual bool ActionBarSingleClick( Artifact &, Artifact & ) override;
-    virtual bool ActionBarDoubleClick( Artifact & ) override;
-    virtual bool ActionBarPressRight( Artifact & ) override;
+    virtual bool ActionBarLeftMouseSingleClick( Artifact & ) override;
+    virtual bool ActionBarLeftMouseSingleClick( Artifact &, Artifact & ) override;
+    virtual bool ActionBarLeftMouseDoubleClick( Artifact & ) override;
+    virtual bool ActionBarRightMouseHold( Artifact & ) override;
```
Comment (ihhub) [inline src/fheroes2/resource/artifact.h:250]: Since we change the code above to add input argument names please do the same here.

File: src/fheroes2/gui/interface_itemsbar.h (hunk 3 above)
Comment (ihhub) [reply src/fheroes2/gui/interface_itemsbar.h:339]: Actually some of return values are handled in `ActionCursorItemIter` method...

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @eos428 I left multiple comments. Could you please take a look into them and also review whether we need to return something from the most of action methods after all?

**Comment by ihhub** [comment]
Hi @eos428 please fix compilation error in `OSX / sdl2` CI job.

File: src/fheroes2/gui/interface_itemsbar.h (hunk 3 above)
Comment (eos428) [reply src/fheroes2/gui/interface_itemsbar.h:339]: I don't know the exact details, but I think the most important ones to keep track are ActionBarCursor and LeftSingleClick. I think ActionBarCursor returning true would stop the rest of event processing, which is not what we'd want.

**Comment by ihhub** [comment]
@eos428 thanks a lot for your priceless contribution to the project!
