### PR TITLE
Fix logic & reward of Daemon Cave object for AI, improve the resource value estimation algorithm for AI

### LINKED ISSUE #7098: Improve AI hero behavior when handling Daemon Cave
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

AI heroes always fight when visiting Daemon Cave but somehow they consider to visit it only when there is an artifact. A hero receives only 2500 Gold after a battle so it is not particularly correct behavior for AI heroes.

### Describe the possible solution

Expand the logic for AI heroes.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
close #7098

This PR also improves the resource value estimation algorithm. Previously, the cost of any resource other than gold was initially equal to 100 gold, which is a rather rough estimate. In this PR, an estimate is introduced based on the production ratio of the respective mines.

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_hero.cpp [hunk 1]
```diff
@@ -885,16 +887,29 @@ namespace AI
...
+                }
+
+                std::tie( resourceType, resourceAmount ) = getDailyIncomeObjectResources( tile ).getFirstValidResource();
+            }
+
+            assert( resourceType != Resource::UNKNOWN && resourceAmount != 0 );
+
+            // Since mines constantly bring resources, they are valuable objects.
+            // Let's evaluate them in proportion to the amount of resources they bring in 3 days (TODO: a fairly arbitrary period).
+            return resourceAmount * getResourcePriorityModifier( resourceType ) * 3;
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_hero.cpp:912]: I'm not sure regarding this multiplier, maybe we shouldn't use it at all and take into account only the daily income from this mine. With the multiplier, the value of the mine is dangerously close to the value of the attacking an enemy hero.

File: src/fheroes2/ai/normal/ai_normal.cpp [hunk 2]
```diff
@@ -68,17 +70,54 @@ namespace AI
...
     double Normal::getResourcePriorityModifier( const int resource ) const
     {
-        // Gold usually measured in 100s
-        double prio = ( resource == Resource::GOLD ) ? 1.0 : 100.0;
+        // Not all resources are equally valuable: 1 gold does not have the same value as 1 gemstone, so we need to
+        // normalize the value of various resources. Let's determine the default relative priority of resources based on
+        // the ratio of the amount of resources extracted by the respective mines. For example, if a gold mine produces
+        // 1000 gold per day, an ore mine produces 2 units of ore per day, and a gem mine produces 1 gem per day, then
+        // the priority of one unit of ore will correspond to the priority of 500 gold, and the priority of one gemstone
+        // will correspond to the priority of 1000 gold.
```
Comment (idshibanov) [inline src/fheroes2/ai/normal/ai_normal.cpp:78]: Maybe we split this between mines and pickup resources? 100x multiplier was there to simply counteract gold piles to be stored in single digits (9 value = 900 gold on pickup).

Value should be derived from multiplier only.

File: src/fheroes2/ai/normal/ai_normal_hero.cpp (hunk 1 above)
Comment (idshibanov) [reply src/fheroes2/ai/normal/ai_normal_hero.cpp:912]: Result should be in range of 2000 - 4000 priority.

Comment (oleg-derevenetz) [reply src/fheroes2/ai/normal/ai_normal_hero.cpp:912]: Hi @idshibanov So ~3000 in case of gold mine (1000 gold per day * 3 days * 1.0 multiplier) maybe OK. However with non-default multiplier the value may be higher.

**Review by ihhub — APPROVED** [review]

File: src/fheroes2/ai/normal/ai_normal.cpp [hunk 3]
```diff
@@ -68,17 +70,54 @@ namespace AI
...
+                assert( resMineIncome > 0 );
+                if ( resMineIncome <= 0 ) {
+                    return;
+                }
+
+                result[res] = goldMineIncome / resMineIncome;
+            } );
+
+            return result;
+        }();
```
Comment (Districh-ru) [inline src/fheroes2/ai/normal/ai_normal.cpp:96]: I noticed that AI now is not so interested in Gold and Treasure chests and sometimes passes them.
But Gold is needed to buy units and build the castle. (And you are mostly short of gold.)

Talking about resources on map: the amount of Wood and Ore resources may be around 5-10, Mercury, Crystal, Sulfur, Gems: around 2-5, while Gold amount is around 600-1000.
So maybe we need to multiply the Gold Priority by 2-3.

<details><summary>Resource values log</summary>

```
Resource: Wood, amount: 7, value = 3500
Resource: Ore, amount: 7, value = 3500
Resource: Sulfur, amount: 5, value = 5000
Resource: Mercury, amount: 3, value = 3000
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Sulfur, amount: 5, value = 5000
Resource: Wood, amount: 7, value = 3500
Resource: Ore, amount: 7, value = 3500
Resource: Mercury, amount: 3, value = 3000
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Sulfur, amount: 5, value = 5000
Resource: Wood, amount: 7, value = 3500
Resource: Ore, amount: 7, value = 3500
Resource: Mercury, amount: 3, value = 3000
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Mercury, amount: 3, value = 3000
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gems, amount: 3, value = 3000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Crystal, amount: 6, value = 6000
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gems, amount: 3, value = 3000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 7, value = 3500
Resource: Sulfur, amount: 3, value = 3000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Mine resource: Wood, amount: 2, value = 2000
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 7, value = 3500
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Mine resource: Wood, amount: 2, value = 2000
Resource: Wood, amount: 6, value = 3000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Mine resource: Wood, amount: 2, value = 2000
Resource: Gold, amount: 1000, value = 1000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 5, value = 2500
Mine resource: Wood, amount: 2, value = 2000
Treasure gold amount: 1000, value = 1000
Resource: Gold, amount: 800, value = 800
Resource: Wood, amount: 6, value = 3000
Resource: Wood, amount: 8, value = 4000
Treasure gold amount: 1000, value = 1000
Resource: Gold, amount: 800, value = 800
Resource: Wood, amount: 6, value = 3000
Resource: Gold, amount: 700, value = 700
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 6, value = 3000
Treasure gold amount: 1000, value = 1000
Resource: Gold, amount: 800, value = 800
Resource: Gold, amount: 700, value = 700
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 6, value = 3000
Treasure gold amount: 1000, value = 1000
Resource: Gold, amount: 800, value = 800
Resource: Gold, amount: 700, value = 700
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 900, value = 900
Resource: Ore, amount: 6, value = 3000
Treasure gold amount: 1000, value = 1000
Resource: Gold, amount: 800, value = 800
Resource: Gold, amount: 700, value = 700
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 900, value = 900
Treasure gold amount: 2000, value = 2000
Resource: Wood, amount: 6, value = 3000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Gold, amount: 500, value = 500
Resource: Sulfur, amount: 3, value = 3000
Resource: Ore, amount: 7, value = 3500
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 600, value = 600
Resource: Wood, amount: 7, value = 3500
Resource: Gold, amount: 500, value = 500
Resource: Sulfur, amount: 3, value = 3000
Resource: Ore, amount: 7, value = 3500
Treasure gold amount: 1000, value = 1000
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 600, value = 600
Resource: Gold, amount: 500, value = 500
Resource: Sulfur, amount: 3, value = 3000
Resource: Ore, amount: 7, value = 3500
Treasure gold amount: 1000, value = 1000
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 600, value = 600
Resource: Gold, amount: 500, value = 500
Resource: Sulfur, amount: 3, value = 3000
Treasure gold amount: 1000, value = 1000
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 600, value = 600
Resource: Gold, amount: 500, value = 500
Treasure gold amount: 1000, value = 1000
Treasure gold amount: 2000, value = 2000
Resource: Gold, amount: 600, value = 600
Resource: Gold, amount: 500, value = 500

```
</summary>

File: src/fheroes2/ai/normal/ai_normal_hero.cpp [hunk 4]
```diff
@@ -885,16 +887,29 @@ namespace AI
...
+                }
+
+                std::tie( resourceType, resourceAmount ) = getDailyIncomeObjectResources( tile ).getFirstValidResource();
+            }
+
+            assert( resourceType != Resource::UNKNOWN && resourceAmount != 0 );
+
+            // Since mines constantly bring resources, they are valuable objects. Let's evaluate them in proportion to the amount of resources they
+            // bring in 2 days (they should be more valuable than chests or resource piles, but less valuable in general than castles or heroes).
+            return resourceAmount * getResourcePriorityModifier( resourceType ) * 2;
```
Comment (Districh-ru) [inline src/fheroes2/ai/normal/ai_normal_hero.cpp:912]: Talking about mines: Should they be less valuable than single resources...?
Currently they are 1.5-2 times less valuable than single resources. IMHO if resource is located near a mine it is better to capture the mine today and a resource - tomorrow (so the mine will give you resources for this day and a single resource will wait for the next day unchanged).
So maybe it'll be better to revert multiplier to 3. Or make the single resources less valuable.

**Review by Districh-ru — COMMENTED** [review]
Hi, @oleg-derevenetz. I'm new to AI logic and don't fully know its specifics.
I left two suggestions after watching the actions of the AI hero.
Could you take a look when you have time.

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Sorry)

**Comment by oleg-derevenetz** [comment]
Hi @Districh-ru I tuned the resource priorities a bit by using different priority coefficients for resources from mines and resources from piles (campfires and so on). Please take a look when you have time.

**Review by Districh-ru — APPROVED** [review]
Great work, @oleg-derevenetz!
I tested AI behavior on "Great War II" map and now if AI is standing in front of a mine and resource piles it first captures a mine and on the next day - the resources. I like this behavior.
AI now does not pass by a Gold or a Treasure Chest.
Also I noticed that IA prefers fighting an enemy to capturing a nearby mine/resource.

<details><summary>Also now if Gold is required to the kingdom its value is slightly above other resources.</summary>

```
Mine: Gems, value: 2000
Resource: Sulfur, amount: 5 value: 2500
Resource: Crystal, amount: 6 value: 1500
Resource: Gems, amount: 6 value: 1500
Resource: Gems, amount: 6 value: 1500
Resource: Gold, amount: 900 value: 1800 <<-- AI needs gold, so its value is 1800, not 900 and it is higher then Gems in previous line
Resource: Gold, amount: 600 value: 1200
Resource: Crystal, amount: 3 value: 750
Resource: Sulfur, amount: 5 value: 2500
Resource: Crystal, amount: 6 value: 1500
Resource: Gems, amount: 6 value: 1500
Treasure chest with Gold, value: 3000
Resource: Gold, amount: 600 value: 1200
Resource: Crystal, amount: 3 value: 750
```

</details>

**Comment by oleg-derevenetz** [comment]
@Districh-ru

> Also now if Gold is required to the kingdom the Gold pile value is slightly above other resources.

Not just gold:

```
Resource: Gold, amount: 600 value: 1200
[...]
Resource: Sulfur, amount: 5 value: 2500
```

Sulfur is marked as a priority resource in this kingdom's budget as well, probably because it needed to build another building in a castle, so it get the priority modifier x2 and value is 2500 instead of 1250 (5 * 250) by default.

**Comment by Districh-ru** [comment]
> Sulfur is marked as a priority resource in this kingdom's budget as well, probably because it needed to build another building in a castle, so it get the priority modifier x2 and value is 2500 instead of 1250 (5 * 250) by default.

@oleg-derevenetz,
Yes, I noticed it. I wrote about Gold because before the last commit it had a low value, even if it was a priority for the kingdom.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for these enhancements!
