### PR TITLE
Display detailed information about the composition of alliances in the scenario info window

### LINKED ISSUE #5793: Alliances are not properly described in Scenario information window
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Instead of displaying something like `You and your allies One, Two, Three must defeat the enemy alliance of Forth and Five.` we display a simple `Your side defeats the opposing side.` which is not descriptive as it is in the original game. We shall fix it.

### Save file

Use any alliance based map to verify this.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5793

The wording was deliberately changed to look better with different composition of alliances.

Screenshot 2022-10-06 в 01 47 08

Screenshot 2022-10-06 в 01 50 46

Screenshot 2022-10-06 в 01 48 00

Screenshot 2022-10-06 в 01 48 33

### CODE REVIEW

File: src/fheroes2/game/game_over.cpp [hunk 1]
```diff
@@ -194,8 +198,49 @@ std::string GameOver::GetActualDescription( uint32_t cond )
...
+
+        assert( enemiesCount > 0 );
+
+        if ( alliesCount == 0 ) {
+            msg = Translation::ngettext( "You must defeat the enemy %{enemies}.", "You must defeat the enemy alliance of %{enemies}.", enemiesCount );
+            StringReplace( msg, "%{enemies}", enemiesList );
+        }
+        else {
+            msg = Translation::ngettext( "You and %{allies}, who is in alliance with you, must defeat the enemy %{enemies}.",
+                                         "You and %{allies}, who is in alliance with you, must defeat the enemy alliance of %{enemies}.", enemiesCount );
```
[the remark this answers is not in the document]
Comment (zenseii) [reply src/fheroes2/game/game_over.cpp:239]: Hi @oleg-derevenetz.

How about
"Your alliance, consisting of you, Red [...], must defeat [...]".

This solves the problem of is/are.

Not sure how to solve the fact that "and" should be placed between the second last and last component of that listing of allies. This wouldn't be the only place in the code where that happens so it's not too big of a deal.

[the remark this answers is not in the document]
Comment (oleg-derevenetz) [reply src/fheroes2/game/game_over.cpp:239]: Hi @zenseii Well maybe, but "your alliance consisting of you"? :) Maybe just "Alliance consisting of you, ..."?

[the remark this answers is not in the document]
Comment (zenseii) [reply src/fheroes2/game/game_over.cpp:239]: > Hi @zenseii Well maybe, but "your alliance consisting of you"? :) Maybe just "Alliance consisting of you, ..."?

Yes, that's better. Just add a "The" before "alliance".

**Review by zenseii — APPROVED** [review]

**Review by zenseii — APPROVED** [review]
This was a clever solution to it.

File: src/fheroes2/game/game_over.cpp [hunk 2]
```diff
@@ -21,26 +21,30 @@
  *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
  ***************************************************************************/
 
-#include "game_over.h"
+#include <cassert>
+#include <cstddef>
+#include <utility>
```
Comment (ihhub) [inline src/fheroes2/game/game_over.cpp:26]: We do not need these headers to be included.

File: src/fheroes2/game/game_over.cpp [hunk 3]
```diff
@@ -194,8 +198,49 @@ std::string GameOver::GetActualDescription( uint32_t cond )
...
+        const int friendColors = currentPlayer->GetFriends();
+
+        auto makeListOfPlayers = []( const int colors ) {
+            std::pair<std::string, size_t> result{ {}, 0 };
+
+            for ( const int col : Colors( colors ) ) {
+                const Player * player = Players::Get( col );
+                assert( player != nullptr );
+
+                if ( ++result.second > 1 ) {
```
Comment (ihhub) [inline src/fheroes2/game/game_over.cpp:218]: Please make variable increment on a separate line.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I left 2 small remarks. Could you please take a look at them?

File: src/fheroes2/game/game_over.cpp (hunk 2 above)
Comment (oleg-derevenetz) [reply src/fheroes2/game/game_over.cpp:26]: Hi @ihhub `<utility>`is for `std::pair`, `cstddef` is for `size_t`. I prefer to not rely on another modules' headers :)

Comment (ihhub) [reply src/fheroes2/game/game_over.cpp:26]: This is strange since Visual Studio allow to compile but I'm not surprised.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , a huge thanks for this fix!
