### PR TITLE
Set the space width as a maximum word width if the text contains only spaces

### LINKED ISSUE #8871: Map editor, crash while creating a message with space and a new line
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

A crash occurs when trying to type "space"+"Enter"(new line)+confirm in the event text field:
image

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Close #8871

### CODE REVIEW

File: src/fheroes2/gui/ui_text.cpp [hunk 1]
```diff
@@ -445,10 +445,11 @@ namespace
     {
         assert( data != nullptr && size > 0 );
 
-        int32_t maxWidth = 1;
-
         const fheroes2::FontCharHandler charHandler( fontType );
 
+        // There might be multi-line text strings that contains only space characters
```
Comment (ihhub) [inline src/fheroes2/gui/ui_text.cpp:450]: How about this solution:
```cpp
        while ( data != dataEnd ) {
            if ( isSpaceChar( *data ) ) {
                // If it is a space (" "), then the word has ended.
                if ( width == 0 ) {
                    // No words exist on this till now. Let's put maximum width as space width.
                    width += charHandler.getWidth( *data );
                }

                if ( maxWidth < width ) {
                    maxWidth = width;
                }

                width = 0;
            }
            else if ( isLineSeparator( *data ) ) {
                // If it is the end of line ("\n"), then the word has ended.
                if ( maxWidth < width ) {
                    maxWidth = width;
                }

                width = 0;
            }
            else {
                width += charHandler.getWidth( *data );
            }

            ++data;
        }
```

Comment (Districh-ru) [reply src/fheroes2/gui/ui_text.cpp]: Sure, your solution looks better.
I just simplified it to reduce duplications.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , a bunch of thanks for this fix!
