### PR TITLE
Fix invalid Stone Liths after AI threat estimation

### LINKED ISSUE #7387: Some "Stone Liths" don't work on last git version
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Some "Stone Liths" don't work on last git version

### Save file

 [saves](url https://disk.yandex.ru/d/kVVtFvq2vKaDQw)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7387

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_kingdom.cpp [hunk 1]
```diff
@@ -92,17 +92,30 @@ namespace
         TemporaryHeroEraser( TemporaryHeroEraser && ) = delete;
 
         explicit TemporaryHeroEraser( const std::vector<Heroes *> & heroes )
-            : _heroes( heroes )
         {
-            for ( const Heroes * hero : _heroes ) {
-                world.GetTiles( hero->GetIndex() ).SetHeroes( nullptr );
+            for ( Heroes * hero : heroes ) {
+                assert( !hero->isFreeman() );
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_kingdom.cpp:97]:
```suggestion
                assert( hero != nullptr && !hero->isFreeman() );
```

**Review by oleg-derevenetz — APPROVED** [review]
Hi @ihhub I just left one optional suggestion, LGTM otherwise.

File: src/fheroes2/ai/normal/ai_normal_kingdom.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/ai/normal/ai_normal_kingdom.cpp]: Fixed.
