### PR TITLE
Fix the AI resurrect spell logic

### LINKED ISSUE #6492: Combat screen, AI fails to cast Resurrect spell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

It was really hard to catch and reproduce the bug.
Here's a guide to reproduce the bug. I recommend to repeat all steps, since depending on hero stats and creatures  the result may vary.

https://user-images.githubusercontent.com/55348946/212499987-bdf1c635-1159-4e37-9346-ad0a3b47caee.mp4

https://user-images.githubusercontent.com/55348946/212499994-9cf9715f-a918-4fdc-8d05-268d66ce3ce3.mp4

It was really hard to catch and reproduce the bug. Sorry for such long video.

AI it strying to use Resurrect spell but nothing happens.

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #6492

### CODE REVIEW

File: src/fheroes2/ai/normal/ai_normal_spell.cpp [hunk 1]
```diff
@@ -528,6 +518,33 @@ namespace AI
...
+            if ( !unit->AllowApplySpell( spell, _commander ) ) {
+                continue;
+            }
+
+            updateBestOutcome( unit );
+        }
+
+        // Then consider the stacks from the graveyard
+        for ( const int32_t idx : arena.GraveyardOccupiedCells() ) {
+            const Unit * unit = arena.GraveyardLastTroop( idx );
```
Comment (ihhub) [inline src/fheroes2/ai/normal/ai_normal_spell.cpp:540]: Should we allow to resurrect any unit on a cell, not only the last one?

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left just one question. Could you please take a look at it?

File: src/fheroes2/ai/normal/ai_normal_spell.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/ai/normal/ai_normal_spell.cpp:540]: Hi @ihhub then behavior will be different from the behavior that is allowed for a human player, because human player is allowed to resurrect only the topmost unit, right?

Comment (ihhub) [reply src/fheroes2/ai/normal/ai_normal_spell.cpp:540]: You're correct. Let's leave it as it is.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , great thanks for this fix!
