### PR TITLE
Fix starting unit values

### LINKED ISSUE #1265: Hero's default creatures
In fheroes2, at the start of the scenario, it happens that the hero has only gargoyles in his army.
In the original game, this never happens.
In the original game, either the hero has one level 1 troop and one level 2 troop, or the hero has one level 1 troop only, but never has one level 2 troop only.

Hero's default creatures 01

### LINKED ISSUE #1693: Hero, number of creatures present in the hero's army when the hero is recruited
In fheroes2, there are more creatures in the hero's army when the hero is recruited than in the original game.
Except for the Peasants. :)

In original game:

Hero screen H2 10

In fheroes2:

Hero screen fh2 10

In original game:

Hero screen H2 11

In fheroes2:

Hero screen fh2 11

In original game:

Hero screen H2 12

In fheroes2:

Hero screen fh2 12

In original game:

Hero screen H2 13

In fheroes2:

Hero screen fh2 13

In original game:

Hero screen H2 14

In fheroes2:

Hero screen fh2 14

In original game:

Hero screen H2 15

In fheroes2:

Hero screen fh2 15

### PR DESCRIPTION
**Pull request by bleakley**
Fixes #1693
Fixes #1265

I generated a lot of starting heroes in the original game and I think I've determined the starting unit quantity formula.

You get 0.8 to 1.2 times the growth rate for tier one units, and 0.4 to 0.6 times the growth rate for tier two units. 10% of the time you get no tier two units. Peasants are an exception, you get an additional +30 modifier to the starting number of peasants.

### CODE REVIEW

File: src/fheroes2/army/army.cpp [hunk 1]
```diff
@@ -1290,17 +1290,17 @@ void Army::Reset( bool soft )
...
-                break;
-            case 2:
-                JoinTroop( mons2, mons2.GetGrown() + mons2.GetGrown() / 2 );
-                break;
-            default:
-                JoinTroop( mons1, 2 * mons1.GetGrown() );
-                JoinTroop( mons2, mons2.GetGrown() );
-                break;
+            int mons1Count = round( mons1.GetGrown() * Rand::Get( 8, 12 ) * 0.1 );
+            int mons2Count = round( mons2.GetGrown() * Rand::Get( 4, 6 ) * 0.1 );
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1294]: Please move this variable inside the second if-body so we don't waste CPU cycles for cases of no second tier unit.

Comment (ihhub) [reply src/fheroes2/army/army.cpp:1294]: Also please make this variable `const`. We don't change it.

File: src/fheroes2/army/army.cpp [hunk 2]
```diff
@@ -1290,17 +1290,17 @@ void Army::Reset( bool soft )
...
-                JoinTroop( mons1, 3 * mons1.GetGrown() );
-                break;
-            case 2:
-                JoinTroop( mons2, mons2.GetGrown() + mons2.GetGrown() / 2 );
-                break;
-            default:
-                JoinTroop( mons1, 2 * mons1.GetGrown() );
-                JoinTroop( mons2, mons2.GetGrown() );
-                break;
+            int mons1Count = round( mons1.GetGrown() * Rand::Get( 8, 12 ) * 0.1 );
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1293]: Instead of using `round` and multiplication by double why don't we just divide the value by 10?
If we want to have a rounding expression we can do like this:
```
( mons1.GetGrown() * Rand::Get( 8, 12 ) + mons1.GetGrown() / 2 ) / 10
```
so then we don't use any floating point calculations. Also round returns double value for some compilers so we should not introduce extra compilation warnings.

Comment (ihhub) [reply src/fheroes2/army/army.cpp:1293]: To fix this problem we can increase random range to `Range::Get( 80, 120 );` and then divide by 100 having the same precision of calculations.

File: src/fheroes2/army/army.cpp [hunk 3]
```diff
@@ -1290,17 +1290,17 @@ void Army::Reset( bool soft )
...
+            int mons2Count = round( mons2.GetGrown() * Rand::Get( 4, 6 ) * 0.1 );
+
+            if ( mons1.GetID() == Monster::PEASANT ) {
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1296]: Let's just put a comment here stating that Peasants are special otherwise other developer might think that this is a bug.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @bleakley, I left multiple comments here. Could you please take a look?

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, do you know the exact formula for this?

**Comment by idshibanov** [comment]
> 
> 
> Hi @LeHerosInconnu, do you know the exact formula for this?

Level 1:
30-50 Peasants
15-25 Goblins
10-20 Sprites
6-10 Centaurs, Halflings and Skeletons

Level 2:
3-5 Archers or Orcs
2-4 for the rest of them

**Comment by ihhub** [comment]
Hi @bleakley could you please then adjust the code based on give @idshibanov information?

File: src/fheroes2/army/army.cpp [hunk 4]
```diff
@@ -1290,18 +1290,32 @@ void Army::Reset( bool soft )
...
+                JoinTroop( mons1, Rand::Get( 10, 20 ) );
                 break;
             default:
-                JoinTroop( mons1, 2 * mons1.GetGrown() );
-                JoinTroop( mons2, mons2.GetGrown() );
+                JoinTroop( mons1, Rand::Get( 6, 10 ) );
                 break;
             }
+
+            if ( Rand::Get( 1, 10 ) != 1 ) {
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1308]: I think we should have an opposite logic. Right now it's 90% chance of triggering this condition.

Comment (bleakley) [reply src/fheroes2/army/army.cpp:1308]: I think it is correct. I generated 50 heroes in the original game and was only missing a level 2 unit 5 times.

**Comment by ihhub** [comment]
@bleakley thank you very much for your contribution to the project!
