### PR TITLE
Make default knowledge value for random hero as 1

### LINKED ISSUE #8750: [Scenario Editor] The default Knowledge value should be "1", not "0"
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the default Knowledge value should be "1", not "0".

In fheroes2:

Default knowkedge value 1 01

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
Also, limit minimum knowledge value to 1 rather than 0.

close #8750

### CODE REVIEW

File: src/fheroes2/heroes/skill.h [hunk 1]
```diff
@@ -203,10 +202,10 @@ namespace Skill
...
         friend StreamBase & operator>>( StreamBase &, Primary & );
 
-        int attack;
-        int defense;
-        int power;
-        int knowledge;
+        int attack{ 0 };
+        int defense{ 0 };
+        int power{ 0 };
+        int knowledge{ 0 };
```
Comment (Districh-ru) [inline src/fheroes2/heroes/skill.h:208]: Should we also set `1` as the default value for power and knowledge skills then?

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub.
In this PR we only clamp the "modified" knowledge value, but the base `knowledge` can still be 0.
We should not allow to enter a value lower than 1 for knowledge in hero edit dialog and in battle only dialog.


https://github.com/ihhub/fheroes2/assets/113276641/3b76f6c2-ee2a-4741-8bd2-8d6c11884520

**Review by Branikolog — APPROVED** [review]
Fix works as intended. I'm not sure, whether it should be possible to set knowledge to zero... Maybe, mapmakers would like to make a hero without spell points though.
Att and Def are ok to be 0 as default since many magic heroes have zero values from start

**Review by Districh-ru — APPROVED** [review]
