### PR TITLE
Mute sound by setting music & effects volume to zero instead of pausing them

### LINKED ISSUE #3113: [SDL2] game freeze when window focus is lost while battle begins
The game becomes completely unresponsive and has to be killed manually. v0.9.2

To reproduce:
- take the ubuntu SDL2 port, start it in window mode
- begin any fight (does not matter if creature or opponent hero)
- while the music plays, just select any other window on your desktop
- as soon as you switch back to the game, it's frozen

### LINKED ISSUE #3240: Combat, sometimes the combat music is not played (fheroes2 0.9.2 3231)
In fheroes2, sometimes the combat music is not played.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115619742-91657f00-a2f4-11eb-8070-b816d642ce93.mp4

Wrathmont attacks Dragontooth.

Here is the save file:
[Before attack defense freeze.zip](https://github.com/ihhub/fheroes2/files/6353760/Before.attack.defense.freeze.zip)

**Edit.**

This issue may be related: https://github.com/ihhub/fheroes2/issues/3244.

### LINKED ISSUE #3244: Adventure map, ambient sounds are not played when the game window returns to "foreground" after the window has been "in background" (sound and music cut off)
In fheroes2, ambient sounds are not played when the game window returns to "foreground" after the window has been "in background" (sound and music cut off).
It is necessary to select another hero (or perform another action) and reselect the hero for the ambient sounds to be played again.

In fheroes2:
Activate the sound of the video.

https://user-images.githubusercontent.com/43583994/115625825-ead1ac00-a2fc-11eb-9df6-95aa91d8de73.mp4

Here is the save file:
[Before Troll Bridge without troll.zip](https://github.com/ihhub/fheroes2/files/6354152/Before.Troll.Bridge.without.troll.zip)

### LINKED ISSUE #3415: Program freezes after switching from background to foreground after a combat is initiated (0.9.3 3370)
Sometimes it happens that the program freezes after switching from background to foreground after a combat is initiated.
In this case there is no other possibility than to terminate the program and restart it.

I haven't found the procedure to reproduce this bug.

In fheroes2:

Program freeze 01

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #3113
fix #3240
fix #3244
fix #3415

After some investigation, I found that _sometimes_ `Mixer::isPaused()` here:

https://github.com/ihhub/fheroes2/blob/94ceef01ddb7cace7e11873e412e9ad9990ccf7b/src/engine/localevent.cpp#L1258

doesn't return 0, and therefore channels are not resumed here:

https://github.com/ihhub/fheroes2/blob/94ceef01ddb7cace7e11873e412e9ad9990ccf7b/src/engine/localevent.cpp#L1272

which leads to freeze when game waits for a particular sound to finish (for example, in the beginning of a battle). Needs to be tested on Windows and Linux as well.

@ihhub BTW it seems that build with WITHOUT_MIXER is broken long ago. Does it make sense to support WITHOUT_MIXER mode?

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @oleg-derevenetz , in my view we should remove all these compilation switches as a many as possible. I've never tested a build with `WITHOUT_MIXER` flag. Interesting to see what will it give to us...

File: src/engine/audio_mixer.cpp [hunk 1]
```diff
@@ -93,6 +93,11 @@ void Mixer::Quit( void )
     }
 }
 
+uint8_t Mixer::GetChannels()
+{
+    return Mix_AllocateChannels( -1 );
```
Comment (ihhub) [inline src/engine/audio_mixer.cpp:98]: `Mix_AllocateChannels` returns **int**. Could you please update the return value?

File: src/engine/audio_mixer.cpp [hunk 2]
```diff
@@ -319,6 +324,11 @@ void Mixer::Quit( void )
     }
 }
 
+uint8_t Mixer::GetChannels()
+{
+    return chunks.size();
```
Comment (ihhub) [inline src/engine/audio_mixer.cpp:329]: Since we're doing static_cast and `size()` returns **size_t** would it be more rational to return **size_t** from this method as well?

File: src/engine/localevent.cpp [hunk 3]
```diff
@@ -1242,23 +1242,31 @@ bool LocalEvent::HandleEvents( bool delay, bool allowExit )
...
-    _isSoundPaused = ( Mixer::isPaused( -1 ) != 0 );
-    Mixer::Pause();
-    Music::Pause();
     _musicVolume = Music::Volume( 0 );
+
+    const size_t channelsCount = static_cast<size_t>( Mixer::GetChannels() );
+
+    _soundVolumes.resize( channelsCount );
+
+    for ( size_t channel = 0; channel < channelsCount; channel++ ) {
```
Comment (ihhub) [inline src/engine/localevent.cpp:1251]: Please use prefix form of increment.

File: src/engine/localevent.cpp [hunk 4]
```diff
@@ -1242,23 +1242,31 @@ bool LocalEvent::HandleEvents( bool delay, bool allowExit )
...
     if ( _isHiddenWindow ) {
+        _isHiddenWindow = false;
+
         Music::Volume( _musicVolume );
-        if ( !_isMusicPaused ) {
-            Music::Resume();
+
+        const size_t channelsCount = std::min( static_cast<size_t>( Mixer::GetChannels() ), _soundVolumes.size() );
+
+        for ( size_t channel = 0; channel < channelsCount; channel++ ) {
```
Comment (ihhub) [inline src/engine/localevent.cpp:1267]: Please use prefix form of increment.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I left few comments in this pull request. Could you please take a look?

**Comment by oleg-derevenetz** [comment]
@ihhub

> in my view we should remove all these compilation switches as a many as possible

I plan to move mute/unmute code from localevent to mixer/music to properly handle situations when, for example, player starts hero teleportation and then switches to another window, so I want to remove obviously dead WITHOUT_MIXER code first. I'll do it in this PR then.

**Comment by oleg-derevenetz** [comment]
Review from @winterheart will be highly appreciated, because I'm not CMake expert, may be some changes could have been done in a more graceful way.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub It's also interesting how this will work on Windows, because on Windows there is AFAIK "one volume to rule them all". Could you please check this on Windows when you'll have the desire and opportunity?

**Comment by winterheart** [comment]
Hi. Everything fine with CMake changes, no issues found.

**Comment by oleg-derevenetz** [comment]
Hi @winterheart 

> Everything fine with CMake changes, no issues found.

Thank you!

**Comment by ihhub** [comment]
Hi @Northfear , could you please test these changes on PS Vita? Just verify that sounds and music are present even when you switch to the main screen and come back.

**Comment by oleg-derevenetz** [comment]
Hi @ihhub BTW I'm going to remove optional parameter from Mixer::isPlaying() (to check channel volume first) later in separate PR, because it seems that it is not used anywhere.

**Comment by ihhub** [comment]
> Hi @ihhub BTW I'm going to remove optional parameter from Mixer::isPlaying() (to check channel volume first) later in separate PR, because it seems that it is not needed anywhere.

Sure!

**Comment by Northfear** [comment]
> Hi @Northfear , could you please test these changes on PS Vita? Just verify that sounds and music are present even when you switch to the main screen and come back.

Done. Everything seems to be working fine

**Comment by ihhub** [comment]
Music volume on Windows still effects sound volume as before. "one volume to rule them all" is still present :)

File: src/engine/audio_mixer.cpp [hunk 5]
```diff
@@ -33,16 +34,18 @@ namespace Mixer
 {
     void Init( void );
     void Quit( void );
+
     bool valid = false;
+
+    bool muted = false;
+    std::vector<int> savedVolumes;
```
Comment (ihhub) [inline src/engine/audio_mixer.cpp:41]: Could we please move these variables under a single structure and then have just one instance of it in anonymous namespace? First of all, we shouldn't pollute this namespace as these variables are used only in this file. Secondly, SonarQube would complain about so many static variables but having only on structure instance will make the code smell number smaller.

File: src/engine/audio_music.cpp [hunk 6]
```diff
@@ -30,16 +30,19 @@
...
 {
     void Play( Mix_Music * mix, /*u32 id,*/ bool loop );
 
     Mix_Music * music = NULL;
+
     int fadein = 0;
     int fadeout = 0;
+
+    bool muted = false;
+    int savedVolume = 0;
```
Comment (ihhub) [inline src/engine/audio_music.cpp:45]: Could we please move these variables under a single structure and then have just one instance of it in anonymous namespace? First of all, we shouldn't pollute this namespace as these variables are used only in this file. Secondly, SonarQube would complain about so many static variables but having only on structure instance will make the code smell number smaller.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I commented just at 2 places. Could you please take a look? The rest of the code looks good.

File: src/engine/audio_music.cpp (hunk 6 above)
Comment (oleg-derevenetz) [reply src/engine/audio_music.cpp:45]: Hi @ihhub May be I just put them into the anonymous namespace? I agree that there is no point to put them into Music namespace if they are used just in this file, but putting them in single structure might be justified if, for example, they both returned from some function or something like that, but doing this just for pleasing SonarQube... It will complain about this structure anyway, and there will be no gain in any aspect (CPU or RAM consumption) :)

Comment (ihhub) [reply src/engine/audio_music.cpp:45]: Sure. Let's put to anonymous namespace at least.

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for fixing these big issues!
