### PR TITLE
Fix rendering flaws of battle journal when using scroll bar

### LINKED ISSUE #8460: Combat screen, rendering flaws of battle journal scroll bar
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

There's a rendering issue while dragging scroll bar in batte journal.

https://github.com/ihhub/fheroes2/assets/55348946/f085e55e-6861-463f-83a3-28449d4a5acd

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #8460 
This PR does `listlog` redraw and render it on the screen when it is needed.

### CODE REVIEW

**Review by ihhub — APPROVED** [review]

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -2796,9 +2800,17 @@ void Battle::Interface::HumanBattleTurn( const Unit & unit, Actions & actions, s
...
+
+    fheroes2::Rect lislogRect;
+    const bool isListlogOpen = listlog && listlog->isOpenLog();
+
+    if ( isListlogOpen ) {
+        lislogRect = listlog->GetArea();
+        battleFieldRect.height -= lislogRect.height;
+    }
+
+    if ( isListlogOpen && ( le.MouseCursor( lislogRect ) || le.MousePressLeft( lislogRect ) ) ) {
```
Comment (dood-apo) [inline src/fheroes2/battle/battle_interface.cpp:2813]: Is this a refactor? I can't spot any functional change in this part.
If the idea was to fix the missing check for `listlog` existence in line 2799, then why not do only this:
```
const int32_t battleFieldHeight = _interfacePosition.height - status.height - ( ( listlog && listlog->isOpenLog() ) ? listlog->GetArea().height : 0 );
```
?

Comment (Districh-ru) [reply src/fheroes2/battle/battle_interface.cpp:2813]: Hi @dood-apo, yes, it is a refactor. Initially I made the fix here, but later moved it to a better place and leaved the changes made here.
Yes, the first one thing it to add a check for `listlog` ( `!= nullptr` ).
And the second - is to avoid three `listlog->GetArea()` calls if listlog is opened: we now cache it to `lislogRect`.

Comment (dood-apo) [reply src/fheroes2/battle/battle_interface.cpp:2813]: Is it better though? That caching adds a substantial amount of code, when `listlog->GetArea()` is just a plain getter.
Also the flow is not atomic now, since `lislogRect` is initialized to zeros and populated with `listlog->GetArea()` only within a conditional. What do you think?

Comment (Districh-ru) [reply src/fheroes2/battle/battle_interface.cpp]: @dood-apo, thanks for the suggestion!
Now `lislogRect` is a const reference and will be initialized only if battle log is opened.

**Comment by ihhub** [comment]
@Districh-ru , a bunch of thanks for this fix!
