### PR TITLE
Death Wave spell animation fix (Battlefield)

### LINKED ISSUE #1041: "Holy Word" and "Holy Shout" spells should have darkening in a middle phase of animation
While using these spells screen darkens a bit in the middle of animation. (Or, probably, increasing contrast?)
Holy shout
While our version has none:

Holy shout2

### LINKED ISSUE #5701: Combat screen, Death Wave spell animation, differences from the original game
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, there are differences from the original game for Death Wave spell animation,
Note: I haven't tested with Death Ripple, but it's certainly the same.

In the original game, the damage animation (red sprites) is played at the same time as the animation of the creature taking damage.

In fheroes2, the damage animation is done first and then the animation of the creatures that take damage.

In original game:

https://user-images.githubusercontent.com/43583994/180996575-0759e2e7-e78d-43e3-9738-d82204c57dbc.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/180996628-791c53a0-ea80-4141-92c8-de84ff894b55.mp4

https://user-images.githubusercontent.com/43583994/180996843-6838d397-ed7e-41e0-a370-f368096c535a.mp4

In fheroes2, the animation of the damage (red sprites) is not at the same position and is reversed horizontally.
In fheroes2, the animation of the troll taking damage is less pronounced  (the posture of the troll is not as inclined) than in Heroes 2.

In original game:

https://user-images.githubusercontent.com/43583994/180997160-67d770f0-1ae3-4f89-bd92-03d9a6142d01.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/180997127-365f0054-619f-428b-8196-36517456de22.mp4

In original game:
vlcsnap-2022-07-26-13h12m30s667

In fheroes2:
Damage red sprites reversed horizontally.
vlcsnap-2022-07-26-13h12m23s766

In original game:
vlcsnap-2022-07-26-13h11m05s545

In fheroes2:
Red sprites position.
vlcsnap-2022-07-26-13h09m59s257

In original game:
vlcsnap-2022-07-26-13h10m36s831

In fheroes2:
The posture of the troll is not as inclined.
vlcsnap-2022-07-26-13h09m47s883
vlcsnap-2022-07-26-13h10m17s731

The wave effect that runs across the screen is also much less pronounced in the original game.
In fheroes2, the artwork of the battlefield is completely distorted, which is not very aesthetic.

In original game:
vlcsnap-2022-07-26-14h05m16s077

In fheroes2:
vlcsnap-2022-07-26-14h05m22s623

### Save file

Here is the test scenario file:
[0 9928.zip](https://github.com/ihhub/fheroes2/files/9189078/0.9928.zip)

### Additional info

Version 0.9.17 5674

### LINKED ISSUE #5710: Mac installation but GOG only offers Windows HoMM2 install?
### Your question

Hello, 
I was able to install `fheroes2` on my M1 macbook pro via `homebrew` without a problem. My next step is to get the original HoMM2 game installed. The documentation recommends I install the [GOG game version](https://www.gog.com/game/heroes_of_might_and_magic_2_gold_edition) but it is only installable on Windows. How does this work? Thank you!

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Close #5701 and close #1041.
Relates to #1229.

Redone the animation sequence for Death Wave, Death Ripple, Holy Word and Holy Shout shout.
Now the flame animation (after the spell animation) is made only after applying damage from the spell. And during this flame animation the death animation and the wince animation is applied to the corresponding creatures.
To do this I had to make a copy of part of the code from `RedrawActionWincesKills` method. :(
To reduce the size of this duplication a new (small) method was made.

fheroes2 Death Death Ripple and Death Wave animations:

https://user-images.githubusercontent.com/113276641/206888610-90a2e068-487d-49cc-9e8a-469f80a587c5.mp4

Original game Death Ripple and Death Wave animations:

https://user-images.githubusercontent.com/113276641/206887219-44e3a4c3-8a93-4f9e-b54c-9c91eb0d64a4.mp4

<details><summary>fheroes2 Holy Word and Holy Shout animation:</summary>

https://user-images.githubusercontent.com/113276641/207246675-ed7064b1-1e7a-4606-82ae-378b12baf6a2.mp4

https://user-images.githubusercontent.com/113276641/207246687-81fa1b97-fc39-40ce-99d9-09cfb551d7ad.mp4

</details>

<details><summary>Original game Holy Word and Holy Shout animation:</summary>

https://user-images.githubusercontent.com/113276641/207246918-7dad4d13-04c6-4487-916b-559976be864d.mp4

https://user-images.githubusercontent.com/113276641/207246934-e32ef987-9709-4a4a-b963-47db28756617.mp4

</details>

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
> close https://github.com/ihhub/fheroes2/issues/5710

#5701 :)

**Comment by Districh-ru** [comment]
Hello, everyone.
After opening this PR I noticed that after the creatures death the flame animation shifts down. It is because the spell position is calculated for every frame based on creatures sprite. I'll try to fix this tomorrow.

**Comment by Districh-ru** [comment]
> > close #5710
> 
> #5701 :)

Hi, @oleg-derevenetz.  thanks for finding the typo. :)

**Comment by Districh-ru** [comment]
> I think, Death Wave (level 3) should have larger and faster wave effect than smaller Death Ripple(level 2) spell.

Hi, @Alucard648.
In original game both Death Wave and Death Ripple have the same speed (5px/frame), Death Ripple height is about 7px and Death Wave height is about 14px.
I used this parameters in the current implementation.

Here is a video from original game for comparison:


https://user-images.githubusercontent.com/113276641/206887219-44e3a4c3-8a93-4f9e-b54c-9c91eb0d64a4.mp4

**Comment by Districh-ru** [comment]
Hello, @Branikolog and @LeHerosInconnu!
Could you please review this PR when you have time.

File: src/fheroes2/gui/ui_tool.cpp [hunk 1]
```diff
@@ -223,51 +223,45 @@ namespace fheroes2
...
-            uint8_t * outImageY = outImageX + offsetOut;
-            uint8_t * outTransformY = outTransformX + offsetOut;
-            const uint8_t * outImageYEnd = outImageX + offsetOutEnd;
+        // Set pointers to the start and the end of the death wave curve.
+        std::vector<int32_t>::const_iterator pntX = deathWaveCurve.begin() + ( x < waveWidth ? waveWidth - x : 0 );
+        const std::vector<int32_t>::const_iterator endX = deathWaveCurve.end() - ( x > width ? x - width : 0 );
 
-            const int32_t offsetIn = offsetY >= 0 ? 0 : -offsetY * width;
+        for ( ; pntX != endX; ++pntX, ++outImageX, ++inImageX ) {
+            const uint8_t * outImageYEnd = outImageX + static_cast<int64_t>( height + *pntX ) * width;
```
Comment (oleg-derevenetz) [inline src/fheroes2/gui/ui_tool.cpp:250]: It's highly unlikely that the result of this multiplication will overflow `int`. However if you want to silence the clang-tidy, it would probably be better to convert to `std::ptrdiff_t` instead (here and on the following line), because currently on 32-bit machines there is one extra conversion performed - first to `int64_t` and then, when adding the multiplication result to pointer, it will be converted once again to `std::ptrdiff_t` which is 32-bit on these machines.

Comment (Districh-ru) [reply src/fheroes2/gui/ui_tool.cpp:250]: Hi @oleg-derevenetz, thanks for the explanations. I'll replace <int64_t> with <ptrdiff_t> to have less type conversions on 32 systems.
But, please, help me to make these lines more clean (without possible overflow).
If I convert the left part of the multiplication to <ptrdiff_t> I thought that the right part will be automatically converted. Or I should do the same conversion for the right part (`static_cast<ptrdiff_t>( width )`)?

Comment (oleg-derevenetz) [reply src/fheroes2/gui/ui_tool.cpp]: > If I convert the left part of the multiplication to <ptrdiff_t> I thought that the right part will be automatically converted.

Yes, both operands of arithmetic operation are promoted/converted to the same type first, so there is no need to manually convert each operand. See the "Conversions" section here:

https://en.cppreference.com/w/cpp/language/operator_arithmetic

and the link regarding integral promotion in that section.

**Comment by Branikolog** [comment]
Hello, @Districh-ru !
I've already made few tests.
Here's an issue I've found:
Red fog is drawn over troops standing in front of the target.
Wave

In the OG:
image

**Comment by Districh-ru** [comment]
> Hello, @Districh-ru ! I've already made few tests. Here's an issue I've found: Red fog is drawn over troops standing in front of the target. 

It is because the `RedrawArmies();` method , which draws the whole army on the battlefield is called first and then the red fog for is drawn.
To fix this issue we need to redesign `RedrawArmies();` method to add ability to draw each unit one by one and spells one by one from the farest to the closest. 
But we have spells with more than one cell blast radius, for example the Cold Ring spell:

https://user-images.githubusercontent.com/113276641/206905837-62154df6-3be4-4e35-a583-330cb0c20526.mp4

It should be drawn under the second peasant, but if the peasant was one cell upper, it should be drawn over him.
I think this issue will happen to every spell animation.

**Comment by ihhub** [comment]
Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.

**Comment by Branikolog** [comment]
@Districh-ru 
I've also noticed differences with splash animations position:
ezgif com-gif-maker (99)
image

**Comment by Districh-ru** [comment]
> @Districh-ru I've also noticed differences with splash animations position

@Branikolog, I tried to fix it, but I think OG has some kind of coordinate table for such sprite positions for each creature. So I set the horizontal position of the sprites close to OG. For the vertical position, I used the unit's cell position because I don't want to rely on the sprite's parameters. Therefore, the vertical position is not as close to OG. But, with such sprites (fog or explosions), it's probably better to snap to grid coordinates, not the parameters of the creature.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.

Hi @ihhub, I think there will be changes that will affect the displaying creatures on the battlefield in different situations. We also have to decide which spell and under what conditions should be drawn under or over each creature.

**Comment by ihhub** [comment]
> > Hi @Districh-ru , the best strategy to avoid heavy redevelopment is to do in steps. I believe that restructuring of `RedrawArmies()` method will require a lot of code changes. If yes it would be wiser to do it in a separate pull request.
> 
> Hi @ihhub, I think there will be changes that will affect the displaying creatures on the battlefield in different situations. We also have to decide which spell and under what conditions should be drawn under or over each creature.

I think we should do this in a separate PR.

**Comment by Branikolog** [comment]
Hi, @Districh-ru !
Now spell effect has consistent position for both sides.
image
Currently, spell effect appears on the back side of the creature sprite. I find it a bit shifted, since it appears not over the creature, but a little behind it. How do you think, is it intended animation, or can we shift those red demons appear closer to the middle of creature hex (for 1-hex creatures) and to the border of adjoining hexes (for 2-hex creatures)?

**Comment by Branikolog** [comment]
Also, I've noticed some differences in creatures sprites animations.
While red splash appears, all creatures perform "taking damage" animation. They freeze for a while being leaned back and then return to standing state.
Original Game:
https://user-images.githubusercontent.com/55348946/207298697-6b73cf64-4aa0-45df-ab5d-e942f02cc3c5.mp4
fheroes2:
https://user-images.githubusercontent.com/55348946/207298791-1e38f33b-53f0-4a6f-9354-bfa8d0e6a8d7.mp4
Take a look at halflings and champions in the current implementation.
Halflings freeze in a state which is not the most leaned back, and after freezing they continue leaning back and then returning to standing state.
Champions are on a contrary, freeze in a state after maximum leaning back. It looks like animation stops on the last "taking damage" frame.

**Comment by Districh-ru** [comment]
Hi, @Branikolog!
I'll shift the red fog sprite as you suggested and try to place it in the middle of two-hex creatures.
Also I'll will do a more thorough analysis of the frame number with maximum wince for each creature.

**Comment by Branikolog** [comment]
Hi, @Districh-ru 
Now wincing seems to happen in correct timings, but It looks like there's last frame missing. Or it happens too promptly, so I couldn't even notice it.

https://user-images.githubusercontent.com/55348946/207544248-ea7226e5-7410-4f84-99da-f3e68ee8cbbd.mp4

File: src/fheroes2/gui/ui_tool.cpp [hunk 2]
```diff
@@ -223,51 +224,45 @@ namespace fheroes2
...
             return Image();
 
         Image out = in;
 
         const int32_t width = in.width();
-        const int32_t height = in.height();
-
-        if ( x + waveWidth < 0 || x - waveWidth >= width )
+        // If the death wave curve is outside of the battlefield - return the original image.
+        if ( x < 0 || ( x - waveWidth ) >= width )
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:236]: If `deathWaveCurve` is empty we don't need to do anything but just return from the function.

File: src/fheroes2/gui/ui_tool.cpp [hunk 3]
```diff
@@ -223,51 +224,45 @@ namespace fheroes2
...
+        const int32_t offsetX = x < waveWidth ? 0 : x - waveWidth;
+        uint8_t * outImageX = out.image() + offsetX;
+        const uint8_t * inImageX = in.image() + offsetX;
 
-            uint8_t * outImageY = outImageX + offsetOut;
-            uint8_t * outTransformY = outTransformX + offsetOut;
-            const uint8_t * outImageYEnd = outImageX + offsetOutEnd;
+        // Set pointers to the start and the end of the death wave curve.
+        std::vector<int32_t>::const_iterator pntX = deathWaveCurve.begin() + ( x < waveWidth ? waveWidth - x : 0 );
+        const std::vector<int32_t>::const_iterator endX = deathWaveCurve.end() - ( x > width ? x - width : 0 );
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:248]: Here we don't check the boundaries of our container. We have to check that `( x < waveWidth ? waveWidth - x : 0 )` is smaller than `deathWaveCurve.size()` (or clamp to its size) and the same for `( x > width ? x - width : 0 )`.

File: src/fheroes2/gui/ui_tool.cpp [hunk 4]
```diff
@@ -223,51 +224,45 @@ namespace fheroes2
...
+            }
 
-            for ( ; outImageY != outImageYEnd; outImageY += width, outTransformY += width, inImageY += width, inTransformY += width ) {
+            // Flip the image under the death wave to create a distortion effect.
+            for ( int32_t i = 0; i > *pntX; --i ) {
                 *outImageY = *inImageY;
-                *outTransformY = *inTransformY;
+                outImageY += width;
+                inImageY -= width;
             }
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:266]: Would we have out of boundaries read if `*pntX` value is bigger than `height`?

File: src/fheroes2/gui/ui_tool.cpp [hunk 5]
```diff
@@ -223,51 +224,45 @@ namespace fheroes2
...
-            uint8_t * outTransformY = outTransformX + offsetOut;
-            const uint8_t * outImageYEnd = outImageX + offsetOutEnd;
+        // Set pointers to the start and the end of the death wave curve.
+        std::vector<int32_t>::const_iterator pntX = deathWaveCurve.begin() + ( x < waveWidth ? waveWidth - x : 0 );
+        const std::vector<int32_t>::const_iterator endX = deathWaveCurve.end() - ( x > width ? x - width : 0 );
 
-            const int32_t offsetIn = offsetY >= 0 ? 0 : -offsetY * width;
+        for ( ; pntX != endX; ++pntX, ++outImageX, ++inImageX ) {
+            const uint8_t * outImageYEnd = outImageX + static_cast<ptrdiff_t>( height + *pntX ) * width;
+            const uint8_t * inImageY = inImageX - static_cast<ptrdiff_t>( *pntX + 1 ) * width;
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:252]: I think we should have a loop to check that all values in `deathWaveCurve` are within accepted range of values. At least in debug mode.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru, I left several comments in this pull request. Could you please take a look at them in your spare time?

**Comment by Districh-ru** [comment]
> Hi, @Districh-ru Now wincing seems to happen in correct timings, but It looks like there's last frame missing. Or it happens too promptly, so I couldn't even notice it.

Hi, @Branikolog. Yes, there is a small logic problem: I change the type of animation and then I increase the frame number. It will be fixed in next commit.

File: src/fheroes2/battle/battle_interface.cpp [hunk 6]
```diff
@@ -5165,50 +5215,121 @@ void Battle::Interface::RedrawTargetsWithFrameAnimation( const TargetsInfo & tar
...
+            }
+
+            SetHeroAnimationReactionToTroopDeath( deathColor );
+        }
+    }
+
+    // For certain spells reflect the spell sprite if the creature is reflected.
+    const bool isReflectICN = ( icn == ICN::SHIELD || icn == ICN::REDDEATH || icn == ICN::MAGIC08 );
+    // Set the defender wince animation state.
+    bool isDefenderAnimatimg = wnce;
```
[the remark this answers is not in the document]
Comment (Districh-ru) [reply src/fheroes2/battle/battle_interface.cpp:5264]: I left a misprint here. It has to be `isDefenderAnimating`.
I named this variable so because it is true if for all units their animation sequence is not finished.

File: src/fheroes2/gui/ui_tool.cpp (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/gui/ui_tool.cpp:236]: If it is so and if it is outside of the battlefield we return the input image unchanged, as the caller function waits for an image.
I'll add the check for the size of deathWaveCurve.

File: src/fheroes2/gui/ui_tool.cpp (hunk 4 above)
Comment (Districh-ru) [reply src/fheroes2/gui/ui_tool.cpp:266]: I'll add a check for each *pntX if it is in the boundaries of the input image at the start of the loop. After this *pntX could not et higher, than the height.

**Review by Branikolog — APPROVED** [review]
Duration of the wave and red fog is still a bit different, from the original game, but it could be polished later. Current fix is a huge improvement!
Great work, @Districh-ru !

**Comment by Districh-ru** [comment]
Thanks, @Branikolog!
I set the step of Death Wave equal to the original game. The original game has different speed settings and, I think, different frame delays when drawing spell effects. Yes, later we can more carefully set this delays.
And did you check the corrected spell effect for Holy Word and Holy Shout? Does this PR fix the #1041 issue? :)

**Comment by Branikolog** [comment]
@Districh-ru 

> And did you check the corrected spell effect for Holy Word and Holy Shout? Does this PR fix the #1041 issue? :)

Yes. Spells look 95% identical.
I've only noticed that in the OG there's a slight difference in colour between the Word and the Shout spells. The Shout spell has a little bit darker (or adding red colur) in the middle of animation. I've tried to make several screenshots of the OG and every time middle frame has slight colour difference, but I'm not sure, if I simply missed needed frame and spells are 100% identical.
ezgif com-gif-maker (100)

Anyway, this difference is barely noticeable. (Like ripple and wave for me. :) )

File: src/fheroes2/battle/battle_interface.cpp [hunk 7]
```diff
@@ -3370,6 +3358,23 @@ void Battle::Interface::RedrawActionWincesKills( const TargetsInfo & targets, Un
         RedrawActionRemoveMirrorImage( mirrorImages );
 }
 
+void Battle::Interface::SetHeroAnimationReactionToTroopDeath( const int32_t deathColor )
+{
+    if ( deathColor != Color::UNUSED ) {
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:3363]: This is optional but to reduce the indentation we can do this:
```cpp
if ( deathColor == Color::UNUSED ) {
    return;
}
....
The rest of code
```

File: src/fheroes2/battle/battle_interface.cpp [hunk 8]
```diff
@@ -3370,6 +3358,23 @@ void Battle::Interface::RedrawActionWincesKills( const TargetsInfo & targets, Un
...
+        const bool attackersTurn = deathColor == arena.GetArmy2Color();
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:3364]: Please add parenthesis for this line: `const bool attackersTurn = ( deathColor == arena.GetArmy2Color() );` to be easier to read.

File: src/fheroes2/battle/battle_interface.cpp [hunk 9]
```diff
@@ -3773,7 +3778,21 @@ void Battle::Interface::RedrawActionSpellCastPart2( const Spell & spell, const T
...
 
         // targets damage animation
-        RedrawActionWincesKills( targets );
+        switch ( spell.GetID() ) {
+            // For some spells the damage animation is done during the flame animation after the spell animation.
+        case Spell::DEATHRIPPLE:
+        case Spell::DEATHWAVE:
+            RedrawTargetsWithFrameAnimation( targets, ICN::REDDEATH, M82::UNKNOWN, true );
+            break;
+
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:3787]: To be consistent please either add an empty line before `default` or remove empty line here.

File: src/fheroes2/battle/battle_interface.cpp [hunk 10]
```diff
@@ -4714,34 +4733,49 @@ void Battle::Interface::RedrawActionDisruptingRaySpell( const Unit & target )
...
     AudioManager::PlaySound( M82::MNRDEATH );
 
-    int position = 10;
+    int32_t position = 0;
     while ( le.HandleEvents() && position < area.width + waveLength ) {
         CheckGlobalEvents( le );
 
         if ( Game::validateAnimationDelay( Game::BATTLE_DISRUPTING_DELAY ) ) {
-            fheroes2::Blit( fheroes2::CreateDeathWaveEffect( copy, position, waveLength, strength ), _mainSurface );
+            fheroes2::Blit( fheroes2::CreateDeathWaveEffect( copy, position, waveLength, deathWaveCurve ), _mainSurface );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:4773]: Here we are wasting resources for copying a full frame for no reason. It is not related to your chances as it is an old code. Can you please add a TODO comment here for the future optimization:
```cpp
// TODO: instead of rendering the whole frame for the wave effect we should render only the area where the effect is active.
```

File: src/fheroes2/battle/battle_interface.cpp [hunk 11]
```diff
@@ -5165,50 +5218,124 @@ void Battle::Interface::RedrawTargetsWithFrameAnimation( const TargetsInfo & tar
...
+                for ( const TargetInfo & target : targets ) {
+                    if ( target.defender == nullptr ) {
+                        continue;
+                    }
+
+                    // Fully animate creature death.
+                    if ( !target.defender->isValid() ) {
+                        target.defender->IncreaseAnimFrame( false );
+
+                        // If the death animation is still in process then set isDefenderAnimatimg to false.
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:5307]: Please correct this comment: `isDefenderAnimatimg` --> `isDefenderAnimating`.

File: src/fheroes2/battle/battle_interface.cpp [hunk 12]
```diff
@@ -5165,50 +5218,124 @@ void Battle::Interface::RedrawTargetsWithFrameAnimation( const TargetsInfo & tar
...
         }
     }
 
-    if ( wnce )
-        for ( TargetsInfo::const_iterator it = targets.begin(); it != targets.end(); ++it )
-            if ( ( *it ).defender ) {
-                ( *it ).defender->SwitchAnimation( Monster_Info::STATIC );
-                _currentUnit = nullptr;
-            }
+    if ( wnce && !mirrorImages.empty() ) {
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.cpp:5335]: We can remove `wnce` check since we populate `mirrorImages` only when `wnce` is **true**.

File: src/fheroes2/gui/ui_tool.cpp [hunk 13]
```diff
@@ -223,51 +226,51 @@ namespace fheroes2
         }
     }
 
-    Image CreateDeathWaveEffect( const Image & in, int32_t x, int32_t waveWidth, int32_t waveHeight )
+    Image CreateDeathWaveEffect( const Image & in, const int32_t x, const int32_t waveWidth, const std::vector<int32_t> & deathWaveCurve )
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:229]: According to the code we create `deathWaveCurve` of the size of `waveWidth`. In this case I suggest to remove `waveWidth` as an input argument and declare this variable within the function:
```cpp
const int32_t waveWidth = static_cast<int32_t>( deathWaveCurve.size() );
```

File: src/fheroes2/gui/ui_tool.cpp [hunk 14]
```diff
@@ -223,51 +226,51 @@ namespace fheroes2
...
+        std::vector<int32_t>::const_iterator pntX = deathWaveCurve.begin() + ( x < waveWidth ? waveWidth - x : 0 );
+        const std::vector<int32_t>::const_iterator endX = deathWaveCurve.end() - ( x > width ? x - width : 0 );
 
-            uint8_t * outImageY = outImageX + offsetOut;
-            uint8_t * outTransformY = outTransformX + offsetOut;
-            const uint8_t * outImageYEnd = outImageX + offsetOutEnd;
+        for ( ; pntX != endX; ++pntX, ++outImageX, ++inImageX ) {
+            // The death curve should have only negative values and should not be higher, than the height of 'in' image.
+            if ( ( *pntX >= 0 ) || ( *pntX <= -height ) ) {
+                DEBUG_LOG( DBG_BATTLE, DBG_WARN, "Death Wave curve is out of range (" << -height << ", 0): " << *pntX )
```
Comment (ihhub) [inline src/fheroes2/gui/ui_tool.cpp:255]: Based on the past problems with the code I suggest to just add `assert( 0 );` instead of logging the error so the issue will be immediately detected and fixed. If such a case happens with logging we would be a lot of log messages as this function is called many times as well as many values could be present.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put few more comments in this pull request. Can you please take a look at them when you have time?

**Comment by ihhub** [comment]
Hi @Districh-ru , I updated your initial message to link #1041 and to be closed upon merging this pull request.

File: src/fheroes2/battle/battle_interface.cpp (hunk 10 above)
Comment (Districh-ru) [reply src/fheroes2/battle/battle_interface.cpp:4773]: I'll try to do this in a new PR.

**Comment by Districh-ru** [comment]
> Hi @Districh-ru , I updated your initial message to link #1041 and to be closed upon merging this pull request.

Hi. @ihhub. Thanks!

File: src/fheroes2/battle/battle_interface.cpp (hunk 10 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp]: Yes, we don't need to do it here.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , huge thanks for upgrading these animations!
