### PR TITLE
Correct spell value estimation for AI heroes

### LINKED ISSUE #7194: The strongest allied hero attacks a neutral monster guarding nothing and loses its entire army
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The strong green hero(Trayan) attacks earth elementals and loses. The neutral guards nothing and there is no visible reward for this battle except experience. There are still many enemy castles and strong heroes on the map, so why take a risk? Also, enemy army evaluation function probably should be made more pessimistic - Zounds can be a lot!

### Save file

[New_Enemies_0178.zip](https://github.com/ihhub/fheroes2/files/11501659/New_Enemies_0178.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
This pull request fixes 2 cases:
1) Town Portal and Town Gate were not considered as valued spells for visiting castles or shrines.
2) Summoning spells were overestimated causing AI heroes to attack too powerful neutral monsters.

close #7194

Moreover, this is a save file when an AI hero attacks Druids having an idea in mind that Summoning spells are too powerful (hit F8 in debug mode for this):
[AI_army_overestimation.zip](https://github.com/ihhub/fheroes2/files/11928748/AI_army_overestimation.zip)

### CODE REVIEW

**Review by oleg-derevenetz — APPROVED** [review]

**Review by Districh-ru — APPROVED** [review]

File: src/fheroes2/spell/spell.cpp [hunk 1]
```diff
@@ -217,27 +217,38 @@ double Spell::getStrategicValue( double armyStrength, uint32_t currentSpellPoint
...
 
     if ( isDamage() ) {
         // Benchmark for Lightning for 20 power * 20 knowledge (maximum uses) is 2500.0
         return amountModifier * Damage() * spellPower;
     }
+
     // These high impact spells can turn tide of battle
     if ( isResurrect() || isMassActions() || id == Spell::BLIND || id == Spell::PARALYZE ) {
         return armyStrength * 0.1 * amountModifier;
     }
```
Comment (Alucard648) [inline src/fheroes2/spell/spell.cpp:244]: Berserk can also turn the tide of the battle.

**Review by idshibanov — APPROVED** [review]

File: src/fheroes2/spell/spell.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/spell/spell.cpp:244]: What exactly are you suggesting to do for this?
