### PR TITLE
Don't let the archers perform a double attack if they are out of ammo

### LINKED ISSUE #5931: Battle, double attacking shooters proceed one attack without arrows
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In a case a shooter has odd number of arrows left he can come up to an attack, when he has only one arrow left.
image
In the OG he's allowed to proceed the second shot, even if he has only one arrow. I think it's a debatable logic. To my mind if shooter has only one arrow, he could make only one shot.
But currently in fheroes2 shooter is able to make a second hit with his knife. It looks like some sort of telekinetic swing. :D
image

### Save file

[Really distant swing.zip](https://github.com/ihhub/fheroes2/files/9733784/Really.distant.swing.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5931

### CODE REVIEW

File: src/fheroes2/battle/battle_troop.cpp [hunk 1]
```diff
@@ -1534,17 +1529,16 @@ void Battle::Unit::SpellRestoreAction( const Spell & spell, uint32_t spoint, con
...
-        return !isHandFighting();
+    if ( isHandFighting() ) {
+        return isAbilityPresent( fheroes2::MonsterAbilityType::DOUBLE_MELEE_ATTACK );
+    }
 
-    default:
-        break;
+    // Archers with double shooting ability can only fire a second shot if they still have ammo
+    if ( isAbilityPresent( fheroes2::MonsterAbilityType::DOUBLE_SHOOTING ) ) {
+        return GetShots() > 0;
```
Comment (ihhub) [inline src/fheroes2/battle/battle_troop.cpp:1538]: Hi @oleg-derevenetz , should it be > 1 instead of > 0?

Comment (oleg-derevenetz) [reply src/fheroes2/battle/battle_troop.cpp:1538]: Hi @ihhub it should be > 0, because this function is called only after the first shot was already fired.

Comment (oleg-derevenetz) [reply src/fheroes2/battle/battle_troop.cpp:1538]: Hi @ihhub After some thought, I decided to rework the logic a bit to make it more obvious.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this fix!
