### PR TITLE
Memorize zoom level of the View World screen

### LINKED ISSUE #6619: View World screen, zoom level of the View World screen is not memorized
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the zoom level of the View World screen is not memorized unlike in the original game.

In original game:

https://user-images.githubusercontent.com/43583994/218465811-9786658d-c718-4aeb-bc77-52d8d5e16c9a.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/218465897-797af0e5-c3e4-458a-8f69-0052cff95b7c.mp4

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
close #6619

### CODE REVIEW

**Comment by Districh-ru** [comment]
Hello @LeHerosInconnu!
Could you please check this PR in your spare time.

File: src/fheroes2/kingdom/view_world.h [hunk 1]
```diff
@@ -68,7 +68,7 @@ class ViewWorld
         const fheroes2::Rect & GetROIinPixels() const;
         fheroes2::Rect GetROIinTiles() const;
 
-        ZoomLevel _zoomLevel{ ZoomLevel2 };
```
Comment (ihhub) [inline src/fheroes2/kingdom/view_world.h:71]: I suggest to keep the previous code to avoid having an uninitialized member.

File: src/fheroes2/system/settings.h [hunk 2]
```diff
@@ -451,6 +461,7 @@ class Settings
 
     int game_type;
     int preferably_count_players;
+    int32_t _viewWorldZoomLevel{ 2 };
```
Comment (ihhub) [inline src/fheroes2/system/settings.h:464]: It is good to avoid using hardcoded values. To minimize file dependencies I suggest to create a separate header file which will contain only `ViewWorldZoomLevel` enumeration (by the way it can be uint8_t as it doesn't have too many entries. Use this enumeration for `ViewWorld` and `Settings` classes. What do you think?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I put few comments here. Would you mind to check them?

File: src/fheroes2/system/settings.h (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/system/settings.h:464]: Hi @ihhub!
In `settings.h` we already have enumerations for `AdventureMapScrollSpeed` and `MusicSource`. What if we put `enum class ViewWorldMode : uint8_t` there, as `zoomLevel` becomes a part of global game configuration?

Comment (ihhub) [reply src/fheroes2/system/settings.h:464]: I think it will be better than just hardcoded values.

File: src/fheroes2/kingdom/view_world.h (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/kingdom/view_world.h:71]: I'll also change it to ZoomLevel1, as it is the default value in original game.

**Review by ihhub — APPROVED** [review]

**Review by Branikolog — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , many thanks for adding this improvement!

**Comment by LeHerosInconnu** [comment]
Hello @Districh-ru,

> Hello @LeHerosInconnu! Could you please check this PR in your spare time.

I did some tests, it seems to work correctly.
