### PR TITLE
Fix next hero choose logic

### LINKED ISSUE #3364: Adventure map, hero with a predetermined path and who has movement points left is not selected when the "Next Hero" button is pressed
In fheroes2, the hero with a predetermined path (with no movement possible on this path) and who has movement points left (he can still move on the road) is not selected when the "Next Hero" button is pressed.

In fheroes2:

https://user-images.githubusercontent.com/43583994/117500383-d89e7180-af7c-11eb-9326-9dfb9cffe06c.mp4

Related issue: https://github.com/ihhub/fheroes2/issues/1986.
The hero should be able to move on any terrain from the road (from the penalty of the terrain where the movement is initiated).

Here is the save file:
[No next hero but move left 01.zip](https://github.com/ihhub/fheroes2/files/6443947/No.next.hero.but.move.left.01.zip)

### PR DESCRIPTION
**Pull request by tau3**
Fixes #3364
A hero with non-zero move points can be chosen as next even if movement is not possible on predetermined path

### CODE REVIEW

File: src/fheroes2/heroes/heroes.cpp [hunk 1]
```diff
@@ -1410,12 +1410,17 @@ void Heroes::ResetMovePoints( void )
...
 {
-    if ( Modes( SLEEPER | GUARDIAN ) || isFreeman() )
+    if ( Modes( SLEEPER | GUARDIAN ) || isFreeman() ) {
         return false;
+    }
 
-    return path.isValid() ? ( move_point >= path.getLastMovePenalty() ) : CanMove();
+    if ( path.isValid() ) {
+        const uint32_t threshold = isConsiderMovePoints ? path.getLastMovePenalty() : 0;
+        return move_point > threshold;
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes.cpp:1421]: This check might be incorrect. Could you please verify what happens when a hero has 1 point of movement which is not enough to even move on a road?

File: src/fheroes2/heroes/heroes.h [hunk 2]
```diff
@@ -251,7 +251,7 @@ class Heroes : public HeroBase, public ColorBase
 
     u32 GetMovePoints( void ) const;
     void IncreaseMovePoints( u32 );
-    bool MayStillMove( void ) const;
+    bool MayStillMove( bool isConsiderMovePoints = true ) const;
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes.h:254]: A small correction: since we're adopting better coding rules could you please make this input variable `const`?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @tau3 , I left just few comments. Could you please take a look?

File: src/fheroes2/heroes/heroes.cpp (hunk 1 above)
Comment (tau3) [reply src/fheroes2/heroes/heroes.cpp]: yep, there should have been "more-or-equal" comparison. fixed it.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test this change?

**Comment by Branikolog** [comment]
Hi, @tau3 
Next hero button works not correct in a case we have multiple heroes in a situation, where they can make a move in one direction, but cannot in other.
Here we have both heroes with no predetermined path, but "Next hero" button works only in focusing on second hero...
image

When we make predetermined path for both heroes (first hero without ability to move, and second hero able to move)...
image
image
..."Next hero" button switches between both of them.

**Comment by ihhub** [comment]
@tau3 , thank you very much for this fix!
