### PR TITLE
Fixed the displayed text in the army bar

### LINKED ISSUE #3622: Castle screen, the text "Cannot move last troop" in the info bar at the bottom of the screen should only be displayed when there is only one creature left in the troop
During the distribution between the hero's army and the garrison, the text "Cannot move last troop" in the info bar at the bottom of the screen should only be displayed when there is only one creature left in the troop, because it is possible to move all creatures except one, and this is done automatically.

In the example, the text displayed should be:

"Move or right clic to redistribute Gargoyles"

Instead of:

"Cannot move last troop"

In fheroes2:

Cannot move last troop 001

Cannot move last troop 002

https://user-images.githubusercontent.com/43583994/120871516-1bfbf800-c59c-11eb-9fe6-92d037156ac3.mp4

### PR DESCRIPTION
**Pull request by felix642**
fix #3622

### CODE REVIEW

File: src/fheroes2/army/army.cpp [hunk 1]
```diff
@@ -1251,6 +1251,16 @@ int Army::GetControl( void ) const
     return commander ? commander->GetControl() : ( color == Color::NONE ? CONTROL_AI : Players::GetPlayerControl( color ) );
 }
 
+u32 Army::getTotalCount( void ) const
+{
+    uint32_t total = 0;
+    for ( const_iterator it = begin(); it != end(); ++it ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/army/army.cpp:1257]: I'd use `std::accumulate()` instead of all these old-school iterators. Something like:

`return std::accumulate( begin(), end(), 0u, []( uint32_t total, const Troop * item ) { return item->isValid() ? total + item->GetCount() : total; } );`

Or range-based `for` at least.

File: src/fheroes2/army/army.cpp [hunk 2]
```diff
@@ -1251,6 +1251,16 @@ int Army::GetControl( void ) const
     return commander ? commander->GetControl() : ( color == Color::NONE ? CONTROL_AI : Players::GetPlayerControl( color ) );
 }
 
+u32 Army::getTotalCount( void ) const
```
Comment (oleg-derevenetz) [inline src/fheroes2/army/army.cpp:1254]: Please use standard type `uint32_t` as a return type instead of `u32` in a new code.

File: src/fheroes2/army/army.h [hunk 3]
```diff
@@ -156,6 +156,7 @@ class Army : public Troops, public Control
 
     int GetColor( void ) const;
     int GetControl( void ) const override;
+    u32 getTotalCount( void ) const;
```
Comment (oleg-derevenetz) [inline src/fheroes2/army/army.h:159]: Please use standard type `uint32_t` as a return type instead of `u32` in a new code.

File: src/fheroes2/army/army_bar.cpp [hunk 4]
```diff
@@ -324,7 +324,7 @@ bool ArmyBar::ActionBarCursor( ArmyTroop & troop )
 
 bool ArmyBar::ActionBarCursor( ArmyTroop & destTroop, ArmyTroop & selectedTroop )
 {
-    bool save_last_troop = selectedTroop.GetArmy()->SaveLastTroop();
+    bool save_last_troop = selectedTroop.GetArmy()->getTotalCount() <= 1;
```
Comment (oleg-derevenetz) [inline src/fheroes2/army/army_bar.cpp:327]: This will not work properly. "Save last troop" logic should be applied only if army is led by a hero. With this change, if there is only one unit left in castle garrison, you will get "Cannot move last troop" status message if you are going to move this unit from castle garrison to the guest hero's army, even if you in fact can. Additional checks for a hero presence (like in `Army::SaveLastTroop()`) are needed here.

**Review by oleg-derevenetz — CHANGES_REQUESTED** [review]
Hi @felix642, I left a few comments, could you please take a look?

File: src/fheroes2/army/army.cpp [hunk 5]
```diff
@@ -1251,6 +1252,11 @@ int Army::GetControl( void ) const
     return commander ? commander->GetControl() : ( color == Color::NONE ? CONTROL_AI : Players::GetPlayerControl( color ) );
 }
 
+uint32_t Army::getTotalCount( void ) const
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1255]: Please remove **void** from method's input parameters. It is redundant.

File: src/fheroes2/army/army.cpp [hunk 6]
```diff
@@ -1251,6 +1252,11 @@ int Army::GetControl( void ) const
...
+{
+    return std::accumulate( begin(), end(), 0u, []( uint32_t count, Troop * troop ) { return troop->isValid() ? count + troop->GetCount() : count; } );
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:1257]: Both input arguments of the lambda function could be `const`.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @felix642 , there are just 2 minor comments left. Would you mind to take a look?

File: src/fheroes2/army/army.cpp (hunk 5 above)
Comment (felix642) [reply src/fheroes2/army/army.cpp:1255]: I also removed it from the .h file.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test thes changes?

**Comment by Branikolog** [comment]
@ihhub , @felix642 
Everything seems to work fine.
I noticed, that in the OG we have "to garrison" in the statement.
image

**Comment by felix642** [comment]
> @ihhub , @felix642
> Everything seems to work fine.
> I noticed, that in the OG we have "to garrison" in the statement.
> image

Should I change the text as well?

**Comment by Branikolog** [comment]
@felix642 
I think, making it the same to original is not a bad idea. ;)

**Comment by ihhub** [comment]
Hi @felix642 , let's make it

> > @ihhub , @felix642
> > Everything seems to work fine.
> > I noticed, that in the OG we have "to garrison" in the statement.
> 
> Should I change the text as well?

Hi @felix642 , let's do this in a separate pull request.

**Comment by ihhub** [comment]
@felix642 , thanks a lot for the fix!
