### PR TITLE
Fix an assertion on corrupted maps

### LINKED ISSUE #10405: Assertion failed crash when starting Archibald campaign
### Preliminary checks

- [x] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [x] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

When starting the Archibald campaign fresh from the menu the game crashes with an assertion failed error message:
Game language is german.

### Save file

No save file possible since it crashes before starting the game.

### Additional info
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: C:\Program Files\fheroes2\fheroes2.exe
File: D:\a\fheroes2\fheroes2\src\fheroes2\world\world.cpp
Line: 1363

Expression: Maps::getLastObjectUID() >= maxUid

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

### PR DESCRIPTION
**Pull request by ihhub**
close #10405

### CODE REVIEW

File: src/fheroes2/world/world.cpp [hunk 1]
```diff
@@ -1354,20 +1354,13 @@ void World::PostLoad( const bool setTilePassabilities, const bool updateUidCount
...
-        // Check that 'getNewObjectUID()' will return values that will not match the existing ones on the started map.
-        if ( Maps::getLastObjectUID() < maxUid ) {
-            // Some maps (even official original campaign maps) can have incorrect UID.
-            // No idea what's the reason but assumed that they were edited by the corrupted Editor.
-            ERROR_LOG( "Last Object UID is not valid. Expected: " << Maps::getLastObjectUID() << ", received: " << maxUid )
-        }
 
-        Maps::setLastObjectUID( maxUid );
-    }
+    Maps::setLastObjectUID( maxUid );
```
Comment (Districh-ru) [inline src/fheroes2/world/world.cpp]: According to the previous logic - we should `setLastObjectUID()` only when `updateUidCounterToMaximum` is true.
To fix the broken maps we need to to call  `setLastObjectUID()`.
But if the map is not broken then there is no need to update the last object UID:

```cpp
    if ( updateUidCounterToMaximum ) {
        // And set the UID counter value with the found maximum.
        Maps::setLastObjectUID( maxUid );
    }
    else if ( Maps::getLastObjectUID() < maxUid ) {
        // Some maps (even official original campaign maps) can have incorrect UID.
        // No idea what's the reason but assumed that they were edited by the corrupted Editor.
        ERROR_LOG( "Last Object UID is not valid. Expected: " << Maps::getLastObjectUID() << ", received: " << maxUid )

        Maps::setLastObjectUID( maxUid );
    }
```

Or if we want to fix all maps then there is no more need for `updateUidCounterToMaximum` argument.

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi @ihhub,  I left one logic-related comment. Could you check it when you have time?

**Review by Districh-ru — APPROVED** [review]
