### PR TITLE
Fix adjacent monsters when removing one

### LINKED ISSUE #2072: Unknown monsters on a world map
There's still can be found some Unknown "peasants" on a world map. At least they simply disappear, while being attacked by player.
image

[Unknown monsters.zip](https://github.com/ihhub/fheroes2/files/5429130/Unknown.monsters.zip)

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #2072 .

Should stop the unknown monsters appearing on the map. Wasn't cleared properly when fighting adjacent units.

### CODE REVIEW

File: src/fheroes2/heroes/heroes_action.cpp [hunk 1]
```diff
@@ -753,9 +753,9 @@ void ActionToMonster( Heroes & hero, u32 obj, s32 dst_index )
     if ( destroy ) {
         AGG::PlaySound( M82::KILLFADE );
         AnimationRemoveObject( tile );
+        tile.RemoveObjectSprite();
```
Comment (ihhub) [inline src/fheroes2/heroes/heroes_action.cpp:756]: Could you please explain why we need to remove the object sprite first?

Comment (idshibanov) [reply src/fheroes2/heroes/heroes_action.cpp:756]: GetObject would return zero object if we do it after, then default logic executes removing wrong sprites.

**Comment by ihhub** [comment]
Good job, @idshibanov !
