### PR TITLE
Fix boat drawing issue

### LINKED ISSUE #2179: Adventure map, hero's shadow is displayed over the boat's sprite
In fheroes2, the hero's shadow is displayed over the boat's sprite.

In fheroes2:

Summon Boat orientation fh2 02

### LINKED ISSUE #2434: Adventure map, the second summoned boat is displayed under the first summoned boat
In fheroes2, the second summoned boat is displayed under the first summoned boat.

In fheroes2:

Boat under boat after second summon fh2 01

### LINKED ISSUE #2720: Summon Boat spell, boat summoned under the hero's sprite
In fheroes2, the boat is summoned under the hero's sprite.

In fheroes2:

Boat summon under hero fh2 01

https://user-images.githubusercontent.com/43583994/106661417-77dc5300-65a1-11eb-9d0b-ec98fc4bf98a.mp4

### PR DESCRIPTION
**Pull request by vasilenkoalexey**
fix #2720
fix #2434
fix #2179

### CODE REVIEW

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 1]
```diff
@@ -185,15 +185,52 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
         return;
     }
 
+    MapsIndexes drawList;
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:188]: Please create 2 separate variables: one for heroes and one for boat so that in the later loop we don't need to check object type.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 2]
```diff
@@ -1533,7 +1533,25 @@ void Maps::Tiles::RedrawMonster( fheroes2::Image & dst, const Rect & visibleTile
     }
 }
 
-void Maps::Tiles::RedrawBoat( fheroes2::Image & dst, const Rect & visibleTileROI, bool withShadow, const Interface::GameArea & area ) const
+void Maps::Tiles::RedrawBoatShadow( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const
+{
+    const Point mp = Maps::GetPoint( GetIndex() );
+
+    if ( visibleTileROI & mp ) {
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1540]: Please use early function return logic:
```
if ( !( visibleTileROI & mp ) ) {
    return;
}
```

File: src/fheroes2/maps/maps_tiles.h [hunk 3]
```diff
@@ -196,12 +196,15 @@ namespace Maps
...
+        void RedrawBottom( fheroes2::Image & dst, const Rect & visibleTileROI, bool isPuzzleDraw, const Interface::GameArea & area ) const;
+        void RedrawBottom4Hero( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
+        void RedrawTop( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
+        void RedrawTop4Hero( fheroes2::Image & dst, const Rect & visibleTileROI, bool skip_ground, const Interface::GameArea & area ) const;
+        void RedrawObjects( fheroes2::Image & dst, bool isPuzzleDraw, const Interface::GameArea & area ) const;
+        void RedrawMonstersAndBoat( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
+        void RedrawBoat( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
+        void RedrawBoatShadow( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
+        void RedrawMonster( fheroes2::Image & dst, const Rect & visibleTileROI, const Interface::GameArea & area ) const;
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.h:207]: What there a big reason to rename `gameArea` into `area`? We still have other methods using `gameArea`.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , I left few comments here. Could you please take a look?

File: src/fheroes2/gui/interface_gamearea.cpp (hunk 1 above)
Comment (vasilenkoalexey) [reply src/fheroes2/gui/interface_gamearea.cpp:188]: It is important to draw boats and heroes in the order in which we found them during top-left to bottom-right loop. Otherwise, we may incorrectly draw boat and hero one on top of the other.

File: src/fheroes2/maps/maps_tiles.cpp (hunk 2 above)
Comment (vasilenkoalexey) [reply src/fheroes2/maps/maps_tiles.cpp]: Done. Moreover,  I think we can replce it by assertion.

File: src/fheroes2/maps/maps_tiles.h (hunk 3 above)
Comment (vasilenkoalexey) [reply src/fheroes2/maps/maps_tiles.h:207]: Renamed completely. Better when an instance of the same class has the same name.

**Comment by ihhub** [comment]
Hi @vasilenkoalexey , we have ab issue with drawing other objects (check lighthouse):
image

**Comment by vasilenkoalexey** [comment]
> Hi @vasilenkoalexey , we have ab issue with drawing other objects (check lighthouse):

Should be fixed now

File: src/fheroes2/maps/maps_tiles.cpp [hunk 4]
```diff
@@ -1533,26 +1535,44 @@ void Maps::Tiles::RedrawMonster( fheroes2::Image & dst, const Rect & visibleTile
...
+    const Game::ObjectFadeAnimation::FadeTask & fadeTask = Game::ObjectFadeAnimation::GetFadeTask();
+    const uint32_t alpha
+        = ( MP2::OBJ_BOAT == fadeTask.object && ( ( fadeTask.fadeOut && fadeTask.fromIndex == maps_index ) || ( fadeTask.fadeIn && fadeTask.toIndex == maps_index ) ) )
+              ? fadeTask.alpha
+              : 255;
+
+    const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::BOAT32, spriteIndex % 128 );
+    area.BlitOnTile( dst, sprite, sprite.x(), TILEWIDTH + sprite.y() - 11, mp, ( spriteIndex > 128 ), alpha );
+
+    RedrawTop( dst, visibleTileROI, area );
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.cpp:1575]: We are calling `RedrawTop` twice. We shouldn't do this. We could check the existance of boat at particular tile in `if ( drawTop ) {` loop and do not draw it.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , I left just one comment in regards to performance. Could you please take a look?

File: src/fheroes2/maps/maps_tiles.cpp (hunk 4 above)
Comment (vasilenkoalexey) [reply src/fheroes2/maps/maps_tiles.cpp:1575]: Yes, you are right. But we have same problem right now for hero. I can fix both in separate pr or put commit to this pr.

Comment (ihhub) [reply src/fheroes2/maps/maps_tiles.cpp:1575]: If the fix is not that big let's put it here please.

Comment (vasilenkoalexey) [reply src/fheroes2/maps/maps_tiles.cpp:1575]: Done

**Comment by ihhub** [comment]
Hi @Branikolog , could you please test these changes?

**Comment by Branikolog** [comment]
@ihhub 
Sure! Give me a few hours.

**Comment by Branikolog** [comment]
Everything looks fine.
My only concern is...
Shouldn't the boat be drawn under the object if they are on the same line?
image
Here I expect boat be drawn under Witch Hut.
Also, hero is drawn under the boat here...
Or should we consider this as another issue?

**Comment by vasilenkoalexey** [comment]
I fixed problem when hero is drawn under the boat. But boat and Witch Hut is different issue #2186

**Comment by ihhub** [comment]
@vasilenkoalexey , a huge thanks for fixing these issues in one shot!
