### PR TITLE
Fix multiple objects and add missing ones in the Editor

### LINKED ISSUE #6845: Editor preparations
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

The next major goal of the project is deliver an in-game editor. This issue serves as a collection of tasks related to the main task.

### Describe the possible solution

This is a list of tasks we have to complete in order to deliver a base version of the Editor:
- [x] remove usage of quantity1 and quantity2 in the code. Make them more readable without the calculation magic present in the code.
- [x] Tiles class should just have a stack of all TilesAddon. Move the same members of the Tiles class away from the class. This will make the code much cleaner and easier to maintain
- [x] Move all auxiliary methods outside of the Tiles class. Tiles class is designed just to store information about a tile in general, not about specific objects
- [x] Create an information table for each object in the game: which images are used to determine the object, its properties, passabilities
- [x] Remove unused structures in mp2.h file and expand the code with necessary explanations within comments where we actually read data for these structures
- [x] add a shortcut key (E) to open an Editor main menu and add there needed buttons like it is done in the original Editor (for now only for debug mode). The main menu image must be resizable
- [x] add a new mode within interface_area to enable Editor mode (something similar what we did for view world
- [x] add UI elements to handle terrain types and change cursor type based on a chosen type
- [x] change terrain type using terrain brush (enable support for keeping objects on terrain as well as selecting an area for terrain)
- [x] add historical changes support: undo and redo functionality
- [x] propose a map format which stores objects as whole and their data. For example, a castle must have only 1 main tile while in the editor and the game it will populate the needed number of tiles.
- [x] add required helper functions into the code to load new map format. These functions should be shared among the Editor and the game
- [x] add a UI toolset to handle objects within the Editor. It should be a different way than in the original game
- [x] display passabilities for objects on the map
- [x] figure out text encoding support for maps
- [x] investigate whether it is required to have a separate format for campaign scenarios
- [x] change `MapObjectType` type to uint16_t to support new objects
- [x] add a window to change Hero properties
- [x] add a window to change Castle / Town properties
- [x] add a window to change Sphinx properties
- [x] add a window to change Bottle / Sign properties
- [x] add a window to change Jail properties
- [x] add a window to change Random Hero properties
- [x] add a window to change Random Town properties
- [x] add a window to change Event properties
- [x] add a window to change Monster properties
- [x] add a window for map properties
- [x] add a window for saving a map
- [x] add a a structure to store Event properties
- [x] add a a structure to store Bottle / Sign properties
- [x] add a a structure to store Sphinx properties
- [x] add a a structure to store Random Hero properties
- [x] add a a structure to store Random Town properties
- [x] handle all original map winning and loosing conditions
- [x] add code to load every object properties
- [x] update the conditions for object placement
- [x] update object layers, mostly for background layer
- [x] fix cursor rendering in File Options window when Animation is stopped
- [x] implement the main menu button for the Editor
- [x] properly connect roads and castles
- [x] fix radar rendering for heroes and castles
- [x] remove beta Editor tag
- [x] add zlib compression to the map format
- [x] fix river delta placement
- [x] add a shortcut to go to Main Menu from the Editor
- [x] add daily event support
- [x] add logic to place random ultimate artifact
- [x] add a window to modify random ultimate artifact radius
- [x] update objects while changing terrains under them
- [x] add rumours into the map format
- [x] make Evil interface for New/Load/Save Map buttons

The above list is going to be expanded based on the progress and discoveries.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6845

All these issues were detected by an algorithm which I will introduce in another pull request.

### CODE REVIEW

File: src/fheroes2/maps/map_object_info.cpp [hunk 1]
```diff
@@ -3268,15 +3302,15 @@ namespace
...
+        // Alchemist Lab.
         {
             Maps::ObjectInfo object{ MP2::OBJ_ALCHEMIST_LAB };
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 26U, fheroes2::Point{ 0, 0 }, MP2::OBJ_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 25U, fheroes2::Point{ -1, 0 }, MP2::OBJ_NON_ACTION_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 27U, fheroes2::Point{ 1, 0 }, MP2::OBJ_NON_ACTION_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
             object.groundLevelParts.back().animationFrames = 6;
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 24U, fheroes2::Point{ -2, 0 }, MP2::OBJ_NONE, Maps::SHADOW_LAYER );
-            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 20U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE, Maps::SHADOW_LAYER );
+            object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNMUL2, 20U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE );
```
Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:3313]: This part is a shadow in the original game (and editor):
изображение

Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:3313]: This part is a shadow in the original game (and editor):
изображение

File: src/fheroes2/maps/map_object_info.cpp [hunk 2]
```diff
@@ -3287,6 +3321,26 @@ namespace
...
+
+        // Alchemist Lab (snow terrain).
+        {
+            Maps::ObjectInfo object{ MP2::OBJ_ALCHEMIST_LAB };
+            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNSNOW, 150U, fheroes2::Point{ 0, 0 }, MP2::OBJ_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
+            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNSNOW, 149U, fheroes2::Point{ -1, 0 }, MP2::OBJ_NON_ACTION_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
+            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNSNOW, 148U, fheroes2::Point{ -2, 0 }, MP2::OBJ_NONE, Maps::SHADOW_LAYER );
+            object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNSNOW, 151U, fheroes2::Point{ 1, 0 }, MP2::OBJ_NON_ACTION_ALCHEMIST_LAB, Maps::OBJECT_LAYER );
+            object.groundLevelParts.back().animationFrames = 6;
+            object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNSNOW, 144U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE );
```
Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:3333]: This is also a shadow:
изображение

File: src/fheroes2/maps/map_object_info.cpp [hunk 3]
```diff
@@ -4227,6 +4301,7 @@ namespace
 
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNDSRT, 80U, fheroes2::Point{ -2, 0 }, MP2::OBJ_NONE, Maps::SHADOW_LAYER );
 
+            object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNDSRT, 77U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE );
```
Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:4304]: This tile is also originally a shadow:
изображение

File: src/fheroes2/maps/map_object_info.cpp [hunk 4]
```diff
@@ -3988,6 +4052,7 @@ namespace
 
             object.groundLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNDIRT, 196U, fheroes2::Point{ -2, 0 }, MP2::OBJ_NONE, Maps::SHADOW_LAYER );
 
+            object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_OBJNDIRT, 193U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE );
```
Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:4055]: Originally it is a shadow :)
изображение

File: src/fheroes2/maps/map_object_info.cpp [hunk 5]
```diff
@@ -3112,6 +3145,7 @@ namespace
             object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_X_LOC1, 115U, fheroes2::Point{ 1, -1 }, MP2::OBJ_NON_ACTION_AIR_ALTAR );
             object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_X_LOC1, 114U, fheroes2::Point{ 0, -1 }, MP2::OBJ_NON_ACTION_AIR_ALTAR );
             object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_X_LOC1, 113U, fheroes2::Point{ -1, -1 }, MP2::OBJ_NONE );
+            object.topLevelParts.emplace_back( MP2::OBJ_ICN_TYPE_X_LOC1, 112U, fheroes2::Point{ -2, -1 }, MP2::OBJ_NONE );
```
Comment (Districh-ru) [inline src/fheroes2/maps/map_object_info.cpp:3148]: Another far shadow.
изображение

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub, I left several comment regarding tile sprite level. Could you please take a look when you have time.

**Review by Districh-ru — APPROVED** [review]
👍
