### PR TITLE
Fix an issue that caused an AI-controlled hero standing next to Stone Liths to block the path of another AI-controlled hero standing on these Stone Liths

### LINKED ISSUE #7138: Adventure map, AI stuck in front of stone liths
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Two yellow heroes are blocking each other:
image

### Save file

[Stuck in Liths.zip](https://github.com/ihhub/fheroes2/files/11420759/Stuck.in.Liths.zip)

### Additional info

_No response_

### LINKED ISSUE #7140: Adventure map, to re-visit stone liths AI choses too distant and not optimal cell
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Sometimes to re-visit stone liths AI hero choses a cell to step and return, which requires him to waste not 1 movement, but 2 or more. Sometimes he starts to walk around some abject and then returns back, wasting all his movement points.

https://user-images.githubusercontent.com/55348946/236819476-18333faf-374b-4341-9ff4-4cd5405561fd.mov

One of red heroes here (0:14) choses a cell right above stone liths.

### Save file

[Stuck in Liths.zip](https://github.com/ihhub/fheroes2/files/11420934/Stuck.in.Liths.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #7138
fix #7140

At first I thought to limit the case to checking only friendly heroes nearby, but then I decided that all AI-controlled heroes should behave "like a gentleman" with enemy ones and give way to them, if it turns out that neither of them has an advantage and does not dare to attack the other.

### CODE REVIEW

File: src/fheroes2/world/world_pathfinding.cpp [hunk 1]
```diff
@@ -912,6 +912,13 @@ bool AIWorldPathfinder::isHeroPossiblyBlockingWay( const Heroes & hero )
         return true;
     }
 
+    // Is the hero standing near the Stone Liths that are occupied by another hero?
+    for ( const int32_t idx : Maps::ScanAroundObject( heroIndex, MP2::OBJ_STONE_LITHS ) ) {
+        if ( world.GetTiles( idx ).GetObject() == MP2::OBJ_HEROES ) {
```
Comment (ihhub) [inline src/fheroes2/world/world_pathfinding.cpp:917]: Should we check that another hero is a friendly one? Blocking a way for an enemy hero seems to be a good tactic. Also do we need to check that the blocked hero cannot move anywhere else except to the tile where the current hero stands?

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left 2 questions regarding the proposed solution. Could you please check them?

File: src/fheroes2/world/world_pathfinding.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/world/world_pathfinding.cpp:917]: @ihhub

> Should we check that another hero is a friendly one?

If neither hero has an advantage to attack the other, then they can get stuck there forever, which IMHO is undesirable.

> Also do we need to check that the blocked hero cannot move anywhere else except to the tile where the current hero stands?

If it's a hero of the same color, then he can't do it 100%, otherwise we wouldn't be here (we only end up here if AI is not able to find tasks for any of the heroes). With heroes of other colors, the situation is more complicated, but I think it would be an extra complication - after all, in other cases this function does not check whether the heroes being moved are really blocking someone, it is enough that they stand in some "narrow place".

Comment (ihhub) [reply src/fheroes2/world/world_pathfinding.cpp:917]: Yes, this would be more reasonable. Also to avoid hardcoded directions we can use passability values.

**Review by Branikolog — APPROVED** [review]

**Comment by Branikolog** [comment]
Many thanks for the prompt fix, @oleg-derevenetz !

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this improvement!
