### PR TITLE
Kingdom Overview screen: automatically update status of castle dwellings that have just been built or upgraded

### LINKED ISSUE #8437: Kingdom Overview screen, type of creatures available for recruitment is not updated when a dwelling is built in the castle
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the type of creatures available for recruitment is not updated when a dwelling is built in the castle from the Kingdom Overview screen.

In the example, paladin sprite to crusader sprite after building the upgraded cathedral.

In fheroes2:

https://github.com/ihhub/fheroes2/assets/43583994/a219bf2a-816c-4f8e-bd08-c8263a58abe9

### Save file

Here is the save file:
[Update kingdom screen 01.zip](https://github.com/ihhub/fheroes2/files/14406777/Update.kingdom.screen.01.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #8437

`master` branch:

https://github.com/ihhub/fheroes2/assets/32623900/29f8d2a4-0b76-4fd1-b0a5-dc040ee26074

This PR:

https://github.com/ihhub/fheroes2/assets/32623900/10647ac2-cddd-44b5-b3c6-43d12b1be8d6

### CODE REVIEW

File: src/fheroes2/castle/buildinginfo.cpp [hunk 1]
```diff
@@ -714,20 +714,17 @@ void BuildingInfo::SetStatusMessage( StatusBar & bar ) const
...
-
 DwellingsBar::DwellingsBar( Castle & cstl, const fheroes2::Size & sz )
     : castle( cstl )
     , backsf( sz.width, sz.height )
 {
     backsf.reset();
 
-    for ( uint32_t dw = DWELLING_MONSTER1; dw <= DWELLING_MONSTER6; dw <<= 1 )
-        content.emplace_back( castle, dw );
+    content.reserve( CountBits( DWELLING_MONSTERS ) );
```
Comment (dood-apo) [inline src/fheroes2/castle/buildinginfo.cpp:723]: If we're already refactoring `CountBits`, we might as well get rid of it and just call `std::bitset<32>{DWELLING_MONSTERS}.count()`.

Comment (oleg-derevenetz) [reply src/fheroes2/castle/buildinginfo.cpp:723]: Hi @dood-apo the purpose of refactoring was to make bit counting `constexpr`, but `std::bitset::count()` is `constexpr` [only since C++23](https://en.cppreference.com/w/cpp/utility/bitset/count). We are now on C++17, so it would be an inadequate replacement.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you so much for this fix!
