### PR TITLE
Fix for the #3117

### LINKED ISSUE #3117: Hero lvlup window, Necromancy skill shows current % instead of actual
Skill info shows the actual % When hero gains necromancy skill: 0 for basic, 10 for advanced, 20 for expert. Only for LVLup window.
In hero info everything is correct.
image
[Necromancy 0.zip](https://github.com/ihhub/fheroes2/files/6269831/Necromancy.0.zip)

### PR DESCRIPTION
**Pull request by kant2002**
Closes #3117

### CODE REVIEW

**Comment by kant2002** [comment]
I place test separately https://github.com/kant2002/fheroes2/commit/782d6c86304f670fb591c659e53d09527de9c864 until Test project lands in main branch.

File: src/fheroes2/heroes/skill.cpp [hunk 1]
```diff
@@ -565,7 +565,7 @@ std::string Skill::Secondary::GetDescription( const Heroes & hero ) const
         }
         break;
     case NECROMANCY: {
-        const uint32_t necroCount = Skill::GetNecromancyPercent( hero );
+        const uint32_t necroCount = std::max( Skill::GetNecromancyPercent( hero ), count );
```
Comment (ihhub) [inline src/fheroes2/heroes/skill.cpp:568]: Could you please verify this check with Spade of Necromancy artifact as well as built Shrines? I think this will not work. The correct solution should be
```
Skill::GetNecromancyPercent( hero ) - hero.GetSecondaryValues( Skill::Secondary::NECROMANCY ) + count;
```

**Review by ihhub — CHANGES_REQUESTED** [review]

File: src/fheroes2/heroes/skill.cpp (hunk 1 above)
Comment (kant2002) [reply src/fheroes2/heroes/skill.cpp:568]: Seems to be correct. If hero `PickupArtifact` `Artifact::SPADE_NECROMANCY` then message with proposed fix produced `Basic Necromancy (+1) allows 20 percent of the creatures killed in combat to be brought back from the dead as Skeletons.` which seems to be right.

Comment (kant2002) [reply src/fheroes2/heroes/skill.cpp:568]: Add one more test in kant2002@b5f72fd9

**Comment by ihhub** [comment]
@kant2002 , thank you so much for fixing this bug!
