### PR TITLE
Add global hotkey to toggle the text support mode, fix the toggling of fullscreen mode a bit

### LINKED ISSUE #6370: Implement Global Hot Key to enable Text Support mode
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

Right now to turn on text support mode you have to be able to visually navigate to the settings after turning on the game in order to turn on text mode. This defeats the purpose of this feature because many people with visual impairment wouldn't be able to do this. A global hotkey for enabling and disabling it could be one solution.

It has to be possible to turn on this feature when first running the game and the welcome dialog appears.

### Describe the possible solution

Add a Hot Key for text mode.

### Additional info

Any other solutions are welcome. For example enabling during installation.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
close #6370

F10 by default.

### CODE REVIEW

**Comment by oleg-derevenetz** [comment]
@ihhub I assigned the 1.01 milestone for this PR, but it's up to you to decide whether you will risk it or not :)

**Comment by oleg-derevenetz** [comment]
> The only thing I noticed is that the state of this option does not visually change in the config dialog when you press F10.

Yeah, I forgot about that config dialog. Thought it was still only set via the configuration file.

File: src/fheroes2/dialog/dialog_game_settings.cpp [hunk 1]
```diff
@@ -214,6 +222,16 @@ namespace
...
             }
+
+            // Text support mode can be toggled using a global hotkey, we need to properly reflect this change in the UI
+            if ( isTextSupportModeEnabled != Settings::Get().isTextSupportModeEnabled() ) {
+                isTextSupportModeEnabled = Settings::Get().isTextSupportModeEnabled();
+
+                emptyDialogRestorer.restore();
+                drawOptions();
+
+                display.render();
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_game_settings.cpp:233]: Please use this call `display.render( { emptyDialogRestorer.x(), emptyDialogRestorer.y(), emptyDialogRestorer.width(), emptyDialogRestorer.height()} );` to avoid whole screen re-rendering. Or you can create a **fheroes2::Rect** before the loop and use it here.

File: src/fheroes2/dialog/dialog_game_settings.cpp [hunk 2]
```diff
@@ -214,6 +222,16 @@ namespace
             else if ( le.MousePressRight( okayButton.area() ) ) {
                 fheroes2::showStandardTextMessage( _( "Okay" ), _( "Exit this menu." ), 0 );
             }
+
+            // Text support mode can be toggled using a global hotkey, we need to properly reflect this change in the UI
+            if ( isTextSupportModeEnabled != Settings::Get().isTextSupportModeEnabled() ) {
+                isTextSupportModeEnabled = Settings::Get().isTextSupportModeEnabled();
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_game_settings.cpp:228]: Please use `conf` over `Settings::Get()`. This variable is declared at the beginning of the function.

File: src/fheroes2/dialog/dialog_game_settings.cpp [hunk 3]
```diff
@@ -149,18 +151,24 @@ namespace
...
+        };
+
+        drawOptions();
 
         fheroes2::ButtonSprite okayButton( windowRoi.x + 112, windowRoi.y + 252, buttonOkayReleased, buttonOkayPressed );
         okayButton.draw();
 
         display.render();
 
+        bool isTextSupportModeEnabled = Settings::Get().isTextSupportModeEnabled();
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_game_settings.cpp:170]: Please use `conf` over `Settings::Get()`. This variable is declared at the beginning of the function.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @oleg-derevenetz , I put several comments in this pull request. Could you please take a look?

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@oleg-derevenetz , thanks a lot for these changes!
