### PR TITLE
Fix number of ghosts and splitting for Shipwreck, Haunt and Abandoned Mine cases

### LINKED ISSUE #5662: Combat, Shipwreck, wrong number of ghosts, ghost groups and their positioning
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the Shipwreck functioning is different from the original game.

In fheroes2:

**Shipwreck:**
- The number of ghosts cannot evolve over the combats, as in the original game.
- There is a different number of ghosts than in the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

In original game:

**Shipwreck:**

It works the same way as for the abandoned mine:
- The number of ghosts does not increase or decrease if the combat is not won and another combat is started on the same shipwreck.
- The number of ghost groups and their positioning in the battlefield hexes is related to the position of the shipwreck on the adventure map.
...
This is certainly determined at the start of the scenario for all shipwrecks.

In original game:

Shipwreck H2 007

Shipwreck H2 003

Shipwreck H2 001

The reward works this way:
- win the combat against 10 ghosts gives 1000 gold (30%).
- win the combat against 15 ghosts gives 2000 gold (30%).
- win the combat against 25 ghosts gives 5000 gold (30%).
- win the combat against 50 ghosts gives 2000 gold and 1 random artifact (10%).

Note: I have used the percentage given on this page: https://handbookhmm.ru/2-objects.

In original game:

10 ghosts:
Shipwreck H2 004

15 ghosts:
Shipwreck H2 002

25 ghosts:
Shipwreck H2 008

50 ghosts:
Shipwreck H2 022

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1185846862_

### Save file

Here is the test scenario file:
[0 9930.zip](https://github.com/ihhub/fheroes2/files/9123469/0.9930.zip)

### Additional info

Related issues: https://github.com/ihhub/fheroes2/issues/5651, https://github.com/ihhub/fheroes2/issues/5663.
Related discussion: https://github.com/ihhub/fheroes2/discussions/5664.

### LINKED ISSUE #5663: Combat, Haunt spell, wrong number of ghost groups and their positioning
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the Haunt spell functioning related to the mine is different from the original game.

In fheroes2:

**Haunt spell:**
- The number of ghosts can evolve over the combats, as in the original game.
- There is a number of ghosts similar to the original game.
- There is a different number of ghost groups and the positioning of these ghost groups than in the original game.

In original game:

**Haunt spell:**

Here again, it works in the same way as for the abandoned mine regarding the number of ghost groups and their positioning in the hexes of the battlefield, which is therefore related to the position of the mine on the adventure map.

The total number of ghosts generated corresponds to 4 ghosts multiplied by the hero's Spell Power value.

In the case of the Haunt spell, the number of ghosts is conserved over the course of the combats if the first combat is not won, and it can therefore increase or decrease if another combat is started on the same haunted mine.

In original game:

Kastore generates 12 ghosts (4 x 3 Spell Power) before attacking them:
Haunt H2 001

Kastore reduced the number of ghosts to 6 before running away and attacking them again:
Haunt H2 002

Innocent peasants are sent to feed the ghosts for the purpose of the demonstration: :)
Haunt H2 003

Kastore attacks again the ghosts whose number has been increased by the martyr imposed on these brave peasants, peace to their souls:
Haunt H2 004

_Originally posted by @LeHerosInconnu in https://github.com/ihhub/fheroes2/issues/5651#issuecomment-1185846862_

### Save file

Here is the test scenario file:
[0 9930.zip](https://github.com/ihhub/fheroes2/files/9123469/0.9930.zip)

### Additional info

Related issues: https://github.com/ihhub/fheroes2/issues/5651, https://github.com/ihhub/fheroes2/issues/5662.
Related discussion: https://github.com/ihhub/fheroes2/discussions/5664.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #5662
fix #5663

Related to #5651 (this PR does nothing with saving the number of ghosts after a battle, let's postpone it for a while because there is a topic for discussion).

Replaces the #5654.

### CODE REVIEW

File: src/fheroes2/army/army.cpp [hunk 1]
```diff
@@ -623,6 +622,36 @@ void Troops::ArrangeForBattle( bool upgrade )
     }
 }
 
+void Troops::ArrangeForBattle( const Monster & monster, const uint32_t monstersCount, const uint32_t stacksCount )
+{
+    assert( stacksCount > 0 && stacksCount <= size() && size() == ARMYMAXTROOPS );
+    assert( std::all_of( begin(), end(), []( const Troop * troop ) { return troop->isEmpty(); } ) );
+
+    size_t stacks;
```
Comment (ihhub) [inline src/fheroes2/army/army.cpp:630]: Let's make it `uint32_t to avoid implicit and explicit casting.

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , everything looks great! I left just one tiny comment. Could you please take a look?

File: src/fheroes2/army/army.cpp (hunk 1 above)
Comment (oleg-derevenetz) [reply src/fheroes2/army/army.cpp:630]: In this case we still need casting when calculating `shift` - either `size()` should be casted to `uint32_t` or `stacks` should be casted to `size_t`.

Comment (ihhub) [reply src/fheroes2/army/army.cpp:630]: Yeah, a bit useless then.

**Comment by ihhub** [comment]
@oleg-derevenetz , thank you very much for these changes!
