### PR TITLE
correct rounding of raising skeletons count

### LINKED ISSUE #6871: Combat, Necromancy, number of skeletons raised is not rounded up correctly
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, the number of skeletons raised is not rounded up correctly.

In fheroes2:

In the example, for 10% of 21 decimated peasants (2.1), 2 skeletons are raised instead of 3 (standard and instant combat):
Necromancy standard combat 003
Necromancy standard combat 004
Necromancy instant combat 001
Necromancy instant combat 002

In the example, for 10% of 22 decimated peasants (2.2), 2 skeletons are raised instead of 3 (standard and instant combat):
Necromancy standard combat 005
Necromancy standard combat 006
Necromancy instant combat 003
Necromancy instant combat 004

In the example, for 10% of 23 decimated peasants (2.3) and then up to 30 decimated peasants, 3 skeletons are raised (standard and instant combat), so from there to 30, it is correct:
Necromancy standard combat 007
Necromancy standard combat 008
Necromancy instant combat 005
Necromancy instant combat 006

### Save file

Here is the test scenario file:
[0 9924d.zip](https://github.com/ihhub/fheroes2/files/11019394/0.9924d.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by undef21**
Number of skeletons is rounded down now.
Also unused code is cleaned. 
fix #6871

### CODE REVIEW

File: src/fheroes2/battle/battle_main.cpp [hunk 1]
```diff
@@ -408,26 +408,24 @@ void Battle::EagleEyeSkillAction( HeroBase & hero, const SpellStorage & spells,
...
 
     if ( 0 == enemyTroopsKilled || ( army.isFullHouse() && !army.HasMonster( Monster::SKELETON ) ) )
         return;
 
     const uint32_t necromancyPercent = GetNecromancyPercent( hero );
-    const uint32_t raisedMonsterType = Monster::SKELETON;
 
-    const Monster mons( Monster::SKELETON );
-    uint32_t raiseCount = Monster::GetCountFromHitPoints( raisedMonsterType, mons.GetHitPoints() * enemyTroopsKilled * necromancyPercent / 100 );
+    uint32_t raiseCount = enemyTroopsKilled * necromancyPercent / 100;
```
Comment (oleg-derevenetz) [inline src/fheroes2/battle/battle_main.cpp:420]: How about

```cpp
const uint32_t raiseCount = std::max( enemyTroopsKilled * necromancyPercent / 100, 1U );
```

instead of this line and both lines below?

Comment (undef21) [reply src/fheroes2/battle/battle_main.cpp]: Thank you. Fixed.

**Review by ihhub — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]

**Comment by ihhub** [comment]
@undef21 , thank you so much for the fix!
