### PR TITLE
Battle log & spell resistance fix

### LINKED ISSUE #2425: Combat, Dwarves and Battle Dwarves must not resist the creatures' ability during combat
In fheroes2, Dwarves and Battle Dwarves must not resist the creatures' ability during combat:
- "Curse" ability from Mummy and Royal Mummy
- "Paralyze" ability from Cyclops
- "Blind" ability from Unicorn
- "Stone" ability from Medusa

In the original game, this does not happen.

Dwarves and Battle Dwarves should resist only when a **spell** is cast by the hero, not at an **ability** of creature, even if this ability has the same effect as a spell.

In fheroes2, Dwarves resist the Curse ability from Mummy:

Dwarves resist mummies spell fh2 01

### LINKED ISSUE #3269: Combat, when Dwarves resist a spell on the first turn of the AI attacking an opposing hero, the spell is not indicated in the logs
In fheroes2, When Dwarves resist a spell on the first turn of the AI attacking an opposing hero, the spell is not indicated in the logs.

In fheroes2:

Spell not indicated fh2 01

End the turn.
(You may have to restart the savegame several times.)

Here is the save file:
[No spell indicated first turn A.zip](https://github.com/ihhub/fheroes2/files/6370737/No.spell.indicated.first.turn.A.zip)

**Edit.**

Also, the expression "Turn 1" should be indicated at the beginning of the combat, before the AI player's actions.

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
fix #2425
fix #3269

Sorry to make a single PR for these two (at first sight) unrelated issues but it's really easier to fix them together.

### CODE REVIEW

File: src/fheroes2/battle/battle_interface.h [hunk 1]
```diff
@@ -205,9 +205,11 @@ namespace Battle
         void SetArmiesOrder( const Units * );
         void FadeArena( bool clearMessageLog );
 
+        void RedrawActionNewTurn() const;
         void RedrawActionAttackPart1( Unit &, Unit &, const TargetsInfo & );
         void RedrawActionAttackPart2( Unit &, TargetsInfo & );
-        void RedrawActionSpellCastPart1( const Spell &, s32, const HeroBase *, const std::string &, const TargetsInfo & );
+        void RedrawActionSpellCastStatus( const Spell & spell, s32 dst, const std::string & name, const TargetsInfo & targets );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_interface.h:211]: Could you please use `int32_t` instead of `s32` since it's a new method?

**Review by ihhub — COMMENTED** [review]
Hi @oleg-derevenetz , I left just few minor comments here. Would you mind to take a look?

**Comment by ihhub** [comment]
@oleg-derevenetz  good job! Thanks for fixing them!
