### PR TITLE
Fix Spell Scroll artifact X position on the Adventure Map

### LINKED ISSUE #8757: Adventure map, center the spell scroll sprite horizontally in the square of the adventure map
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.

### Describe the problem requiring a solution

It has been bugging me for a long time, even in the original game, that the spell scroll sprite isn't centered horizontally in the square of the adventure map.
I corrected this in the original game by modifying the original sprite.
It would be nice to do this as standard in fheroes2. :)

In original game:

Spell scroll heroes 2 01

In original game with the corrected graphic:

Spell scroll heroes 2 modified 01

In fheroes2:

Center spell scroll 01

### Describe the possible solution

Center the spell scroll sprite horizontally in the square of the adventure map.

### Additional info

Related issue: https://github.com/ihhub/fheroes2/issues/8756.

### PR DESCRIPTION
**Pull request by ihhub**
Spell Scroll is the only artifact that consists of 1 image so what we needed to do is to center it properly in a tile.

image

close #8757

### CODE REVIEW

**Comment by LeHerosInconnu** [comment]
Hello @iihhub,

The spell scroll sprite should be shifted three pixels to the left to be centered horizontally.

In fheroes2:

Spellscroll recadré 01

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , unfortunately to do this we need to create 2 images of one. Let's consider this as an intermediate step towards the final goal.

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -4247,7 +4247,12 @@ namespace
         case ICN::OBJNARTI:
             LoadOriginalICN( id );
             if ( _icnVsSprite[id].size() == 206 ) {
-                // If we have the Price of Loyalty assets we make a map sprite for the Magic Book artifact.
+                // These are the Price of Loyalty assets.
+
+                // Spell Scroll has an invalid offset by X axis.
+                _icnVsSprite[id][173].setPosition( ( 32 - _icnVsSprite[id][173].width() ) / 2, _icnVsSprite[id][173].y() );
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:4253]: Hi, @ihhub, the original sprite width is 21 pixels so we have ( 32 - 21 ) / 2 = 5 pixels to shift this sprite without a need to move shadow to the left part sprite. Now we can move it 3 pixels to the left without worrying. :)

изображение

```suggestion
                _icnVsSprite[id][173].setPosition( ( 32 - _icnVsSprite[id][173].width() ) / 2 - 3, _icnVsSprite[id][173].y() );
```

Comment (ihhub) [reply src/fheroes2/agg/agg_image.cpp:4253]: You are absolutely right!

**Comment by ihhub** [comment]
Hi @LeHerosInconnu , the position was updated.

**Review by Districh-ru — APPROVED** [review]

**Comment by LeHerosInconnu** [comment]
Hello @iihhub,

> Hi @LeHerosInconnu , the position was updated.

I've tested it and it's perfect.
Thank you.
