### PR TITLE
Fixed missing column of pixels

### LINKED ISSUE #5433: Scenario window, purple color of the background of the text indication of the opponents' colors does not go to the frame for red, yellow and purple players
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

In fheroes2, purple color of the background of the text indication of the opponents' colors does not go to the frame for red, yellow and purple players.
One pixel wide is of a different color.

In fheroes2:

Scenario window flèches 01

### Save file

Not needed.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by felix642**
closes #5433 

image

### CODE REVIEW

File: src/fheroes2/gui/player_info.cpp [hunk 1]
```diff
@@ -269,6 +269,10 @@ void Interface::PlayersInfo::RedrawInfo( bool show_play_info ) const /* show_pla
 
         const fheroes2::Sprite & playerIcon = fheroes2::AGG::GetICN( ICN::NGEXTRA, index );
         fheroes2::Blit( playerIcon, display, rect1.x, rect1.y );
+
+        // playerIcon sprite is missing a column of pixels.
```
Comment (ihhub) [inline src/fheroes2/gui/player_info.cpp:273]: This is not a correct fix. Please do this in agg_image.cpp file:
```cpp
            case ICN::NGEXTRA: {
                LoadOriginalICN( id );
                std::vector<Sprite> & images = _icnVsSprite[id];

                if ( images.size() >= 34 ) {
                    
                    // Fix extra column at the end of AI controlled player.
                    for ( size_t i = 27; i < 34; ++i ) {
                        if ( images[i].width() == 62 && images[i].height() == 58 ) {
                            Copy( images[i], 58, 44, images[i], 59, 44, 1, 11 );
                        }
                    }

                    for ( size_t i = 39; i < 45; ++i ) {
                        if ( images[i].width() == 62 && images[i].height() == 58 ) {
                            Copy( images[i], 58, 44, images[i], 59, 44, 1, 11 );
                        }
                    }
                }
                if ( images.size() >= 70 ) {
                    // fix transparent corners on pressed OKAY and CANCEL buttons
                    CopyTransformLayer( images[66], images[67] );
                    CopyTransformLayer( images[68], images[69] );
                }
                return true;
            }
```

**Review by ihhub — CHANGES_REQUESTED** [review]

**Comment by ihhub** [comment]
Hi @felix642 , please fix code styling in this pull request.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@felix642 , thank you very much for this fix!
