### PR TITLE
aling horizontal positions of columns and flags at oracle dialog

### LINKED ISSUE #1592: Adventure Map, Oracle screen, wrong position of the flags
In fheroes2, for the categories "Gold in Treasury:", "Wood & Ore:" and "Gems, Cr, Slf & Mer:" the flags of the green player are not located in the column "1st" as it is the case in the original game (the category "Artifacts:" is missing (https://github.com/ihhub/fheroes2/issues/1591)).

In original game:

Oracle 03

In fheroes2:

Oracle 04

### LINKED ISSUE #1593: Adventure Map, Oracle screen, wrong position of the columns
In fheroes2, the horizontal position of the columns "1st", "2nd", etc. is not the same as in the original game.

In original game:

Oracle 03

In fheroes2:

Oracle 04

### PR DESCRIPTION
**Pull request by undef21**
fix #1592
fix #1593

### CODE REVIEW

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 1]
```diff
@@ -406,16 +403,15 @@ void Dialog::ThievesGuild( bool oracle )
...
     if ( 4 < count )
-        DrawFlags( v, dst_pt, maxw, colors.size() );
+        DrawFlags( v, dst_pt, stepx, colors.size() );
 
     // head 2
     ii = 0;
     for ( Colors::const_iterator color = colors.begin(); color != colors.end(); ++color ) {
         text.Set( Color::String( *color ) );
-        dst_pt.x = cur_pt.x + startx + maxw / ( colors.size() * 2 ) + ii * maxw / colors.size() - text.w() / 2;
+        dst_pt.x = cur_pt.x + startx + ii++ * stepx - text.w() / 2;
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:412]: Please do not use variable increment within another statement. Make it on a separate line.

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 2]
```diff
@@ -253,18 +250,18 @@ void Dialog::ThievesGuild( bool oracle )
...
     const int textx = 185;
-    const int startx = 210;
-    const int maxw = 430;
+    const int startx = 264;
+    const int stepx = 68;
     Text text;
 
     // head 1
-    u32 ii = 0;
+    uint32_t ii = 0;
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:264]: Please make this variable type `int32_t`.

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 3]
```diff
@@ -196,35 +196,32 @@ void GetBestHeroArmyInfo( std::vector<ValueColors> & v, const Colors & colors )
...
 {
-    const uint32_t chunk = static_cast<uint32_t>( width / count );
-
-    for ( u32 ii = 0; ii < count; ++ii ) {
+    for ( uint32_t ii = 0; ii < count; ++ii ) {
         if ( ii < v.size() ) {
             const Colors colors( v[ii].second );
-            const u32 sw = fheroes2::AGG::GetICN( ICN::FLAG32, 1 ).width();
-            s32 px = pos.x + chunk / 2 + ii * chunk - ( colors.size() * sw ) / 2;
+            const uint32_t sw = fheroes2::AGG::GetICN( ICN::FLAG32, 1 ).width();
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:204]: Please make this variable type `int32_t`.

File: src/fheroes2/dialog/dialog_thievesguild.cpp [hunk 4]
```diff
@@ -196,35 +196,32 @@ void GetBestHeroArmyInfo( std::vector<ValueColors> & v, const Colors & colors )
     }
 }
 
-void DrawFlags( const std::vector<ValueColors> & v, const fheroes2::Point & pos, size_t width, size_t count )
+void DrawFlags( const std::vector<ValueColors> & v, const fheroes2::Point & pos, int step, size_t count )
 {
-    const uint32_t chunk = static_cast<uint32_t>( width / count );
-
-    for ( u32 ii = 0; ii < count; ++ii ) {
+    for ( uint32_t ii = 0; ii < count; ++ii ) {
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_thievesguild.cpp:201]: Please make this variable type `int32_t`.

**Review by ihhub — COMMENTED** [review]
Hi @undef21 , I left few comments here. Would you mind to take a look?
