### PR TITLE
fix hardcoded icon

### LINKED ISSUE #1155: Wrong "Okay" button is in System Options menu
Gray button should be added into this menu.
Okay button

### PR DESCRIPTION
**Pull request by ghostBot**
fix #1155. Button icon was hardcoded

### CODE REVIEW

File: src/fheroes2/dialog/dialog_system.cpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ int Dialog::SystemOptions( void )
 
     LocalEvent & le = LocalEvent::Get();
 
-    Button buttonOkay( area.x + 96, area.y + 350, ICN::SPANBTN, 0, 1 );
+    Button buttonOkay( area.x + 96, area.y + 350, Settings::Get().ExtGameEvilInterface() ? ICN::SPANBTNE : ICN::SPANBTN, 0, 1 );
```
Comment (ihhub) [inline src/fheroes2/dialog/dialog_system.cpp:79]: @ghostBot  please use `conf` variable instead which is defined at the beginning of this method.

Comment (ghostBot) [reply src/fheroes2/dialog/dialog_system.cpp]: oops, fix it. thanks

**Comment by ihhub** [comment]
@ghostBot , thank you very much for your continuous contribution!
