### PR TITLE
Fix crash at the start of every map

### LINKED ISSUE #6765: Crash when starting a map that contains heroes with non-default experience value
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

How to reproduce:

1. Build the game in debug mode (with `WITH_DEBUG` defined);
2. Run the game and start the attached map (or any other map that contains heroes with non-default experience, e.g. "Arrax the Jerk");
3. Observe the crash inside the `Heroes::Scoute()` method during the hero level up.

### Save file

[!BOATTST.zip](https://github.com/ihhub/fheroes2/files/10893226/BOATTST.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6765

### CODE REVIEW

**Review by oleg-derevenetz — APPROVED** [review]

**Review by Districh-ru — APPROVED** [review]
I added the condition to the `LevelUpSecondarySkill()` method which is called during map load for all heroes before they are assigned to any kingdom. IMHO it is not good to reveal the fog for the unused player with NONE color as it might lead to possible game crush in future.

File: src/fheroes2/heroes/heroes.cpp [hunk 1]
```diff
@@ -1440,8 +1441,8 @@ void Heroes::LevelUpSecondarySkill( const HeroSeedsForLevelUp & seeds, int prima
         else
             secondary_skills.AddSkill( Skill::Secondary( selected.Skill(), Skill::Level::BASIC ) );
 
-        // post action
-        if ( selected.Skill() == Skill::Secondary::SCOUTING ) {
+        // Scout the area around the hero if his Scouting skill was leveled and he belongs to any kingdom.
+        if ( ( selected.Skill() == Skill::Secondary::SCOUTING ) && ( GetColor() != Color::NONE ) ) {
```
Comment (oleg-derevenetz) [inline src/fheroes2/heroes/heroes.cpp:1445]: Hi @Districh-ru Probably even better to check for `!isFreeman()` here instead.

**Comment by ihhub** [comment]
Hi @Branikolog , please test this pull request once it allow to download artifact ASAP. Crashes are not acceptable by any means.

File: src/fheroes2/heroes/heroes.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/heroes/heroes.cpp]: Thanks, @oleg-derevenetz!
It will be a better protection.

Comment (oleg-derevenetz) [reply src/fheroes2/heroes/heroes.cpp:1445]: @Districh-ru After some thought, I realized that jailed heroes are not freemans as well, because  they are not available for hire, although they shouldn't scout.

Comment (Districh-ru) [reply src/fheroes2/heroes/heroes.cpp:1445]: @oleg-derevenetz yes, you are right.

**Comment by ihhub** [comment]
@oleg-derevenetz and @Districh-ru , thank you guys for polishing this fix!
