### PR TITLE
Fix catapult's boulder animation

### LINKED ISSUE #6075: Castle siege, catapult projectile misses spinning animation
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

image
image

Currently rock sprite moves over the battlefield being static.
In the original game projectile spins during the whole flight.

### Save file

Could be reproduced at any castle siege.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #6075

### CODE REVIEW

**Review by Branikolog — APPROVED** [review]

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -3991,9 +3990,13 @@ void Battle::Interface::RedrawActionCatapult( int target, bool hit )
     pt2.y += area.y;
     max.y += area.y;
 
-    const std::vector<fheroes2::Point> points = GetArcPoints( pt1, pt2, max, missile.width() );
+    const fheroes2::Sprite & boulderFirstFrame = fheroes2::AGG::GetICN( ICN::BOULDER, 0 );
+    const std::vector<fheroes2::Point> points = GetArcPoints( pt1, pt2, max, boulderFirstFrame.width() );
     std::vector<fheroes2::Point>::const_iterator pnt = points.begin();
 
+    uint32_t boulderFrameId = 0;
+    const uint32_t boulderMaxFrame = fheroes2::AGG::GetICNCount( ICN::BOULDER );
```
Comment (oleg-derevenetz) [inline src/fheroes2/battle/battle_interface.cpp:3998]: I would like just to point out that `...MaxFrame` might give an impression that this frame is included in the set of allowed frame id values, although from the rest of the code looks like this is not really the case :) Maybe `boulderFramesCount` is better? LGTM in general.

**Review by oleg-derevenetz — APPROVED** [review]

File: src/fheroes2/battle/battle_interface.cpp (hunk 1 above)
Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp:3998]: I can't argue with this. I will update the pull request.

Comment (ihhub) [reply src/fheroes2/battle/battle_interface.cpp]: Fixed.
