### PR TITLE
Fix hero, castle and status army info

### LINKED ISSUE #203: Creatures are shown overlapped in world map menu window
Have multiple creatures in your army and see them in world map window:
viber_image_2019-10-23_23-10-26

You could see that creatures are overlap each other which is a serious bug (check right bottom part of the image).

### PR DESCRIPTION
**Pull request by idshibanov**
Fixes #203 

1. Army in status window (using OG values and text to the side rather than under the icon).
2. Castle window update: shifted top part and re-aligned the troops. Amount of information depend on thief guild level rather than Scouting skill - we can do it later.
3. Hero window rework: hide stats for enemy heroes and align the army accordingly.

image

### CODE REVIEW

File: src/fheroes2/army/army.h [hunk 1]
```diff
@@ -140,6 +140,7 @@ class Army : public Troops, public Control
     static void DrawMons32Line( const Troops &, s32, s32, u32, u32 = 0, u32 = 0 );
     static void DrawMons32LineWithScoute( const Troops &, s32, s32, u32, u32, u32, u32 );
     static void DrawMons32LineShort( const Troops &, s32, s32, u32, u32, u32 );
+    static void DrawMonsterLines( const Troops & troops, s32 posX, s32 posY, u32 lineWidth, u32 scout = 3, bool compact = true );
```
Comment (ihhub) [inline src/fheroes2/army/army.h:143]: Assigning `scout` to 3 is incorrect as we do not know what 3 means. To be safe let's remove default value for **scout**

File: src/fheroes2/army/army.h [hunk 2]
```diff
@@ -140,6 +140,7 @@ class Army : public Troops, public Control
     static void DrawMons32Line( const Troops &, s32, s32, u32, u32 = 0, u32 = 0 );
     static void DrawMons32LineWithScoute( const Troops &, s32, s32, u32, u32, u32, u32 );
     static void DrawMons32LineShort( const Troops &, s32, s32, u32, u32, u32 );
```
Comment (ihhub) [inline src/fheroes2/army/army.h:142]: We could remove `DrawMons32LineShort` function as it is not used anywhere after the changes.

**Comment by ihhub** [comment]
@idshibanov , thanks a lot for fixing this issue!
