### PR TITLE
AI heroes now use spells from scrolls

### LINKED ISSUE #5930: Battle, AI seemed to ignore spells from scrolls
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

I noticed, that in 100% same conditions AI doesn't use spell "Haste" from the obtained scroll, but at the same time, when we choose opponent as Necromancer (which obviously has "Haste" spell in his spell book) he uses the spell regularly.
image

### Save file

[save.zip](https://github.com/ihhub/fheroes2/files/9732260/save.zip)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
Also heroes will have better army estimation. close #5930

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @Branikolog , please verify this change. I used your saves and AI now uses Scrolls.

File: src/fheroes2/ai/normal/ai_normal_spell.cpp [hunk 1]
```diff
@@ -376,7 +376,7 @@ namespace AI
         else if ( spellID == Spell::ANTIMAGIC && !target.Modes( IS_GOOD_MAGIC ) && _enemySpellStrength > antimagicLowLimit ) {
             double ratioLimit = 0.9;
 
-            const std::vector<Spell> & spellList = _commander->GetSpells();
+            const SpellStorage & spellList = _commander->getAllSpells();
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_spell.cpp:379]: We don't need a reference here. While technically this will work because of reference lifetime extension, this doesn't provide any benefits.

File: src/fheroes2/ai/normal/ai_normal_spell.cpp [hunk 2]
```diff
@@ -545,7 +545,7 @@ namespace AI
 
     double BattlePlanner::commanderMaximumSpellDamageValue( const HeroBase & commander )
     {
-        const std::vector<Spell> & spells = commander.GetSpells();
+        const SpellStorage & spells = commander.getAllSpells();
```
Comment (oleg-derevenetz) [inline src/fheroes2/ai/normal/ai_normal_spell.cpp:548]: We don't need a reference here as well.

File: src/fheroes2/heroes/heroes_base.cpp [hunk 3]
```diff
@@ -333,7 +332,7 @@ int HeroBase::GetLuckModificator( std::string * strs ) const
 
 double HeroBase::GetMagicStrategicValue( const double armyStrength ) const
 {
-    const std::vector<Spell> & spells = GetSpells();
+    const SpellStorage & spells = getAllSpells();
```
Comment (oleg-derevenetz) [inline src/fheroes2/heroes/heroes_base.cpp:335]: We don't need a reference here as well.

**Review by oleg-derevenetz — CHANGES_REQUESTED** [review]
Hi @ihhub I just left a few minor suggestions, please take a look when it's convenient for you.

**Review by Branikolog — APPROVED** [review]
Now AI uses spells from scrolls in his inventory. 👍 Thanks a lot for such a prompt fix!

**Review by zenseii — APPROVED** [review]

**Review by oleg-derevenetz — APPROVED** [review]
