### PR TITLE
Fix mouse cursor switching while navigating on hero or castle panel

### LINKED ISSUE #2324: Adventure screen, sometimes the mouse cursor "Horse" is displayed briefly when the player alternately clicks on the portrait of two heroes in the hero list
In fheroes2, sometimes the mouse cursor "Horse" is displayed briefly when the player alternately clicks on the portrait of two heroes in the hero list or when the player alternately clicks on the graphic of a castle in the castle list and the portrait of a hero in the hero list.

Horse cursor heroes list fh2 01

In fheroes2:

vlcsnap-2020-12-04-14h04m08s092

### PR DESCRIPTION
**Pull request by vincent-grosbois**
close #2324

### CODE REVIEW

**Comment by ihhub** [comment]
Hi @vincent-grosbois I think some of the changes are already presented in master branch from your different pull request. Could you please rebase from master so this pull request will reflect only needed changes?

File: src/fheroes2/gui/interface_events.cpp [hunk 1]
```diff
@@ -54,7 +54,7 @@ void Interface::Basic::CalculateHeroPath( Heroes * hero, s32 destinationIdx )
         gameArea.SetRedraw();
 
         LocalEvent & le = LocalEvent::Get();
-        const int32_t cursorIndex = gameArea.GetValidTileIdFromPoint( le.GetMouseCursor() );
+        const int32_t cursorIndex = gameArea.GetValidTileIdFromPoint( le.GetMouseCursor(), true );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_events.cpp:57]: Hi @vincent-grosbois , the change in `GetValidTileIdFromPoint` is not really relevant to what the method is doing. Let's change the code in **this** method like this:
```
LocalEvent & le = LocalEvent::Get();
const Point mousePos = le.GetMouseCursor();
if ( mousePos & gameArea.GetROI() ) {
    const int32_t cursorIndex = gameArea.GetValidTileIdFromPoint( mousePos );
    Cursor::Get().SetThemes( GetCursorTileIndex( cursorIndex ) );
}
```

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vincent-grosbois could you please take a look at proposed alternative solution?

**Comment by ihhub** [comment]
@vincent-grosbois a bunch of thanks for your valuable contribution to the project!
