### PR TITLE
Center text in hero battle info window

### LINKED ISSUE #7459: Battle screen, text alignment of hero info window
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

The spaces between frame and primary attributes are not equal.
Hero info text

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by ihhub**
close #7459

image

### CODE REVIEW

File: src/fheroes2/battle/battle_dialogs.cpp [hunk 1]
```diff
@@ -844,52 +844,54 @@ int Battle::Arena::DialogBattleHero( const HeroBase & hero, const bool buttons,
...
-    tp.y = pos_rt.y + 40;
+    tp.x = statsTextOffset.x + ( maxStatsTextWidth - text.w() ) / 2;
+    tp.y = statsTextOffset.y;
     text.Blit( tp.x, tp.y );
     str = _( "Defense" ) + std::string( ": " ) + std::to_string( hero.GetDefense() );
     text.Set( str );
-    tp.x = pos_rt.x + 190 - text.w() / 2;
-    tp.y = pos_rt.y + 51;
+    tp.x = statsTextOffset.x + ( maxStatsTextWidth - text.w() ) / 2;
+    tp.y = statsTextOffset.y + statsTextRowHeight;
```
Comment (Districh-ru) [inline src/fheroes2/battle/battle_dialogs.cpp:869]: This and next `tp.y = ` lines can be simplified to:
```suggestion
    tp.y +=  statsTextRowHeight;
```

**Review by Districh-ru — CHANGES_REQUESTED** [review]
Hi, @ihhub, I left one suggestion. Could you please take a look in your spare time.

**Review by Districh-ru — APPROVED** [review]
👍

**Review by Branikolog — APPROVED** [review]
