### PR TITLE
Fixed heroes position on battle screen

### LINKED ISSUE #1491: Combat screen, position of defending hero on the battlefield
In fheroes2, the position of the defending hero on the battlefield is shifted horizontally.

In original game:

Battlefield H2 01

In fheroes2:

Battlefield fh2 02

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.

Battlefield H2 01 right hero 01 Battlefield fh2 02 right hero 01

### PR DESCRIPTION
**Pull request by felix642**
closes #1491

### CODE REVIEW

**Comment by felix642** [comment]
@LeHerosInconnu I would appreciate it if you could take a look at this PR.

**Comment by LeHerosInconnu** [comment]
Hello @felix642,

> @LeHerosInconnu I would appreciate it if you could take a look at this PR.

So I checked the position of the hero defender sprite.
The vertical position is correct.
The horizontal position must be shifted 1 pixel to the left.

In original game:

Defender hero H2 10

In fheroes2:

Defender hero fh2 10

Open the two images in different tabs in your browser, enlarge the images and switch between the two tabs alternately.
Heroes 2 first, fheroes2 second.

Defender hero H2 coupé 10 Defender hero fh2 coupé 10

**Comment by felix642** [comment]
@LeHerosInconnu 

Thank you for the feedback :) 

I have moved the hero to the left by 1 pixel. Just to be sure that we don't break anything would you mind checking the hero at the left to also make sure that his position matches the one in the original game?

**Comment by felix642** [comment]
@ihhub we are ready to merge this PR :)

File: src/fheroes2/battle/battle_interface.cpp [hunk 1]
```diff
@@ -748,7 +748,7 @@ void Battle::OpponentSprite::Redraw( fheroes2::Image & dst ) const
         fheroes2::Blit( hero, dst, offset.x + fheroes2::Display::DEFAULT_WIDTH - HERO_X_OFFSET - ( hero.x() + hero.width() ), offset.y + RIGHT_HERO_Y_OFFSET + hero.y(),
                         reflect );
     else
-        fheroes2::Blit( hero, dst, offset.x + HERO_X_OFFSET + hero.x(), offset.y + LEFT_HERO_Y_OFFSET + hero.y() );
+        fheroes2::Blit( hero, dst, offset.x + HERO_X_OFFSET + hero.x() + 1, offset.y + LEFT_HERO_Y_OFFSET + hero.y() );
```
Comment (oleg-derevenetz) [inline src/fheroes2/battle/battle_interface.cpp:751]: Hi @felix642 how about doing this instead of using this "magic number": make a separate `LEFT_HERO_X_OFFSET` and `RIGHT_HERO_X_OFFSET` (just like their Y offsets) with different values? Is there any reason not to do this?

Comment (felix642) [reply src/fheroes2/battle/battle_interface.cpp]: Thank you for the feedback, I have separated both constants into 2 variables

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @LeHerosInconnu, could you please verify this change?

**Comment by LeHerosInconnu** [comment]
Hello @ihhub,

> Hi @LeHerosInconnu, could you please verify this change?

I checked and the position of the two heroes is correct.

**Comment by ihhub** [comment]
@felix642 , thank you so much for fixing this issue!
