### PR TITLE
Fix idling condition check

### LINKED ISSUE #606: Looped idle animation in battle
One random unit's idle animation is looped. Unit is moving infinitely.

### PR DESCRIPTION
**Pull request by idshibanov**
Reminder to myself: code after `||` won't be executed.

Fixes #606 .

### CODE REVIEW

File: src/fheroes2/battle/battle_army.cpp [hunk 1]
```diff
@@ -392,7 +392,7 @@ bool Battle::Force::animateIdleUnits()
         if ( unit.isValid() && !unit.Modes( SP_BLIND | IS_PARALYZE_MAGIC ) ) {
             if ( unit.isIdling() ) {
                 if ( unit.isFinishAnimFrame() ) {
-                    redrawNeeded = redrawNeeded || unit.SwitchAnimation( Monster_Info::STATIC );
+                    redrawNeeded = unit.SwitchAnimation( Monster_Info::STATIC ) || redrawNeeded;
```
Comment (ihhub) [inline src/fheroes2/battle/battle_army.cpp:395]: How about `|` instead of `||`? :)

**Comment by ihhub** [comment]
@idshibanov , thank you very much for fixing this issue in a fast manner!
