### PR TITLE
Fix Chain lightning logic

### LINKED ISSUE #537: Chain Lighting spell sequence problem
Chain Lighting spell hits units with improper sequence.
Chain
Chain2
On the screenshot I hit 3rd unit with the spell. Then it goes to 2nd unit. After 4th and then 1st.

### LINKED ISSUE #840: "Chain lighting" spell operation while casting over dwarves
"Chain lighting" spell behaves incorrectly, while dwarves' resistance occurs. 
Sometimes the spell hits only one pack of dwarves. Like single Lighting bolt.

### LINKED ISSUE #2327: Combat, Chain Lightning spell doesn't work as it should
In fheroes2, the Chain Lightning spell doesn't work as it should.

In the video examples, there is a troop closer than the Titans or Archmagi of the hero Kastore who should be hit by the spell (Archmagi or Steel Golems of the hero Myra).

In fheroes2:

vlcsnap-2020-12-04-16h00m09s704

vlcsnap-2020-12-04-16h01m32s870

Attack Myra with Kastore.
Reproduce the combat as shown in the larger video.
Here are the save file and videos that show the bug encountered:
[Bug chain lightning fh2 01.zip](https://github.com/ihhub/fheroes2/files/5643747/Bug.chain.lightning.fh2.01.zip)

### PR DESCRIPTION
**Pull request by tau3**
close #2327 
close #840 
close #537

### CODE REVIEW

File: src/fheroes2/battle/battle_board.h [hunk 1]
```diff
@@ -43,7 +43,8 @@ namespace Battle
         return d = ( TOP_LEFT == d ? CENTER : direction_t( d >> 1 ) );
     }
 
-    typedef std::vector<s32> Indexes;
+    typedef s32 Index;
```
Comment (ihhub) [inline src/fheroes2/battle/battle_board.h:46]: Please don't typedef POD. It's very confusing to understand that's it is POD after all.

File: src/fheroes2/battle/battle_arena.h [hunk 2]
```diff
@@ -161,6 +161,9 @@ namespace Battle
 
         s32 GetFreePositionNearHero( int ) const;
         std::vector<int> GetCastleTargets( void ) const;
+        TargetsInfo TargetsForChainLightning( const HeroBase *, Index );
+        Indexes FindChainLightningTargetIndexes( const HeroBase *, Index ) const;
+        bool IsImmuneToChainLightning( Index troop, const HeroBase * hero ) const;
```
Comment (ihhub) [inline src/fheroes2/battle/battle_arena.h:166]: Please do not drop input argument names. The old code contains such but this is a bad styling making the code unreadable to other developers.

Comment (ihhub) [reply src/fheroes2/battle/battle_arena.h:166]: Also here every input argument could be `const`.

File: src/fheroes2/battle/battle_action.cpp [hunk 3]
```diff
@@ -624,51 +674,8 @@ Battle::TargetsInfo Battle::Arena::GetTargetsForSpells( const HeroBase * hero, c
...
-                Unit * target = GetTroopBoard( *it );
-
-                if ( target ) {
-                    res.defender = target;
-                    // store temp priority for calculate damage
-                    res.damage = std::distance( trgts.begin(), it );
-                    targets.push_back( res );
-                }
-            }
+            TargetsInfo targetsForSpell = TargetsForChainLightning( hero, dst );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_action.cpp:677]: This variable should be `const`.

File: src/fheroes2/battle/battle.h [hunk 4]
```diff
@@ -96,6 +96,12 @@ namespace Battle
     struct TargetsInfo : public std::vector<TargetInfo>
     {
         TargetsInfo() {}
+
+        void addAll( const Battle::TargetsInfo & rhs )
```
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/battle/battle.h:100]: Also this method should accept input argument by r-value `&&` and we will just move elements instead of copying them. Use `emplace_back` for this purpose.

File: src/fheroes2/battle/battle_action.cpp [hunk 5]
```diff
@@ -585,6 +585,56 @@ void Battle::Arena::TargetsApplySpell( const HeroBase * hero, const Spell & spel
...
+    const Indexes targetIndexes = FindChainLightningTargetIndexes( hero, attackedTroop );
+    TargetInfo res;
+    for ( auto it = targetIndexes.begin(); it != targetIndexes.end(); ++it ) {
+        Unit * target = GetTroopBoard( *it );
+
+        if ( target ) {
+            res.defender = target;
+            // store temp priority for calculate damage
+            res.damage = std::distance( targetIndexes.begin(), it );
+            targets.push_back( res );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_action.cpp:632]: We can use this:
```
targets.emplace_back();
TargetInfo & res = targets,back();

res.defender = target;
// store temp priority for calculate damage
res.damage = std::distance( targetIndexes.begin(), it );
```
In this case we don't make a copy and also we can remove `TargetInfo res;`.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @tau3 I left multiple comments. Could you please take a look into them?

File: src/fheroes2/battle/battle_action.cpp (hunk 3 above)
Comment (tau3) [reply src/fheroes2/battle/battle_action.cpp:679]: not sure i understand: how do we use it as a `const` with `void append( TargetsInfo && rhs )`?

File: src/fheroes2/battle/battle_action.cpp [hunk 6]
```diff
@@ -585,6 +585,58 @@ void Battle::Arena::TargetsApplySpell( const HeroBase * hero, const Spell & spel
...
+
+Battle::Indexes Battle::Arena::FindChainLightningTargetIndexes( const HeroBase * hero, s32 attackedTroopIndex ) const
+{
+    s32 currentTargetIndex = attackedTroopIndex;
+    Indexes result = { currentTargetIndex };
+    Indexes ignoredTroops = { currentTargetIndex };
+
+    auto predicate = [hero, this]( s32 index ) { return IsImmuneToChainLightning( index, hero ); };
+    while ( result.size() < CHAIN_LIGHTNING_CREATURE_COUNT ) {
+        Indexes nearestTroops = board.GetNearestTroopIndexes( currentTargetIndex, &ignoredTroops );
```
Comment (idshibanov) [inline src/fheroes2/battle/battle_action.cpp:606]: `board.GetNearestTroopIndexes` is buggy and a part of the problem here. It can add two-hex unit twice if you cast the lightning at the "tail" hex. In addition it always calculates distance to "head" index when "tail" could be closer.

File: src/fheroes2/battle/battle_action.cpp [hunk 7]
```diff
@@ -585,6 +585,58 @@ void Battle::Arena::TargetsApplySpell( const HeroBase * hero, const Spell & spel
...
+        std::remove_if( nearestTroops.begin(), nearestTroops.end(), predicate );
```
Comment (idshibanov) [inline src/fheroes2/battle/battle_action.cpp:607]: Add Immune/magic resist troops to `ignoredTroops` list instead of checking/removing it every cycle.

File: src/fheroes2/battle/battle_action.cpp [hunk 8]
```diff
@@ -585,6 +585,58 @@ void Battle::Arena::TargetsApplySpell( const HeroBase * hero, const Spell & spel
...
 }
 
+bool Battle::Arena::IsImmuneToChainLightning( s32 troopIndex, const HeroBase * hero ) const
+{
+    const Unit * target = GetTroopBoard( troopIndex );
+    if ( !target ) {
+        return true;
+    }
+    const int power = hero ? hero->GetPower() : 0;
+    return target->GetMagicResist( Spell::CHAINLIGHTNING, power ) == 100;
```
Comment (idshibanov) [inline src/fheroes2/battle/battle_action.cpp:595]: This comparison is incorrect in my opinion, if resist is in 1-99 range you should run a Rand() call to check if unit resists it this time (Dwarves for example).

File: src/fheroes2/battle/battle.h [hunk 9]
```diff
@@ -96,6 +96,14 @@ namespace Battle
     struct TargetsInfo : public std::vector<TargetInfo>
     {
         TargetsInfo() {}
+
+        void append( TargetsInfo && rhs )
```
Comment (ihhub) [inline src/fheroes2/battle/battle.h:100]: Let's please call it `targetsInfo` to have more sense in the name.

File: src/fheroes2/battle/battle.h [hunk 10]
```diff
@@ -96,6 +96,14 @@ namespace Battle
...
+        {
+            reserve( size() + rhs.size() );
+            for ( TargetInfo info : rhs ) {
+                push_back( info );
```
Comment (ihhub) [inline src/fheroes2/battle/battle.h:104]: We're just copying the data so there is no reason to pass the argument by r-value. Also we could simply use `insert` method which does exactly what this loop is doing.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @tau3 I left multiple comments in this pull request. Could you please take a look into them?

**Comment by ihhub** [comment]
Hi @tau3 could you please fix merge conflict and code styling issues?

File: src/fheroes2/battle/battle_board.cpp [hunk 11]
```diff
@@ -358,40 +359,73 @@ Battle::Indexes Battle::Board::GetPassableQualityPositions( const Unit & b )
...
-        result.reserve( dists.size() );
-        for ( std::vector<IndexDistance>::const_iterator it = dists.begin(); it != dists.end(); ++it )
-            result.push_back( ( *it ).first );
+Battle::Indexes SortIndexesByDistanceAsc( std::vector<IndexDistance> & distances )
+{
+    if ( distances.size() > 1 ) {
+        std::sort( distances.begin(), distances.end(), IndexDistance::Shortest );
+        const uint32_t smallestDistance = distances.front().second;
+        const auto predicate = [smallestDistance]( const IndexDistance & distance ) { return distance.second == smallestDistance; };
+        distances.resize( std::count_if( distances.begin(), distances.end(), predicate ) );
```
Comment (ihhub) [inline src/fheroes2/battle/battle_board.cpp:399]: We don't need to sort the container as `std::count_if` runs through every element of the container. However, since we need to find the smaller element we can do like this to speed things up:
```
std::sort( distances.begin(), distances.end(), IndexDistance::Shortest );
const uint32_t smallestDistance = distances.front().second;

for ( size_t i = 1; i < distances.size(); ++i ) {
    if ( distances[i] != smallestDistance ) {
        distances.resize( i );
        break;
    }
}
```

File: src/fheroes2/battle/battle_board.cpp [hunk 12]
```diff
@@ -358,40 +359,73 @@ Battle::Indexes Battle::Board::GetPassableQualityPositions( const Unit & b )
...
     }
 
+    Battle::Indexes result;
+    for ( IndexDistance distance : distances ) {
```
Comment (ihhub) [inline src/fheroes2/battle/battle_board.cpp:403]: Please use const reference as here we're making a copy of std::pair.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @tau3 ,

I left multiple comments regarding the implementation. Could you please take a look into them?

File: src/fheroes2/battle/battle_action.cpp [hunk 13]
```diff
@@ -585,6 +585,66 @@ void Battle::Arena::TargetsApplySpell( const HeroBase * hero, const Spell & spel
...
+        if ( target == nullptr ) {
+            continue;
+        }
+
+        targets.emplace_back();
+        TargetInfo & res = targets.back();
+
+        res.defender = target;
+        // store temp priority for calculate damage
+        res.damage = std::distance( targetIndexes.begin(), it );
```
[the remark this answers is not in the document]
Comment (tau3) [reply src/fheroes2/battle/battle_action.cpp:642]: i think we shouldn't expect that `FindChainLightningTargetIndexes` return invalid indexes, so check for null can be replaced with `assert`

File: src/fheroes2/battle/battle_board.cpp [hunk 14]
```diff
@@ -358,40 +359,73 @@ Battle::Indexes Battle::Board::GetPassableQualityPositions( const Unit & b )
...
+    }
     return result;
 }
 
+Battle::Indexes Battle::Board::GetNearestTroopIndexes( int32_t position, const Indexes & blackList ) const
+{
+    std::vector<IndexDistance> distances;
+    distances.reserve( 15 /* TODO magic number */ );
+
+    for ( Cell cell : *this ) {
```
[the remark this answers is not in the document]
Comment (tau3) [reply src/fheroes2/battle/battle_board.cpp:414]: yep, good catch.

File: src/fheroes2/battle/battle_board.h [hunk 15]
```diff
@@ -27,6 +27,7 @@
 
 #include "battle.h"
 #include "battle_cell.h"
+#include "pairs.h"
```
[the remark this answers is not in the document]
Comment (tau3) [reply src/fheroes2/battle/battle_board.h:30]: yes, we use `IndexDistance`

**Comment by tau3** [comment]
@ihhub fixed. Unfortunately, i can't see why clang-format fails in reports :\

**Comment by ihhub** [comment]
@tau3 thank you very much for helping to fix these issues!
