### PR TITLE
Fixing Golden bow sprite glowing pixels

### LINKED ISSUE #8520: Golden bow sprite has glowing pixel
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Both large and small sprites of "Golden Bow" artifact have one glowing yellow pixel.
golden bow 1
golden bow 2

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by shprotru**
fix #8520

after this fix:

https://github.com/ihhub/fheroes2/assets/53114202/c78c9672-e3a5-4d78-b509-00aa4f94c175

### CODE REVIEW

**Comment by shprotru** [comment]
Please, help me to find the place where the small artifact icons should be processed.

File: src/fheroes2/agg/agg_image.cpp [hunk 1]
```diff
@@ -3911,6 +3911,11 @@ namespace fheroes2
             case ICN::ARTIFACT:
                 LoadOriginalICN( id );
                 if ( _icnVsSprite[id].size() > 99 ) {
+                    // This fixes "Golden Bow" (#64) large artifact icon glowing yellow pixel
+                    if ( _icnVsSprite[id][64].width() == 64 && _icnVsSprite[id][64].height() == 64 ) {
```
Comment (ihhub) [inline src/fheroes2/agg/agg_image.cpp:3915]: This check is not needed as Copy function will do the same.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @shprotru , I left one suggestion. You also need to modify `ICN::ARTFX` and `ICN::OBJNARTI` resources.

File: src/fheroes2/agg/agg_image.cpp (hunk 1 above)
Comment (shprotru) [reply src/fheroes2/agg/agg_image.cpp]: done

**Comment by shprotru** [comment]
Hi @ihhub ! I added `ICN::ARTFX`, PR already updated and ready to merge. Where I can see `ICN::OBJNARTI` in the game? At the global map Golden Bow artifact was checked by @Branikolog and there is no any glowing pixels.

**Review by Districh-ru — COMMENTED** [review]
Hi, @shprotru.
I've checked this fix and all is OK - the glowing pixels are properly replaced with the correct ones:

изображение изображение

Could you please, sync this PR with a master branch: we've added extra artifact image for Editor recently and used `case ICN::ARTFX:` in **agg_image.cpp** in the 4121 line.
And then updete this PR: the fix from current lines 3931-3934 should be moved the recently added `case ICN::ARTFX:` to properly merge this PR.

File: src/fheroes2/agg/agg_image.cpp [hunk 2]
```diff
@@ -4126,10 +4126,17 @@ namespace fheroes2
                     const Sprite & originalImage = GetICN( ICN::ARTIFACT, 83 );
                     SubpixelResize( originalImage, _icnVsSprite[id][82] );
                 }
+                else if ( _icnVsSprite[id].size() > 63 ) {
```
Comment (Districh-ru) [inline src/fheroes2/agg/agg_image.cpp:4129]: This one should be just `if` without `else`: we just check that we are going to fix image that exists and we do want to fix both images.
```suggestion
                if ( _icnVsSprite[id].size() > 63 ) {
```

**Review by Districh-ru — APPROVED** [review]

**Comment by ihhub** [comment]
Hi @shprotru , please resolve merge conflicts for this branch.

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
Let's move with this change. However, for any other similar issues we need to use a general approach for scanning an image and fixing such glowing pixels.

@shprotru , could you please rebase this branch from `master` branch as we are not able to merge it due to GitHub Actions checks?

**Comment by ihhub** [comment]
@shprotru , thank you so much for the change!
