### PR TITLE
Fix object fading animation

### LINKED ISSUE #2441: Adventure map, the boat and the shadow of the boat should be displayed at the same time
In the original game, when a boat is summoned, the boat and the shadow of the boat are displayed at the same time with a progressive effect.
In fheroes2, the boat is displayed with a progressive effect, but the boat shadow is displayed abruptly and after the progressive effect of the boat.

In original game:

https://user-images.githubusercontent.com/43583994/102687808-1da25100-41f2-11eb-8a56-f887ec66aa28.mp4

In fheroes2:

https://user-images.githubusercontent.com/43583994/102687843-6ce88180-41f2-11eb-882a-d6fc8d7904aa.mp4

### PR DESCRIPTION
**Pull request by vasilenkoalexey**
Should fix #2441 and #2442
Also we should draw animate for monsters and boats only if `drawMonstersAndBoats == true`, also we should draw animate for monsters and boats before redraw top, because boat have long shadow.

### CODE REVIEW

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 1]
```diff
@@ -192,6 +192,34 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
                 tile.RedrawMonstersAndBoat( dst, tileROI );
             }
         }
+
+        // object fade in/fade out animation for monster and boat only
+        const Game::ObjectFadeAnimation::Info & fadeInfo = Game::ObjectFadeAnimation::Get();
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:197]: Please declare this object outside the if-body as it's same as on line 256.

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 2]
```diff
@@ -230,25 +258,7 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
         const Point & mp = Maps::GetPoint( fadeInfo.tile );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:258]: Declare this variable inside `if ( icn != ICN::MONS32 && fadeInfo.object != MP2::OBJ_BOAT ) {` block.

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 3]
```diff
@@ -192,6 +192,34 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
                 tile.RedrawMonstersAndBoat( dst, tileROI );
             }
         }
+
+        // object fade in/fade out animation for monster and boat only
+        const Game::ObjectFadeAnimation::Info & fadeInfo = Game::ObjectFadeAnimation::Get();
+        if ( fadeInfo.object != MP2::OBJ_ZERO ) {
+            const Point & mp = Maps::GetPoint( fadeInfo.tile );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:199]: What if we have a boat animation just between 2 boats: at the top and at the bottom? Would be more accurate to do in this way:
- check if it's a valid animation
- check if it's boat or monster
- set a boolean flag to true if above conditions are true
- if the boolean flag is true check if current position in the loop above is the same
- if the position is the same do the animation

Does it make more sense?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , I left multiple comments here. Could you please take a look?

File: src/fheroes2/gui/interface_gamearea.cpp (hunk 3 above)
Comment (vasilenkoalexey) [reply src/fheroes2/gui/interface_gamearea.cpp:199]: I got idea, but i suggest put this logic to `RedrawBoat` then we can use `withShadow ` flag during fade in\out. It will be more correct. What you think?

Comment (ihhub) [reply src/fheroes2/gui/interface_gamearea.cpp]: Mm... I don't get about `withShadow` flag related to fading animation. Could you please explain the structure of your future implementation?

Comment (vasilenkoalexey) [reply src/fheroes2/gui/interface_gamearea.cpp]: > Mm... I don't get about `withShadow` flag related to fading animation. Could you please explain the structure of your future implementation?

So... For example we process boat fade out... Called `RedrawMonstersAndBoat` (with alpha and shadow)  inside` GameArea::Redraw`, then called `hero.second->Redraw` where `RedrawBottom4Hero` called in which `RedrawMonstersAndBoat` called again with alpha (because we still process fade out) but WITHOUT shadow (as we want prevent shadow double rendering). In addition, I have a future solution for #2179, where I also plan to redraw the boat inside `hero.second->Redraw`.  In the last commit, I implemented the correct way to do this, and realized more common and correct way for fade processing.

File: src/fheroes2/game/game.h [hunk 4]
```diff
@@ -270,21 +270,10 @@ namespace Game
...
-            uint8_t index;
-            int32_t tile;
-            uint32_t alpha;
-            fheroes2::Size surfaceSize;
-            bool isFadeOut;
-        };
-
-        void Set( const Info & info );
-        Info & Get();
+        using FadeTask = std::tuple<uint8_t, uint32_t, int32_t, uint32_t, uint32_t, uint32_t, bool, bool, uint8_t>;
```
Comment (ihhub) [inline src/fheroes2/game/game.h:273]: Please do **not** use tuple. For example, no developer will understand the meaning of these arguments. Use a normal structure.

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 5]
```diff
@@ -206,6 +231,23 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
...
             }
         }
+
+        // fade out animation for monsters only
+        if ( MP2::OBJ_MONSTER == object && fadeOut ) {
+            const auto fromIndex = std::get<3>( fadeTask );
+            const Point & mp = Maps::GetPoint( fromIndex );
+            const auto objectIndex = std::get<1>( fadeTask );
+            const auto animationIndex = std::get<2>( fadeTask );
+            const auto alpha = std::get<5>( fadeTask );
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:241]: Using a normal structure we don't even need to use extra temporary variables.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , please remove tuple usage in the code. It is very confusing to read it for anyone.

File: src/fheroes2/gui/interface_gamearea.cpp (hunk 5 above)
Comment (vasilenkoalexey) [reply src/fheroes2/gui/interface_gamearea.cpp]: Done

File: src/fheroes2/gui/interface_gamearea.cpp [hunk 6]
```diff
@@ -206,6 +223,18 @@ void Interface::GameArea::Redraw( fheroes2::Image & dst, int flag, bool isPuzzle
...
             }
         }
+
+        // fade out animation for monsters only
+        if ( MP2::OBJ_MONSTER == fadeTask.object && fadeTask.fadeOut ) {
+            const Point & mp = Maps::GetPoint( fadeTask.fromIndex );
+            const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::MINIMON, fadeTask.objectIndex );
+            BlitOnTile( dst, sprite, sprite.x() + 16, sprite.y() + TILEWIDTH, mp, false, fadeTask.alpha );
+
+            if ( fadeTask.animationIndex ) {
```
Comment (ihhub) [inline src/fheroes2/gui/interface_gamearea.cpp:233]: Is it correct that here we can use only values above 0? If yes could you please write an explicit expression of it as negative values will make this condition true as well.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , I left multiple comments here. Could you please take a look?

File: src/fheroes2/game/game.h [hunk 7]
```diff
@@ -270,21 +270,21 @@ namespace Game
...
-            int32_t tile;
+            uint32_t objectIndex;
+            uint32_t animationIndex;
+            uint32_t fromIndex;
+            uint32_t toIndex;
             uint32_t alpha;
-            fheroes2::Size surfaceSize;
-            bool isFadeOut;
+            bool fadeOut;
+            bool fadeIn;
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/game/game.h:282]: > Is there a case when the same object has both animation types?
Yes, summon boat have both fade in and fade out animation.

File: src/fheroes2/heroes/heroes_spell.cpp [hunk 8]
```diff
@@ -391,35 +391,14 @@ bool ActionSpellSummonBoat( const Heroes & hero )
...
     const MapsIndexes & boats = Maps::GetObjectPositions( center, MP2::OBJ_BOAT, false );
-    for ( size_t i = 0; i < boats.size(); ++i ) {
-        const s32 boat = boats[i];
-        if ( Maps::isValidAbsIndex( boat ) ) {
-            if ( Rand::Get( 1, 100 ) <= chance ) {
-                Maps::Tiles & boatFile = world.GetTiles( boat );
-                boatFile.RemoveObjectSprite();
-                boatFile.SetObject( MP2::OBJ_ZERO );
-                Game::ObjectFadeAnimation::Set( Game::ObjectFadeAnimation::Info( MP2::OBJ_BOAT, 18, dst_water, 0, false ) );
+    for ( auto it = boats.cbegin(); it != boats.cend(); ++it ) {
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/heroes/heroes_spell.cpp:395]: I just made the style of the code slightly more modern (romove `u32` and `auto` using).

The last commit, in which summon boat does not depend on the skills of the hero, I agreed with Branikolog. If it important i can put this changes to another pr.

File: src/fheroes2/maps/maps_tiles.cpp [hunk 9]
```diff
@@ -1538,7 +1538,7 @@ void Maps::Tiles::RedrawMonster( fheroes2::Image & dst, const Rect & visibleTile
     const fheroes2::Sprite & sprite = fheroes2::AGG::GetICN( ICN::MINIMON, spriteIndicies.first );
     area.BlitOnTile( dst, sprite, sprite.x() + 16, sprite.y() + TILEWIDTH, mp );
 
-    if ( spriteIndicies.second != -1 ) {
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/maps/maps_tiles.cpp:1541]: Look at `Maps::Tiles::GetMonsterSpriteIndices( const Tiles & tile, uint32_t monsterIndex )`
there only one place where `spriteIndices.second` filled
`spriteIndices.second = monsterIndex * 9 + 1 + monsterAnimationSequence[( Game::MapsAnimationFrame() + mp.x * mp.y ) % ARRAY_COUNT( monsterAnimationSequence )];`
It mean we can use zero value here as "no animation" flag. I think its more comprehensive solution.

File: src/fheroes2/gui/interface_gamearea.cpp (hunk 6 above)
Comment (vasilenkoalexey) [reply src/fheroes2/gui/interface_gamearea.cpp:233]: `fadeTask.animationIndex` unsigned and filled in `Game::ObjectFadeAnimation::StartFadeTask` by `Maps::Tiles::GetMonsterSpriteIndices` in one case (I explained above about this method) or by `ICN::AnimationFrame` in another case (when we draw object but not monster) and this method again unsigned (another reason to make unsigned animation index and using zero value).

File: src/fheroes2/heroes/heroes_action.cpp [hunk 10]
```diff
@@ -309,10 +309,8 @@ void BattleLose( Heroes & hero, const Battle::Result & res, bool attacker, int c
 
 void AnimationRemoveObject( const Maps::Tiles & tile )
 {
-    if ( tile.GetObject() == MP2::OBJ_ZERO )
-        return;
-
-    Game::ObjectFadeAnimation::Set( Game::ObjectFadeAnimation::Info( tile.GetObjectTileset(), tile.GetObjectSpriteIndex(), tile.GetIndex() ) );
+    if ( tile.GetObject() != MP2::OBJ_ZERO )
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/heroes/heroes_action.cpp]: Done

File: src/fheroes2/game/game_startgame.cpp [hunk 11]
```diff
@@ -1003,24 +1003,45 @@ int Interface::Basic::HumanTurn( bool isload )
...
                 else {
-                    fadeInfo.alpha += ( fadeInfo.isFadeOut ) ? -20 : 20;
+                    if ( fadeTask.fadeIn ) {
+                        if ( fadeTask.alpha == 0 ) {
+                            Maps::Tiles & tile = world.GetTiles( fadeTask.toIndex );
+                            if ( MP2::OBJ_BOAT == fadeTask.object ) {
+                                tile.setBoat( Direction::RIGHT );
+                            }
+                        }
+                        if ( fadeTask.alpha < ( 235 ) ) {
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/game/game_startgame.cpp]: Done

File: src/fheroes2/game/game.h [hunk 12]
```diff
@@ -270,21 +270,21 @@ namespace Game
...
-        struct Info
+        struct FadeTask
         {
-            Info();
-            Info( u8 object_, u8 index_, s32 tile_, u32 alpha_ = 255u, bool fadeOut = true );
-
             uint8_t object;
-            uint8_t index;
-            int32_t tile;
+            uint32_t objectIndex;
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/game/game.h]: Done

File: src/fheroes2/heroes/heroes_spell.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (ihhub) [reply src/fheroes2/heroes/heroes_spell.cpp:395]: Could we please revert changes in this file and open another pull request for it? It is a goo practice to separate changes for different issue.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @vasilenkoalexey , could you please take a look on few given comments? Soon I will ask QA team to test it deeply again.

File: src/fheroes2/game/game.h [hunk 13]
```diff
@@ -26,6 +26,7 @@
 #include <string>
 
 #include "gamedefs.h"
+#include "mp2.h"
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/game/game.h]: Done

File: src/fheroes2/game/game.h [hunk 14]
```diff
@@ -270,21 +271,46 @@ namespace Game
...
+            {
+                object = object_;
+                objectIndex = objectIndex_;
+                animationIndex = animationIndex_;
+                fromIndex = fromIndex_;
+                toIndex = toIndex_;
+                alpha = alpha_;
+                fadeOut = fadeOut_;
+                fadeIn = fadeIn_;
+                objectTileset = objectTileset_;
```
[the remark this answers is not in the document]
Comment (vasilenkoalexey) [reply src/fheroes2/game/game.h]: Done

**Comment by vasilenkoalexey** [comment]
Done

**Comment by ihhub** [comment]
@vasilenkoalexey , thank you very much for fixing these issues!
