### PR TITLE
Shipyard: Treat water with an object's shadow as water free of objects

### LINKED ISSUE #8039: Seven Lakes, Red player cannot build a shipyard
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Windows

### Describe the bug

Shipyard somehow is not available for red player. 
fheroes2:
image
image

OG:
image

### Save file

None.

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by Districh-ru**
Fix #8039

### CODE REVIEW

**Review by Branikolog — APPROVED** [review]
@Districh-ru 
Thanks for such a fast fix! I can now build a shipyard even in a previously generated game.

**Comment by Branikolog** [comment]
@Districh-ru 
Oh, the only small issue here...
I'm not able to build a boat in this city.

**Comment by Districh-ru** [comment]
> @Districh-ru 
> Oh, the only small issue here...
> I'm not able to build a boat in this city.

Sad. :)
I'll try to fix it tomorrow morning

**Review by Branikolog — APPROVED** [review]
Now shipyard is available and I can purchase a boat there. 👍

File: src/fheroes2/castle/castle.cpp [hunk 1]
```diff
@@ -2176,9 +2176,10 @@ bool Castle::HasSeaAccess() const
             return true;
         }
 
-        // If this is an action object and it can be removed then it is possible to put a boat here.
+        // If this is an object's shadow or this is an action object that can be removed then it is possible to put a boat here.
         const MP2::MapObjectType objectType = tile.GetObject();
-        return MP2::isPickupObject( objectType ) || objectType == MP2::OBJ_BOAT;
+        return MP2::isPickupObject( objectType ) || objectType == MP2::OBJ_BOAT
+               || ( objectType == MP2::OBJ_NONE && tile.getLayerType() == Maps::ObjectLayerType::SHADOW_LAYER );
```
Comment (ihhub) [inline src/fheroes2/castle/castle.cpp:2182]: We are checking object layer only of main object on the tile, not the whole tile. I suggest to use `Maps::Tiles::isShadow()` that covers everything. However, this does no cover all possible cases. I think the logic should be like this:
```cpp
MP2::isPickupObject( objectType ) || // pickup objects can be removed later
objectType == MP2::OBJ_BOAT || // obviously, if boat exists then it can be removed later
!tile.isObjectOrBackgroundLayerType()
```
The last function does not exist but the idea is to check main tile addon and bottom layers addon that none of addons are on object and background layers.

By the way `isObjectOrBottomLayerType` is named incorrectly as it should be for OBJECT_LAYER and BACKGROUND_LAYER layers, not for bottom layer.

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I left one suggestion here. Could you please take a look at it when you have time?

File: src/fheroes2/castle/castle.cpp (hunk 1 above)
Comment (Districh-ru) [reply src/fheroes2/castle/castle.cpp]: Hi, @ihhub, sure.
The `isObjectOrBottomLayerType()` function name is fixed now and moved to the tile and addon methods.
I used the suggested `!tile.isObjectOrBackgroundLayerType()` logic.
Thanks!

File: src/fheroes2/maps/maps_tiles.h [hunk 2]
```diff
@@ -174,6 +180,12 @@ namespace Maps
             return objectType == _mainObjectType;
         }
 
+        // Returns true if tile's main addon layer type is Object or Background and false if it is Terrain or Shadow.
+        bool isObjectOrBackgroundLayerType() const
+        {
+            return _mainAddon.isObjectOrBackgroundLayerType();
+        }
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.h:187]: This is not entirely correct for all cases. There could be a situation when **_addonBottomLayer** can have an object with this layer type but the main addon doesn't. We should run through all entries of **_addonBottomLayer** as well.

I also suggest to rename this function to avoid misleading reading. Including a word **tile** will solve the issue.

File: src/fheroes2/maps/maps_tiles.h [hunk 3]
```diff
@@ -67,6 +67,12 @@ namespace Maps
 
         ~TilesAddon() = default;
 
+        // Returns true if addon's layer type is Object or Background and false if it is Terrain or Shadow.
+        bool isObjectOrBackgroundLayerType() const
```
Comment (ihhub) [inline src/fheroes2/maps/maps_tiles.h:71]: While addressing comments for Ocean Objects PR I was thinking how we properly name this function. How about we name it as `doesOccupyTile()`? Or even better `isPassabilityTransparent()` and use opposite logic as:
```cpp
bool isPassabilityTransparent() const
{
    return _layerType == SHADOW_LAYER || _layerType == TERRAIN_LAYER;
}
```

What do you think?

**Review by ihhub — CHANGES_REQUESTED** [review]
Hi @Districh-ru , I added few more comments here. Could you please take a look at them?

**Comment by ihhub** [comment]
This pull request should be merged for the upcoming release as it is a regression fix. Therefore, I am marking it as the high priority PR.

File: src/fheroes2/maps/maps_tiles.h (hunk 2 above)
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.h]: Hi, @ihhub, yes we should also check this case. I changed the function.

File: src/fheroes2/maps/maps_tiles.h (hunk 3 above)
Comment (Districh-ru) [reply src/fheroes2/maps/maps_tiles.h]: Yes, lets do so. I named the tile function the same way.
I'm not good in naming functions and variables. :(

**Review by ihhub — APPROVED** [review]

**Comment by ihhub** [comment]
@Districh-ru , thank you so much for these fixes!
